### PR TITLE
Loosen version requirement on fpylll and align its conda version

### PR DESCRIPTION
**Pull request by tobiasdiez**
Currently, the conda workflow fails (e.g https://github.com/sagemath/sage/actions/runs/6556683128/job/17807012736) because it installs fpylll 0.6 and we still require 0.5.9.
To fix this, the version constraint is loosened, and to prevent it from happening in the future the same version constraint is introduced for conda.

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by malb** [comment]
FPyLLL only works with Cython 3.0, though, would that be a problem?

**Comment by mkoeppe** [comment]
> FPyLLL only works with Cython 3.0, though, would that be a problem?

No, Sage has fully switched to Cython 3.0 too.

**Comment by mkoeppe** [comment]
From the PR description:
> to prevent it from happening in the future the same version constraint is introduced for conda.

This explanation makes no sense, but yes, it's fine to add a lower version bound to conda.txt.

**Review by mkoeppe — APPROVED** [review]

**Comment by tobiasdiez** [comment]
Thanks!

**Pull request merged**
