### PR TITLE
build/pkgs/{gdb,gmp,libgd,python3,symmetrica}: Reduce xz to order-only dep

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
What is the motivation?  Why change now?

Actually I wonder why xz was not an order-only dependency in the first place.

**Comment by mkoeppe** [comment]
It's unrelated to the xz backdoor!

I think I may have gotten here because @culler reported some strange behavior of the build system to me a while ago.

**Comment by kwankyu** [comment]
OK. Would you rebase? I want to see this pass B&T at least.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
