### PR TITLE
 Include TESTS in doc preview for PRs

### PR DESCRIPTION
**Pull request by kwankyu**
We include TESTS blocks in development documentation, so that they are visible at least during development. 

Then not to ruin CHANGES.html, we refactor doc build github workflow. The idea is to upload artifact `doc-develop` so that doc diffs are computed against the doc contained in the artifact.

test: https://doc-develop--sagemath-test.netlify.app/html/en/reference/structure/sage/structure/sage_object Look around  for new "TESTS" blocks.

We also remove all spurious diffs caused by EXAMPLES tabs indices change. Tests for PR event:

doc-develop artifact: https://github.com/kwankyu/sage/actions/runs/11787561475
doc-build workflow run: https://github.com/kwankyu/sage/actions/runs/11789320959/job/32837887930 

Note that doc build for this PR itself fails here, of course. We may ignore this. 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

#38468

### CODE REVIEW

**Comment by mkoeppe** [comment]
> And we include TESTS blocks in development documentation, so that they are visible at least during development.

Interesting idea. Do you have plans beyond this for the TESTS blocks?

**Comment by kwankyu** [comment]
> > And we include TESTS blocks in development documentation, so that they are visible at least during development.
> 
> Interesting idea. Do you have plans beyond this for the TESTS blocks?

No. Actually while investigating the cause of the hunk 1 in https://doc-pr-38468--sagemath.netlify.app/changes, I have now realized that this PR won't work as I expected, at least with the current infrastructure.

When we compute diffs to create CHANGES.html, we compare the "new" doc for the PR with the "old" doc built by `CI Linux` workflow for the develop branch. The "old" doc was built with parsed examples and no TESTS. We should not change this. For reasonable diffs, the "new" doc could not deviate from this mode.

One way to escape the dilemma is to get the "old" doc from the artifact produced by `doc-build` workflow run for develop branch. I don't know if this is doable or desirable...

I may close this PR for now.

**Comment by kwankyu** [comment]
I did necessary refactoring to implement this PR. Now doc build for pull request event downloads doc-develop artifact to compute diffs to create CHANGES.html.

**Comment by kwankyu** [comment]
> One way to escape the dilemma is to get the "old" doc from the artifact produced by `doc-build` workflow run for develop branch. I don't know if this is doable or desirable...

Done.

**Comment by kwankyu** [comment]
@mkoeppe I think this PR is now tasty.

**Comment by kwankyu** [comment]
The last commit is to mitigate the "out of disk space" failure.

**Comment by dimpase** [comment]
[build-doc](https://github.com/sagemath/sage/actions/runs/11787558967/job/32833079952?pr=38449#logs) CI step is failing, as you introduced new "target" doc-develop.

Is there  a way to fix this?

**Comment by kwankyu** [comment]
It is expected, and cannot be "fixed" here. The artifact doc-develop will be generated at next beta release after merging this pr.

If you want to see a test result,  I will prepare one in my repo. Wait some minutes.

**Comment by kwankyu** [comment]
doc-build for a dummy PR for testing is running here: 

https://github.com/kwankyu/sage/actions/runs/11789320959/job/32837887930

**Review by dimpase — APPROVED** [review]
Looks good.

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
