### PR TITLE
add method `orient` to `Graph`

### PR DESCRIPTION
**Pull request by dcoudert**
As suggested by @maxale in https://github.com/sagemath/sage/issues/38758#issuecomment-2391505302, we add a method to apply an orientation function to a graph and obtain the corresponding directed graph. 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by tscrim — COMMENTED** [review]
Lines 172 to 175 are never reached since they are an "else" after two cases, one of which *must* be true. Is line 172 supposed to be an `if`?

**Comment by dcoudert** [comment]
These lines can be reached setting `data_structure=None`, `immutable=None` and `sparse=True` or `False`.

In fact, lines 154-182 are copy-paste from method `copy` in `generic_graph.py`.  May be I should make a method like `_choose_data_structure_for_copy` in `generic_graph.py` and use it for both methods ?

**Comment by tscrim** [comment]
Ah, I see. It’s fine for now. Then can you add doctests covering those cases?

**Comment by dcoudert** [comment]
We'll see if the new tests are sufficient.

**Review by tscrim — APPROVED** [review]
That should be good. Thank you.

**Comment by dcoudert** [comment]
Thanks for the review.

**Pull request merged**
