### PR TITLE
Revert "gh-36678: CI conda: Ignore baseline test failures "

### PR DESCRIPTION
**Pull request by tobiasdiez**
Reverts #36678, which was marked as "positive review" although not all reviewer concern had been addressed.

I'll set this directly as "positive review" since this is a trivial git revert.

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
This nonsense really needs to stop.

**Comment by mkoeppe** [comment]
It really doesn't work this way, even if you think that a particular PR should be reverted.

**Comment by mkoeppe** [comment]
This is obviously not a blocker.

**Comment by roed314** [comment]
This PR is not appropriate and is a violation of Sage's code of conduct: directly reverting a PR where you disagree with the community's decision, then giving yourself positive review with a comment that it is a "trivial git revert" is completely unacceptable.

**Pull request closed without merging**
