### PR TITLE
Implement period_lattice for elliptic curves over RealField, ComplexField, etc.

### PR DESCRIPTION
**Pull request by user202729**
Implement `E.period_lattice()` method for elliptic curves over other fields.

(The code is mostly already there, just need minor adaptation.)

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion. (not aware of one)
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by user202729** [comment]
The failing test looks unrelated to the changes, I think.

**Comment by tscrim** [comment]
@JohnCremona Perhaps you might be interested in this.

**Comment by JohnCremona** [comment]
I'll look at this next week

**Comment by user202729** [comment]
Caveat:

* A `EllipticCurve_number_field` inherits from `EllipticCurve_field`.
* Given an instance of `EllipticCurve_field`, you can call `.period_lattice()` on it with no argument and it will return something.
* This contract is not satisfied with an `EllipticCurve_number_field` object, violate Liskov substitution principle.

What do you think?

One way is to default `embedding=None` for `EllipticCurve_number_field.period_lattice()`, but then we need to think what to do in that case.

* use `E.base_field().coerce_embedding()` (suggested in https://github.com/sagemath/sage/issues/38363 ). This breaks backwards compatibility, but I think this is the best option.

* give an error: this is not the current behavior with `embedding=None` (thus also break backwards compatibility), but would be the safest option.

* follow the current behavior of `PeriodLattice_ell` constructor when `embedding=None`:

	> - ``embedding`` -- (default: ``None``) an embedding of the base
	> field `K` of ``E`` into a real or complex field.  If ``None``:
	> 	- use the built-in coercion to `\RR` for `K=\QQ`;
	> 	- use the first embedding into `\RR` given by
	> 	``K.embeddings(RealField())``, if there are any;
	> 	- use the first embedding into `\CC` given by
	> 	``K.embeddings(ComplexField())``, if `K` is totally complex.

**Comment by user202729** [comment]
@JohnCremona Can I get a review? Thanks.

**Review by JohnCremona — APPROVED** [review]
I am happy with this, assuming that old tests still pass.   It is a good idea to change the behavious over number fields with no specified embedding: the choice to use the "first" one was quite random, probably introduced by me when I first did this.  Certainly, when there is a default embedding for the number field, that is the one to use.

**Comment by JohnCremona** [comment]
I think it is up to the original author to fix the failing tests, which do not look serious.  My positive review was only *in principle*, once these things have been sorted out.

**Comment by user202729** [comment]
Indeed the failing tests are not serious (it's just one error message over another).

Changing the behavior to only use coerce_embedding instead of arbitrarily pick the first embedding sounds like a good idea, I will implement it later.

**Comment by user202729** [comment]
I decide to just fix the failing tests by relax the thing being tested for.

The part of using canonical embedding feels like a behavioral change ⟹ deprecation period ⟹ etc. and it's probably easiest to handle it in a separate pull request.

**Comment by JohnCremona** [comment]
There are still some failing tests being flagged.  Do they fail when run locally?

**Comment by user202729** [comment]
I… use GitHub Actions to run the tests, sorry. Should really get around to figure out how to run it locally…

**Comment by user202729** [comment]
The tests passed now, can someone add the "s: positive review" label? Thanks.

**Comment by JohnCremona** [comment]
I will -- but first can you merge with the base branch?

**Review by JohnCremona — APPROVED** [review]

**Comment by vbraun** [comment]
On 32-bit:
```
**********************************************************************
File "src/sage/schemes/elliptic_curves/period_lattice.py", line 1746, in sage.schemes.elliptic_curves.period_lattice.PeriodLattice_ell.elliptic_logarithm
Failed example:
    L.elliptic_exponential(_)
Expected:
    (3.00000000000000 + 9.20856947066460e-16*I : -5.59022723358798 - 0.0894418024719718*I : 1.00000000000000)
Got:
    (3.00000000000000 + 9.21992199947644e-16*I : -5.59022723358798 - 0.0894418024719718*I : 1.00000000000000)
**********************************************************************
File "src/sage/schemes/elliptic_curves/period_lattice.py", line 1750, in sage.schemes.elliptic_curves.period_lattice.PeriodLattice_ell.elliptic_logarithm
Failed example:
    L.elliptic_exponential(_)
Expected:
    (3.0000000000000000000000000000 - 1.4773628579202938936348512161e-30*I : -5.5902272335879800026836302686 - 0.089441802471969391005702381090*I : 1.0000000000000000000000000000)
Got:
    (3.0000000000000000000000000000 - 1.4773628576434657795460561386e-30*I : -5.5902272335879800026836302686 - 0.089441802471969391005702381090*I : 1.0000000000000000000000000000)
**********************************************************************
1 item had failures:
   2 of  98 in sage.schemes.elliptic_curves.period_lattice.PeriodLattice_ell.elliptic_logarithm
    [447 tests, 2 failures, 3.31s wall]
**********************************************************************
```

**Comment by user202729** [comment]
Looks innocuous --- just add some appropriate `# abs tol`.

**Review by JohnCremona — APPROVED** [review]

**Pull request merged**
