### PR TITLE
Fix sync labels issues for step 2 going live completion

### PR DESCRIPTION
**Pull request by soehms**
Unfortunately the fix in https://github.com/sagemath/sage/pull/36213 has not been completed properly. There is still a `return` from the `get_review_decision` method which is not `None` where it should be.

This is fixed here. Sorry for this unnecessary trouble and my lack of attention!

In a next step this PR fixes a bug which has been noticed by an accidentally activation of the `unlabeled` trigger (see https://github.com/sagemath/sage/pull/36292#issuecomment-1723266908). Simultaneously the `labeled`-trigger has been disabled. This is an unrealistic setting which was not covered by the code.

Explicitly, a state label could not be removed even though other state labels where set (examples  https://github.com/sagemath/sage/pull/36128 and https://github.com/sagemath/sage/pull/36020). This PR leads to the following changes of behavior:

1. The reaction on the `unlabeled`-event is reduced to the case of the last label
2. The `unlabeled`-event will not lead to a rejection of the removal any more
3. Instead of a warning comment a hint comment is posted.

We found a way to test the bot a little more realistically (see https://github.com/soehms/sage/pull/11). Additional problems emerged and were also resolved. This led to the following changes in the workflow:

4. A bug in `actor_valid` is fixed (see https://github.com/soehms/sage/pull/10#issuecomment-1730034384)
5. Preparing to use our own bot user (e.g. [sagemathadmins](https://github.com/sagemathadmins)) (see https://github.com/soehms/sage/pull/11#issuecomment-1747330149)
6. Waiver of observing the `reviewDecision` feature provided by GitHub (see 2. in https://github.com/soehms/sage/pull/11#issuecomment-1739662270)
7. Allow the user to revert his decision of label selection (see  https://github.com/soehms/sage/pull/11#issuecomment-1750084494)
8. Don't reject label addition any more, except in the case where the author tries to set `s: positive review` to his own PR which has no reviews from others (see https://github.com/soehms/sage/pull/11#issuecomment-1755763797)
9. Dismiss stale reviews of the bot after a push to the branch and on submission of a new review which is more than just a comment (see https://github.com/soehms/sage/pull/11#issuecomment-1755763797).

Despite the fact that the testing was now more realistic, it is still not guaranteed that the bot's behavior in `sagemath/sage` will be completely covered by our testing.

The changes in this PR cannot be activated immediately after merging into the develop branch due to a bug in the GitHub web interface observed during testing in https://github.com/soehms/sage/pull/11 (see https://github.com/soehms/sage/pull/11#issuecomment-1750247509 and https://github.com/soehms/sage/pull/11#issuecomment-1759029435). The problem is that the panel at the top right of the webpage that contains the labels does not update immediately after the bot changes the labels. Since this might cause confusion, I've created the following [bug report](https://support.github.com/ticket/personal/0/2448092) about it:

gh_bug_rep1
gh_bug_rep2

Some answers to these reports can be seen in [this sage-devel post](https://groups.google.com/g/sage-devel/c/sulCa-6EZRA/m/iz5x2JPdAAAJ).

##### What happens when adding `s: needs review` to a PR?

```mermaid
---
title: add the needs review label
---
flowchart LR

%% vertices

    trigger([label\n 's: needs review'\n added])
    mark_as_ready([mark as\n ready for\n review])
    remove_other_labels([remove other\n state labels])
    warning_about_label_addition([warning\n about label\n addition])
    needs_review_valid[[needs review\n valid?]]
    is_draft{is PR\n a draft?}

%% edges

    trigger --> needs_review_valid
    needs_review_valid -- true ---> remove_other_labels
    needs_review_valid -- false ---> is_draft
    is_draft -- yes ---> mark_as_ready
    is_draft -- no ---> warning_about_label_addition
    mark_as_ready --> remove_other_labels
```

The warning is posted as a comment which will be deleted after 5 minutes.

```mermaid
---
title: needs review valid?
---
flowchart LR

%% vertices

    needs_review_valid([needs review\n valid?])
    true([true])
    false([false])
    latest_review_by_actor{latest review\n by actor}
    needs_work_valid[[needs work\n valid?]]
    positive_review_valid[[positive review\n valid?]]
    is_draft{is PR\n a draft?}

%% edges

    needs_review_valid ---> is_draft
    is_draft -- yes ---> false
    is_draft -- no ---> latest_review_by_actor
    latest_review_by_actor -- yes ---> true
    latest_review_by_actor -- no ---> needs_work_valid
    needs_work_valid -- true ---> false
    needs_work_valid -- false ---> positive_review_valid
    positive_review_valid -- true ---> false
    positive_review_valid -- false ---> true
```

```mermaid
---
title: needs work valid?
---
flowchart LR

%% vertices

    needs_work_valid([needs work\n valid?])
    true([true])
    false([false])
    latest_review_request_changes{latest proper\n review requests\n changes?}

%% edges

    needs_work_valid  --> latest_review_request_changes
    latest_review_request_changes -- yes ---> true
    latest_review_request_changes -- no ---> false
```

```mermaid
---
title: positive review valid?
---
flowchart LR

%% vertices

    positive_review_valid([positive review\n valid?])
    true([true])
    false([false])
    latest_proper_review_approved{latest proper\n review\n approved?}

%% edges

    positive_review_valid  --> latest_proper_review_approved
    latest_proper_review_approved -- yes ---> true
    latest_proper_review_approved -- no ---> false
```

Here, proper means that the review is more than a comment.

##### What happens when adding s: needs work to a PR?

```mermaid
---
title: add the needs work label
---
flowchart LR

%% vertices

    trigger([label\n 's: needs work'\n added])
    request_changes([request changes])
    remove_other_labels([remove other\n state labels])
    warning_about_label_addition([warning\n about label\n addition])
    needs_work_valid[[needs work\n valid?]]
    is_draft{is PR\n a draft?}

%% edges

    trigger --> needs_work_valid
    needs_work_valid -- true ---> remove_other_labels
    needs_work_valid -- false ---> is_draft
    is_draft -- yes ---> warning_about_label_addition
    is_draft -- no ---> request_changes
    request_changes --> remove_other_labels
```

##### What happens when adding `s: positive review` to a PR?

```mermaid
---
title: add the positive review label
---
flowchart LR

%% vertices

    trigger([label\n 's: positive review'\n added])
    positive_review_valid[[positive review\n valid?]]
    approve_pr([approve])
    remove_other_labels([remove other\n state labels])
    actor_valid[[actor valid?]]
    approve_allowed[[approve\n allowed?]]
    warning_about_label_addition([warning\n about label\n addition])
    reject_label_addition[[reject\n label\n addition]]

%% edges

    trigger --> positive_review_valid
    positive_review_valid -- yes ---> remove_other_labels
    positive_review_valid -- no ---> actor_valid
    actor_valid -- yes ---> approve_allowed
    actor_valid -- no ---> reject_label_addition
    approve_allowed -- yes ---> approve_pr
    approve_allowed -- no ---> warning_about_label_addition
    approve_pr --> remove_other_labels
```

The boxes `actor_valid` and `reject_label_addition` are unchanged.

```mermaid
---
title: approve allowed?
---
flowchart LR

%% vertices

    trigger([approve\n allowed?])
    true([true])
    false([false])
    review_of_others_request_changes{changes\n requested by\n someone\n else exists?}

%% edges

    trigger --> review_of_others_request_changes
    review_of_others_request_changes -- yes ---> false
    review_of_others_request_changes -- no ---> true
```

Here, only reviews of someone else are considered which are more recent than any commit.

##### What happens when a state label is added to an issue?

```mermaid
---
title: add a state label to an issue
---
flowchart LR

%% vertices

    trigger([label added])
    warning_about_label_addition([warning\n about label\n addition])
    nothing([do nothing])
    is_needs_info{is label\n 's: needs info'?}

%% edges

    trigger --> is_needs_info
    is_needs_info -- yes --->  nothing
    is_needs_info -- no --->  warning_about_label_addition
```

##### What happens when removing a state label from a PR?

```mermaid
---
title: remove a state label
---
flowchart LR

%% vertices

    trigger([label removed])
    nothing([do nothing])
    hint_about_label_removal([hint\n about label\n removal])
    other_state_label{other state\n labels exist?}
    is_needs_info{is label\n 's: needs info'?}

%% edges

    trigger --> other_state_label
    other_state_label -- yes ---> nothing
    other_state_label -- no ---> is_needs_info
    is_needs_info -- yes --->  nothing
    is_needs_info -- no ---> hint_about_label_removal
```

The hint is postet as a comment which will be deleted after 5 minutes.

##### What happens when adding a priority label?

```mermaid
---
title: add a priority label
---
flowchart LR

%% vertices

    trigger([label added])
    remove_other_labels([remove other\n priority labels])

%% edges

    trigger --> remove_other_labels
```

##### What happens when removing a priority label?

```mermaid
---
title: remove a priority label
---
flowchart LR

%% vertices

    trigger([label removed])
    nothing([do nothing])
    hint_about_label_removal([hint\n about label\n removal])
    other_prio_label{other priority\n labels exist?}

%% edges

    trigger --> other_prio_label
    other_prio_label -- yes ---> nothing
    other_prio_label -- no ---> hint_about_label_removal
```

##### What happens when a PR is approved?

```mermaid
---
title: approve
---
flowchart LR

%% vertices

    trigger([approve\n])
    select_positive_review(['s: positive review'\n label selected])
    nothing([do nothing])
    positive_review_valid[[positive review\n valid?]]
    pending_review_requests{pending\n review requests\n exists?}
    actor_authorized{is actor\n a member of\n Triage?}

%% edges

    trigger ---> pending_review_requests
    pending_review_requests -- yes ---> nothing
    pending_review_requests -- no ---> actor_authorized
    actor_authorized -- yes ---> positive_review_valid
    actor_authorized -- no ---> nothing
    positive_review_valid -- true ---> select_positive_review
    positive_review_valid -- false ---> nothing
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
Will this fix the problem with the bot setting a "needs review" when the PR has been approved with a "positive review" set. See #36128. Frankly, I see this as the bot is very broken, and it is quite frustrating that the bot is really that dumb.

**Comment by soehms** [comment]
> Will this fix the problem with the bot setting a "needs review" when the PR has been approved with a "positive review" set? See #36128. Frankly, I see this as the bot is very broken, and it is quite frustrating that the bot is really that dumb.

I'm very sorry about the trouble. It was not planned to activate the reaction on removing a label, yet. It happened accidentially (see https://github.com/sagemath/sage/pull/36213#issuecomment-1722731711) and I don't have the permission to disable it again. Thus we have to wait until @tobiasdiez or some other maintainer does it.

This PR is about a bug concerning setting a label. It should have been fixed already in PR #36213 but unfortunately two lines where missing. 

Maybe I should remove the `unlabeled` trigger completely from code of the bot (since it is not very useful) and as I see now, is rather critical.

**Comment by kwankyu** [comment]
Somewhere in your code, you write "state-label". I think "state label" (without hyphen) reads better, like "priority label".

**Comment by soehms** [comment]
> Somewhere in your script, you wrote "state-label". I think "state label" (without hyphen) reads better, like "priority label".

I suspected that you mean that, but I can't find it:

```
grep -i state-label .github/sync_labels.py 
```

gives no results.

**Comment by kwankyu** [comment]
It is generated here:
```python
    def reject_label_removal(self, item):
        r"""
        Post a comment that the given label can not be removed and select
        a corresponding other one.
        """
        if type(item) == State:
            sel_list = 'state'
        else:
            sel_list = 'priority'
-->     self.add_warning('Label *%s* can not be removed. Please add the %s-label which should replace it' % (item.value, sel_list))
        self.add_label(item.value)
        return        
```

**Comment by soehms** [comment]
I've merged some more changes that I tested in my fork repository in PR https://github.com/soehms/sage/pull/10 (see https://github.com/soehms/sage/pull/10#issuecomment-1730034384 for the test results). In short: the `unlabeled` event is no longer restrictive and therefore harmless. However, we should activate it as the last step, if at all.

**Review by kwankyu — APPROVED** [review]
Positive review without reading the code since we test the code on the battle field.

**Comment by tobiasdiez** [comment]
Btw it should be possible to have the bot accept/reject PRs without any comment (at least through the cli, not sure about the python api). For an example,
https://github.com/JabRef/jabref/blob/c49832491f86d01f3dd00aee0245911d7fb3e9b3/.github/workflows/automerge.yml#L19
results in
https://github.com/JabRef/jabref/pull/10394#pullrequestreview-1639431136

**Comment by soehms** [comment]
> Positive review without reading the code since we test the code on the battle field.

Thanks! Unfortunately we don't have an alternative chance to test, since the behavior in a fork repository is different.

**Comment by soehms** [comment]
> Btw it should be possible to have the bot accept/reject PRs without any comment (at least through the cli, not sure about the python api). For an example, https://github.com/JabRef/jabref/blob/c49832491f86d01f3dd00aee0245911d7fb3e9b3/.github/workflows/automerge.yml#L19 results in [JabRef/jabref#10394 (review)](https://github.com/JabRef/jabref/pull/10394#pullrequestreview-1639431136)

Yes, that works:

```
gh pr review --approve https://github.com/sagemath/sage/pull/36020
✓ Approved pull request #36020
```
grafik



The restriction only applies to *request changes*.

Shall I remove the body of the approval? Maybe in the next PR?

**Comment by kwankyu** [comment]
Please do it here.

**Comment by kwankyu** [comment]
For "request changes" triggered by "s: needs work" label, could the comment be "owned" by the one who added the label? Then the comment could be edited to contain the reason of the the "needs work".

**Comment by soehms** [comment]
> Please do it here.

I've opened https://github.com/soehms/sage/pull/11 for this. You test it there if you just add `s: positive review`. If this is successful I will merge it.

**Comment by soehms** [comment]
> For "request changes" triggered by "s: needs work" label, could the comment be "owned" by the one who added the label? Then the comment could be edited to contain the reason of the the "needs work".

In my fork I can edit such [review comments](https://github.com/soehms/sage/pull/10#pullrequestreview-1632487787) of the GitHub bot:

grafik

But probably this works since I'm the owner. For the `sagemath` repo I fear that it is not possible to give edit permissions to the actor who added the state label.

The information you can obtain from the REST-API for the review shown in the screenshot is this:

```
gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/soehms/sage/pulls/10/reviews
[
  {
    "id": 1632487787,
    "node_id": "PRR_kwDOI72C3M5hTclr",
    "user": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "body": "soehms requested changes for this PR",
    "state": "DISMISSED",
    "html_url": "https://github.com/soehms/sage/pull/10#pullrequestreview-1632487787",
    "pull_request_url": "https://api.github.com/repos/soehms/sage/pulls/10",
    "author_association": "NONE",
    "_links": {
      "html": {
        "href": "https://github.com/soehms/sage/pull/10#pullrequestreview-1632487787"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/soehms/sage/pulls/10"
      }
    },
    "submitted_at": "2023-09-19T06:15:18Z",
    "commit_id": "2650554f514af3515a7797159e240778f81c41b2"
  },
...
```

From the [docs](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28) I don't see any function that would allow such a manipulation.

**Comment by kwankyu** [comment]
> From the [docs](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28) I don't see any function that would allow such a manipulation.

OK.

**Comment by soehms** [comment]
> I don't have enough permissions to do that in your repo. 

I've added you as collaborator. Can you try again?

> If it works for you, I am okay.

I can't do it since I'm the author (see https://github.com/soehms/sage/pull/11#issuecomment-1736667968).

**Comment by kwankyu** [comment]
I tried again, as collaborator. There are still problems.

**Comment by kwankyu** [comment]
Is this ready?

**Comment by soehms** [comment]
> Is this ready?

From my point of view: Yes! I've merged https://github.com/soehms/sage/pull/11 into this PR. Thus, everything we discussed there is done. Sorry, that I forgot to say this explicitly.

**Comment by kwankyu** [comment]
OK. Then let's get in.

**Comment by soehms** [comment]
> OK. Then let's get in.

Thanks!

**Pull request merged**
