### PR TITLE
Remove `sage.finance`, deprecated in #32427 (2021)

### PR DESCRIPTION
**Pull request by mkoeppe**
This completes the work of #32427.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by orlitzky** [comment]
It looks like the doctest change in `graphique_doctest.py` caused a failure:

```
2023-09-20T00:41:16.0190598Z Failed example:
2023-09-20T00:41:16.0191032Z     sage.stats.time_series.TimeSeries(liste).plot_histogram(bins=20)
2023-09-20T00:41:16.0191441Z Exception raised:
2023-09-20T00:41:16.0191812Z     Traceback (most recent call last):
2023-09-20T00:41:16.0192252Z       File "/sage/src/sage/doctest/forker.py", line 709, in _run
2023-09-20T00:41:16.0192741Z         self.compile_and_execute(example, compiler, test.globs)
2023-09-20T00:41:16.0193226Z       File "/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
2023-09-20T00:41:16.0193662Z         exec(compiled, globs)
2023-09-20T00:41:16.0194412Z       File "<doctest sage.tests.books.computational-mathematics-with-sagemath.graphique_doctest[26]>", line 1, in <module>
2023-09-20T00:41:16.0195111Z         sage.stats.time_series.TimeSeries(liste).plot_histogram(bins=Integer(20))
2023-09-20T00:41:16.0195554Z         ^^^^^^^^^^^^^^^^^^^^^^
2023-09-20T00:41:16.0196786Z     AttributeError: module 'sage.stats' has no attribute 'time_series'
```

**Comment by mkoeppe** [comment]
The failure in qqbar is unrelated

**Comment by orlitzky** [comment]
OK

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
