### PR TITLE
Issue #34949: sage.{categories,matrix,structure}: Replace imports from sage.*.all for namespace packages

### LINKED ISSUE #34949: sage.{categories,matrix,structure}: Replace imports from sage.*.all for namespace packages
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @tscrim @fchapoton

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34949_

### PR DESCRIPTION
**Pull request by mkoeppe**
Closes #34949

### CODE REVIEW

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Tests fail with 
```
sage -t --random-seed=119552442577065273759575227667889303090 sage/structure/element.pyx  # 6 doctests failed
```

**Comment by mkoeppe** [comment]
I've fixed this and updated all other uses as well. Let's see what Build&Test has to say now.

**Comment by mkoeppe** [comment]
Turns out the placement of `# optional` tags was not to blame, after all, it was just a bad `import`. But I'm glad I made these changes; I also fixed some missing `# optional` tags for follow-up lines in doctests.

**Review by tobiasdiez — APPROVED** [review]
LGTM. I'll leave this at "needs review" as someone else might want to have a look at it. Feel free to set it to "positive review" in a week or so.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
