### PR TITLE
Fix some doctest warnings

### PR DESCRIPTION
**Pull request by mkoeppe**
These are some of the last remaining doctest warnings as of 10.3.beta7, as seen e.g. in https://github.com/sagemath/sage/pull/37250/files "Unchanged files with check annotations".

The ones not fixed here will need a solution for:
- #36099

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dcoudert — COMMENTED** [review]
the CI indicates a doctest warning in `src/sage/geometry/polyhedron/backend_field.py` line 93 that could be fixed in this PR: `Variable 'p' referenced here was set only in doctest marked '# needs sage.rings.number_field sage.symbolic'`

**Comment by mkoeppe** [comment]
Indeed, thanks.

**Review by dcoudert — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
