### PR TITLE
`sage.monoids`: Modularization fixes, `# needs`

### PR DESCRIPTION
**Pull request by mkoeppe**
- Cherry-picked from #35095.

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by dcoudert — COMMENTED** [review]
I see a warning line 146 of `src/sage/categories/hecke_modules.py`
```
Warning: Variable 'M' referenced here was set only in doctest marked '# needs sage.libs.pari sage.modular'
```
Is it fixed in another PR ?

otherwise, LGTM.

**Comment by mkoeppe** [comment]
I've opened #38146 for this, it should become a "CI Fix"

**Review by dcoudert — APPROVED** [review]
so then, LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
