### PR TITLE
GAP 4.13.1

### PR DESCRIPTION
**Pull request by orlitzky**
Follow-up to:

* https://github.com/sagemath/sage/pull/37884
* https://github.com/sagemath/sage/pull/38169

With the four additional work items I mentioned in a comment on the latter:

1. Everything has been rebased
2. There's a new feature to detect the polenta GAP package
3. The three failing simplicial sets tests have been marked `# needs gap_package_polenta`
4. I backported https://github.com/gap-system/gap/pull/5796 to the GAP spkg so that the optional GRAPE tests will pass (untested).

Let's see what the CI has to say...

### CODE REVIEW

**Comment by orlitzky** [comment]
Locally, I've still got the `element.pyx` segfault from https://github.com/sagemath/sage/issues/37026, but everything else is passing.

The CI is unhappy about the upgrade path, but I'm not sure why exactly. This is the failure... it looks like sagelib wasn't rebuilt after GAP was upgraded. The `Makefile` should handle that IIRC.

```
2024-10-12T21:10:34.0893216Z Running doctests with ID 2024-10-12-21-10-34-b8b2f1f4.
2024-10-12T21:10:34.0894767Z Running with SAGE_LOCAL='/sage/local' and SAGE_VENV='/sage/local/var/lib/sage/venv-python3.10'
2024-10-12T21:10:34.0895510Z Using --optional=debian,pip,sage,sage_spkg
2024-10-12T21:10:34.0906368Z Features to be detected: 4ti2,SAGE_SRC,benzene,bliss,buckygen,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dvipng,ecm,fpylll,fricas,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,ipython,jmol,jupymake,jupyter_sphinx,kenzo,kissat,latte_int,lrcalc_python,lrslib,mathics,matroid_database,mcqd,meataxe,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,requests,rpy2,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sphinx,symengine_py,sympy,tdlib,threejs,topcom
2024-10-12T21:10:34.0914912Z Sorting sources by runtime so that slower doctests are run first....
2024-10-12T21:10:34.0915388Z Doctesting 7 files using 4 threads.
2024-10-12T21:10:34.7054133Z Traceback (most recent call last):
2024-10-12T21:10:34.7054986Z   File "/sage/src/bin/sage-runtests", line 9, in <module>
2024-10-12T21:10:34.7055891Z     sys.exit(main())
2024-10-12T21:10:34.7056369Z   File "/sage/src/sage/doctest/__main__.py", line 192, in main
2024-10-12T21:10:34.7056896Z     err = DC.run()
2024-10-12T21:10:34.7057321Z   File "/sage/src/sage/doctest/control.py", line 1602, in run
2024-10-12T21:10:34.7057833Z     self.run_doctests()
2024-10-12T21:10:34.7058344Z   File "/sage/src/sage/doctest/control.py", line 1186, in run_doctests
2024-10-12T21:10:34.7058972Z     self.dispatcher = DocTestDispatcher(self)
2024-10-12T21:10:34.7059543Z   File "/sage/src/sage/doctest/forker.py", line 1717, in __init__
2024-10-12T21:10:34.7060084Z     init_sage(controller)
2024-10-12T21:10:34.7060569Z   File "/sage/src/sage/doctest/forker.py", line 207, in init_sage
2024-10-12T21:10:34.7061119Z     controller.load_environment()
2024-10-12T21:10:34.7061693Z   File "/sage/src/sage/doctest/control.py", line 686, in load_environment
2024-10-12T21:10:34.7062385Z     return import_module(self.options.environment)
2024-10-12T21:10:34.7063079Z   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-10-12T21:10:34.7063842Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-10-12T21:10:34.7064586Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-10-12T21:10:34.7065115Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-10-12T21:10:34.7065674Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-10-12T21:10:34.7066233Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-10-12T21:10:34.7066768Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-10-12T21:10:34.7067350Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-10-12T21:10:34.7067983Z   File "/sage/src/sage/repl/ipython_kernel/all_jupyter.py", line 6, in <module>
2024-10-12T21:10:34.7068494Z     from sage.all_cmdline import *
2024-10-12T21:10:34.7068886Z   File "/sage/src/sage/all_cmdline.py", line 17, in <module>
2024-10-12T21:10:34.7069483Z     from sage.all import *
2024-10-12T21:10:34.7069807Z   File "/sage/src/sage/all.py", line 98, in <module>
2024-10-12T21:10:34.7070171Z     from sage.groups.all import *
2024-10-12T21:10:34.7070543Z   File "/sage/src/sage/groups/all.py", line 5, in <module>
2024-10-12T21:10:34.7070966Z     from sage.groups.matrix_gps.all import *
2024-10-12T21:10:34.7071437Z   File "/sage/src/sage/groups/matrix_gps/all.py", line 13, in <module>
2024-10-12T21:10:34.7071963Z     import sage.groups.matrix_gps.pickling_overrides
2024-10-12T21:10:34.7072523Z   File "/sage/src/sage/groups/matrix_gps/pickling_overrides.py", line 7, in <module>
2024-10-12T21:10:34.7073273Z     from sage.groups.matrix_gps.finitely_generated_gap import FinitelyGeneratedMatrixGroup_gap
2024-10-12T21:10:34.7074066Z   File "/sage/src/sage/groups/matrix_gps/finitely_generated_gap.py", line 30, in <module>
2024-10-12T21:10:34.7074750Z     from sage.groups.matrix_gps.matrix_group_gap import MatrixGroup_gap
2024-10-12T21:10:34.7075392Z   File "/sage/src/sage/groups/matrix_gps/matrix_group_gap.py", line 24, in <module>
2024-10-12T21:10:34.7076006Z     from sage.groups.libgap_mixin import GroupMixinLibGAP
2024-10-12T21:10:34.7076516Z   File "/sage/src/sage/groups/libgap_mixin.py", line 15, in <module>
2024-10-12T21:10:34.7076983Z     from sage.libs.gap.libgap import libgap
2024-10-12T21:10:34.7077509Z ImportError: libgap.so.8: cannot open shared object file: No such file or directory
```

**Comment by orlitzky** [comment]
I tried to remove `$HOME/.sage/gap` before running the tests in the CI but that didn't help. My interest in a proprietary test suite that I can't actually run only goes so far.

Tomorrow I'll test the SPKG upgrade path myself.

**Comment by dimpase** [comment]
> proprietary test suite that I can't actually run only goes so far.

It's not proprietary: you can either attach your runner to GitHub CI, or run tests fully locally: https://nektosact.com/ (you'd need Docker and go installed, though)

**Comment by enriqueartal** [comment]
For what it is worth in a test installation of Fedora 40, with this branch using spkg gap and installing gap_packages and sirocco, no gap-related test fails.

**Comment by orlitzky** [comment]
`make` doesn't rebuild the extension modules in `sage/libs/gap` after the gap upgrade. I can force it to rebuild locally by touching the three pyx files, but I guess that doesn't help the CI.

**Comment by enriqueartal** [comment]
If I understand correctly, in several local installation the branch is successful, but not in CI, because some files are not rebuilt. What can be done to make possible a positive review?

**Comment by orlitzky** [comment]
> If I understand correctly, in several local installation the branch is successful, but not in CI, because some files are not rebuilt. What can be done to make possible a positive review?

Some tweak to the makefile spaghetti is required to force a rebuild of sagelib (specifically, any extensions linked to libgap) when GAP is updated. Or as a workaround, we might touch a bunch of files to trigger said rebuild, and leave this bug for the next sucker who tries to upgrade GAP.

**Review by dimpase — COMMENTED** [review]
I imagine meson being better in sorting out dependencies

**Comment by orlitzky** [comment]
> I imagine meson being better in sorting out dependencies

Meson for sagelib won't care at all, this is a problem with the sage-the-distro "package manager" i.e. three makefiles in a trenchcoat.

**Comment by orlitzky** [comment]
I think the Conda CI is failing because the `environment-*.yaml` files pin the GAP version to 4.12.2, e.g.

```
  - gap-core=4.12.2=he8f4e70_3
  - gap-defaults=4.12.2=hce30654_3
```

**Comment by enriqueartal** [comment]
Conda packages exist for 4.13.1. Is it enough to update these files? It is worth to try.

**Comment by orlitzky** [comment]
> Conda packages exist for 4.13.1. Is it enough to update these files? It is worth to try.

Sure, I just have no idea how to do it.

**Comment by enriqueartal** [comment]
Conda still runs 4.12.2

**Comment by tobiasdiez** [comment]
I can upgrade gap in conda after https://github.com/sagemath/sage/pull/38728 is merged.

**Review by enriqueartal — APPROVED** [review]

**Comment by orlitzky** [comment]
Thanks. I can easily revert https://github.com/sagemath/sage/pull/38804/commits/34817df8f6ed9d08d1a911317a951e713a7ac952 once this lands in a beta.

Does anyone care about / know how to fix the other incremental failures? I don't have any problems on Gentoo despite the CI failing.

My main concern is that the Conda workflows will make the CI fail on every other PR until GAP is upgraded.

**Comment by tobiasdiez** [comment]
It's indeed not idea but already in Volker's release branch, so I'll try to prepare the necessary conda updates and mark them as ci-fix as soon as the new beta is out.

**Comment by dimpase** [comment]
This has completely missed the needed for gap_packages bump to libsemigroups - they should be done in lockstep. @orlitzky

**Comment by orlitzky** [comment]
> This has completely missed the needed for gap_packages bump to libsemigroups - they should be done in lockstep. @orlitzky

Sorry, it simply never occurred to me.

**Comment by dimpase** [comment]
I've opened a PR to upgrade

**Comment by dimpase** [comment]
This is certainly an upstream issue. Please report it to
github.com/gap-packages/semigroups

**Comment by culler** [comment]
I did some experiments to see what is going on here.   It turns out that the -no-avx flag causes the static assertion to fail.  If that flag is removed from the g++ command then the static assertion succeeds.  The flag is there because we were trying to support all Intel CPUs that are compatible with macOS 10.12.  Essentially we are targeting the Core-2 Duo chip, which did not support avx.  Maybe I will declare that SageMath-10-5.app requires at least a Sandy Bridge CPU.  I doubt that libsemigroups wants to do any extra work in order to support older CPUs than Sandy Bridge.  That means Mac models released before 2010.

**Comment by dimpase** [comment]
My old core2 duo macAir stopped being useful 5 or more years ago. I suppose we can drop supporting these configurations in Sage in general

**Comment by dimpase** [comment]
after all, macOS 12 has reached EOL last month.
Let's drop support for it.
https://endoflife.date/macos

**Comment by culler** [comment]
I am talking about macOS 10.12, which is 9 years old, not macOS 12 which is
only 3 years old.  I am certainly not dropping support for 3 year old
operating systems. But it isn't the macOS version that matters,  it is the
Intel CPU model.

How long we will support Intel is another question.

**Comment by dimpase** [comment]
> I am talking about macOS 10.12, which is 9 years old, not macOS 12 which is
> only 3 years old.  I am certainly not dropping support for 3 year old
> operating systems.

OK, I messed up with digita here... 
How about macOS 10?
And 11 too? @vbraun - any opinion on this?


 
 https://endoflife.date/macos

**Comment by culler** [comment]
As I said, the OS version is irrelevant.  It is the CPU model that
matters.  For SageMath-10-5.app I am setting the target OS version to 10.12
and disabling avx2 and bmi2 but not avx.  I think that makes sense.  As far
as I know there is no issue with that.  There is no point in setting the
target OS version higher than necessary.  It does not cost anything to set
it at the oldest version that builds.  And that is also the right thing to
do.

Dropping support for macOS 10 or 11 would be completely counter-productive
in my opinion, saving us nothing but definitely cutting off some users who
have machines which are updated to the newest macOS version that runs on
their hardware.

Also, this is not an issue for Sage developers.  It only matters for people
who are making binary Sage packages.

**Comment by vbraun** [comment]
Afaik the oldest hardware that Apple supports is a 2017 iMac (running Ventura). Thats 7-th Gen Intel (Kaby Lake). That definitely runs AVX. We shouldn't try to build new versions for hardware that the manufacturer abandoned.

**Comment by culler** [comment]
On Wed, Oct 30, 2024 at 7:05 PM Volker Braun ***@***.***>
wrote:

> Afaik the oldest hardware that Apple supports is a 2017 iMac (running
> Ventura). Thats 7-th Gen Intel (Kaby Lake). That definitely runs AVX. We
> shouldn't try to build new versions for hardware that the manufacturer
> abandoned.
>
Nobody is proposing to build any new versions of anything.  Certainly I am
not.  I just said that I plan to set my OS target version and the relevant
compiler flags to match the oldest OS version and oldest CPU for which
everything builds.  That seems like a no-brainer, and it is just a matter
of how I set the CFLAGS in my build script; It demands nothing of anyone
else.  I think we can stop wasting our time on this discussion, please.

- Marc

**Comment by dimpase** [comment]
This discussion comes from the fact you stumbled upon a macOS specific issue, which originated from trying to support museum-grade hardware. Which I would classify as a Sage bug. Thanks for digging it up.

If Sage didn't support the aforementioned in the first place, we would not be having this discussion in the first place. Now we have uncovered this bug, and we shall proceed to fix it. Right, @vbraun ?

**Comment by culler** [comment]
There is no Sage bug involved.  I removed the -no-avx flag from my CFLAGS
and everything built with no issue, including libsemigroups-2.7.3 and
gap_packages-4.13.1.  We learned that those two packages don't build
correctly if you set the -no-avx flag.  Removing that flag means that a
small number of very old macs will not be supported by SageMath-10-5.app,
and that is fine with me.  Nothing else needs to be done by me and nothing
at all needs to be done by Sage.

I think it was appropriate for me to report the error that I saw, before I
understood its cause.  Once I figured out what the cause was I resolved the
issue by myself.  That should be the end of this story.

I will be blunt about this:  *This discussion is over.*

**Pull request merged**
