### PR TITLE
Remove `tomli` from some build dependencies

### PR DESCRIPTION
**Pull request by mkoeppe**
No longer needed because our current version of `flit_core` vendors it.

Also eliminates one use of `--no-build-isolation`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
`flit_core` installs `tomli-w`, instead of `tomli`. Is this only needed?

**Comment by mkoeppe** [comment]
> `flit_core` installs `tomli-w`

I don't think it does; more info?

**Comment by kwankyu** [comment]
https://github.com/pypa/flit/blob/main/pyproject.toml ?

**Comment by kwankyu** [comment]
That's what `https://pypi.org/project/flit-core/` leads me to.

**Comment by mkoeppe** [comment]
In that source tree, flit-core is found in the subdirectory https://github.com/pypa/flit/tree/main/flit_core; so https://github.com/pypa/flit/blob/main/flit_core/pyproject.toml is the relevant file.

**Comment by kwankyu** [comment]
Ah, thanks. 

The relevant file has only `dependencies = []`. Then "flit_core vendors tomli"?

**Comment by mkoeppe** [comment]
> flit_core vendors tomli

Yes, see https://github.com/pypa/flit/tree/main/flit_core/flit_core/vendor

**Comment by kwankyu** [comment]
I see. tomli is included. Thanks!

**Review by kwankyu — APPROVED** [review]
Sage builds well.

**Pull request merged**
