### PR TITLE
Use GNU make tokenpool protocol to manage parallelism of doctesting

### LINKED ISSUE #30369: Parallel docbuild, cythonization: Use GNU make's POSIX jobserver protocol
<div id="comment:0"></div>

The correct way out of the mess with recommending `MAKE='make -j8'` instead of `make -j8` (which we do because of the outdated GNU make 3.81 on macOS - see #21610, #30345) is to use GNU make's POSIX job server protocol - https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html

- Create a wrapper script in Python that tries to acquire >= A, <= B jobs from the jobserver within <= T wall clock seconds, sets the environment variable `SAGE_NUM_THREADS` to min(C, NUM_JOBS_RECEIVED), and invokes an arbitrary script.  

- Use this script as a wrapper for the sagelib build and docbuild.

- Replace the recommendation `MAKE='make -j8' make` by the familiar `make -j8`.

- In the top-level `Makefile`, filter out `-j` so that also users who continue to follow the old recommendation `MAKE='make -j8' make` benefit from the improvements, and to get rid of the "disabling jobserver" messages.

CC:  @dimpase @orlitzky @jhpalmieri @Etn40ff

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/30369_

### PR DESCRIPTION
**Pull request by mkoeppe**
This is useful when running our doctester in parallel with other build steps, or several doctesters in parallel, as happens for example in `make SAGE_CHECK=yes pypi-wheels`, and more of that after #35095.

To test:
```
MAKE="make -j14" make SAGE_NUM_THREADS=100 DEBUG_JOBCLIENT=1 ptest
```
This will make the doctester attempt to use 100 workers, but it will only get tokens for 14 workers from `make`.
`DEBUG_JOBCLIENT=1` shows what's happening.

Upstream PR:
- https://github.com/milahu/gnumake-tokenpool/pull/3 (merged)

- Resolves #30369

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by orlitzky** [comment]
Do we have to make it standard? Other than that I think all it needs is some doc updates:

- `SAGE_NUM_THREADS` in `src/doc/en/installation/source.rst`
- `-p` flag in `src/bin/sage-runtests`
- A few places in `src/doc/en/developer/doctesting.rst`

**Comment by mkoeppe** [comment]
> Do we have to make it standard?

I think nothing is gained by making it optional. It's a very simple Python script

**Comment by mkoeppe** [comment]
I've made the documentation changes in 39a192667bd

**Review by orlitzky — APPROVED** [review]
I'm happy with it now, thanks.

Some day we might be able to replace `SAGE_NUM_THREADS` in the build entirely, but I'm not going to think about it too hard until ninja supports the job server.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Please don't push broken PRs to me, wtf. You are only allowed to remove the needs work after you actually check that it works.

**Comment by mkoeppe** [comment]
Sorry, I'll check what went wrong here.

**Comment by mkoeppe** [comment]
All green now.

**Comment by jhpalmieri** [comment]
This PR seems to be causing alarm problems on OS X, as reported at https://groups.google.com/g/sage-release/c/uP-rwlM__MU/m/MuI_BhfmCQAJ. It may be fine on older versions of OS X, according to someone else's experience.

**Comment by mkoeppe** [comment]
How to reproduce these failures? Do they show with `sage -tp` or only with `make ptest`?

**Comment by mkoeppe** [comment]
The `AssertionError` that you report in https://groups.google.com/g/sage-release/c/uP-rwlM__MU/m/IXLL5mZrAwAJ seems unrelated; I would think if this is new, it's coming from one of the recent IPython upgrade PRs

**Comment by jhpalmieri** [comment]
> How to reproduce these failures? Do they show with `sage -tp` or only with `make ptest`?

I've only seen them with `make ptestlong`. I've been unable to reproduce them with `sage -tp ...`.

**Comment by jhpalmieri** [comment]
> The `AssertionError` that you report in https://groups.google.com/g/sage-release/c/uP-rwlM__MU/m/IXLL5mZrAwAJ seems unrelated; I would think if this is new, it's coming from one of the recent IPython upgrade PRs

If I remember correctly, I also see this in 10.2.beta1, so it's not related to this PR. I don't know how long it's been happening. (I also see it on a linux virtual machine running on my Intel mac, so it's not just OS X.)

**Comment by mkoeppe** [comment]
It may be related to #33428

**Comment by jhpalmieri** [comment]
I consider these alarm doctest failures to be a blocker issue. Aside from reverting this PR, what options are there?

**Comment by mkoeppe** [comment]
Could you open a new Issue please with a clear reproducer (and distinguishing between `./sage -t` and `make test` and `make ptest`)?

**Comment by jhpalmieri** [comment]
> Could you open a new Issue please with a clear reproducer (and distinguishing between `./sage -t` and `make test` and `make ptest`)?

See #36944.

**Pull request merged**
