### PR TITLE
update GAP to 4.12.2

### LINKED ISSUE #34391: Upgrade: GAP 4.12
<div id="comment:0"></div>

GAP 4.12.1 fixes critical bugs in 4.12.0

[GAP 4.12.1 release page](https://www.gap-system.org/Releases/4.12.1.html)

GAP 4.12.0 was released in August 2022.

- [GAP 4.12.0 release announcement](https://lists.uni-kl.de/gap/arc/forum/2022-08/msg00031.html)
- [GAP 4.12.0 release page](https://www.gap-system.org/Releases/4.12.0.html)
- [GAP 4.12.0: changes since GAP 4.11.1](https://github.com/gap-system/gap/blob/master/CHANGES.md#gap-4120-august-2022)

We should upgrade our corresponding spkgs:

- gap
- gap_packages
- libsemigroups

Previous upgrades:

- #31498: GAP 4.11.1
- #29314: GAP 4.11, libsemigroup 1.0.9

Upstream: **Completely fixed; Fix reported upstream**

CC:  @antonio-rojas @dimpase @slel @tornaria @kiwifb @collares @tscrim

Component: **packages: standard**

Keywords: **spkg, upgrade, gap, libsemigroups**

Author: **Antonio Rojas, Dima Pasechnik**

Reviewer: **Dima Pasechnik, Antonio Rojas, Mauricio Collares, François Bissey**

_Issue created by migration from https://trac.sagemath.org/ticket/34391_

### PR DESCRIPTION
**Pull request by dimpase**
upgrades our corresponding spkgs:

* gap
* gap_packages
* libsemigroups
* Previous upgrades:
   - #31498: GAP 4.11.1
   - #29314: GAP 4.11, libsemigroup 1.0.9
* Upstream: Completely fixed; Fix reported upstream

Closes #34391

### CODE REVIEW

**Comment by mkoeppe** [comment]
Testing at https://github.com/mkoeppe/sage/actions/runs/4158242492

**Comment by tornaria** [comment]
We've been shipping an earlier version of this PR in void linux since last october when we upgraded gap to 4.12.1, without any trouble. Upgrading to 4.12.2 works ok.

My patches:
 - https://github.com/void-linux/void-packages/blob/master/srcpkgs/sagemath/patches/trac-34391-upgrade_gap_4.12-a6c293d67cfcdf8fba7bc6aa7899e2086d42cc7e.patch
 - https://github.com/void-linux/void-packages/blob/master/srcpkgs/sagemath/patches/trac-33446-make_GAP_SO_unnecessary-31e3fc4ec8b8687bccd22d2e3161c86cf5553e06.patch

For the upgrade to sagemath 9.8 I tried including the changes here and in #35094 in full, as obtained from
 - https://github.com/sagemath/sage/pull/35094.diff
but I get lots of segfaults...

However, if I keep instead the two patches I am using on 9.7, everything seems to work ok on 9.8.

I'll investigate further. Do you mind if I rebase #35094 on top of 9.8? I think that is independent of the gap upgrade.

**Comment by tornaria** [comment]
I found the issue: I was setting `GAP_ROOT_DIR` in my `sage_conf` but these variables have changed to `GAP_SHARE_DIR` and `GAP_LIB_DIR`, so gap init cannot find `lib/init.g`. Setting the new variables fixes the issue.

It's a big drastic to segfault because a file cannot be found... The message about not finding `lib/init.g` is there, but the reported segmentation fault makes the issue look much worse than it is. 

I'm back to preparing a void package for 9.8 using the whole PR  together with #35094 as in https://github.com/sagemath/sage/pull/35094.diff.

I will report back, this will build and check on x86_64 (glibc and musl), and on i686 (glibc) using system gap 4.12.2.

**Comment by kiwifb** [comment]
I decided to ship 9.8 with gap 4.12.2 in sage-on-gentoo as well. In fact I backported to sage 9.7 a few weeks ago to avoid issues with two versions of gap being available in the overlay. This upgrade has been relatively smooth compared to previous ones in gentoo.

**Comment by kiwifb** [comment]
Most of the errors I see on the runner so far, are unrelated to this upgrade. Did we figure what blocked it for 9.8 when Volker tried to merge it?

**Comment by dimpase** [comment]
> Most of the errors I see on the runner so far, are unrelated to this upgrade. Did we figure what blocked it for 9.8 when Volker tried to merge it?

imho it was just a random timeout failure on a dodgy 32-bit buildbot

**Comment by dimpase** [comment]
> Testing at https://github.com/mkoeppe/sage/actions/runs/4158995778

there is apparently a failure of the multi-stage build - any idea why, @mkoeppe ?

**Comment by kiwifb** [comment]
> > Most of the errors I see on the runner so far, are unrelated to this upgrade. Did we figure what blocked it for 9.8 when Volker tried to merge it?
> 
> imho it was just a random timeout failure on a dodgy 32-bit buildbot

Right, I'll still want to see what happens to the runner when it hits the currently queued 32bit systems but my default position is get it in ASAP.

**Comment by mkoeppe** [comment]
> > Testing at https://github.com/mkoeppe/sage/actions/runs/4158995778
> 
> there is apparently a failure of the multi-stage build - any idea why, @mkoeppe ?

Replaced by https://github.com/mkoeppe/sage/actions/runs/4167928897, which will take some time to complete

**Comment by tornaria** [comment]
Once I fixed the `GAP_*` variables, everything works, so this is :+1: from me.

Note that I am also testing 32 bit. See e.g.  https://github.com/void-linux/void-packages/actions/runs/4166635040/jobs/7211215245 (there are a few unrelated failures -- because I patched sage to support singular 4.3.1p3 but I didn't upgrade singular yet).

**Review by tornaria — APPROVED** [review]

**Comment by tornaria** [comment]
Note: I only tested sage-the-library. Also, I don't build optional packages (not even `io`, I patched atlasrep so it doesn't attempt to hit the network). I thought 2 reviews requested mean we only give positive_review when both accept.

**Review by mkoeppe — APPROVED** [review]
Portability tests at https://github.com/mkoeppe/sage/actions/runs/4167928897 seem OK. (Doctest failures come from other upgraded packages on https://github.com/mkoeppe/sage/tree/ci-10.0.beta0%2Bupgrades-2)

**Comment by mkoeppe** [comment]
> I thought 2 reviews requested mean we only give positive_review when both accept.

I don't think we have rigid rules about this. If a reviewer approves and is confident to have covered all aspects of the PR, then I'd think it's OK to set `positive review` in addition to "approving" the PR. Here for this upgrade ticket, I guess we were waiting for the portability tests to finish (= my review), so it may have been better to leave it in `needs review` status.

Let's get this upgrade in.

**Comment by tornaria** [comment]
This needs rebasing due to #35015 in just one commit.

In case it's useful, my rebase of this PR is at 1aa1d12f351, and that of #35094 is at 22457738a48.

**Comment by tornaria** [comment]
ping @dimpase : can you please rebase this and #35094 on top of 10.0.beta2 so it can be merged?

I would do it, but unfortunately I don't know any way in github to change the branch that would be merged like we used to do in trac. Is there a way?

BTW, I was skeptical of the move, but in spite of all the warts github has it's a real improvement in productivity in many, many ways. How everything was moved from trac to github is amazing and the improved search on issues is already worth it. I hope the workflow will evolve over time for good as we learn our way around.

**Comment by mkoeppe** [comment]
> I don't know any way in github to change the branch that would be merged like we used to do in trac. Is there a way?

We can promote you to "maintainer". Maintainers can make edits to other people's PRs (unless explicitly disabled when the PR is created) by pushing to the branch.

**Comment by dimpase** [comment]
> ping @dimpase : can you please rebase this and #35094 on top of 10.0.beta2 so it can be merged?
> 
done.

> I would do it, but unfortunately I don't know any way in github to change the branch that would be merged like we used to do in trac. Is there a way?

you don't have to know if you use web interface - did you try hitting "Resolve conficts" button?
It's self-evident what to do there: edit the files with conflicts in the web editor that will pop up
(it will even tell you how many conflicts you have in each file), click "mark as resolved", click "commit"...

> 
> BTW, I was skeptical of the move, but in spite of all the warts github has it's a real improvement in productivity in many, many ways. How everything was moved from trac to github is amazing and the improved search on issues is already worth it. I hope the workflow will evolve over time for good as we learn our way around.

**Comment by tornaria** [comment]
> > ping @dimpase : can you please rebase this and #35094 on top of 10.0.beta2 so it can be merged?
> 
> done.

Thanks! I hope this can be merged soon since it's a blocker for me to use the development branch on my box (i.e. every PR I want to try, I have to merge with this branch). The other not-yet merged PR cause very localized test failures, but without this sage is unusable for me.

Also because I think changing such a core package is better done early in the release cycle so it gets to be tested thoroughly.

> you don't have to know if you use web interface - did you try hitting "Resolve conficts" button? It's self-evident what to do there: edit the files with conflicts in the web editor that will pop up (it will even tell you how many conflicts you have in each file), click "mark as resolved", click "commit"...

I know how to resolve conflicts on the CLI, and I guess I would know how to do it on GH web. But the point is that:
 - [dimpase](https://github.com/dimpase) wants to merge 24 commits into [sagemath:develop](https://github.com/sagemath/sage) from [dimpase:u/dimpase/packages/gap/4_12_2](https://github.com/dimpase/sage/tree/u/dimpase/packages/gap/4_12_2)

On the one hand I cannot change the branch `dimpase:u/dimpase/packages/gap/4_12_2` since it's yours. This is the same as in trac. On the other hand, I cannot change the PR so that it "'wants to merge" a different branch  (say, under my control). This was possible on trac (we had the "Branch:" field and we could change it).
 
I tried doing a PR against your branch in your repo as the documentation somewhere suggests, but I don't know if I did that correctly.

**Comment by dimpase** [comment]
> I tried doing a PR against your branch in your repo as the documentation somewhere suggests, but I don't know if I did that correctly.

you did these PRs, they are there - but for some reason I didn't see notifications, sorry - it's not that I deliberately ignored them.

**Comment by dimpase** [comment]
CI test failure is unrelated

**Comment by vbraun** [comment]
I'm getting failures on various build bots, e.g. http://build.sagemath.org/#/builders/57/builds/1/steps/15/logs/stdio

In fact seem to be all time outs so either it hangs or got significantly slower
```
sage -t --long --random-seed=0 src/doc/en/thematic_tutorials/group_theory.rst  # Timed out
sage -t --long --random-seed=0 src/sage/coding/linear_code.py  # Timed out
sage -t --long --random-seed=0 src/sage/combinat/designs/incidence_structures.py  # Timed out
sage -t --long --random-seed=0 src/sage/graphs/generic_graph.py  # Timed out
sage -t --long --random-seed=0 src/sage/groups/finitely_presented_named.py  # Timed out
sage -t --long --random-seed=0 src/sage/groups/perm_gps/permgroup.py  # Timed out
sage -t --long --random-seed=0 src/sage/groups/perm_gps/permgroup_morphism.py  # Timed out
sage -t --long --random-seed=0 src/sage/topology/simplicial_complex.py  # Timed out
sage -t --long --random-seed=0 src/sage/topology/simplicial_complex_examples.py  # Timed out
```

**Comment by dimpase** [comment]
@vbraun - I have no idea why these "slow AIMS" buildbots are timing out. Not for the 1st time. 
Neither you have an idea.

 Let's move on and merge this please.

**Comment by tornaria** [comment]
> I'm getting failures on various build bots, e.g. http://build.sagemath.org/#/builders/57/builds/1/steps/15/logs/stdio
> 
> In fact seem to be all time outs so either it hangs or got significantly slower
> 
> ```
> sage -t --long --random-seed=0 src/doc/en/thematic_tutorials/group_theory.rst  # Timed out
> sage -t --long --random-seed=0 src/sage/coding/linear_code.py  # Timed out
> sage -t --long --random-seed=0 src/sage/combinat/designs/incidence_structures.py  # Timed out
> sage -t --long --random-seed=0 src/sage/graphs/generic_graph.py  # Timed out
> sage -t --long --random-seed=0 src/sage/groups/finitely_presented_named.py  # Timed out
> sage -t --long --random-seed=0 src/sage/groups/perm_gps/permgroup.py  # Timed out
> sage -t --long --random-seed=0 src/sage/groups/perm_gps/permgroup_morphism.py  # Timed out
> sage -t --long --random-seed=0 src/sage/topology/simplicial_complex.py  # Timed out
> sage -t --long --random-seed=0 src/sage/topology/simplicial_complex_examples.py  # Timed out
> ```

Based on the last thing executed before each timeout, my guess is that it might be a network timeout. Is this bot network filtered  in some way? It turns out atlasrep will try to download some data files to shortcut some computations.

Could you try patching gap with [atlasrep-dont_use_network_by_default.patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gap/patches/atlasrep-dont_use_network_by_default.patch) which changes the default for atlasrep to not download data files? The actual computations don't take long (at least the ones done by sage doctests).

**Comment by dimpase** [comment]
> Could you try patching gap with [atlasrep-dont_use_network_by_default.patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gap/patches/atlasrep-dont_use_network_by_default.patch) which changes the default for atlasrep to not download data files? The actual computations don't take long (at least the ones done by sage doctests).

OK, done. @vbraun - could you please check on the bots if it helps.

**Comment by vbraun** [comment]
Yes the buildbots poison the `http_proxy` environment variables to prevent unwanted network access

**Comment by tornaria** [comment]
> Yes the buildbots poison the `http_proxy` environment variables to prevent unwanted network access

How? So I can try to reproduce this locally.

**Comment by vbraun** [comment]
I'm setting (python syntax)
```
        offline_env['http_proxy'] = 'http://192.0.2.0:5187/'
        offline_env['https_proxy'] = 'http://192.0.2.0:5187/'
        offline_env['ftp_proxy'] = 'http://192.0.2.0:5187/'
        offline_env['rsync_proxy'] = 'http://192.0.2.0:5187/'
```

**Comment by dimpase** [comment]
> > Could you try patching gap with [atlasrep-dont_use_network_by_default.patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gap/patches/atlasrep-dont_use_network_by_default.patch) which changes the default for atlasrep to not download data files? The actual computations don't take long (at least the ones done by sage doctests).


just in case, to revert the effect of this patch at the start of Sage session, one can do
```
libgap.SetUserPreference("AtlasRep", "AtlasRepAccessRemoteFiles", true )
```
this has to happen at the startup - after `AtlasRep` is loaded, it has no effect.

**Pull request merged**
