### PR TITLE
Make matroid `copy` and `deepcopy` simply return `self`

### PR DESCRIPTION
**Pull request by gmou3**
I abstracted all `copy`/`deepcopy` subclass implementations to a generic one in the main matroid class (in `matroid.pyx`).
I am unsure as to whether something of value is lost with this change (e.g. relating to the manual `memo` passing in `deepcopy`).

This follows a recommendation by @mkoeppe made in https://github.com/sagemath/sage/pull/37340#discussion_r1537110548.

### ⌛ Dependencies
* Depends on #37667

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Comment by vbraun** [comment]
merge conflict

**Comment by gmou3** [comment]
I just tried and it got merged cleanly.

**Comment by mkoeppe** [comment]
This "merge conflict" message means that there was a conflict when Volker tried to merge it into his integration branch.

**Comment by mkoeppe** [comment]
There is a conflict with #37667; if you want, you can merge it here to resolve the conflict.

**Comment by gmou3** [comment]
Got it. Thanks!

**Pull request merged**
