### PR TITLE
.github/workflows/docker.yml: Remove defunct steps that refer to Trac

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

`docker.yml` still had some steps (used by upstream projects that use this reusable workflow) that referred to Trac. As we have taken down Trac, upstream ci-sage workflows would fail (see https://github.com/scipopt/SCIP-SDP/pull/4#issuecomment-1574939863)
We remove these steps now.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
so, no need to replace these steps by anything ?

**Comment by mkoeppe** [comment]
I may or may not build a similar feature using GitHub PRs, but making that available is not urgent

**Review by fchapoton — APPROVED** [review]
ok, well, then

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
