### PR TITLE
add doctest for #13569

### LINKED ISSUE #13569: group multiplication seems to depend on order sometimes
<div id="comment:0"></div>

See [this ask.sagemath.org question](http://ask.sagemath.org/question/1836/order-of-elements-in-group-multiplication).  This doesn't always happen, but usually happens pretty soon.

```
sage: G.random_element()*H.random_element()
(1,3,2)
sage: H.random_element()*G.random_element()
()
sage: H.random_element()*G.random_element()
(1,2,3)
sage: H.random_element()*G.random_element()
(1,2,3)
sage: H.random_element()*G.random_element()
(1,3,2)
sage: H.random_element()*G.random_element()
ERROR: An unexpected error occurred while tokenizing input

TypeError: unsupported operand parent(s) for '*': 'Alternating group of order 3!/2 as a permutation group' and 'Symmetric group of order 3! as a permutation group'
```

Component: **group theory**

_Issue created by migration from https://trac.sagemath.org/ticket/13569_

### PR DESCRIPTION
**Pull request by mezzarobba**
Closes #13569.

### CODE REVIEW

**Review by edgarcosta — APPROVED** [review]

**Review by edgarcosta — CHANGES_REQUESTED** [review]
Could you add a reference to the test saying:
`This test addresses ticket ...`

However, I am unsure of the format now that we are using GitHub

**Comment by edgarcosta** [comment]
I heard back from @roed314, and it is okay to have
```
This test addresses ticket :trac:`13569`::
```

**Comment by mezzarobba** [comment]
On Wednesday, 8 February 2023 00:31:54 CET Edgar Costa wrote:
> Could you add a reference to the test saying:
> `This test addresses ticket ...`

Done.

**Review by fchapoton — APPROVED** [review]
ok, good to go

**Review by roed314 — APPROVED** [review]

**Pull request merged**
