### PR TITLE
Doc preview for all languages

### PR DESCRIPTION
**Pull request by kwankyu**
Currently our doc preview for PR is uploading only English docs. We fix it for all languages.

Along the way, we remove more spurious diffs in CHANGES.

Note that the doc preview for this PR is somewhat broken. But this would be ironed out in the next beta.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Looks like we should exclude `en/jupyter_execute` from [the diff ](https://deploy-preview-36601--sagemath-tobias.netlify.app/changes)

**Comment by kwankyu** [comment]
> Looks like we should exclude `en/jupyter_execute` from [the diff ](https://deploy-preview-36601--sagemath-tobias.netlify.app/changes)

Right... I will fix it here.

**Comment by kwankyu** [comment]
> > Looks like we should exclude `en/jupyter_execute` from [the diff ](https://deploy-preview-36601--sagemath-tobias.netlify.app/changes)
> 
> Right... I will fix it here.

I fixed it by "diff"ing only html files.

**Comment by mkoeppe** [comment]
Looking great!

**Comment by kwankyu** [comment]
Thank you!

**Pull request merged**
