### PR TITLE
Replace relative imports by absolute ones in rings

### PR DESCRIPTION
**Pull request by tobiasdiez**
As preparation for compiling with meson, we replace relative imports by absolute ones.
Relative imports are not used consistently in the codebase and result in issues for doctesting with pytest (which admittedly is a limitation of pytest). We normalize the relative imports in `sage.rings` to be absolute imports. Small code-style improvements along the way (mainly to nicely order the imports)

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
The only thing that is needed to solve the problem with Cython is to take care of relative `cimport`s, not `import`s. 

Doing this in one PR creates lots of gratuitous merge conflicts with #35095.

**Comment by tobiasdiez** [comment]
As the description of this PR says, my main motivation is making it work with pytest. For this the normal imports have to be changed as well. I'm sorry for the merge conflicts, but they should be easy to resolve.

**Comment by mkoeppe** [comment]
Rebased cleanly -- without need for manual intervention -- on top of https://github.com/sagemath/sage/pull/36666.

**Review by dimpase — APPROVED** [review]
LGTM. Is #36666 strictly contained here? If so, #36666 may be closed.

**Comment by mkoeppe** [comment]
> Is #36666 strictly contained here? If so, #36666 may be closed.

Note that Tobias force-pushed his original branch. It no longer contains the changes from #36666.

**Comment by tobiasdiez** [comment]
> LGTM. Is #36666 strictly contained here? If so, #36666 may be closed.

Thanks a lot for the review!

With the similar PRs https://github.com/sagemath/sage/pull/36572 and https://github.com/sagemath/sage/pull/36589, #36666 can indeed be closed I think. So I would very much appreciate if you could review these PRs as well.

**Pull request merged**
