### PR TITLE
Improving the documentation of Discrete Dynamical Systems by fixing typos and eliminating repeated sentences

### LINKED ISSUE #37188: Improve the documentation of discrete dynamical systems
### Steps To Reproduce

There are typos and repeated sentences in https://doc.sagemath.org/html/en/reference/dynamics/sage/dynamics/finite_dynamical_system.html

### Expected Behavior

There shouldn't be any typos!

### Actual Behavior

There are typos!

### Additional Information

Tthis, A discrete dynamical system (henceforth DDS) is a pair of a set and a map . This set is called the ground set of the DDS, while the map is called the evolution of the DDS.

A discrete dynamical system (short: DDS) is a pair of a set and a map .

### Environment

```markdown
irrelevant
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by Dhrumil07**
The typos and the repeated sentences issue in the documentation of [Discrete dynamical systems](https://doc.sagemath.org/html/en/reference/dynamics/sage/dynamics/finite_dynamical_system.html) is solved

Fixes #37188 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

None.

### CODE REVIEW

**Comment by mantepse** [comment]
Please edit the description from "It fixes the issue https://github.com/sagemath/sage/issues/37188" to `Fixes #37188`, otherwise this won't show up there.

**Comment by Omegaconstant** [comment]
Hi,
Glad to see this PR :-)

Earlier, I made a few notes while doing some changes (but did not push them). Here, I am suggesting some changes; it would be great if @mantepse and @Dhrumil07 put some thoughts/ comments on this.

In line number 5
```
-    A *discrete dynamical system* (henceforth *DDS*) is a
+    A *discrete dynamical system* (short: *DDS*) is a
```

In line number 55:
```
-      infection on a chessboard; Conway's game of life.
+      infection on a chessboard; Conway's Game of Life.
```

In line number 99:
```
-    A *discrete dynamical system* (henceforth *DDS*) is a
+    A *discrete dynamical system* (short: *DDS*) is a
     pair `(X, \phi)` of a set `X` and a map `\phi : X \to X`.
-    This set `X` is called the *ground set* of the DDS, while
-    the map `\phi` is called the *evolution* of the DDS.
-
-    A *discrete dynamical system* (short: *DDS*) is a pair
-    `(X, \phi)` of a set `X` and a map `\phi : X \to X`.
-    (This is one of several things known as a "discrete
-    dynamical system" in mathematics.)
-    Thus, a DDS is the same as an endomorphism of a set.
-    The DDS is said to be *finite* if `X` is finite.
+    A DDS is the same as an endomorphism of a set.
+    The DDS is said to be *finite* if the set `X` is finite.
     The DDS is said to be *invertible* if the map `\phi` is
     invertible.
     The set `X` is called the *ground set* of the DDS;
-    the map `\phi` is called the *evolution* of the DDS;
+    the map `\phi` is called the *evolution* of the DDS; and
     the inverse map `\phi^{-1}` (when it exists) is called the
     *inverse evolution* of the DDS.

```

In line number 510:
```
-            A discrete dynamical system with ground set
+            A discrete dynamical system with a ground set
```

In line number 514:
```
-            A discrete dynamical system with unspecified ground set
+            A discrete dynamical system with an unspecified ground set
```

In line number 517:
```
-            return "A discrete dynamical system with unspecified ground set"
+            return "A discrete dynamical system with an unspecified ground set"
```

In line number 518:
```
-            return "A discrete dynamical system with ground set " \
+            return "A discrete dynamical system with a ground set " \
```

In line number 693:
```
-    A *discrete dynamical system* (henceforth *DDS*) is a
+    A *discrete dynamical system* (short: *DDS*) is a
```

In line number 721:
```
-      argument is not provided; but it assumes the orbits
+      argument is not provided, but it assumes the orbits
```

In line number 840:
```
-            An invertible discrete dynamical system with ground set
+            An invertible discrete dynamical system with a ground set
```

In line number 844:
```
-            An invertible discrete dynamical system with unspecified ground set
+            An invertible discrete dynamical system with an unspecified ground set
```

In line number 847 and 848:
```
-            return "An invertible discrete dynamical system with unspecified ground set"
-        return "An invertible discrete dynamical system with ground set " \
+            return "An invertible discrete dynamical system with an unspecified ground set"
+        return "An invertible discrete dynamical system with a ground set " \
```

In line number 984:
```
-    A *finite discrete dynamical system* (henceforth *FDDS*) is a
+    A *finite discrete dynamical system* (short: *FDDS*) is a
```

In line number 1022:
```
-            A finite discrete dynamical system with ground set
+            A finite discrete dynamical system with a ground set
```

In line number 1025:
```
-        return "A finite discrete dynamical system with ground set " \
+        return "A finite discrete dynamical system with a ground set " \
```

In line number 1128:
```
-    A *finite discrete dynamical system* (henceforth *FDDS*) is a
+    A *finite discrete dynamical system* (short: *FDDS*) is a
```

In line number 1177:
```
-            An invertible finite discrete dynamical system with ground set
+            An invertible finite discrete dynamical system with a ground set
```

In line number 1180:
```
-        return "An invertible finite discrete dynamical system with ground set " \
+        return "An invertible finite discrete dynamical system with a ground set " \
```


Thank you.

**Comment by mantepse** [comment]
I don't think that the article (mostly before "ground set", eg. "An invertible finite discrete dynamical system with a ground set") is correct.  Moreover, this might change doctests of code outside of sage, which I'd rather not do.

I don't mind `henceforth` vs. `short:`, I think that either is OK.

I am more used to `is called` (rather than `is said`).

**Comment by Dhrumil07** [comment]
Thank you @Omegaconstant for your input. 

Some of the changes that you suggest are about changing `therefore` to `short`, to which @mantepse mentioned either of the terminology to be ok.

The other changes are regarding the correct use of articles `a, an, the` at some places.
@mantepse are we focusing on these minute article errors in this issue?

Also, regarding preferring `is called` over `is said`, I will add a commit to the PR, to fix it.

**Comment by mantepse** [comment]
@Dhrumil07, please fix the linter error (and please run the linter before pushing), see https://doc.sagemath.org/html/en/developer/tools.html

**Comment by Dhrumil07** [comment]
@mantepse thank you for pointing out the linter error. I have fixed the linter error and also run the linter before pushing the commit.

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Pull request merged**
