### PR TITLE
Default SAGE_ECMBIN to "ecm".

### PR DESCRIPTION
**Pull request by tornaria**
Having `None` as default breaks the feature ecm.  This restores the previous default, which corresponds to the upstream name for the binary.

See https://github.com/sagemath/sage/pull/37011#issuecomment-2023089743

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.

### CODE REVIEW

**Comment by enriqueartal** [comment]
I have tried this change in Fedora 39, checking in particular the failing test in https://github.com/sagemath/sage/pull/37011#issuecomment-2027360506

I see no change: successful if it uses the system package, error with the spkg `ecm`. Do I miss something? I run `./bootstrap`, `configure --with-system-ecm=no` and `make build`.

**Comment by dimpase** [comment]
it's something with Sage's ecm, nothing to do with this PR

**Review by dimpase — APPROVED** [review]
lgtm. please change the tags, I am on a phone

**Comment by dimpase** [comment]
> I have tried this change in Fedora 39, checking in particular the failing test in https://github.com/sagemath/sage/pull/37011#issuecomment-2027360506
> 
> I see no change: successful if it uses the system package, error with the spkg `ecm`. Do I miss something? I run `./bootstrap`, `configure --with-system-ecm=no` and `make build`. 

please open another issue - this one doesn't have anything to do with Sage's ecm spkg

**Pull request merged**
