### PR TITLE
provide default argument for monomial_coefficients

### LINKED ISSUE #39037: leading_coefficient() for multivariate polynomials exists but fails with a strange error
### Steps To Reproduce

```
sage: P.<x,y> = QQ[]
sage: x.leading_coefficient()
```

### Expected Behavior

Not sure. I think the method is new (i.e. this used to raise an `AttributeError`). It should probably do the same as `lc()`, at least if the definitions are compatible.

### Actual Behavior

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/co/sage/src/sage/categories/modules_with_basis.py:1676, in ModulesWithBasis.ElementMethods.support(self)
   1675 try:
-> 1676     return self._support_view
   1677 except AttributeError:

File ~/co/sage/src/sage/structure/element.pyx:495, in sage.structure.element.Element.__getattr__()
    494 """
--> 495 return self.getattr_from_category(name)
    496

File ~/co/sage/src/sage/structure/element.pyx:508, in sage.structure.element.Element.getattr_from_category()
    507     cls = P._abstract_element_class
--> 508 return getattr_from_other_class(self, cls, name)
    509

File ~/co/sage/src/sage/cpython/getattr.pyx:363, in sage.cpython.getattr.getattr_from_other_class()
    362     dummy_error_message.name = name
--> 363     raise AttributeError(dummy_error_message)
    364 attribute = <object>attr

AttributeError: 'sage.rings.polynomial.multi_polynomial_libsingular.MPolynomial_libsingular' object has no attribute '_support_view'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 x.leading_coefficient()

File ~/co/sage/src/sage/categories/modules_with_basis.py:1923, in ModulesWithBasis.ElementMethods.leading_coefficient(self, *args, **kwds)
   1896 def leading_coefficient(self, *args, **kwds):
   1897     r"""
   1898     Return the leading coefficient of ``self``.
   1899
   (...)
   1921         -5
   1922     """
-> 1923     return self.leading_item(*args, **kwds)[1]

File ~/co/sage/src/sage/categories/modules_with_basis.py:1864, in ModulesWithBasis.ElementMethods.leading_item(self, *args, **kwds)
   1831 def leading_item(self, *args, **kwds):
   1832     r"""
   1833     Return the pair ``(k, c)`` where
   1834
   (...)
   1862         ([3], -5)
   1863     """
-> 1864     k = self.leading_support(*args, **kwds)
   1865     return k, self[k]

File ~/co/sage/src/sage/categories/modules_with_basis.py:1829, in ModulesWithBasis.ElementMethods.leading_support(self, *args, **kwds)
   1802 def leading_support(self, *args, **kwds):
   1803     r"""
   1804     Return the maximal element of the support of ``self``.
   1805
   (...)
   1827         [3]
   1828     """
-> 1829     return max(self.support(), *args, **kwds)

File ~/co/sage/src/sage/categories/modules_with_basis.py:1680, in ModulesWithBasis.ElementMethods.support(self)
   1678 from sage.structure.support_view import SupportView
   1679 zero = self.parent().base_ring().zero()
-> 1680 mc = self.monomial_coefficients(copy=False)
   1681 support_view = SupportView(mc, zero=zero)
   1682 try:
   1683     # Try to cache it for next time, but this may fail for Cython classes

TypeError: monomial_coefficients() got an unexpected keyword argument 'copy'
```

### Additional Information

Probably an unintended consequence of #38767. The same issue likely applies to `leading_monomial()` and possibly some other methods.

### Environment

Sage 10.5.rc0

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mantepse**
This is a followup to #38767, where we put polynomials into the category of modules with basis.  Back then, we missed the fact that `monomial_coefficients` should take an optional argument `copy`, which we fix here.

Fixes #39037

### CODE REVIEW

**Comment by mezzarobba** [comment]
Thanks for looking into the issue! The fix looks good to me except for the typo revealed by the tests.

**Comment by mezzarobba** [comment]
Would you mind tests that `leading_monomial()` and `leading_term()` work correctly on multivariate polynomials, though?

**Comment by user202729** [comment]
Would also be useful to have test for both cases (`copy=False` and `copy=True`), as well as adding documentation what it means (ideally just point all of them to one place)

**Comment by mantepse** [comment]
> Would also be useful to have test for both cases (`copy=False` and `copy=True`), as well as adding documentation what it means (ideally just point all of them to one place)

It's not clear to me how to do this without a lot of boring work which I'd rather not do.  There is not really a benefit, I think.

**Comment by mantepse** [comment]
@fchapoton, the linter is complaining, should I fix these here or separately?  Also, what is the correct invocation at home?  If I do `./sage -tox -e pycodestyle-minimal -- src/sage/rings/polynomial/multi_polynomial.pyx` it is selecting the wrong set of rules:
```
pycodestyle-minimal: commands[0] /home/martin/sage-trac/src> pycodestyle --select E111,E21,E221,E222,E225,E227,E228,E25,E271,E275,E303,E305,E306,E401,E502,E701,E702,E703,E71,E72,W291,W293,W391,W605 sage/rings/polynomial/multi_polynomial.pyx
sage/rings/polynomial/multi_polynomial.pyx:483:22: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:536:21: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:536:25: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:546:25: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:546:36: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:547:21: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:547:33: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:568:34: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:778:16: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:778:28: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:778:51: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:778:63: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:2131:19: E225 missing whitespace around operator
sage/rings/polynomial/multi_polynomial.pyx:2137:23: E225 missing whitespace around operator
14      E225 missing whitespace around operator
pycodestyle-minimal: exit 1 (0.15 seconds) /home/martin/sage-trac/src> pycodestyle --select E111,E21,E221,E222,E225,E227,E228,E25,E271,E275,E303,E305,E306,E401,E502,E701,E702,E703,E71,E72,W291,W293,W391,W605 sage/rings/polynomial/multi_polynomial.pyx pid=27666
  pycodestyle-minimal: FAIL code 1 (0.21=setup[0.07]+cmd[0.15] seconds)
  evaluation failed :( (0.37 seconds)
```

**Comment by fchapoton** [comment]
the linter must pass. You just need to start with `r"""` the block containing the new `\Z`

**Comment by user202729** [comment]
Thinking about it…

It might be much better for the user to just deprecate the `copy` feature and requires `copy=True` everywhere. It's better for elements to be immutable anyway, and especially not by mutating an unrelated object.

But then grepping for `monomial_coefficients(copy=False)` in the code base, it *is* used in quite a lot of places as a small performance optimization. Not sure if it's worth it (we can always move `copy=False` to an internal implementation detail e.g. `def _monomial_coefficients_nocopy()` which classes can define if it has a special no-copy version)

**Comment by tscrim** [comment]
No, we definitely should *not* get rid of `copy` input. It is a very important performance feature for sparse implementations already in that `dict` form. Specifically `IndexedFreeModuleElement`.

**Comment by mantepse** [comment]
Alternatively, would it make sense to return an immutable `dict`?

(But, please, not in this PR)

**Comment by user202729** [comment]
Python doesn't have immutable dict. Maybe a dict view would be reasonable but that would be significant change… yes, for this PR we should not consider that issue.

**Comment by tscrim** [comment]
Indeed Python doesn't, and sometimes we do want to modify the internal `dict`.

**Comment by mantepse** [comment]
> Would you mind tests that `leading_monomial()` and `leading_term()` work correctly on multivariate polynomials, though?

I did add doctests, involving different term orderings, see for example `src/sage/categories/modules_with_basis.py` lines 1906ff.

Is this what you had in mind, @mezzarobba ?

**Comment by mezzarobba** [comment]
Yes, thank you!

**Review by mezzarobba — APPROVED** [review]

**Pull request merged**
