### PR TITLE
Use `pypa/build` instead of `pip wheel`

### LINKED ISSUE #34590: Use python-build instead of "pip wheel"
<div id="comment:0"></div>

(for packages that don't use `--no-use-pep517`)

... as another step to more modern tooling.

Depends on #34344
Depends on #34272
Depends on #32483

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/34590_

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

This is the next step of the long term effort to use the standard tools of modern Python packaging in the build system of the Sage distribution, enabled by making `python_build` a standard package. We add `python_build` to our `PYTHON_TOOLCHAIN` and replace the use of `pip wheel` by using `python -m build`.

- Resolves #34590.
- Also, we remove the unused helper function `sdh_prefix_args`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #37300

### CODE REVIEW

**Comment by kwankyu** [comment]
This seems related
```
Using cached file /Users/kwankyu/GitHub/sage-dev/upstream/editables-0.5.tar.gz
Setting up build directory /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/editables-0.5
No patch files found in ../patches
Host system: Darwin Hera.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64 x86_64
C compiler: gcc, Apple clang version 14.0.0 (clang-1400.0.29.202), Target: x86_64-apple-darwin21.6.0, Thread model: posix, InstalledDir: /Library/Developer/CommandLineTools/usr/bin
No stamp file for package 'editables' in /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/lib/sage/installed
No spkg-legacy-uninstall script; nothing to do
[spkg-install] Installing editables-0.5
[spkg-install] /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3: No module named build
[spkg-install] Warning: building with "python3 -m build --wheel --outdir=dist   ." failed.
[spkg-install] Retrying with "python3 -m build --wheel --outdir=dist --no-isolation --skip-dependency-check  .".
[spkg-install] /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3: No module named build
[spkg-install] ********************************************************************************
[spkg-install] Error building a wheel for editables-0.5
[spkg-install] ********************************************************************************
************************************************************************
Error installing package editables-0.5    
```

**Comment by mkoeppe** [comment]
Indeed. I've pushed a fix.

**Review by kwankyu — APPROVED** [review]
working fine.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
