### PR TITLE
`sage.libs.pari`, `sage.rings.real_mpfr`: Modularization fixes

### PR DESCRIPTION
**Pull request by mkoeppe**
Main change: Eliminate the compile-time dependency of `sage.rings.real_mpfr` on PARI.

- Cherry-picked from #35095

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Merge conflict

**Comment by tornaria** [comment]
Something weird is happening after this.

The file `src/sage/libs/pari/convert_sage_matrix.pyx` is not being compiled, and thus I get `ModuleNotFoundError: No module named 'sage.libs.pari.convert_sage_matrix'`.

I cleaned up everything to start from scratch in case this was something, but still same failure.

**Comment by mkoeppe** [comment]
Hmm.... it has a `sage_setup: distribution` line by mistake, try deleting that

**Comment by mkoeppe** [comment]
Which setup.py do you use?

**Comment by mkoeppe** [comment]
I'll open a PR that fixes this.

**Comment by tornaria** [comment]
> Which setup.py do you use?

The one in `pkgs/sagemath-standard`, been doing that for a long time.

**Comment by tornaria** [comment]
> Hmm.... it has a `sage_setup: distribution` line by mistake, try deleting that

Yes, that works.

**Pull request merged**
