### PR TITLE
Scipy 1.12

### PR DESCRIPTION
**Pull request by mkoeppe**
https://scipy.github.io/devdocs/release/1.12.0-notes.html

"requires Python 3.9+ and NumPy 1.22.4 or greater"

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #37252

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
It works well.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by tornaria** [comment]
scipy 1.13 was released https://scipy.github.io/devdocs/release/1.13.0-notes.html

It still "requires Python 3.9+ and NumPy 1.22.4 or greater", but it "aims to support NumPy 2.0.0".

It works fine after the trivial doctest fix in #37763 (fwiw, I only tested with numpy 1.26.4)

**Comment by mkoeppe** [comment]
Yes, I think we'll do that update when NumPy 2.0.0 comes out

**Pull request merged**
