### PR TITLE
Drop obsolete html5lib package

### PR DESCRIPTION
**Pull request by orlitzky**
I'm pretty sure this package is obsolete, let's see.

### CODE REVIEW

**Comment by jhpalmieri** [comment]
This looks okay to me. Sage builds and passes tests, and `html5lib` is not mentioned anywhere in the source code except in its own build directory.

**Comment by kwankyu** [comment]
I don't know if this is worth to be kept or not. But this is a standard package. What is the drop procedure of a standard package? I can't find anything in the developer manual.

It seems reasonable to me there is a one-year deprecation period when we drop a (standard) package. Or needs a discussion in sage-devel?

@mkoeppe ?

**Comment by jhpalmieri** [comment]
I find it very unlikely that someone both (a) relies on `html5lib` in Sage and (b) can't pip-install it themselves. I don't see a need for a deprecation period. About two years ago we removed `ATLAS` (#30350) and `mpir` (#32549) without any deprecation, so there is precedent.

**Comment by kwankyu** [comment]
OK. Thanks.

**Comment by mkoeppe** [comment]
I agree with John that a deprecation period is not needed for changes like this. This package was added because it was a dependency of another standard package, `bleach`, which is a dependency of the user-facing package `nbconvert`, which is invoked by a Jupyter menu item.

By the way, `html5lib` is not really "obsolete". We just don't need to install it any more because `bleach` started to vendor its own copy of `html5lib` 1.1 at some point.

**Comment by vbraun** [comment]
merge conflict

**Pull request merged**
