### PR TITLE
Replace relative imports by absolute ones in modules

### PR DESCRIPTION
**Pull request by tobiasdiez**
Relative imports are not used consistently in the codebase and result in issues for doctesting with pytest (which admittedly is a limitation of pytest). We normalize the relative imports in `sage.modules` to be absolute imports. Small code-style improvements along the way (mainly to nicely order the imports).

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
> dup of #36594?

Kind of, but I'm also doing python files here.

**Comment by mkoeppe** [comment]
Same comment as https://github.com/sagemath/sage/pull/36588#issuecomment-1792842988

**Comment by mkoeppe** [comment]
Needs rebasing.

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by tobiasdiez** [comment]
Thanks Dima for the review!

**Pull request merged**
