### PR TITLE
build/pkgs/sphinx: Set upper bound <7.3

### PR DESCRIPTION
**Pull request by mkoeppe**
Because of:
- #37996

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by kiwifb — APPROVED** [review]
LGTM

**Comment by mkoeppe** [comment]
Thanks!

**Comment by kwankyu** [comment]
Sorry for being late. But we may close this PR in favor of #38100 if it works well.

**Comment by mkoeppe** [comment]
Closing as suggested

**Pull request closed without merging**
