### PR TITLE
Deprecate `is_Algebra`, `is_CommutativeAlgebra`

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description
Part of 
- https://github.com/sagemath/sage/issues/32738
- #32414

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
One currently needs to be careful about testing against `CommutativeAlgebras(base_ring)` as the category of `A` might be `CommutativeAlgebras(base_ring.category())` (this was done to not create large numbers of equivalent categories over, say, `GF(p)`). There needs to be a better mechanism to test this, but the current change actually makes the test more strict than it was before. So code in the wild might fail.

**Comment by mkoeppe** [comment]
Nice catch. I'll add a test for this

**Comment by mkoeppe** [comment]
Hm... Do you have an example? It looks to me to be a non-issue because
```
sage: CommutativeAlgebras(QQ).is_subcategory(CommutativeAlgebras(QQ.category()))
True
```

**Comment by mkoeppe** [comment]
Or rather, because:
```
sage: QQ['a'].category()
Join of Category of euclidean domains and Category of commutative algebras over (number fields and quotient fields and metric spaces) and Category of infinite sets
sage: QQ['a'] in CommutativeAlgebras(QQ)
True
sage: QQ['a'] in CommutativeAlgebras(QQ.category())
True
```

**Comment by tscrim** [comment]
I guess this was fixed at some point (or I am remembering a slightly different but similar issue I had seen before). That's good.

Although now we have another issue which is that we don't want to create a whole family of categories over `GF(p)`. So we should just replace `Algebras(base_ring)` with `Algebras(base_ring.category())` and similar.

**Comment by mkoeppe** [comment]
Thanks, this seems to work

**Review by tscrim — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
