### PR TITLE
Fix French notation for Tableau plots

### PR DESCRIPTION
**Pull request by thecaligarmo**
### 📚 Description

The change fixes a bug in which the plot of a Tableau was not properly showing French notation when trying to display the plot.

The fix in place allows the plot of a Tableau to accurately show the tableau in both French and English notation, as requested by the user.

This resolves open issue: #33998 which was imported from Trac

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

(As the issue is with plot and is a bug; no tests can cover the changes and documentation does not need changing)

### CODE REVIEW

**Comment by dimpase** [comment]
don't you want to add tests to show this output in the different conventions? maybe using `sphinx_plot()`, e.g. like in
`src/sage/combinat/path_tableaux/frieze.py`

**Comment by thecaligarmo** [comment]
> don't you want to add tests to show this output in the different conventions? maybe using `sphinx_plot()`, e.g. like in `src/sage/combinat/path_tableaux/frieze.py`

Good idea =D I've included a couple of plots to show the difference. I think there's no way to test them though right?

**Comment by dimpase** [comment]
looking at the results (actually, right  here, after `build-docs` CI step is done would be good enough. Also, the edicational value of seeing the difference between French and English in the docs is a plus.

**Review by dimpase — CHANGES_REQUESTED** [review]
can we have these examples slightly less non-generic? (It would also take away the fear that in general it might not work)

**Review by dimpase — APPROVED** [review]
lgtm

**Pull request merged**
