### PR TITLE
Make installation of "wheel" packages less noisy

### PR DESCRIPTION
**Pull request by mkoeppe**
Some care for `build/bin/sage-spkg`, reducing unhelpful verbosity. In particular, for "wheel" packages (https://deploy-livedoc--sagemath.netlify.app/html/en/developer/packaging#package-source-types), there is no build step, so there is no point in talking about what C compiler is in use.
 
Also saving a few lines of output (and making it clearer who does what) by prefixing the output from the various `spkg-...` scripts.

Example:
```
$ make packaging-no-deps
[packaging-23.2] Using cached file /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/upstream/packaging-23.2-py3-none-any.whl
[packaging-23.2] Setting up build directory /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/packaging-23.2
[packaging-23.2] [spkg-piprm] Found existing installation: packaging 23.2
[packaging-23.2] [spkg-piprm] Uninstalling packaging-23.2:
[packaging-23.2] [spkg-piprm]   Successfully uninstalled packaging-23.2
[packaging-23.2] Removing stamp file /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/lib/sage/installed/packaging-23.2
[packaging-23.2] [spkg-install] Staged wheel file, staged /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/lib/sage/scripts/packaging/spkg-requirements.txt
[packaging-23.2] Moving package files from temporary location /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/packaging-23.2/inst to /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11
[packaging-23.2] [spkg-pipinst] Using pip 23.3.1 from /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/lib/python3.11/site-packages/pip (python 3.11)
[packaging-23.2] [spkg-pipinst] Looking in links: /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/lib/sage/wheels
[packaging-23.2] [spkg-pipinst] Processing /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/lib/sage/wheels/packaging-23.2-py3-none-any.whl (from -r /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/lib/sage/scripts/packaging/spkg-requirements.txt (line 1))
[packaging-23.2] [spkg-pipinst] Installing collected packages: packaging
[packaging-23.2] [spkg-pipinst] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[packaging-23.2] [spkg-pipinst] meson-python 0.15.0 requires meson>=0.63.3; python_version < "3.12", which is not installed.
[packaging-23.2] [spkg-pipinst] tox 4.11.1 requires cachetools>=5.3.1, which is not installed.
[packaging-23.2] [spkg-pipinst] tox 4.11.1 requires chardet>=5.2, which is not installed.
[packaging-23.2] [spkg-pipinst] Successfully installed packaging-23.2
[packaging-23.2] Deleting build directory /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/packaging-23.2
[packaging-23.2] Finished installing packaging-23.2
```

Also displaying build times for each package, even when using `make V=0`, but suppressing very short build times:
```
$ make V=0
...
[setuptools_scm-8.0.4] installing. Log file: /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/logs/pkgs/setuptools_scm-8.0.4.log
[hatchling-1.20.0] installing. Log file: /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/logs/pkgs/hatchling-1.20.0.log
  [setuptools_scm-8.0.4] successfully installed.
  [hatchling-1.20.0] successfully installed.
...
  [sage_conf-10.3.beta8] successfully installed (real 11.36 user 8.32 sys 2.67).
  [pyproject_metadata-0.7.1] successfully installed (real 16.57 user 10.70 sys 2.97).
  [ipykernel-6.27.1] successfully installed (real 19.31 user 11.35 sys 3.71).
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
@tornaria I know that you don't use the Sage distribution, but you may want to look at how we build our Python packages here (with build isolation).

**Comment by kwankyu** [comment]
I get 
```
[sagemath_doc_html-none] Setting up build directory /Users/kwankyu/GitHub/sage-dev/local/var/tmp/sage/build/sagemath_doc_html-none
[sagemath_doc_html-none] Host system: Darwin Hera.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64 x86_64
[sagemath_doc_html-none] C compiler: gcc, Apple clang version 14.0.0 (clang-1400.0.29.202), Target: x86_64-apple-darwin21.6.0, Thread model: posix, InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[sagemath_doc_html-none] No stamp file for package 'sagemath_doc_html' in /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/installed
[sagemath_doc_html-none] No spkg-legacy-uninstall script; nothing to do
[sagemath_doc_html-none] [spkg-install] mkdir -p en/reference/repl
[sagemath_doc_html-none] [spkg-install] sage -advanced > en/reference/repl/options.txt
[sagemath_doc_html-none] [spkg-install] make doc-inventory--reference-references
[sagemath_doc_html-none] [spkg-install] sage --docbuild --no-pdf-links reference/references inventory 
[sagemath_doc_html-none] [spkg-install] [reference] Configuration error:
[sagemath_doc_html-none] [spkg-install] [reference] There is a programmable error in your configuration file:
[sagemath_doc_html-none] [spkg-install] [reference] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/sphinx/config.py", line 358, in eval_config_file
[sagemath_doc_html-none] [spkg-install] [reference]     exec(code, namespace)  # NoQA: S102
[sagemath_doc_html-none] [spkg-install] [reference]     ^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/doc/en/reference/references/conf.py", line 15, in <module>
[sagemath_doc_html-none] [spkg-install] [reference]     from sage_docbuild.conf import release, exclude_patterns
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage_docbuild/conf.py", line 957, in <module>
[sagemath_doc_html-none] [spkg-install] [reference]     for feature in all_features():
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/all.py", line 39, in all_features
[sagemath_doc_html-none] [spkg-install] [reference]     yield from af()
[sagemath_doc_html-none] [spkg-install] [reference]                ^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/sagemath.py", line 1126, in all_features
[sagemath_doc_html-none] [spkg-install] [reference]     sage__symbolic()]
[sagemath_doc_html-none] [spkg-install] [reference]     ^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 86, in __call__
[sagemath_doc_html-none] [spkg-install] [reference]     return cls.__classcall__(cls, *args, **kwds)
[sagemath_doc_html-none] [spkg-install] [reference]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 107, in __classcall__
[sagemath_doc_html-none] [spkg-install] [reference]     cached = _trivial_unique_representation_cache[key] = type.__call__(cls, *args, **options)
[sagemath_doc_html-none] [spkg-install] [reference]                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/sagemath.py", line 1057, in __init__
[sagemath_doc_html-none] [spkg-install] [reference]     PythonModule('sage.dynamics.complex_dynamics'),
[sagemath_doc_html-none] [spkg-install] [reference]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 86, in __call__
[sagemath_doc_html-none] [spkg-install] [reference]     return cls.__classcall__(cls, *args, **kwds)
[sagemath_doc_html-none] [spkg-install] [reference]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 107, in __classcall__
[sagemath_doc_html-none] [spkg-install] [reference]     cached = _trivial_unique_representation_cache[key] = type.__call__(cls, *args, **options)
[sagemath_doc_html-none] [spkg-install] [reference]                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 990, in __init__
[sagemath_doc_html-none] [spkg-install] [reference]     Feature.__init__(self, name, **kwds)
[sagemath_doc_html-none] [spkg-install] [reference]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 165, in __init__
[sagemath_doc_html-none] [spkg-install] [reference]     self._num_hidings = Value('i', 0)
[sagemath_doc_html-none] [spkg-install] [reference]                         ^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 135, in Value
[sagemath_doc_html-none] [spkg-install] [reference]     return Value(typecode_or_type, *args, lock=lock,
[sagemath_doc_html-none] [spkg-install] [reference]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/sharedctypes.py", line 79, in Value
[sagemath_doc_html-none] [spkg-install] [reference]     lock = ctx.RLock()
[sagemath_doc_html-none] [spkg-install] [reference]            ^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 73, in RLock
[sagemath_doc_html-none] [spkg-install] [reference]     return RLock(ctx=self.get_context())
[sagemath_doc_html-none] [spkg-install] [reference]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 194, in __init__
[sagemath_doc_html-none] [spkg-install] [reference]     SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
[sagemath_doc_html-none] [spkg-install] [reference]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
[sagemath_doc_html-none] [spkg-install] [reference]     sl = self._semlock = _multiprocessing.SemLock(
[sagemath_doc_html-none] [spkg-install] [reference]                          ^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] [reference] OSError: [Errno 24] Too many open files
[sagemath_doc_html-none] [spkg-install] Exception ignored in atexit callback: <function spyx_tmp.<locals>.<lambda> at 0x15f2d4c20>
[sagemath_doc_html-none] [spkg-install] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install]   File "/Users/kwankyu/GitHub/sage-dev/src/sage/misc/temporary_file.py", line 543, in <lambda>
[sagemath_doc_html-none] [spkg-install]     atexit.register(lambda: d.cleanup())
[sagemath_doc_html-none] [spkg-install]                             ^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tempfile.py", line 950, in cleanup
[sagemath_doc_html-none] [spkg-install]     self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
[sagemath_doc_html-none] [spkg-install]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tempfile.py", line 930, in _rmtree
[sagemath_doc_html-none] [spkg-install]     _shutil.rmtree(name, onexc=onexc)
[sagemath_doc_html-none] [spkg-install]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 785, in rmtree
[sagemath_doc_html-none] [spkg-install]     _rmtree_safe_fd(fd, path, onexc)
[sagemath_doc_html-none] [spkg-install]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 661, in _rmtree_safe_fd
[sagemath_doc_html-none] [spkg-install]     onexc(os.scandir, path, err)
[sagemath_doc_html-none] [spkg-install]   File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 657, in _rmtree_safe_fd
[sagemath_doc_html-none] [spkg-install]     with os.scandir(topfd) as scandir_it:
[sagemath_doc_html-none] [spkg-install]          ^^^^^^^^^^^^^^^^^
[sagemath_doc_html-none] [spkg-install] OSError: [Errno 24] Too many open files: '/var/folders/td/fw1q9ljs311ggyph77rs53_40000gn/T/tmpkobva7k7'
```
seems related?

**Comment by mkoeppe** [comment]
> seems related?

I don't think so. Is it reproducible? How much parallelization do you use?

**Comment by kwankyu** [comment]
> > seems related?
> 
> I don't think so. 

Right.

> Is it reproducible? 

Yes. In develop branch, from scratch :-)

> How much parallelization do you use?

`make -j4`

**Comment by kwankyu** [comment]
I like the new logs, but one thing.

Before:
```
[cryptominisat-5.8.0] -- Installing: /Users/kwankyu/GitHub/sage-dev/local/var/tmp/sage/build/cryptominisat-5.8.0/inst/Users/kwankyu/GitHub/sage-dev/local/bin/cryptominisat5
[cryptominisat-5.8.0] 
[cryptominisat-5.8.0] real	1m5.351s
[cryptominisat-5.8.0] user	2m46.293s
[cryptominisat-5.8.0] sys	0m18.940s
[cryptominisat-5.8.0] Moving package files from temporary location /Users/kwankyu/GitHub/sage-dev/local/var/tmp/sage/build/cryptominisat-5.8.0/inst to /Users/kwankyu/GitHub/sage-dev/local
[cryptominisat-5.8.0] Successfully installed cryptominisat-5.8.0
[cryptominisat-5.8.0] Deleting temporary build directory
[cryptominisat-5.8.0] /Users/kwankyu/GitHub/sage-dev/local/var/tmp/sage/build/cryptominisat-5.8.0
[cryptominisat-5.8.0] Finished installing cryptominisat-5.8.0

real	1m11.488s
user	2m47.481s
sys	0m19.858s
Sage build/upgrade complete!
```

After:
```
[cryptominisat-5.8.0] [spkg-install] -- Installing: /Users/kwankyu/GitHub/sage-temp/local/var/tmp/sage/build/cryptominisat-5.8.0/inst/Users/kwankyu/GitHub/sage-temp/local/bin/cryptominisat5
[cryptominisat-5.8.0] [spkg-install] real 67.19 user 167.33 sys 19.86
[cryptominisat-5.8.0] Moving package files from temporary location /Users/kwankyu/GitHub/sage-temp/local/var/tmp/sage/build/cryptominisat-5.8.0/inst to /Users/kwankyu/GitHub/sage-temp/local
[cryptominisat-5.8.0] Deleting build directory /Users/kwankyu/GitHub/sage-temp/local/var/tmp/sage/build/cryptominisat-5.8.0
[cryptominisat-5.8.0] Finished installing cryptominisat-5.8.0
[cryptominisat-5.8.0] real 84.51 user 168.24 sys 20.74
Sage build/upgrade complete!
real 85.12 user 168.70 sys 20.93
```

Note that the time is shown only in seconds. Is this better? I think I like the time in (hours and) minutes and seconds

**Comment by mkoeppe** [comment]
> Note that the time is shown only in seconds. Is this better?

Making it print in this portable format (`/usr/bin/time -p`) was the easiest solution for what I thought was important -- suppressing the noise from displaying short running times

**Comment by kwankyu** [comment]
Would this work
```bash
$ /usr/bin/time -h -o timefile sleep 9
$ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
$ /usr/bin/time -h -o timefile sleep 10
$ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
	10.00s real		0.00s user		0.00s sys
$ /usr/bin/time -h -o timefile sleep 61
$ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
	1m1.00s real		0.00s user		0.00s sys
```
?

**Comment by mkoeppe** [comment]
Thanks. I've done something along these lines in 79dfd13

**Review by kwankyu — APPROVED** [review]
Looks nice. Thanks!

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
merge conflict

**Comment by tornaria** [comment]
> Would this work
> 
> ```shell
> $ /usr/bin/time -h -o timefile sleep 9
> $ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
> $ /usr/bin/time -h -o timefile sleep 10
> $ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
> 	10.00s real		0.00s user		0.00s sys
> $ /usr/bin/time -h -o timefile sleep 61
> $ grep -v '[^0-9m][0-9]\.[0-9]*s real' timefile
> 	1m1.00s real		0.00s user		0.00s sys
> ```
> 
> ?

FYI, `time -h` is not a portable option, and in fact doesn't work with gnu time (i.e. most linux, at the very least).

**Comment by mkoeppe** [comment]
Yes, you are right. This last minute change introduced a macOS-ism (or AT&T UNIX-ism)

**Comment by tornaria** [comment]
> Yes, you are right. This last minute change introduced a macOS-ism (or AT&T UNIX-ism)

image

This shows a CI failure that was ignored. Did someone look at that? Was this PR tested on linux?

image

This shows the PR was merged with 14 of 34 checks passed.

**Pull request merged**
