### PR TITLE
Suppress mentions of ipython_genutils (7 years deprecated)

### PR DESCRIPTION
**Pull request by Carreau**
This should not be a dependency of anything for the last ~7 years. If it is; it is a bug in the package.

I think that sage is one of the last pieces of software that mention it And might be the reason we still recieve request to remove nose as a testing framework to package it in opensuse ?

--- 

I don't have much clue what I'm doing, I grep-ed through all the files and removed any mentions, maybe some of those files need to be regenerated ?

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by Carreau** [comment]
(also sending to ee if something breaks, and what need to be patched)

**Review by fchapoton — APPROVED** [review]
looks good, thanks a lot

**Comment by fchapoton** [comment]
let's wait at least for the tests to finish

**Comment by fchapoton** [comment]
It seems that we could use
```
./bootstrap-conda && tox -e update_conda_lock
```
but maybe it is enough to do this by hand. 

@tobiasdiez please tell us if the merge request is ok like it is now

**Comment by tobiasdiez** [comment]
The conda lock files don't need to be changed by hand, and in fact `ipython_genutils` will be installed in the env anyway because its pulled in as a dependency of some other package.

I cannot really speak about the changes in sage-the-distro but it appears to me that `ipympl` does still depends on `ipython_genutils` (only removed in https://github.com/matplotlib/ipympl/commit/564cf6d6767667743cf0e79b0b9a3670feb75c7c, which is not yet released).

**Comment by Carreau** [comment]
Yeah, I just realized it is needed by spyder as well as it vendors an old dependency. 
It's annoying but it will take a few more month to be removable.

**Comment by Carreau** [comment]
(closing for now)

**Pull request closed without merging**
