### PR TITLE
`sage.libs.pynac`: Remove, deprecated in #32386 (2021)

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by antonio-rojas** [comment]
This is causing multiple test failures here
```
sage -t --long /usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py  # 6 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/interfaces/gp.py  # 1 doctest failed
sage -t --long /usr/lib/python3.12/site-packages/sage/libs/pari/tests.py  # 2 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/rings/lazy_series.py  # 2 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/rings/lazy_series_ring.py  # 2 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/rings/qqbar.py  # 1 doctest failed
sage -t --long /usr/lib/python3.12/site-packages/sage/rings/padics/padic_generic_element.pyx  # 2 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/stats/basic_stats.py  # 2 doctests failed
sage -t --long /usr/lib/python3.12/site-packages/sage/stats/distributions/discrete_gaussian_lattice.py  # Timed out (and interrupt failed)
```
eg. on the first file:
```
sage -t --long --random-seed=165638275945038594370995858313379188724 /usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 258, in sage.groups.misc_gps.argument_groups.AbstractArgument._act_on_
Failed example:
    _.parent()
Expected:
    Symbolic Ring
Got:
    <class 'sage.symbolic.ring.SymbolicRing'>
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 262, in sage.groups.misc_gps.argument_groups.AbstractArgument._act_on_
Failed example:
    _.parent()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.groups.misc_gps.argument_groups.AbstractArgument._act_on_[10]>", line 1, in <module>
        _.parent()
    TypeError: unbound method SageObject.parent() needs an argument
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 1116, in sage.groups.misc_gps.argument_groups.ArgumentByElement._symbolic_
Failed example:
    _.parent()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.groups.misc_gps.argument_groups.ArgumentByElement._symbolic_[2]>", line 1, in <module>
        _.parent()
        ^^^^^^^^
    AttributeError: 'int' object has no attribute 'parent'
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 1153, in sage.groups.misc_gps.argument_groups.ArgumentByElement.__pow__
Failed example:
    _.parent()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.groups.misc_gps.argument_groups.ArgumentByElement.__pow__[2]>", line 1, in <module>
        _.parent()
        ^^^^^^^^
    AttributeError: 'int' object has no attribute 'parent'
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 1158, in sage.groups.misc_gps.argument_groups.ArgumentByElement.__pow__
Failed example:
    _.parent()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.groups.misc_gps.argument_groups.ArgumentByElement.__pow__[3]>", line 1, in <module>
        _.parent()
        ^^^^^^^^
    AttributeError: 'int' object has no attribute 'parent'
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/groups/misc_gps/argument_groups.py", line 1522, in sage.groups.misc_gps.argument_groups.Sign._act_on_
Failed example:
    _.parent()
Expected:
    Symbolic Ring
Got:
    <class 'sage.rings.complex_mpfr.ComplexField_class_with_category'>
**********************************************************************
```

**Comment by antonio-rojas** [comment]
https://github.com/sagemath/sage/pull/38081

**Pull request merged**
