### PR TITLE
Some fixes for Specht modules and diagrams

### PR DESCRIPTION
**Pull request by tscrim**
### :books: Description

This fixes a bug in the Specht modules when the cells of the diagram are bigger than the number of boxes:
```python
sage: SGA = SymmetricGroupAlgebra(QQ, 2)
sage: SGA.specht_module([(2,2), (5,5)])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
IndexError: list index out of range
```

We also fix a few typos in `combinat/diagram.py`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
@darijgr This is the fix to Specht modules (and to `diagram.py`) you told me about. The problem was a bit different than you were thinking. The `n` is correct; it is the number of boxes. However, how I was building/checking the diagram was with the wrong size. In fact, this change can make it much more efficient for "dense" diagrams.

@mkoeppe Can you promote @darijgr to the "triage" team?

**Comment by mkoeppe** [comment]
Done

**Comment by tscrim** [comment]
Thank you.

**Review by darijgr — APPROVED** [review]
These changes are good.

**Comment by tscrim** [comment]
Thank you.

**Pull request merged**
