### PR TITLE
`configure --disable-notebook`: Also disable `jupyter_sphinx`

### PR DESCRIPTION
**Pull request by mkoeppe**
`jupyter_sphinx` is only needed for the live documentation and for some illustrations in `src/doc/en/tutorial/latex.rst`.

We conditionalize the use of this extension using a Feature.

`configure --disable-notebook` now also disables `jupyter_sphinx`, to avoid pulling in lots of Jupyter packages via its dependencies (including `jsonschema`, which has gotten itself a Rust-based dependency, see #38219).

This implements the policy for use of platform-dependent wheels proposed in #38219 ("if a platform-dependent ``wheel`` package is a standard package, there must be a ``configure`` option that disables it").

We also repair the mechanism for conditional documentation based on feature tags. 
In particular, the link for Boolean polynomials is restored. https://doc-pr-38224--sagemath.netlify.app/html/en/reference/polynomial_rings/#boolean-polynomials

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38468 (merged here)

### CODE REVIEW

**Comment by mkoeppe** [comment]
Need to conditionalize `.. JUPYTER-EXECUTE` in `src/doc/en/tutorial/latex.rst` using `.. ONLY`

**Comment by orlitzky** [comment]
This beta's no better than the last one for me:

```
[sagelib-10.4.rc0] [spkg-install] Updating Cython code....
[sagelib-10.4.rc0] [spkg-install] ************************************************************************
[sagelib-10.4.rc0] [spkg-install] Traceback (most recent call last):
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
[sagelib-10.4.rc0] [spkg-install]     main()
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
[sagelib-10.4.rc0] [spkg-install]     json_out["return_val"] = hook(**hook_input["kwargs"])
[sagelib-10.4.rc0] [spkg-install]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
[sagelib-10.4.rc0] [spkg-install]     return _build_backend().build_wheel(
[sagelib-10.4.rc0] [spkg-install]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
[sagelib-10.4.rc0] [spkg-install]     return self._build_with_temp_dir(
[sagelib-10.4.rc0] [spkg-install]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
[sagelib-10.4.rc0] [spkg-install]     self.run_setup()
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
[sagelib-10.4.rc0] [spkg-install]     exec(code, locals())
[sagelib-10.4.rc0] [spkg-install]   File "<string>", line 95, in <module>
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
[sagelib-10.4.rc0] [spkg-install]     return distutils.core.setup(**attrs)
[sagelib-10.4.rc0] [spkg-install]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
[sagelib-10.4.rc0] [spkg-install]     return run_commands(dist)
[sagelib-10.4.rc0] [spkg-install]            ^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
[sagelib-10.4.rc0] [spkg-install]     dist.run_commands()
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
[sagelib-10.4.rc0] [spkg-install]     self.run_command(cmd)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
[sagelib-10.4.rc0] [spkg-install]     super().run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
[sagelib-10.4.rc0] [spkg-install]     cmd_obj.run()
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
[sagelib-10.4.rc0] [spkg-install]     self.run_command("build")
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
[sagelib-10.4.rc0] [spkg-install]     self.distribution.run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
[sagelib-10.4.rc0] [spkg-install]     super().run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
[sagelib-10.4.rc0] [spkg-install]     cmd_obj.run()
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
[sagelib-10.4.rc0] [spkg-install]     self.run_command(cmd_name)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
[sagelib-10.4.rc0] [spkg-install]     self.distribution.run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
[sagelib-10.4.rc0] [spkg-install]     super().run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
[sagelib-10.4.rc0] [spkg-install]     cmd_obj.run()
[sagelib-10.4.rc0] [spkg-install]   File "/home/mjo/src/sage.git/pkgs/sagemath-standard/sage_setup/command/sage_build_ext.py", line 25, in run
[sagelib-10.4.rc0] [spkg-install]     self.run_command('build_cython')
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
[sagelib-10.4.rc0] [spkg-install]     self.distribution.run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
[sagelib-10.4.rc0] [spkg-install]     super().run_command(command)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
[sagelib-10.4.rc0] [spkg-install]     cmd_obj.run()
[sagelib-10.4.rc0] [spkg-install]   File "/home/mjo/src/sage.git/pkgs/sagemath-standard/sage_setup/command/sage_build_cython.py", line 220, in run
[sagelib-10.4.rc0] [spkg-install]     extensions = cythonize(
[sagelib-10.4.rc0] [spkg-install]                  ^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1150, in cythonize
[sagelib-10.4.rc0] [spkg-install]     result.get(99999)  # seconds
[sagelib-10.4.rc0] [spkg-install]     ^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
[sagelib-10.4.rc0] [spkg-install]     raise self._value
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/multiprocessing/pool.py", line 540, in _handle_tasks
[sagelib-10.4.rc0] [spkg-install]     put(task)
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/multiprocessing/connection.py", line 206, in send
[sagelib-10.4.rc0] [spkg-install]     self._send_bytes(_ForkingPickler.dumps(obj))
[sagelib-10.4.rc0] [spkg-install]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagelib-10.4.rc0] [spkg-install]   File "/usr/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
[sagelib-10.4.rc0] [spkg-install]     cls(buf, protocol).dump(obj)
[sagelib-10.4.rc0] [spkg-install] AttributeError: Can't pickle local object '_prepare_extension_detection.<locals>.<lambda>'
[sagelib-10.4.rc0] [spkg-install] ************************************************************************
[sagelib-10.4.rc0] [spkg-install] Error building the Sage library
[sagelib-10.4.rc0] [spkg-install] ************************************************************************
[sagelib-10.4.rc0] [spkg-install] Please email sage-devel (http://groups.google.com/group/sage-devel)
[sagelib-10.4.rc0] [spkg-install] explaining the problem and including the relevant part of the log file
[sagelib-10.4.rc0] [spkg-install]   
[sagelib-10.4.rc0] [spkg-install] Describe your computer, operating system, etc.
[sagelib-10.4.rc0] [spkg-install] ************************************************************************
[sagelib-10.4.rc0] [spkg-install] 
[sagelib-10.4.rc0] [spkg-install] ERROR Backend subprocess exited when trying to invoke build_wheel
[sagelib-10.4.rc0] [spkg-install] ********************************************************************************
[sagelib-10.4.rc0] [spkg-install] Error building a wheel for sagelib-10.4.rc0
[sagelib-10.4.rc0] [spkg-install] ********************************************************************************
[sagelib-10.4.rc0] ************************************************************************
[sagelib-10.4.rc0] Error installing package sagelib-10.4.rc0
[sagelib-10.4.rc0] ************************************************************************
```

I'm going back outside.

**Comment by mkoeppe** [comment]
I think @kiwifb can tell you about this gentoo-specific problem

**Comment by kiwifb** [comment]
@orlitzky you are officially bitten by https://github.com/cschwan/sage-on-gentoo/issues/783 the good news is that upstream accepted to fix and an appropriate version of scikit-build-core is in the gentoo tree.

**Comment by orlitzky** [comment]
> @orlitzky you are officially bitten by [cschwan/sage-on-gentoo#783](https://github.com/cschwan/sage-on-gentoo/issues/783) the good news is that upstream accepted to fix it and an appropriate version of scikit-build-core is in the gentoo tree.

Yep, that was it. Upgrading fixed it. Thanks!

**Comment by orlitzky** [comment]
Further, at least:

```
[sagelib-10.4.rc0] Finished installing sagelib-10.4.rc0
[sagelib-10.4.rc0] real 1m23.544s user 1m15.795s sys 0m9.496s
make[2]: Leaving directory '/home/mjo/src/sage.git/build/make'
Sage build/upgrade complete!
real 1m25.445s user 1m19.133s sys 0m11.506s
make[1]: Leaving directory '/home/mjo/src/sage.git'
mjo@gantu ~/src/sage.git $ ./sage
************************************************************************
It seems that you are attempting to run Sage from an unpacked source
tarball, but you have not compiled it yet (or maybe the build has not
finished). You should run `make` in the SAGE_ROOT directory first.
If you did not intend to build Sage from source, you should download
a binary tarball instead. Read README.txt for more information.
************************************************************************
```

**Comment by kwankyu** [comment]
> This implements the policy for use of platform-dependent wheels proposed in https://github.com/sagemath/sage/pull/38219 ("if a platform-dependent wheel package is a standard package, there must be a configure option that disables it").

Is there a discussion on this policy? What is the rationale of the policy? It (disabling a standard package) sounds like a oxymoron to me...

**Comment by mkoeppe** [comment]
To me, a standard package is simply one that is configured to be installed by default.

**Comment by kwankyu** [comment]
"disabling standard package" sounds strange but is okay. My question is rather on "must be". Why "must be" for "platform-dependent wheel"?

**Comment by kwankyu** [comment]
I get 
```
sage: from sage.features.sphinx import JupyterSphinx
sage: JupyterSphinx().is_present()
FeatureTestResult('jupyter_sphinx', True)
```
but the part covered by ".. ONLY:: html and feature_jupyter_sphinx" is missing in the built document. Is this normal?

**Comment by kwankyu** [comment]
Shouldn't it be
```diff
diff --git a/src/sage_docbuild/conf.py b/src/sage_docbuild/conf.py
index 6938594713e..d9711163f43 100644
--- a/src/sage_docbuild/conf.py
+++ b/src/sage_docbuild/conf.py
@@ -1093,4 +1093,5 @@ if 'tags' not in locals():
 
 
 for feature in all_features():
-    tags.add('feature_' + feature.name.replace('.', '_'))
+    if feature.is_present():
+        tags.add('feature_' + feature.name.replace('.', '_'))
```
?

**Comment by mkoeppe** [comment]
> Why "must be a configure option" for "platform-dependent wheel"?

Currently, standard Sage can be built from source, so (at least in theory) on a wide range of architectures. If we allow standard packages to be provided by platform-dependent wheels, that restricts such packages to the fixed range of architectures for which wheels have been provided. This could be highly controversial, which is why I am proposing the conservative policy in #38219 that such packages at least must have a `--disable-...` option.

**Comment by kwankyu** [comment]
> > Why "must be a configure option" for "platform-dependent wheel"?
> 
> Currently, standard Sage can be built from source, so (at least in theory) on a wide range of architectures. If we allow standard packages to be provided by platform-dependent wheels, that restricts such packages to the fixed range of architectures for which wheels have been provided. 

I understand up to this point.

> This could be highly controversial, which is why I am proposing the conservative policy in #38219 that such packages at least must have a `--disable-...` option.

Let's assume a platform on which the standard package has no wheel yet. What should happen to the package when sage is built on that platform? Failure? So `--disable-...` option?

**Comment by mkoeppe** [comment]
> > This could be highly controversial, which is why I am proposing the conservative policy in #38219 that such packages at least must have a `--disable-...` option.
> 
> Let's assume a platform on which the standard package has no wheel yet.

Not just "not yet": Making wheels for the packages is not under the control of our project.

> What should happen to the package when sage is built on that platform? Failure?

Yes, it's a hard error.

> So `--disable-...` option?

Exactly.

**Comment by kwankyu** [comment]
I think that a standard package could be installed on all supported platforms, regardless of "--disable" option. A platform-dependent-wheel standard package breaks that assumption...

How about making jupyter-sphinx an optional package, and thus live doc as well?

**Comment by kwankyu** [comment]
Orthogonally, platform-dependent wheels could be just implementation detail of a standard package? If a wheel is available, it is used, otherwise it is installed from source? Reasonable?

**Comment by mkoeppe** [comment]
Package type (standard, optional, experimental) and package source type (normal, wheel, script, dummy, pip) are already orthogonal.

**Comment by mkoeppe** [comment]
> If a wheel is available, it is used, otherwise it is installed from source?

I wouldn't want to implement this because the benefit is relatively small (faster installation for users), it comes with drawbacks for users (the prebuilt wheel is not optimized for the specific processor architecture variant), and the maintenance cost is high (we would need to add tests for both installation from source and installation from wheels).

**Comment by kwankyu** [comment]
Was this concept of "platform-dependent-wheel standard package" discussed before? In #38219, there is no discussion about it...

**Comment by mkoeppe** [comment]
The discussion indeed belongs in #38219, which simply has not received any comments yet.

**Comment by kwankyu** [comment]
> I get
> 
> ```
> sage: from sage.features.sphinx import JupyterSphinx
> sage: JupyterSphinx().is_present()
> FeatureTestResult('jupyter_sphinx', True)
> ```
> 
> but the block covered by `.. ONLY:: html and feature_jupyter_sphinx` is missing in the built document. Is this normal?

Would you answer this? Is ".. ONLY:: feature_..." thing working correctly?

**Comment by kwankyu** [comment]
> ... Is ".. ONLY:: feature_..." thing working correctly?

As far as I can see,

**Comment by kwankyu** [comment]
Oops. I clicked a wrong button. Sorry. Reopen please.

**Comment by mkoeppe** [comment]
> the block covered by `.. ONLY:: html and feature_jupyter_sphinx` is missing in the built document.

Indeed, that's a bug. I'll investigate.

**Comment by mkoeppe** [comment]
CI docbuild fails, but diff logic fails here
- #38467

**Comment by mkoeppe** [comment]
> > the block covered by `.. ONLY:: html and feature_jupyter_sphinx` is missing in the built document.
> 
> Indeed, that's a bug. I'll investigate.

Fixed now

**Comment by kwankyu** [comment]
This PR gives me a philosophical confusion about the meaning of standard packages in sage.

A standard package is installed by default. Hence code in sage assumes its existence (or rather the functions provided by the package). The code in this PR allows the possibility that the feature provided by a standard package may not exist.

Don't we have "optional package" just for the case? I think there is no essential difference between (S) standard package that may be disabled and (O) optional package that may be enabled.

On the other hand, I am aware that similar blurring was already introduced into the sage library through the modularization...

**Comment by mkoeppe** [comment]
> A standard package is installed by default.

Exactly, and that's the complete answer.

**Comment by mkoeppe** [comment]
> Don't we have "optional package" just for the case?

No, an optional package is not installed by default.

**Comment by kwankyu** [comment]
> > A standard package is installed by default.
> 
> Exactly, and that's the complete answer.

Do we have a precedence that a standard package can be disabled and the possibility is reflected in sage code?

**Comment by mkoeppe** [comment]
Yes, there are a bunch of `--disable-...` options, see https://github.com/sagemath/sage/blob/develop/configure.ac#L442

**Comment by mkoeppe** [comment]
> and the possibility is reflected in sage code?

Yes, you can find a bunch of `# needs cvxopt`

**Comment by kwankyu** [comment]
Package-wise, I see only three relevant cases: `--disable-cvxopt`,` --disable-notebook`, `--disable-r`. 

R is an optional package. I don't understand why  `--disable-r` exists. Perhaps just an overlook.

So cvxopt and notebook are relevant examples of standard packages that can be disabled. I think these are rather exceptions, made for practical purposes.

If an arbitrary standard package can be disabled in principle, then code in sage should spend time checking its availability before doing anything useful. For example, Singular is a standard package, and the code in sage relying on Singular can assume its existence. I cannot agree with your definition of standard packages.  

Since notebook is already an exception, perhaps jupyter-sphinx may be treated also as an exception -- standard package that can be disabled and hence needs to be checked for its availability.

**Comment by mkoeppe** [comment]
> R is an optional package. I don't understand why `--disable-r` exists. Perhaps just an overlook.

`--disable-r` also disables `rpy2`, which is a standard package. (Actually a "semi-standard" package -- `rpy2` is automatically disabled when there is no system `r`.)

**Comment by mkoeppe** [comment]
> If an arbitrary standard package can be disabled in principle, then code in sage should spend time checking its availability before doing anything useful. For example, Singular is a standard package, and the code in sage relying on Singular can assume its existence.

Yes, and the various `# needs` tags introduced in the modularization do exactly this.

**Review by kwankyu — APPROVED** [review]
Working well. LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
