### PR TITLE
details on complex reflection groups

### PR DESCRIPTION
**Pull request by fchapoton**
### :books: Description

Remove a deprecated method in the category of complex reflection groups

Also one little code enhancement

and some pep8 cleanups.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM. The test failure must be sporadic-unrelated.

**Comment by fchapoton** [comment]
I am not so sure that the test failure is unrelated. Of course, the changes look rather harmless..

**Comment by vbraun** [comment]
Merge conflict,

**Comment by vbraun** [comment]
Merge conflict

**Comment by fchapoton** [comment]
setting back to positive aftere trivial merge

**Pull request merged**
