### PR TITLE
`build/pkgs/meson`: Update to 1.3.1, require >= 1.2.3 for Python 3.12 support, reject meson installed in inaccessible user schemes

### PR DESCRIPTION
**Pull request by mkoeppe**
As reported in https://groups.google.com/g/sage-devel/c/9ETciH8efTE/m/UfUO7xmsAQAJ, our `configure` script currently accepts "system" meson that will not be functional in our venv.
```
$ pip install --user meson
Collecting meson
  Using cached meson-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Using cached meson-1.3.1-py3-none-any.whl (976 kB)
Installing collected packages: meson
Successfully installed meson-1.3.1
$ python3 -c 'import sysconfig; print(sysconfig.get_path("scripts", "posix_user"))'
/Users/mkoeppe/Library/Python/3.11/bin
$ /Users/mkoeppe/Library/Python/3.11/bin/meson --version
1.3.1
$ ./sage -sh -c '/Users/mkoeppe/Library/Python/3.11/bin/meson --version'
Traceback (most recent call last):
  File "/Users/mkoeppe/Library/Python/3.11/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
```

Also tightening the version requirement. Only needed for Python 3.12 support (https://github.com/mesonbuild/meson-python/blob/main/pyproject.toml#L36), but we do this unconditionally for simplicity.

Also updating meson to latest and changing to a wheel package.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Removing blocker as there are problems with other PRs, see https://github.com/sagemath/sage/issues/37428 for more details.

**Comment by mkoeppe** [comment]
Restoring "blocker" -- this PR needs to go into the stable release. 
Same comment as https://github.com/sagemath/sage/pull/37351#issuecomment-1961810481 -- https://github.com/sagemath/sage/issues/37428 has absolutely no details, mass removal of the "blocker" label on 9 PRs is not OK.

**Comment by mkoeppe** [comment]
Thanks, Volker.

**Comment by mkoeppe** [comment]
Same is also needed for `cmake` @comboproblem

**Pull request merged**
