### PR TITLE
Deprecate `is_FreeAlgebra`, `is_QuaternionAlgebra`, `is_SymmetricFunctionAlgebra`

### LINKED ISSUE #32738: Deprecate is_Algebra, is_CommutativeAlgebra, is_FreeAlgebra, is_QuaternionAlgebra, is_SymmetricFunctionAlgebra
<div id="comment:0"></div>

... and the re-export of `sage.rings.ring.Algebra` and `sage.rings.ring.CommutativeAlgebra` by `sage.algebras.algebra` and `sage.rings.commutative_algebra`

Depends on #32870

Component: **refactoring**

_Issue created by migration from https://trac.sagemath.org/ticket/32738_

### PR DESCRIPTION
**Pull request by mkoeppe**
- Fixes #32738

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
LGTM (although I am mildly hesitant with the `is_FreeAlgebra` because it is testing multiple classes).

**Comment by mkoeppe** [comment]
Thanks!  Of course we can later follow up with an ABC for FreeAlgebra, but I didn't want to mix a discussion on naming or API in this PR.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks.

**Pull request merged**
