### PR TITLE
`scipy`: Fix build on macOS with Xcode CLT 15.0

### LINKED ISSUE #36342: Build failures with Xcode CLT 15.0: scipy (via meson), ecm
SciPy build failure when homebrew's gfortran is used (via meson), reported in https://groups.google.com/g/sage-release/c/1wOBmhvNJqc/m/dT-6HGAjCAAJ
- see also https://github.com/mesonbuild/meson/issues/12282

ECM build failure reported in https://groups.google.com/g/sage-release/c/dvPti2UkyjQ/m/Nj4e5zApCQAJ:

```
 checking what assembly label suffix to use... :
checking if globals are prefixed by underscore... configure: error: Test program links neither with nor without underscore.
********************************************************************************
Error configuring ecm-7.0.5 See the file
    /Users/iohara/Desktop/sage-10.2.beta4/local/var/tmp/sage/build/ecm-7.0.5/src/config.log
for details.
```
This looks similar to https://gitlab.inria.fr/zimmerma/ecm/-/issues/21856 @dimpase @zimmermann6 

Our latest ECM upgrade was made in https://github.com/sagemath/sage/issues/31325.

### PR DESCRIPTION
**Pull request by mkoeppe**
- Fixes #36342 
- using the fix discussed at https://github.com/mesonbuild/meson/issues/12282

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jhpalmieri** [comment]
This works for me on three machines:

- an Intel mac
- an M2 mac laptop
- an M1 mac (on which, for reasons I do not understand, `scipy` was building without any problems before this branch, even though it is running the latest OS, the latest version of CLT, fully updated homebrew, just like the laptop)

With the first two I had been forced to do `./configure --with-system-gfortran=no` to build successfully, but with this branch I did not need to do that. I should double-check that everything still works with Sage's `gfortran`, but I don't see why it wouldn't. If that works, then I'll set to positive review.

**Comment by mkoeppe** [comment]
Thanks a lot for testing!

**Review by jhpalmieri — APPROVED** [review]

**Comment by vbraun** [comment]
This breaks  CLT 13, probably others too:
```
****************************************************
C compiler: gcc
C compiler version:
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
****************************************************
Package 'scipy' is currently not installed
No legacy uninstaller found for 'scipy'; nothing to do
Installing scipy-1.11.3
Processing /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  + meson setup /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src/.mesonpy-dkvkbd9g -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src/.mesonpy-dkvkbd9g/meson-python-native-file.ini
  The Meson build system
  Version: 1.2.3
  Source dir: /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src
  Build dir: /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src/.mesonpy-dkvkbd9g
  Build type: native build
  Project name: SciPy
  Project version: 1.11.3
  ../meson.build:1:0: ERROR: Compiler gcc cannot compile programs.
  A full log can be found at /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src/.mesonpy-dkvkbd9g/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/bin/python3 /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/06/0yb8f59j2ks8f0cph9fvkyp40000gp/T/tmpmagwwn48
  cwd: /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/scipy-1.11.3/src
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
********************************************************************************
```

**Comment by mkoeppe** [comment]
Thanks for catching this

**Comment by jhpalmieri** [comment]
Check the version of the command-line tools, as in https://github.com/sagemath/sage/pull/36337#issuecomment-1741485061?

**Comment by mkoeppe** [comment]
To put in src/bin/sage-env? Probably a good idea, let's try that; could you open a PR with this change please?

**Comment by jhpalmieri** [comment]
> To put in src/bin/sage-env? Probably a good idea, let's try that; could you open a PR with this change please?

Done in #36599.

**Comment by jhpalmieri** [comment]
With the branch at #36599, scipy builds for me.

**Comment by mkoeppe** [comment]
Closing in favor of #36599

**Pull request closed without merging**
