### PR TITLE
trying to refresh symbolic units

### PR DESCRIPTION
**Pull request by fchapoton**
by allowing the conversion constants in the stored data to be either strings or rationals

Part of the conversion table are replaced by integers or rational but  not systematically.

This file is not correctly indented, but this is not fixed here.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by tscrim — CHANGES_REQUESTED** [review]
It probably would be better to more systematically change all of the rational conversions to rationals... Otherwise LGTM.

**Comment by fchapoton** [comment]
yes, I am slightly too lazy to do that.

**Comment by fchapoton** [comment]
maybe enough things were converted now ?

**Review by tscrim — APPROVED** [review]
Thank you. Yes, this is good for now.

**Pull request merged**
