### PR TITLE
Add parameter key to methods multiple_edges and edge_boundary

### PR DESCRIPTION
**Pull request by dcoudert**
Part of #35902.

### :books: Description

We add parameter `key` to methods `multiple_edges` and `edge_boundary`. This is useful when users manipulate graphs with edges of incomparable types.

On the way, we avoid some calls to `multiple_edges` with `sort=True` in method `is_tree`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dimpase — APPROVED** [review]

**Comment by dcoudert** [comment]
Thank you.

**Comment by vbraun** [comment]
Merge conflict

**Comment by dcoudert** [comment]
I don't see any conflict with 10.1.beta7, so I set this ticket back to positive review.

**Comment by dimpase** [comment]
I'd suggest to rebase over beta7, just to be sure

**Comment by dcoudert** [comment]
It's what I did using the button on the GitHub interface.

**Comment by vbraun** [comment]
please wait for the next beta

**Comment by dcoudert** [comment]
I fixed the merge conflicts. Let me know if I can set back to positive.

Note that the bot reports many doctests errors that are not related to this ticket. I observe the same errors in unrelated tickets like #35981, #35982.

**Comment by dcoudert** [comment]
The failing doctests are independent from this PR. One of them is fixed in #36040.

I'm setting this PR back to positive review.

**Pull request merged**
