### PR TITLE
add .torsion_basis() method to EllipticCurve_finite_field

### LINKED ISSUE #34718: add .torsion_basis() method to EllipticCurve_finite_field
<div id="comment:0"></div>

Computing a basis of a particular `m`-torsion subgroup is an important subroutine in several algorithms for isogenies and endomorphism rings of elliptic curves over finite fields.

This patch adds a `.torsion_basis()` method to `EllipticCurve_finite_field`. Its current implementation is merely a thin wrapper around `.abelian_group()` and `.torsion_subgroup()` — the point of this patch is to introduce the interface first so that more optimizations can be incorporated later.

CC:  @defeo

Component: **elliptic curves**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34718_

### PR DESCRIPTION
**Pull request by yyyyx4**
Fixes #34718.

### CODE REVIEW

**Comment by roed314** [comment]
There are failing tests, but otherwise this looks good to me.

**Comment by yyyyx4** [comment]
The test failure is unrelated to the changes here. See #35017.

**Comment by JohnCremona** [comment]
Looks good to me and tests do now pass -- @roed314 can you do a positive review and change the label accordingly?  (I can do the latter, but you are the official reviewer.)

**Review by roed314 — APPROVED** [review]
Lgtm

**Pull request merged**
