### PR TITLE
Fix pycodestyle warning E721

### PR DESCRIPTION
**Pull request by jhpalmieri**
Fix the warnings coming from pycodestyle E721, "E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`".

Mostly I've made changes like `type(x) == type(y)` to `type(x) is type(y)`, also adding some uses of `isinstance`. When I run `pycodestyle --select=E721 --statistics src/sage/` I now get no hits.

### :memo: Checklist

- [X] The title is concise, informative, and self-explanatory.
- [X] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jhpalmieri** [comment]
Well, maybe I missed some of them: .pyx files in particular. I can add those on if people think this ticket is a good idea, or we can do them with a separate PR.

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Comment by jhpalmieri** [comment]
Thanks! We can address more such changes with another PR.

**Comment by vbraun** [comment]
Merge conflict

**Comment by jhpalmieri** [comment]
Rebased.

**Pull request merged**
