### PR TITLE
fix performance regression in elliptic-curve point constructor

### PR DESCRIPTION
**Pull request by yyyyx4**
See [here](https://github.com/sagemath/sage/issues/37593#issuecomment-1989251306).

### CODE REVIEW

**Comment by GiacomoPope** [comment]
If you have this built locally, can you run a test or two from the examples in https://github.com/sagemath/sage/issues/37593 to show the new relative performance?

Nice work also cleaning up all the R(1) in the code.

**Comment by yyyyx4** [comment]
$q=11$, Sage 10.2:
```
6.05 µs ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.22 µs ± 41.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
$q=11$, this branch:
```
6.61 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.74 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

$q=(2^{127}-1)^3$, Sage 10.2:
```
28.3 µs ± 299 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
19.3 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
$q=(2^{127}-1)^3$, this branch:
```
28.3 µs ± 61.9 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
19.2 µs ± 66.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

**Review by GiacomoPope — APPROVED** [review]
LGTM

Thanks for the quick fix!

Could you add a "Fixes https://github.com/sagemath/sage/issues/37593" to close this issue on merge?

**Comment by yyyyx4** [comment]
Thanks for noticing the problem and for the review, and sorry for causing the slowdown in the first place!

> Could you add a "Fixes #37593" to close this issue on merge?

This is in one of the commit messages, which should work as well, according to [the GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by GiacomoPope** [comment]
> which should work as well

I agree but I didn't see the linked issue in the GitHub UI on the PR tracker... Maybe this is a silly UI issue though and what you've done is fine.

As an aside, have you ever looked into `P._add_` and adding 2 methods which deal separately for short and long weierstrass curves? This would save a handful of additions and multiplications by zero for short weierstrass curves.

**Comment by GiacomoPope** [comment]
Doctest failure due to `if t.is_zero():  #what if R(t) == 0 ?` where `t` is of type `int`

**Review by GiacomoPope — APPROVED** [review]
LGTM -- thank you!

**Comment by GiacomoPope** [comment]
@vbraun although this is a small fix, it would be great to get this into 10.3 so that we don't ship degraded performance on something so widely used.

**Pull request merged**
