### PR TITLE
`build/pkgs`: Update scip to 9, scip_sdp to 4.4, soplex to 7, papilo to 2.2, pyscipopt to 5, onetbb to 2021.11 

### PR DESCRIPTION
**Pull request by mkoeppe**
https://www.scipopt.org/doc-9.0.0/html/RN90.php

- [x] https://github.com/scipopt/SCIP-SDP/issues/12
- [ ] https://github.com/scipopt/soplex/issues/35
- [x] needs pyscipopt update

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #37237 
- Depends on #37351 
- Depends on #36970
- Depends on #37392

### CODE REVIEW

**Comment by mkoeppe** [comment]
- https://github.com/scipopt/SCIP-SDP/issues/12
- needs pyscipopt update

**Comment by kwankyu** [comment]
"CI Linux incremental" all broken at
```
Dockerfile:57
--------------------
  55 |     ADD  src src
  56 |     ARG TARGETS="build"
  57 | >>> RUN  make SAGE_SPKG="sage-spkg -y -o" ${USE_MAKEFLAGS} ${TARGETS}  
  58 |     
  59 |     FROM with-targets as with-targets-optional
```
?

**Comment by kwankyu** [comment]
`make pyscipopt` fails for me.

[pyscipopt-5.0.0.log](https://github.com/sagemath/sage/files/15072369/pyscipopt-5.0.0.log)

**Comment by kwankyu** [comment]
Perhaps `pyscipopt` has obsolete patches?

**Comment by kwankyu** [comment]
Removing `build/pkgs/pyscipopt/patches/792.patch` makes it go through.

**Comment by mkoeppe** [comment]
Indeed. Looks like I only tested it via the upstream workflow (https://github.com/scipopt/PySCIPOpt/pull/630), which auto-removes the Sage patches.

**Comment by kwankyu** [comment]
It would be good to see at least one success of "CI Linux incremental" instances, but they seem all broken.

Anyway, this PR works well on my system.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
> It would be good to see at least one success of "CI Linux incremental" instances, but they seem all broken.

Well, there's no friendly green checkmark because of unrelated technical issues, but you do get "All tests passed!", for example in https://github.com/sagemath/sage/actions/runs/8811573741/job/24185749981?pr=37494#step:11:13091

**Comment by mkoeppe** [comment]
Thanks for the review!

**Comment by mkoeppe** [comment]
@vbraun This file is missing on the mirrors
```
Attempting to download package scip-9.0.0.tar.gz from mirrors
https://github.com/sagemath/sage/releases/download/10.4/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//github.com/sagemath/sage/releases/download/10.4/scip-9.0.0.tar.gz'
https://github.com/sagemath/sage/releases/download/10.3/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//github.com/sagemath/sage/releases/download/10.3/scip-9.0.0.tar.gz'
https://github.com/sagemath/sage/releases/download/10.2/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//github.com/sagemath/sage/releases/download/10.2/scip-9.0.0.tar.gz'
https://mirror.lyrahosting.com/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror.lyrahosting.com/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz'
https://mirror.csclub.uwaterloo.ca/sage/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror.csclub.uwaterloo.ca/sage/spkg/upstream/scip/scip-9.0.0.tar.gz'
https://mirror.koddos.net/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror.koddos.net/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz'
http://files.sagemath.org/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//files.sagemath.org/spkg/upstream/scip/scip-9.0.0.tar.gz'
https://mirror.dogado.de/sage/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror.dogado.de/sage/spkg/upstream/scip/scip-9.0.0.tar.gz'
https://mirror-hk.koddos.net/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror-hk.koddos.net/sagemath/spkg/upstream/scip/scip-9.0.0.tar.gz'
```

**Comment by mkoeppe** [comment]
@vbraun Still missing: scip-9.0.0.tar.gz https://github.com/sagemath/sage/actions/runs/9234698750/job/25408697887#step:5:1686

**Comment by vbraun** [comment]
ok should be be uploaded now

**Pull request merged**
