### PR TITLE
Remove spurious diffs in doc build changes

### PR DESCRIPTION
**Pull request by kwankyu**
Remove all spurious and chronic diffs in the changes of our documentation preview.

Improve CHANGES.html using diffsite. See https://deploy-preview-36483--sagemath-tobias.netlify.app/changes

diffsite allows to compare changes visually. *Scroll until vertical alignment breaks or search for some diff text.*

In this regard, refrain from using a function as the default value of an argument in Python definitions. Use `None` instead and apply the default (the function) in the code part.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36475

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM, thanks for making these fixes!

**Comment by kwankyu** [comment]
Thanks. But I found a glitch. Let me fix this first :-)

**Comment by kwankyu** [comment]
Ready to go. Thanks!

**Comment by mkoeppe** [comment]
needs rebase now

**Comment by kwankyu** [comment]
Thanks. Merged with develop cleanly by git.

**Comment by kwankyu** [comment]
By the way, is there a reason that changes are only from `html/en`, that is, English doc?

**Comment by mkoeppe** [comment]
Only the English docs are uploaded to netlify, see the end of the "Copy docs" step. 
I don't recall if this was discussed when the netlify deployment was developed.

**Comment by kwankyu** [comment]
Ah, right.

Then this is a bigger problem, to be discussed elsewhere. Thanks.

**Comment by mkoeppe** [comment]
The improved CHANGES display is really nice.

**Comment by kwankyu** [comment]
Thanks. It would've been better if diffsite scrolls to (or highlight) diff parts. I found no way to do that automatically (perhaps need AI). But from my experience, the manual method in the description of this PR works well enough.

**Pull request merged**
