### PR TITLE
Lint: Install tox from ubuntu, as done in CI Build&Test etc.

### PR DESCRIPTION
**Pull request by mkoeppe**
... instead of via pip.
This is for uniformity and motivated by stability concerns prompted by #38205 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
The situation is that pip-installed `tox` fails in auto-provisioning (upgrading) itself because of incompatible version of `filelock`, and the distribution-provided `tox` is supposed to be more stable from this kind of instability. Am I right?

**Comment by kwankyu** [comment]
Is there a test run?

**Comment by mkoeppe** [comment]
> The situation is that pip-installed `tox` fails in auto-provisioning (upgrading) itself because of incompatible version of `filelock`, and the distribution-provided `tox` is supposed to be more stable and immune from this kind of instability. Am I right?

Yes, that's right.

**Comment by mkoeppe** [comment]
A test run (when there was still a broken filelock on PyPI): https://github.com/sagemath/sage/actions/runs/9488101498/job/26146233900

**Review by kwankyu — APPROVED** [review]
OK. LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
