### PR TITLE
CI Build&Test: Fix "test modularized distributions" after #37022

### LINKED ISSUE #37734: Test modularised distributions causes CI failure
### Steps To Reproduce

Check the CI for recently run PR. For example: 

1. https://github.com/sagemath/sage/pull/37441
2. https://github.com/sagemath/sage/pull/37513
3. https://github.com/sagemath/sage/pull/37615

```
Run make V=0 tox && make pypi-wheels-check
make -j2 --output-sync=recurse build/make/Makefile --stop
make[1]: 'build/make/Makefile' is up to date.
build/bin/sage-logger \
	"cd build/make && ./install 'tox'" logs/install.log
Nothing to (re)build / all up-to-date.
make -j2 --output-sync=recurse build/make/Makefile --stop
make[1]: 'build/make/Makefile' is up to date.
build/bin/sage-logger \
	"cd build/make && ./install 'pypi-wheels-check'" logs/install.log
*** ALL ENVIRONMENT VARIABLES BEFORE BUILD: ***
sage_sws2rst-10.4.beta1
sage_setup-10.4.beta1
[sage_sws2rst-10.4.beta1] + set -e
[sage_sws2rst-10.4.beta1] + sage-sws2rst -h
sagemath_environment-10.4.beta1
sagemath_objects-10.4.beta1
make[1]: *** [Makefile:3584: sagemath_environment-SAGE_VENV-check] Error 1
make[1]: *** Waiting for unfinished jobs....
[sagemath_objects-10.4.beta1] ERROR: Could not find a version that satisfies the requirement cysignals>=1.10.2 (from versions: none)
[sagemath_objects-10.4.beta1] ERROR: No matching distribution found for cysignals>=1.10.2
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: remove tox env folder /sage/pkgs/sagemath-objects/.tox/.pkg-sagepython-sagewheels-nopypi
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: find interpreter for spec PythonSpec(path=/bin/python3)
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: proposed PythonInfo(spec=CPython3.8.10.final.0-64, exe=/bin/python3, platform=linux, version='3.8.10 (default, Nov 22 2023, 10:22:35) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8)
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: create virtual environment via CPython3Posix(dest=/sage/pkgs/sagemath-objects/.tox/.pkg-sagepython-sagewheels-nopypi, clear=False, no_vcs_ignore=False, global=False)
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/github/home/.local/share/virtualenv)
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: add activators for Bash, CShell, Fish, Nushell, PowerShell, Python
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: freeze> python -m pip freeze --all
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: exit 0 (0.68 seconds) /sage/pkgs/sagemath-objects> python -m pip freeze --all pid=61304
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi: pip==23.3.1,setuptools==69.0.2,wheel==0.42.0
[sagemath_objects-10.4.beta1] .pkg-sagepython-sagewheels-nopypi_sdist_meta: remove tox env folder /sage/pkgs/sagemath-objects/.tox/.pkg-sagepython-sagewheels-nopypi_sdist_meta
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: find interpreter for spec PythonSpec(path=/bin/python3)
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: proposed PythonInfo(spec=CPython3.8.10.final.0-64, exe=/bin/python3, platform=linux, version='3.8.10 (default, Nov 22 2023, 10:22:35) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8)
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: create virtual environment via CPython3Posix(dest=/sage/pkgs/sagemath-objects/.tox/sagepython-sagewheels-nopypi-norequirements, clear=False, no_vcs_ignore=False, global=False)
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/github/home/.local/share/virtualenv)
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: add activators for Bash, CShell, Fish, Nushell, PowerShell, Python
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: install_package_deps> python -I -m pip install 'cysignals>=1.10.2' 'gmpy2~=2.1.b999'
[sagemath_objects-10.4.beta1] sagepython-sagewheels-nopypi-norequirements: exit 1 (0.83 seconds) /sage/pkgs/sagemath-objects> python -I -m pip install 'cysignals>=1.10.2' 'gmpy2~=2.1.b999' pid=61312
[sagemath_objects-10.4.beta1] Looking in links: file:///sage/local/var/lib/sage/venv-python3.11.1/var/lib/sage/wheels
[sagemath_objects-10.4.beta1]   sagepython-sagewheels-nopypi-norequirements: FAIL code 1 (1.97 seconds)
[sagemath_objects-10.4.beta1]   evaluation failed :( (2.05 seconds)
[sagemath_objects-10.4.beta1] Failures testing the package
[sagemath_objects-10.4.beta1] 
[sagemath_objects-10.4.beta1] real	0m2.228s
[sagemath_objects-10.4.beta1] user	0m1.675s
[sagemath_objects-10.4.beta1] sys	0m0.670s
[sagemath_objects-10.4.beta1] ************************************************************************
[sagemath_objects-10.4.beta1] Error testing package sagemath_objects-10.4.beta1
[sagemath_objects-10.4.beta1] ************************************************************************
[sagemath_objects-10.4.beta1] Please email sage-devel (http://groups.google.com/group/sage-devel)
[sagemath_objects-10.4.beta1] explaining the problem and including the log files
[sagemath_objects-10.4.beta1]   /sage/logs/pkgs/sagemath_objects-10.4.beta1.log
[sagemath_objects-10.4.beta1] and
[sagemath_objects-10.4.beta1]   /sage/config.log
[sagemath_objects-10.4.beta1] Describe your computer, operating system, etc.
[sagemath_objects-10.4.beta1] If you want to try to fix the problem yourself, *don't* just cd to
[sagemath_objects-10.4.beta1] /sage/build/pkgs/sagemath_objects and type 'make check' or whatever is appropriate.
[sagemath_objects-10.4.beta1] Instead, the following commands setup all environment variables
[sagemath_objects-10.4.beta1] correctly and load a subshell for you to debug the error:
[sagemath_objects-10.4.beta1]   (cd '/sage/build/pkgs/sagemath_objects' && '/sage/sage' --buildsh)
[sagemath_objects-10.4.beta1] When you are done debugging, you can type "exit" to leave the subshell.
[sagemath_objects-10.4.beta1] ************************************************************************

make[1]: *** [Makefile:3584: sagemath_objects-SAGE_VENV-check] Error 1

real	0m3.126s
user	0m4.423s
sys	0m1.758s
***************************************************************
Error building Sage.

The following package(s) may have failed to build (not necessarily
during this run of 'make pypi-wheels-check'):

* package:         sagemath_environment-10.4.beta1
  last build time: Apr 3 11:24
  log file:        /sage/logs/pkgs/sagemath_environment-10.4.beta1.log

* package:         sagemath_objects-10.4.beta1
  last build time: Apr 3 11:24
  log file:        /sage/logs/pkgs/sagemath_objects-10.4.beta1.log

It is safe to delete any log files and build directories, but they
contain information that is helpful for debugging build problems.
WARNING: If you now run 'make' again, the build directory of the
same version of the package will, by default, be deleted. Set the
environment variable SAGE_KEEP_BUILT_SPKGS=yes to prevent this.

make: *** [Makefile:40: pypi-wheels-check] Error 1
Error: Process completed with exit code 2.
```

### Expected Behavior

The CI should pass when these parts of Sage are unchanged 

### Actual Behavior

The CI fails

### Additional Information

_No response_

### Environment

```markdown
- **OS**:
- **Sage Version**:
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mkoeppe**
- Cherry-picked updates of testing infrastructure from #35095.
- Add upper version bounds to avoid a regression in 4.14.1
- Fixes #37734.
- Also removes some unnecessary runs of the "CI Linux Incremental" workflow.

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
I get
```
[sagemath_environment-10.4.beta2] [spkg-check] Running tox -r -p auto -v --installpkg /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/lib/sage/wheels/sagemath_environment-10.4b2-py3-none-any.whl
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: remove tox env folder /Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment/.tox/.pkg-sagepython-sagewheels-nopypi
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: find interpreter for spec PythonSpec(path=/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3)
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: proposed PythonInfo(spec=CPython3.12.2.final.0-64, system=/usr/local/opt/python@3.12/bin/python3.12, exe=/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3, platform=darwin, version='3.12.2 (main, Feb 20 2024, 04:30:04) [Clang 14.0.0 (clang-1400.0.29.202)]', encoding_fs_io=utf-8-utf-8)
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: create virtual environment via CPython3macOsBrew(dest=/Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment/.tox/.pkg-sagepython-sagewheels-nopypi, clear=False, no_vcs_ignore=False, global=False)
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/kwankyu/Library/Application Support/virtualenv)
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi: add activators for Bash, CShell, Fish, Nushell, PowerShell, Python
[sagemath_environment-10.4.beta2] [spkg-check] .pkg-sagepython-sagewheels-nopypi_sdist_meta: remove tox env folder /Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment/.tox/.pkg-sagepython-sagewheels-nopypi_sdist_meta
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: remove tox env folder /Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment/.tox/sagepython-sagewheels-nopypi-norequirements
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: find interpreter for spec PythonSpec(path=/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3)
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: proposed PythonInfo(spec=CPython3.12.2.final.0-64, system=/usr/local/opt/python@3.12/bin/python3.12, exe=/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3, platform=darwin, version='3.12.2 (main, Feb 20 2024, 04:30:04) [Clang 14.0.0 (clang-1400.0.29.202)]', encoding_fs_io=utf-8-utf-8)
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: create virtual environment via CPython3macOsBrew(dest=/Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment/.tox/sagepython-sagewheels-nopypi-norequirements, clear=False, no_vcs_ignore=False, global=False)
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/kwankyu/Library/Application Support/virtualenv)
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: add activators for Bash, CShell, Fish, Nushell, PowerShell, Python
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: install_package> python -I -m pip install --force-reinstall --no-deps /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/lib/sage/wheels/sagemath_environment-10.4b2-py3-none-any.whl
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: exit 0 (1.58 seconds) /Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment> python -I -m pip install --force-reinstall --no-deps /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/lib/sage/wheels/sagemath_environment-10.4b2-py3-none-any.whl pid=86426
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: commands[0]> '{envpython}' -c 'import sys; "" in sys.path and sys.path.remove(""); from sage.features.all import all_features; print(sorted(all_features(), key=lambda x: x.name)); import sage.misc.package'
[sagemath_environment-10.4.beta2] [spkg-check] sagepython-sagewheels-nopypi-norequirements: exit 2 (0.00 seconds) /Users/kwankyu/GitHub/sage-dev/pkgs/sagemath-environment> '{envpython}' -c 'import sys; "" in sys.path and sys.path.remove(""); from sage.features.all import all_features; print(sorted(all_features(), key=lambda x: x.name)); import sage.misc.package'
[sagemath_environment-10.4.beta2] [spkg-check]   sagepython-sagewheels-nopypi-norequirements: FAIL code 2 (2.39=setup[2.39]+cmd[0.00] seconds)
[sagemath_environment-10.4.beta2] [spkg-check]   evaluation failed :( (2.50 seconds)
[sagemath_environment-10.4.beta2] [spkg-check] Failures testing the package
[sagemath_environment-10.4.beta2] [spkg-check] /Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/sagemath_environment-10.4.beta2/src/.tox/sagepython-sagewheels-nopypi-norequirements/log/2-commands[0].log
[sagemath_environment-10.4.beta2] ************************************************************************
[sagemath_environment-10.4.beta2] Error testing package sagemath_environment-10.4.beta2
[sagemath_environment-10.4.beta2] ************************************************************************
```

**Comment by kwankyu** [comment]
```
./sage -sh -c '(cd pkgs/sagemath-categories && SAGE_NUM_THREADS=8 tox -v -v -v -e sagepython-sagewheels-nopypi-norequirements)'
```
fails for me.

**Comment by kwankyu** [comment]
I get
```
[sagemath_objects-10.4.beta2] [spkg-check]   sagepython-sagewheels-nopypi-norequirements: OK (8.99=setup[8.39]+cmd[0.30,0.30] seconds)
[sagemath_objects-10.4.beta2] [spkg-check]   congratulations :) (9.26 seconds)
[sagemath_objects-10.4.beta2] [spkg-check] Passed the test suite
[sagemath_objects-10.4.beta2] [spkg-check] /Users/kwankyu/GitHub/sage-dev/build/pkgs/sagemath_objects/src/.tox/sagepython-sagewheels-nopypi-norequirements/log/3-commands[0].log
[sagemath_objects-10.4.beta2] [spkg-check] /Users/kwankyu/GitHub/sage-dev/build/pkgs/sagemath_objects/src/.tox/sagepython-sagewheels-nopypi-norequirements/log/4-commands[1].log
[sagemath_objects-10.4.beta2] [spkg-check] 29.48s real 16.20s user 6.70s sys
[sagemath_objects-10.4.beta2] Passed the test suite for sagemath_objects-10.4.beta2.
[sagemath_objects-10.4.beta2] 30.13s real 16.42s user 6.97s sys
Sage build/upgrade complete!
31.04s real 16.98s user 7.20s sys
```

This success seems the main thing achieved by this PR. Right?

**Comment by kwankyu** [comment]
Other changes in the files `tox.ini` seems just minor maintenance works. Right?

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by vbraun** [comment]
merge conflict

**Comment by mkoeppe** [comment]
Fixed a doctest failure in the modularized tests, seen in PR CI runs

**Comment by mkoeppe** [comment]
The failure in "Test changed files" is the unrelated:
- #37536

**Pull request merged**
