### PR TITLE
Fix test failures with ipython 8.11

### PR DESCRIPTION
**Pull request by antonio-rojas**
### 📚 Description

ipython 8.11 throws new warnings "UserWarning: Shell was already running a gui event loop for sage; switching to sage." when running some tests

### 📝 Checklist

- [X] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kiwifb** [comment]
Yes, I can see those.

**Review by kiwifb — APPROVED** [review]
LGTM

**Comment by tornaria** [comment]
Hmm... are we sure the warning only happens on these doctests?

Wouldn't it be better to either fix or ignore the warning? Someone put the warning there for some reason. Even if the warning is irrelevant, did you make sure it  won't show up to a normal user?

**Comment by tornaria** [comment]
As of fb2a1f9e6d73 the inputhook is not installed once at initialization but each time a file is attached  (including when attached files are reloaded). The warning complains about that.

The following seems to fix it: the `install()` function checks whether the inputhook is already ours. I'm not sure this is the proper fix, maybe @vbraun can comment / review since he wrote this code.

The call to `get_test_shell()` in the doctest is necessary, otherwise `get_ipython()` returns `None` and nothing is tested!

I still don't know how to replace the branch in a PR like we used to do in trac. Opening a new PR seems too much noise.

```diff
--- a/src/sage/repl/inputhook.py
+++ b/src/sage/repl/inputhook.py
@@ -49,13 +49,23 @@ def install():
 
     EXAMPLES::
 
+    Make sure ipython is running so we really test this function
+
+        sage: from sage.repl.interpreter import get_test_shell
+        sage: get_test_shell()
+        <sage.repl.interpreter.SageTestShell object at ...>
+
+    Test the function twice, to make sure it is idempotent (see :trac:`35235`)
+
         sage: from sage.repl.inputhook import install
         sage: install()
+        sage: install()
     """
     ip = get_ipython()
     if not ip:
         return   # Not running in ipython, e.g. doctests
-    ip.enable_gui('sage')
+    if ip._inputhook != sage_inputhook:
+        ip.enable_gui('sage')
 
 
 def uninstall():
```

**Comment by kiwifb** [comment]
I certainly do like the approach. Is it compatible with older ipython or does it require us to move to ipython 8.11? I would not have an issue with that but I would be surprised if it was needed.

**Comment by tornaria** [comment]
> I certainly do like the approach. Is it compatible with older ipython or does it require us to move to ipython 8.11? I would not have an issue with that but I would be surprised if it was needed.

I didn't test but I don't think it is, indeed, all checks have passed here using older ipython.

All we do here is to skip changing the inputhook if it is already set to our own. In this case `ip.enable_gui('sage')` would be a noop except for the warning.

**Comment by tornaria** [comment]
I pushed the branch with my fix to [tornaria:ipython-8.11](https://github.com/tornaria/sage/tree/ipython-8.11). The commit is https://github.com/tornaria/sage/commit/502cb00992ace881248b364a4e25581c2373b54b, in case it helps.

I don't know if it's possible to replace [antonio-rojas:ipython-8.11](https://github.com/antonio-rojas/sage/tree/ipython-8.11) by [tornaria:ipython-8.11](https://github.com/tornaria/sage/tree/ipython-8.11) in this PR, maybe @arojas can just grab my commit.

**Comment by antonio-rojas** [comment]
Done

**Comment by antonio-rojas** [comment]
@tornaria `tox -e rst` is failing with `./sage/repl/inputhook.py:51:1: RST218 Literal block expected; none found.`. I have no idea what that means or how to fix it, please take a look
`

**Comment by kiwifb** [comment]
Looking at other files I believe you need something like'
```
EXAMPLES: <-notice only one ":"

some text:: <- introduce the double "::" here

    code
    code
    code

some more text:: <- again here

    more code
```

**Comment by tornaria** [comment]
Sorry, I usually don't build docs... I'll redo my commit.

It turns out running `tox -e rst` takes about 2 minutes and I guess it checks the whole source tree. Is there a way to run this test for a single file? For development it would be useful.

Can someone link to documentation explaining the doctest formats?

**Comment by tornaria** [comment]
I have updated my branch [tornaria:ipython-8.11](https://github.com/tornaria/sage/tree/ipython-8.11). The new commit is https://github.com/tornaria/sage/commit/23471e2d242c4de8789d7b1fc8b07a4b1d1e595a.

Note that I rebased on top of beta4 and redid the commit -- you won't be able to merge, just resetting your branch to mine seems the easier way (also, I find it very noisy that we keep a commit + revert the commit).

I'm still wondering: maybe the workflow should be that we close this PR and I open a separate one. It's very unfortunate that there is so much friction to work cooperatively on a PR.  @mkoeppe  any suggestions?

**Comment by antonio-rojas** [comment]
Let's just open a new pull request with your branch

**Pull request closed without merging**
