### PR TITLE
Implementing a generic one method for unital algebras

### PR DESCRIPTION
**Pull request by tscrim**
We implement a generic `one()` method for unital algebras in order to fix the following:
```python
sage: S2 = simplicial_complexes.Sphere(2)
sage: H = S2.cohomology_ring(QQ)
sage: C = cartesian_product([H, H])
sage: C.one()  # this raises an error currently
B[(0, (0, 0))] + B[(1, (0, 0))]
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
failing doctests

**Comment by tscrim** [comment]
This should fix the errors.

**Review by fchapoton — APPROVED** [review]
ok, arigato, merci

**Comment by tscrim** [comment]
@fchapoton merci!

**Comment by vbraun** [comment]
conflict

**Comment by tscrim** [comment]
Trivial conflict.

**Pull request merged**
