### PR TITLE
Fix failure of  doc preview changes when an html is removed

### LINKED ISSUE #36887: `.ci/create-changes-html.sh` fails when an HTML file is removed
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/7217053087/job/19664244861?pr=36885#step:11:156

### Expected Behavior

diff created 

### Actual Behavior

```
+ PATH=/sage/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin .ci/create-changes-html.sh 4725a0315a962bee6a612f04009dcb66c4e55b09 /sage/local/share/doc/sage/html
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/sage/local/share/doc/sage/html/en/reference/spkg/deprecation.html'
cat: diff.html: No such file or directory
rm: cannot remove 'diff.html': No such file or directory
```

### Additional Information

_No response_

### Environment

```markdown
CI
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #36887. 

Tested with #36892 and #36885.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36871

### CODE REVIEW

**Comment by mkoeppe** [comment]
Still failing -- https://github.com/sagemath/sage/actions/runs/7217634218/job/19686132231#step:11:156

**Comment by kwankyu** [comment]
Strange as `FileNotFoundError` exception is impossible since it is captured by `try ... error`...

**Comment by kwankyu** [comment]
> Still failing -- https://github.com/sagemath/sage/actions/runs/7217634218/job/19686132231#step:11:156

The branch works well on my test. Would you double check?

**Comment by kwankyu** [comment]
It seems that this fix is not applied by the blocker mechanism. I don't know why.

**Comment by mkoeppe** [comment]
OK, I'll try it out by merging it manually

**Comment by kwankyu** [comment]
Thanks. I was about to suggest that :-)

**Comment by mkoeppe** [comment]
It works! Thanks very much for fixing this.

**Pull request merged**
