### PR TITLE
AdditiveAbelianGroup_class.exponent() returns a Python int for the trivial group

### LINKED ISSUE #34872: AdditiveAbelianGroup_class.exponent() returns a Python int for the trivial group
<div id="comment:0"></div>

```sage
sage: type(AdditiveAbelianGroup([]).exponent())
<class 'int'>
```

Component: **group theory**

Author: **Lorenz Panny**

Branch/Commit: **[public/34872](https://github.com/sagemath/sagetrac-mirror/tree/public/34872) @ [`6d6e020`](https://github.com/sagemath/sagetrac-mirror/commit/6d6e02089ccf56760cb6f63f27f7ad4ccbb2d405)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34872_

### PR DESCRIPTION
**Pull request by yyyyx4**
Fixes #34872.

### CODE REVIEW

**Comment by mezzarobba** [comment]
@kwankyu You may want to use the github review tool (look under *Files changed*) to “approve” the PR instead of just labeling it with `positive review`

**Comment by kwankyu** [comment]
I only copied the label from the converted issue to this PR. As I am not the original reviewer, I cannot approve the PR. Perhaps you ping to the original reviewer @mkoeppe. I just did :-)

**Comment by kwankyu** [comment]
> As I am not the original reviewer, I cannot approve the PR. 

Why not? Giving positive review and approving the PR (with positive review) may be two separate steps.

**Comment by kwankyu** [comment]
@tobiasdiez 

But I don't see the "approve" button. Perhaps I don't have the permission :-)

**Comment by tobiasdiez** [comment]
image

**Review by kwankyu — APPROVED** [review]
Perfect!

**Comment by kwankyu** [comment]
Tobias, why "Merging is blocked"?

**Comment by tobiasdiez** [comment]
Because only the release manager (actually all admins, but nevermind that) has the right to merge PRs for now.

**Comment by mkoeppe** [comment]
https://github.com/sagemath/sage/issues/34872 was merged into 10.0.beta0; there are no changes left to be merged.

**Pull request closed without merging**
