### PR TITLE
`sage --package list`: Sort output, add switches `--{in,ex}clude-dependencies`

### PR DESCRIPTION
**Pull request by mkoeppe**
We enhance the command `sage --package list`:
- New switches `--{in,ex}clude-dependencies` walk the tree of dependencies declared in `dependencies` files
- Output is always (uniquified and) sorted, eliminating the use of `sort` in various scripts
- Handling of `--exclude` is moved to the end, which improves its applicability.

The new parsing of the `dependencies*` files in `sage_bootstrap` is generic preparation for handling more of the bootstrapping phase in Python, as sketched in #33860 (part of #29146).

This PR is immediate preparation for #35593, where it is desired to create "minimized" lists of system packages that do not include all standard packages that are really only needed as dependencies of "top-level" packages.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by orlitzky** [comment]
Do we have a notion of "top level" package yet, or is that TBD? I ask because things like `gengetopt` and `patch` are listed in the output of `sage --package list --exclude-dependencies :standard:` and I'm fairly sure that those are only needed as dependencies of other things that sage needs.

Unrelated, this outputs a list of packages,

```
$ ./sage --package list --exclude-dependencies :all:
```

but this,

```
$ ./sage --package list --exclude-dependencies
```

outputs nothing. IIUC they should do the same thing?

**Comment by mkoeppe** [comment]
> Do we have a notion of "top level" package yet, or is that TBD? 

No, this cannot be declared yet (any thoughts?); for use in #35593 I just with `--exclude-dependencies` to eliminate packages that will be pulled in by others.

> I ask because things like `gengetopt` and `patch` are listed in the output of `sage --package list --exclude-dependencies :standard:` and I'm fairly sure that those are only needed as dependencies of other things that sage needs.

`gengetopt` and `patch` are order-only dependencies, but the new switches only deal with proper dependencies.

> Unrelated, this outputs a list of packages,
> 
> ```
> $ ./sage --package list --exclude-dependencies :all:
> ```
> 
> but this,
> 
> ```
> $ ./sage --package list --exclude-dependencies
> ```
> 
> outputs nothing. IIUC they should do the same thing?

Without the new switches, the default is indeed :all:, which is nice for interactive use. But with the new switches given, I have changed the default to empty, which works better for scripting uses.

**Comment by orlitzky** [comment]
> > Do we have a notion of "top level" package yet, or is that TBD?
> 
> No, this cannot be declared yet (any thoughts?); for use in #35593 I just with `--exclude-dependencies` to eliminate packages that will be pulled in by others.

It's hard to do properly without writing a package manager. The entries in `build/pkgs/sagelib/dependencies` are a good start, but there are lots of runtime dependencies missing, and the `$(FOO)` deps to worry about, and the things controlled by `./configure --disable-foo`...

We may wind up with a hard-coded list for a while., but at least the distribution maintainers have already come up with that list (they should all be _roughly_ the same).

> Without the new switches, the default is indeed :all:, which is nice for interactive use. But with the new switches given, I have changed the default to empty, which works better for scripting uses.

Can the `--help` output mention this then? That's the only documentation we have.

**Comment by mkoeppe** [comment]
> > Without the new switches, the default is indeed :all:, which is nice for interactive use. But with the new switches given, I have changed the default to empty, which works better for scripting uses.
> 
> Can the `--help` output mention this then?

Good idea, done

**Review by orlitzky — APPROVED** [review]
I'm not sure that this in-between approach is how I'd do it: if we came up with that list of direct dependencies now, we might also be able to find a way to hide the other packages from `./configure` and `make`. That would be nice for conda and the distros because the package manager install instructions would contain only a minimal list, and `./configure` would be able to skip a few hundred pointless checks for non-direct dependencies.

Still, this doesn't hurt anything, so it's OK too.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by vbraun** [comment]
Merge conflict

**Pull request merged**
