### PR TITLE
update eclib to version 20231212

### PR DESCRIPTION
**Pull request by JohnCremona**
eclib version 20231212 has some bugfixes and also uses flint3 if available.  No Sage code or doctest changes are required.

build/pkgs/eclib/spkg-install.in has been simplified
buid/pkgs/eclib/spkg-configure.m4 now uses [ge] and not [eq] to check eclib version

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Comment by JohnCremona** [comment]
As far as I can see, the test failures have nothing to do with my changes.

**Comment by mkoeppe** [comment]
How about this one (on 32bit)
```
sage -t --random-seed=94831720532873652004228675690153881729 src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
    Killed due to abort
```
(https://github.com/sagemath/sage/actions/runs/7212244941/job/19649586297?pr=36879#step:11:10473)

**Comment by JohnCremona** [comment]
> How about this one (on 32bit)
> 
> ```
> sage -t --random-seed=94831720532873652004228675690153881729 src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
>     Killed due to abort
> ```
> 
> (https://github.com/sagemath/sage/actions/runs/7212244941/job/19649586297?pr=36879#step:11:10473)

I don't think any of that code is changed.  It was not written by me -- it is a translation into cython of code in eclib (in C++), and is almost certainly now available directly on pari which has a lot more elliptic curve functionality than when this was written.

ANyway, I ca't see anything wrong with the function, but I am no cython expert.

**Comment by JohnCremona** [comment]
As with my other oper PR, there appear to be failing tests which have nothing to do with any code I changed.  Of course I may be wrong.

**Review by dimpase — APPROVED** [review]
OK, looks good

**Pull request merged**
