### PR TITLE
Sort #34892 doctest output vectors to fix randomness

### PR DESCRIPTION
**Pull request by grhkm21**
Reported at https://github.com/sagemath/sage/pull/38492#issuecomment-2295021400 by @jhpalmieri and @GMS103. Added an extra test because why not.

### CODE REVIEW

**Comment by grhkm21** [comment]
By the way, is this intended?
```python
sage: L = IntegralLattice(Matrix(QQ, [[1000, 0], [0, 1]]))
....: L.0.norm()
1
```

**Comment by yyyyx4** [comment]
> By the way, is this intended?
> 
> ```python
> sage: L = IntegralLattice(Matrix(QQ, [[1000, 0], [0, 1]]))
> ....: L.0.norm()
> 1
> ```

This is because the given matrix is interpreted as the Gram matrix of the lattice: The basis vectors are always `(1,0)` and `(0,1)`, and their pairwise inner products are specified by the matrix entries. To compute the norm, you'd have to do `L.0 * L.gram_matrix() * L.0`, I suppose. Perhaps there's a shortcut.

**Comment by yyyyx4** [comment]
Indeed, presumably this is not optimal. The `parent` of this vector is set to the correct lattice, but the `.norm()` method behaves the same as for the standard Euclidean lattice regardless of the actual parent. This seems like something worth fixing.

**Comment by grhkm21** [comment]
Yeah that's what I was thinking, `v.parent()` gives the lattice

**Review by yyyyx4 — COMMENTED** [review]
Your patch (thanks!) will fix the doctest failures, but it also leaves us with tests which basically only check that the method doesn't crash. I'm not sure how to best resolve this. Practically, perhaps we can get away with a `sorted()` and deal with it properly if/when it breaks again on some other setup?

**Comment by jhpalmieri** [comment]
If you don't want to use `sorted`, you could check membership of some entries. Do you know whether `(3, 2, -2, -4)` will alway be among the first 20 entries, for example? I don't know the code at all. Are there any meaningful tests you can run on the output?

> > By the way, is this intended?
> > ```python
> > sage: L = IntegralLattice(Matrix(QQ, [[1000, 0], [0, 1]]))
> > ....: L.0.norm()
> > 1
> > ```
> 
> This is because the given matrix is interpreted as the Gram matrix of the lattice: The basis vectors are always `(1,0)` and `(0,1)`, and their pairwise inner products are specified by the matrix entries. To compute the norm, you'd have to do `L.0 * L.gram_matrix() * L.0`, I suppose. Perhaps there's a shortcut.

Why does the second line start with `....:` instead of `sage:`?

**Comment by grhkm21** [comment]
For now, I will add change it to a `sorted` call, and if it breaks in any other architecture then ~~too bad~~ we can figure out from there, perhaps testing membership of a short vector as suggested.

**Comment by jhpalmieri** [comment]
> > > > By the way, is this intended?
> > > > ```python
> > > > sage: L = IntegralLattice(Matrix(QQ, [[1000, 0], [0, 1]]))
> > > > ....: L.0.norm()
> > > > 1
> > > > ```
> > > 
> > > 
> > > This is because the given matrix is interpreted as the Gram matrix of the lattice: The basis vectors are always `(1,0)` and `(0,1)`, and their pairwise inner products are specified by the matrix entries. To compute the norm, you'd have to do `L.0 * L.gram_matrix() * L.0`, I suppose. Perhaps there's a shortcut.
> > 
> > 
> > Why does the second line start with `....:` instead of `sage:`?
> 
> Because I copied this from my REPL and it's not a doctest.

Sorry, I thought you were quoting from the code.

**Comment by grhkm21** [comment]
I'll sort it by the norm *and* the original vector then

**Review by yyyyx4 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
