### PR TITLE
Meson: Improve handling of dependencies

### PR DESCRIPTION
**Pull request by tobiasdiez**
Make the dependency declaration in the meson build files more precise and add a few missing dependencies for some files.

Extracted from https://github.com/sagemath/sage/pull/38872.

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by dimpase** [comment]
tests won't start:
```
Traceback (most recent call last):
  File "/mnt/opt/Sage/sage-clang/src/bin/sage-runtests", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/__main__.py", line 192, in main
    err = DC.run()
          ^^^^^^^^
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/control.py", line 1610, in run
    self.run_doctests()
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/control.py", line 1194, in run_doctests
    self.dispatcher = DocTestDispatcher(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/forker.py", line 1726, in __init__
    init_sage(controller)
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/forker.py", line 207, in init_sage
    controller.load_environment()
  File "/mnt/opt/Sage/sage-clang/src/sage/doctest/control.py", line 695, in load_environment
    return import_module(self.options.environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/mnt/opt/Sage/sage-clang/src/sage/repl/ipython_kernel/all_jupyter.py", line 6, in <module>
    from sage.all_cmdline import *
  File "/mnt/opt/Sage/sage-clang/src/sage/all_cmdline.py", line 17, in <module>
    from sage.all import *
  File "/mnt/opt/Sage/sage-clang/src/sage/all.py", line 86, in <module>
    from sage.rings.all import *
  File "/mnt/opt/Sage/sage-clang/src/sage/rings/all.py", line 57, in <module>
    from sage.rings.number_field.all import *
  File "/mnt/opt/Sage/sage-clang/src/sage/rings/number_field/all.py", line 2, in <module>
    from sage.rings.number_field.number_field import (NumberField, NumberFieldTower, CyclotomicField, QuadraticField,
  File "/mnt/opt/Sage/sage-clang/src/sage/rings/number_field/number_field.py", line 87, in <module>
    import sage.rings.real_mpfi
  File "real_mpfi.pyx", line 1, in init sage.rings.real_mpfi
  File "mpfi.pyx", line 1, in init sage.rings.convert.mpfi
ImportError: /mnt/opt/Sage/sage-clang/build/cp312/src/sage/rings/complex_interval.cpython-312-x86_64-linux-gnu.so: undefined symbol: fmpz_tdiv_q_2exp
```

The latter symbol is from `libflint`, but `complex_interval.cpython-312-x86_64-linux-gnu.so` is not linked to `libflint`

**Comment by dimpase** [comment]
in order for `$ ./sage -tp --all` to start, I had to do
```diff
diff --git a/src/sage/rings/finite_rings/meson.build b/src/sage/rings/finite_rings/meson.build
index e81724aa5c8..f9dae256d86 100644
--- a/src/sage/rings/finite_rings/meson.build
+++ b/src/sage/rings/finite_rings/meson.build
@@ -41,7 +41,7 @@ extension_data = {
 foreach name, pyx : extension_data
   deps = [py_dep, cysignals, gmp]
   if name == 'element_pari_ffelt'
-    deps += [cypari2]
+    deps += [cypari2, pari]
   elif name == 'residue_field_pari_ffelt'
     deps += [cypari2]
   endif
diff --git a/src/sage/rings/meson.build b/src/sage/rings/meson.build
index a06dd098c06..5ecdbeb00e0 100644
--- a/src/sage/rings/meson.build
+++ b/src/sage/rings/meson.build
@@ -124,13 +124,13 @@ extension_data = {
 foreach name, pyx : extension_data
   deps = [py_dep, cysignals, gmp]
   if name == 'complex_arb'
-    deps += [flint, mpfi]
+    deps += [flint, mpfi, gsl]
   elif name == 'complex_conversion'
     deps += [gsl, mpfr]
   elif name == 'complex_double'
     deps += [gmpy2, gsl]
   elif name == 'complex_interval'
-    deps += [mpfi]
+    deps += [mpfi, flint]
   elif name == 'complex_mpc'
     deps += [gmpy2, mpfr, mpc]
   elif name == 'complex_mpfr'
```

should I push it? I'm not 100% sure it's a correct fix.

**Comment by tobiasdiez** [comment]
Thanks! This worked well. Tests are passing, except for one on python 3.11 - that looks unrelated.

**Review by dimpase — APPROVED** [review]
LGTM

**Comment by tobiasdiez** [comment]
Thanks for the review!

**Pull request merged**
