### PR TITLE
src/sage/misc/latex.py: replace tmp_dir()

### PR DESCRIPTION
**Pull request by orlitzky**
These bits of code only use one temporary file, but they call a function `_run_latex_()` that writes its output file to the same directory as its input file. Since we don't want the output path to be predictable (for security reasons), we have to "hide" the one temporary file inside of a temporary directory that will only be writable by the Sage user.

In other words: standard `tempfile.TemporaryDirecrory()` replacement.

Issue: https://github.com/sagemath/sage/issues/36322

### CODE REVIEW

**Review by mezzarobba — COMMENTED** [review]
Is there a reason not to use `with TemporaryDirectory()` (or a `try`-`finally` block) — especially in `view`, which has two possible exit points even in the absence of any exception?

**Comment by orlitzky** [comment]
> Is there a reason not to use `with TemporaryDirectory()` (or a `try`-`finally` block) — especially in `view`, which has two possible exit points even in the absence of any exception?

The context manager is better but it makes the diff awful if you have to indent the entire method. I've made the change in a separate commit if you don't mind looking through it though.

**Review by mezzarobba — APPROVED** [review]
thanks!

**Comment by EmmanuelCharpentier** [comment]
This bungles `view()`. Highly damageable to console (or emacs' `sage-shell-mode`) users.

I opened https://github.com/sagemath/sage/issues/36526.

**Pull request merged**
