### PR TITLE
Fix link to tutorial in PDF docs. This fixes #35736.

### LINKED ISSUE #35736: Tutorial link of pdf pointing to wrong document name
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: ubuntu
- **Sage Version**: 10.0
```

### Steps To Reproduce

1. After build doc-pdf, open "sage-10.0/local/share/doc/sage/index.html"
2. PDF/Tutorial link cannot find the pdf file:
    sage-10.0/local/share/doc/sage/pdf/en/tutorial/SageTutorial.pdf

### Expected Behavior

PDF/Tutorial in "sage-10.0/local/share/doc/sage/index.html" should point to "sage_tutorial.pdf" instead of "SageTutorial.pdf".

### Actual Behavior

Your file couldn’t be accessed

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jhpalmieri**
Fix link to PDF tutorial (English) in docs. This should fix #35736.

The document name for the English tutorial is broken: it doesn't match the name expected in the index.html file for the documentation. So we change the document name.

### :memo: Checklist

- [X] The title is concise, informative, and self-explanatory.
- [X] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
There's nothing wrong with `src/doc/en/tutorial/conf.py`. Instead of that, make this change
```diff
--- a/src/doc/en/website/root_index.html
+++ b/src/doc/en/website/root_index.html
@@ -113,7 +113,7 @@ title="SageMath Mathematical Software">
 <div class="cell lang"><a href='html/en/index.html'>English</a></div>
 <div class="cell doc">
 <div class='entry lang-en'><a href='pdf/en/a_tour_of_sage/a_tour_of_sage.pdf'>A Tour of Sage</a></div>
-<div class='entry lang-en'><a href='pdf/en/tutorial/SageTutorial.pdf'>Tutorial</a></div>
+<div class='entry lang-en'><a href='pdf/en/tutorial/sage_tutorial.pdf'>Tutorial</a></div>
 <div class='entry lang-en'><a href='pdf/en/thematic_tutorials/thematic_tutorials.pdf'>Thematic Tutorials</a></div>
 <div class='entry lang-en'><a href='pdf/en/prep/prep_tutorials.pdf'>PREP Tutorials</a></div>
 <div class='entry lang-en'><a href='pdf/en/constructions/constructions.pdf'>Constructions</a></div>
```
This file is copied to `local/share/doc/sage/index.html` by [https://github.com/sagemath/sage/blob/0fd596703c824a53f4ffb54556f336de436dde59/src/sage_docbuild/builders.py#L449](https://github.com/sagemath/sage/blob/0fd596703c824a53f4ffb54556f336de436dde59/src/sage_docbuild/builders.py#L449)

**Comment by jhpalmieri** [comment]
Is there a reason to prefer one of these approaches to the other? They both just change a single string. Note that there is no particular consistency for naming conventions for PDF documents; in some languages we use "tutorial.pdf" (or variants) and in others "SageTutorial.pdf" (or variants).

**Comment by kwankyu** [comment]
As filenames, I think `sage_tutorial.tex` and `sage_tutorial.pdf` are consistent with others, at least with documents in English. See `src/doc/en/a_tour_of_sage/conf.py`.

I seems that the issue is caused simply by a mistake I made to the file  `src/doc/en/website/root_index.html`, which I created. Hence it is the file to be fixed.

**Comment by jhpalmieri** [comment]
Seems like bikeshedding — the two changes seem equivalent to me — but here is your proposed version.

**Comment by kwankyu** [comment]
Thanks.

**Review by kwankyu — APPROVED** [review]

**Pull request merged**
