### PR TITLE
simplify some trivial iterations

### PR DESCRIPTION
**Pull request by fchapoton**
### :books: Description

replace a lot of `(x for x in something)` by `something`, inside `all`, `any`, `sum`, etc

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
```
sage -t --random-seed=325292134826394888144321814057003138306 sage/combinat/multiset_partition_into_sets_ordered.py  # 2 doctests failed
sage -t --random-seed=325292134826394888144321814057003138306 sage/matroids/matroid.pyx  # 1 doctest failed
```

**Review by dcoudert — APPROVED** [review]
LGTM.

**Comment by fchapoton** [comment]
so may I set to positive review ?

**Comment by vbraun** [comment]
Merge conflict

**Comment by fchapoton** [comment]
somebody broke the linter somewhere. I am bored about fixing other's mistakes. Not here, in any case.

**Comment by dcoudert** [comment]
Agreed.

**Review by dcoudert — APPROVED** [review]
LGTM.

**Pull request merged**
