### PR TITLE
make EllipticCurve.lift_x() deterministic

### LINKED ISSUE #35281: EllipticCurve.lift_x() is often deterministic, but not always
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Many doctests use `.lift_x()` to construct a specific point, hence they implicitly rely on the method being deterministic. This is true in many cases, but there are base-ring implementations for which it fails:

```sage
sage: F.<t> = GF((101,3))
sage: E = EllipticCurve(F, [1,1])
sage: for _ in range(10):
....:     print(E.lift_x(t+1))
....:
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
```

This creates the unpleasant situation that users will write code which silently assumes that `.lift_x()` is deterministic, then encounter surprising bugs once they try the same code on other base fields where it suddenly behaves randomly.

Cc: @JohnCremona

### Proposed Solution

Make `.lift_x()` deterministic and document that guarantee.

This can be as easy as calling `ys.sort()` in two places in `.lift_x()`, but it breaks a lot of doctests — including some that I'm not confident enough about to change them.

### Alternatives Considered

Make all `.sqrt()` methods deterministic.

This seems more work, is more likely to miss some cases, and is prone to other implementations being added later that break the guarantee again.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yyyyx4**
Resolves #35281.

### CODE REVIEW

**Review by JohnCremona — APPROVED** [review]
Looks good! See the comments on the liked issue for details.

**Comment by JohnCremona** [comment]
Last doctest is fine, I also ran ptestlong and can confirm that that was the only outstanding one.  I didn't know there were elliptic curves used in tests in rings/polynomial/multi_polynomial_ideal.py. This last one was just lazy, the author of the test could easily have given x and y coordinates!

**Review by JohnCremona — APPROVED** [review]

**Comment by vbraun** [comment]
Merge conflict

**Review by JohnCremona — APPROVED** [review]
I assume you just fixed the merge conflicts and this is the same otherwise

**Comment by yyyyx4** [comment]
Indeed, trivial rebase.

**Pull request merged**
