### PR TITLE
add missing #long time markers to ell_number_field

### LINKED ISSUE #34959: Fix doctest in sage/schemes/elliptic_curves/ell_number_field.py
<div id="comment:0"></div>

A "long" annotation is missing in a doctest introduced in #34537, causing:

```
sage -t --random-seed=257591867899933130420640722238032668369 sage/schemes/elliptic_curves/ell_number_field.py
**********************************************************************
File "sage/schemes/elliptic_curves/ell_number_field.py", line 2304, in sage.schemes.elliptic_curves.ell_number_field.EllipticCurve_number_field.gens
Failed example:
    P=gg[0]; P.order()
Exception raised:
    Traceback (most recent call last):
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_number_field.EllipticCurve_number_field.gens[7]>", line 1, in <module>
        P=gg[Integer(0)]; P.order()
    NameError: name 'gg' is not defined
```

CC:  @dimpase

Component: **doctest coverage**

_Issue created by migration from https://trac.sagemath.org/ticket/34959_

### PR DESCRIPTION
**Pull request by mezzarobba**
Fixes #34959.

It would be nice if this could be merged quickly as this (I think) is making CI tests fail on all PRs.

### CODE REVIEW

**Comment by mezzarobba** [comment]
fixes  #34959

**Comment by fchapoton** [comment]
ok, good to go

**Comment by yyyyx4** [comment]
I think the "fixes #..." syntax only works in the pull request *description*.

**Comment by mezzarobba** [comment]
> I think the "fixes #..." syntax only works in the pull request _description_.

Indeed, thank you.

**Review by fchapoton — APPROVED** [review]
good to go

**Review by JohnCremona — APPROVED** [review]

**Comment by JohnCremona** [comment]
I was just experimenting with the review process -- clearly this patch did not need a second review.

**Comment by saraedum** [comment]
@vbraun we are considering to merge this since it's breaking the CI for everybody at SageDays. We'll discuss this with a few more people here but it seems that the CI should always pass on the develop branch.

**Comment by saraedum** [comment]
@roed314 is preparing a separate PR to fix the linter errors.

**Review by dimpase — APPROVED** [review]
ok, merging!

**Pull request merged**
