### PR TITLE
Sphinx ext links for Sage source files

### LINKED ISSUE #33756: extlinks for Sage source files
<div id="comment:0"></div>

The documentation refers to various source files:

```
$ git grep -E "SAGE_ROOT/(build|src|pkgs)" src/doc
...
src/doc/en/developer/doctesting.rst:  * ``SAGE_ROOT/src/doc/en``
src/doc/en/developer/doctesting.rst:  * ``SAGE_ROOT/src/doc/fr``
src/doc/en/developer/packaging.rst:available packages are the subdirectories of ``SAGE_ROOT/build/pkgs/``.
src/doc/en/developer/packaging.rst:``SAGE_ROOT/build/bin/sage-spkg``. This script is typically invoked by
src/doc/en/developer/packaging.rst:of each individual package in ``SAGE_ROOT/build/pkgs``. In section
...
```
We create a new extlink format for it in `src/sage/misc/sagedoc.py`, 

```
:sage_root:`src/doc/en`
```
which creates links to the corresponding file in https://github.com/sagemath/sage

CC:  @kwankyu

Component: **documentation**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/33756_

### PR DESCRIPTION
**Pull request by mkoeppe**
In the documentation, we can now write `` :sage_root:`src/setup.py` `` or `` :sage_root:`src/doc/en/installation` ``, and it will be formatted uniformly, and a link to the file in the repository will be created.

- Rebased version of #33756

Fixes #33756.

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dcoudert — COMMENTED** [review]
With `:sage_root:`, we have nice links to source files in the documentation.

Concerning ``` :file:`SAGE_ROOT/some/path/to/some/file` ```, it seems that so far it is only used to as a replacement to ``` ``SAGE_ROOT/some/path/to/some/file`` ```, at least in view of the result in the documentation. Is it used to possibly add more functionality later ?

**Comment by mkoeppe** [comment]
> Concerning `` :file:`SAGE_ROOT/some/path/to/some/file` ``, it seems that so far it is only used to as a replacement to `` ``SAGE_ROOT/some/path/to/some/file`` ``, at least in view of the result in the documentation. Is it used to possibly add more functionality later ?

``` :file:`...` ``` is just the standard Sphinx markup for filenames. I'm using it here for filenames that are examples rather than files that exist in the repository. 
I think a different theme could render it differently from how it renders plain ``` ``...`` ```, but there's no difference in our current theme.

**Review by kwankyu — APPROVED** [review]
LGTM.

Some links of the form ```:file:`SAGE_ROOT/...` ``` could still be changed to `:sage_root:`. The distinction is not clear to me. Anyway, these are not defects.

**Comment by vbraun** [comment]
merge conflict

**Pull request merged**
