### PR TITLE
fix Meson file list for src/sage/schemes/elliptic_curves

### PR DESCRIPTION
**Pull request by yyyyx4**
Patch from https://github.com/sagemath/sage/pull/39036#issuecomment-2551245944.

### CODE REVIEW

**Comment by grhkm21** [comment]
Would it be okay for this PR to add `numpy_util.pxd` to `src/sage/modules/meson.build` as well? This is according to `tools/update-meson.py`.

**Comment by yyyyx4** [comment]
Done.

**Review by tobiasdiez — COMMENTED** [review]
Thanks a lot, but this is already fixed in #39139 (with the same changes).

**Comment by yyyyx4** [comment]
I see, thanks for the heads-up. I'll close this one and label the other one as "CI fix" instead.

**Pull request closed without merging**
