### PR TITLE
Change inheritance order in  UniqueRepresentation

### PR DESCRIPTION
**Pull request by enriqueartal**
Currently in `UniqueRepresentation`, the MRO is constructed by
```class UniqueRepresentation(CachedRepresentation, WithEqualityById):```
However, in order to maximize the utility of the `WithEqualityById` class, in particular with subclasses of `UniqueRepresentation`, we should place it *first* in the MRO. This is useful in #37128, where this resolves MRO resolution issues and not having to reimplement (or set aliases) the behavior of `WithEqualityById`.

However, this change, while seemingly innocuous, does cause a problem with one doctest dealing with very old pickles (Sage version <= 4.0) in `combinat/root_system/cartan_type.py` concerning `class CartanType_simple_finite:`. Currently, it is unclear why this change is resulting in the error:
```
sage: from sage.misc.fpickle import unpickleModule
sage: pg_make_integer = unpickle_global('sage.rings.integer', 'make_integer')
sage: si2 = pg_make_integer('4')
sage: unpickle_build(si1, {'tools':unpickleModule('sage.combinat.root_system.type_A'), 't':['A', si2], 'letter':'A', 'n':si2})
Traceback (most recent call last):
  File "/sage/src/sage/doctest/forker.py", line 715, in _run
    self.compile_and_execute(example, compiler, test.globs)
  File "/sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
    exec(compiled, globs)
  File "<doctest sage.combinat.root_system.cartan_type.CartanType_simple_finite.__setstate__[5]>", line 1, in <module>
    unpickle_build(si1, {'tools':unpickleModule('sage.combinat.root_system.type_A'), 't':['A', si2], 'letter':'A', 'n':si2})
  File "/sage/src/sage/misc/explain_pickle.py", line 2442, in unpickle_build
    setstate(state)
  File "/sage/src/sage/combinat/root_system/cartan_type.py", line 3106, in __setstate__
    self.__class__ = T.__class__
TypeError: __class__ assignment: 'CartanType' object layout differs from 'CartanType_simple_finite'
```
However, since these are very old pickles and we cannot reproduce the failure otherwise, we feel that it is prudent to drop support for this and remove the corresponding class.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by enriqueartal** [comment]
@tscrim, @miguelmarco,  can you complete the description?

**Comment by tscrim** [comment]
Changed.

You also need to remove the class in order for the tests to pass.

**Comment by enriqueartal** [comment]
After a merge there are a couple of failing tests for `sage/categories/category_singleton.pyx` and `sage/categories/sets_cat.py` which are the two files where the tests were changed. Before changing the tests, I wonder if the final order in that cases is what we want.

**Comment by tscrim** [comment]
The changed order looks like it is the correct thing given the change to the MRO we are making.

**Review by tscrim — APPROVED** [review]
Okay, then let this be so. Hopefully this will get merged into the next beta0 to get lots of testing. Sorry for being extremely slow with this!

**Comment by enriqueartal** [comment]
Thanks, as you said, beta0 is the right place.

**Comment by enriqueartal** [comment]
I understood that there was a positive review but the label has not been changed.

**Comment by tscrim** [comment]
Sorry, I thought I had changed it.

**Pull request merged**
