### PR TITLE
Implement _latex_ method for (quasi)modular forms ring elements

### LINKED ISSUE #34767: Implement _latex_ method for (quasi)modular forms ring elements
<div id="comment:0"></div>

CC:  @videlec

Component: **modular forms**

Author: **David Ayotte**

Branch/Commit: **[u/gh-DavidAyotte/latex_quasimodforms](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/latex_quasimodforms) @ [`03ab6c6`](https://github.com/sagemath/sagetrac-mirror/commit/03ab6c624ee5b8c4beb3a1caf7784773cc7e2453)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34767_

### PR DESCRIPTION
**Pull request by DavidAyotte**
Fixes #34767

This has already been set to positive review before the Github transition (but I assume that I can't set it myself to this status).

### CODE REVIEW

**Comment by DavidAyotte** [comment]
@tscrim

**Comment by DavidAyotte** [comment]
@dimpase did I do anything wrong when pushing my branches to this PR?

**Comment by dimpase** [comment]
we just updated develop to hopefully let CI work

**Review by tscrim — APPROVED** [review]

**Comment by mkoeppe** [comment]
https://github.com/sagemath/sage/issues/34767 was merged into 10.0.beta0; no more changes are left to be merged.

**Pull request closed without merging**
