### PR TITLE
deprecated functions is_Cone, is_Polyhedron, is_LatticePolytope

### LINKED ISSUE #34307: Deprecate is_Polyhedron, is_Cone, is_LatticePolytope
<div id="comment:0"></div>

... and change all uses to `isinstance(sage.geometry.abc.Polyhedron)` etc.

(see #32414)

CC:  @yuan-zhou @jplab @NicoleYueqiLi

Component: **geometry**

_Issue created by migration from https://trac.sagemath.org/ticket/34307_

### PR DESCRIPTION
**Pull request by vamshipy**
<deprecated 3 functions is_Cone, is_Polyhedron, is_LatticePolytope>

< The change will issue a warning when the functions are used that will inform the user about the functions being deprecated and to use a different instead>
<Fixes #34307>

### :memo: Checklist

- [x ] The title is concise, informative, and self-explanatory.
- [ x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
@mkoeppe

**Comment by mkoeppe** [comment]
This PR is missing the changes from #37052 that rewrite the uses of these newly deprecated functions by `isinstance` calls. Hence all the doctest failures

**Comment by mkoeppe** [comment]
Cherry-picked from #37052.

**Review by tscrim — APPROVED** [review]
Green bot => positive review.

**Comment by mkoeppe** [comment]
Thanks, Travis! Now it's green.

**Pull request merged**
