### PR TITLE
Update the logo at README.md

### PR DESCRIPTION
**Pull request by prirai**
The original logo at the README.md seems broken while accessing from GitHub's web interface. After careful consideration, I decided not to use the original black logo (at /src/doc/common/static/logo_sagemath_black.svg) due to potential disparities in its visibility when viewed by users with different display settings, such as light and dark modes. Therefore, I have update it now to use different variants for dark and light schemes.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have updated the documentation accordingly.

### ⌛ Dependencies

Not required.

### CODE REVIEW

**Comment by kwankyu** [comment]
I think we should consider removing the logo entirely from `readme.md` unless it looks as good (both in light mode and dark mode) as the numpy logo https://github.com/numpy/numpy

**Comment by tobiasdiez** [comment]
This looks like a duplicate of https://github.com/sagemath/sage/pull/35142. It's also possible to show different logos for dark/light mode: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by prirai** [comment]
I think the blue sage logo looks fine for light and dark backgrounds. 

Also, the light/dark mode might not appear well on locally installed markdown viewers which do not support GitHub flavoured markdown. @kwankyu , @tobiasdiez , does the blue logo work for now. If so, can it be merged?

If you want, I can work on a logo which is more consistent throughout. Or is a newer logo already made?

**Comment by kwankyu** [comment]
This works well
```html
<a href="https://sagemath.org">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="src/doc/common/static/logo_sagemath_white.svg">
    <img src="src/doc/common/static/logo_sagemath_black.svg" height="60" align="left">
  </picture>
</a>   
```

**Comment by kwankyu** [comment]
> If you want, I can work on a logo which is more consistent throughout. Or is a newer logo already made?

One of qualms that I have on the logo is that it consists of letters (sci-fi, this is my another qualm) but has the baseline at the bottom boundary of the image so that it does not align well with the surrounding text. The proper baseline should be that of the letters. (Because of this problem, I prefer a geometric logo. Indeed we have a geometric logo, but this logo needs work too, in my opinion)

It seems we can set a baseline to an svg image: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline You may work on this if you want to make the sage logo look better, in a new PR.

**Comment by kwankyu** [comment]
> This looks like a duplicate of #35142.

As this got already positive review, you may need to follow the workflow https://github.com/sagemath/trac-to-github/blob/master/docs/Migration-Trac-to-Github.md#for-contributing-a-change-that-addresses-an-existing-open-issue-that-already-has-a-pr-

**Comment by prirai** [comment]
So, I followed the link above and also got to correct my upstream and origin urls which were set incorrectly. 
I ran `git fetch upstream pull/35142/head:fix-link` and checked out `fix-link`. From here I made this change:

```
<a href="https://sagemath.org/">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="src/doc/common/static/logo_sagemath_white.svg">
    <img src="src/doc/common/static/logo_sagemath_black.svg" height="60" align="left">
  </picture>
</a>
```

After this I pushed this to my fork and then issued a pull request here: https://github.com/wermos/sage/pull/1 

Did I do it correctly or I need to submit a PR here?

**Comment by kwankyu** [comment]
You made a PR to your fork. You should force-push your local branch to this PR.

**Comment by tobiasdiez** [comment]
I think a pure markdown solution is better than the HTML one suggested above.

**Comment by kwankyu** [comment]
Markdown solution has a drawback: https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/#the-problem-with-non-standard-solutions

Also would the anchor work with the markdown solution?

**Review by kwankyu — APPROVED** [review]

**Comment by prirai** [comment]
Imo, a universal solution (the one in HTML) is better than GitHub markdown for the points mentioned here - https://github.com/sagemath/sage/pull/35155#issuecomment-1436277263 and here - https://github.com/sagemath/sage/pull/35155#issuecomment-1435705261 . Does this work?

**Comment by kwankyu** [comment]
Your branch works well.

**Comment by prirai** [comment]
Do I need to do something from my side?

**Comment by kwankyu** [comment]
No.

**Comment by prirai** [comment]
>It seems we can set a baseline to an svg image: [developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline) You may work on this if you want to make the sage logo look better, in a new PR.

- So, how should I start with this? Are we keeping the geometric logo with the sci-fi text one or either of them? 
- Also, what should be the directory of the new logo in case I start a PR now?
- Should I use a separate branch for this?
- Should I make the PR in the repository at - https://github.com/sagemath/artwork instead?

**Comment by kwankyu** [comment]
> * So, how should I start with this? Are we keeping the geometric logo with the sci-fi text one or either of them?

This is experimental. Hence you keep the old ones and add new ones with their own names. 

> * Also, what should be the directory of the new logo in case I start a PR now?

I suggest

```
src/doc/common/static/logo_sagemath_white_new.svg
src/doc/common/static/logo_sagemath_black_new.svg
```
> * Should I use a separate branch for this?

You always create a new local branch for a new PR.

> * Should I make the PR in the repository at - https://github.com/sagemath/artwork instead?

I didn't know the existence of the repo :-) I think we experiment in this repo. Logos are something that matters to everyone. Hence if we like the new logo with baseline and want to replace the old ones with the new ones, then you should propose it to sage-devel https://groups.google.com/g/sage-devel, where people discuss and decide on developer-community-wide matters. After all this, you may optionally make another PR to the artwork repo, I think.

**Comment by kwankyu** [comment]
You also need to update the PR description in the first comment, reflecting what you have really done.

**Pull request merged**
