### PR TITLE
`build/pkgs/boost_cropped`: Switch upstream to scipy, update to 1.75.0

### LINKED ISSUE #34748: update boost-cropped to 1.82.0
<div id="comment:0"></div>

our boost is 5+ years old, and it apparently is a problem, cf #34726 (solved); #35801 (open)

Component: **packages: standard**

Author: **Dima Pasechnik**

Branch/Commit: **[u/dimpase/packages/boost_1_80_0](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/packages/boost_1_80_0) @ [`b7c7fde`](https://github.com/sagemath/sagetrac-mirror/commit/b7c7fde2b35704bdfe0e5e4a4499e007d6251cb8)**

_Issue created by migration from https://trac.sagemath.org/ticket/34748_

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

https://github.com/scipy/boost-headers-only

Resolves #34748

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
boost 1.75 is 2.5 years old. The current boost version is 1.82.0.

Why is scipy  stuck in 1.75?

**Comment by dimpase** [comment]
anyhow, I reckon that all the platforms we support do ship a new enough boost, so this is a low-priority update of a vendored package. 

I'd rather be getting rid of internal boost-cropped. There is always a chance that some Sage package will need more than this from boost, e.g. there are GAP packages which use boost...

**Comment by dcoudert** [comment]
At least this PR should simplify the management of this package.

**Comment by dimpase** [comment]
I think `scipy` has more or less abandoned their boost-headers only clone, and instead went with directly vendoring `Boost.Math` (the only thing they need), cf https://github.com/scipy/scipy/pull/17432

**Comment by dcoudert** [comment]
oups. So then it's not a good idea to switch to this tarball :(

**Pull request closed without merging**
