### PR TITLE
fixing category of ncsym and dual

### PR DESCRIPTION
**Pull request by fchapoton**
by making them Commutative and CoCommutative resp.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Comment by darijgr** [comment]
Has the meaning of commutativity for graded objects been decided at last? I recall there being a controversy between topologists and algebraists there...

**Comment by fchapoton** [comment]
Not sure. But we now see in the tab conpletion
```
sage: F=Algebras(QQ)
sage: F.Supercommutative()
```

**Comment by darijgr** [comment]
Thanks. Looks good to me then!

**Review by darijgr — APPROVED** [review]
Correct and doesn't seem to clash with anything.

**Comment by fchapoton** [comment]
Thanks, Darij. please set to positive review if you are allowed to

**Comment by darijgr** [comment]
I think I did, but I'm new to this workflow :)

**Comment by fchapoton** [comment]
approve is one thing, but you can also add the label "positive review". If you cannot, tell me and I will do

**Comment by fchapoton** [comment]
perfect, spasiba, arigato, merci, danke schön

**Comment by darijgr** [comment]
varsågod

**Comment by vbraun** [comment]
merge conflict

**Comment by fchapoton** [comment]
back to positive after trivial resolution of conflicts

**Pull request merged**
