### PR TITLE
fix ruff PLR1730 checks

### PR DESCRIPTION
**Pull request by GiacomoPope**
In many places we use comparisons followed by conditional assignment. `PLR1730` identifies this and we can instead use `min` and `max`

With https://github.com/sagemath/sage/pull/38541 this should fix the three errors from the lint CI (run from develop)

```
Jack: sage % ruff check --ignore PLR2004,I001,F401,E741,F821,PLR0912,PLR0913,E402,PLR0915,PLW2901,PLR5501,PLR0911,E731,F405,PLR1714,PLR1736,F403,PLR0402,PLW0603,F841,E713,PLW0602,PLR1711,E714,PLR1701,PLR1704,PLW3301,PLW1510,E721,PLW0120,F811,PLC2401,PLC0414,E743,PLE0101,PLR0124,PLW0127,F541,PLW1508,PLC3002,E742,PLE0302,PLW0129,F402,PLC0208 ./src/sage/ --statistics
warning: `PLR1701` has been remapped to `SIM101`.
479 PLW0211 bad-staticmethod-argument
 69 PLR1730 if-stmt-min-max
 63 PLW0642 self-or-cls-assignment
```

Run from this branch

```
Jack: sage % ruff check --ignore PLR2004,I001,F401,E741,F821,PLR0912,PLR0913,E402,PLR0915,PLW2901,PLR5501,PLR0911,E731,F405,PLR1714,PLR1736,F403,PLR0402,PLW0603,F841,E713,PLW0602,PLR1711,E714,PLR1701,PLR1704,PLW3301,PLW1510,E721,PLW0120,F811,PLC2401,PLC0414,E743,PLE0101,PLR0124,PLW0127,F541,PLW1508,PLC3002,E742,PLE0302,PLW0129,F402,PLC0208 ./src/sage/ --statistics
warning: `PLR1701` has been remapped to `SIM101`.
479	PLW0211	bad-staticmethod-argument
 63	PLW0642	self-or-cls-assignment
```

### CODE REVIEW

**Comment by GiacomoPope** [comment]
@fchapoton I'm not sure how to best rebase this PR on top of your work in https://github.com/sagemath/sage/pull/38516 -- any Git/GitHub tips on how to do this best?

**Comment by fchapoton** [comment]
not sure either, sorry. Fetch both branches and merge one into the other ?

**Comment by GiacomoPope** [comment]
I imagine your CI fix will be merged before this, so I might just wait for this and then I'll rebase from develop

**Comment by GiacomoPope** [comment]
@fchapoton This now is up to date with your changes which got merged

**Review by fchapoton — APPROVED** [review]
ok, good

**Pull request merged**
