### PR TITLE
Fix NumberFieldElement_quadratic.is_integral() when D is not square-free

### LINKED ISSUE #34800: wrong result for .is_integral() in quadratic field
<div id="comment:0"></div>

```sage
sage: K.<t> = QuadraticField(-10007^2)
sage: a = t / 10007
sage: a.minpoly()
x^2 + 1
sage: a.minpoly() in ZZ['x']
True
sage: a.is_integral()
False
```

Component: **number fields**

_Issue created by migration from https://trac.sagemath.org/ticket/34800_

### PR DESCRIPTION
**Pull request by pjbruin**
Fixes #34800. The current implementation of is_integral() assumes that D is square-free. We implement the check for integrality of the trace and norm in a way that works for general D.

### CODE REVIEW

**Comment by tscrim** [comment]
Does it make sense to keep the old test for the square-free case (which, of course, would include a check in the method for that)?

**Comment by pjbruin** [comment]
> Does it make sense to keep the old test for the square-free case (which, of course, would include a check in the method for that)?

The problem with that is that knowing whether `D` is square-free requires factoring `D`, which we should certainly avoid. In my implementation, we only need to check one specific candidate for a square divisor, namely `denom` or `u = denom/2` depending on a parity condition.

**Review by tscrim — APPROVED** [review]
Thank you for the explanation. I wasn’t sure if this was already tested somewhere during the initialization (or could have been cached by some other computation) and if the new test would have been (relatively) slower than the old in the case it was already known.

Anyways, positive review.

**Comment by pjbruin** [comment]
Thank you!

**Pull request merged**
