### PR TITLE
#27428 fix use of sig_on()/sig_off() in CBF.integral()

### PR DESCRIPTION
**Pull request by mezzarobba**

### CODE REVIEW

**Comment by mezzarobba** [comment]
Tests morally passing

**Review by fchapoton — APPROVED** [review]
looks good to me

**Comment by vbraun** [comment]
On 32-bit:
```
**********************************************************************
File "src/sage/combinat/bijectionist.py", line 1578, in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
Failed example:
    for p in bij.constant_blocks(): print(list(p))
Expected:
    [[2, 1, 3, 4], [1, 2, 4, 3], [1, 3, 2, 4], [4, 2, 3, 1]]
    [[3, 2, 1], [1, 3, 2], [2, 1, 3]]
    [[2, 4, 3, 1], [3, 2, 4, 1], [2, 3, 1, 4], [1, 3, 4, 2]]
    [[1, 4, 2, 3], [3, 1, 2, 4], [4, 2, 1, 3], [4, 1, 3, 2]]
    [[1, 4, 3, 2], [3, 2, 1, 4]]
    [[2, 1, 4, 3], [4, 3, 2, 1]]
    [[2, 4, 1, 3], [3, 4, 2, 1], [4, 3, 1, 2], [3, 1, 4, 2]]
Got:
    [[1, 2, 4, 3], [4, 2, 3, 1], [1, 3, 2, 4], [2, 1, 3, 4]]
    [[2, 1, 3], [3, 2, 1], [1, 3, 2]]
    [[1, 3, 4, 2], [2, 3, 1, 4], [3, 2, 4, 1], [2, 4, 3, 1]]
    [[3, 1, 2, 4], [4, 2, 1, 3], [4, 1, 3, 2], [1, 4, 2, 3]]
    [[3, 2, 1, 4], [1, 4, 3, 2]]
    [[2, 1, 4, 3], [4, 3, 2, 1]]
    [[3, 4, 2, 1], [2, 4, 1, 3], [4, 3, 1, 2], [3, 1, 4, 2]]
**********************************************************************
File "src/sage/combinat/bijectionist.py", line 1587, in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
Failed example:
    for p in bij.constant_blocks(optimal=True): sorted(p, key=len)
Expected:
    [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]
    [[1, 3, 2],
     [2, 1, 3],
     [3, 2, 1],
     [2, 3, 4, 1],
     [1, 3, 4, 2],
     [2, 1, 3, 4],
     [1, 3, 2, 4],
     [2, 3, 1, 4],
     [1, 2, 4, 3],
     [3, 2, 4, 1],
     [2, 1, 4, 3],
     [2, 4, 3, 1],
     [4, 2, 3, 1],
     [4, 3, 2, 1],
     [1, 4, 3, 2],
     [3, 2, 1, 4]]
    [[1, 4, 2, 3],
     [4, 2, 1, 3],
     [2, 4, 1, 3],
     [4, 3, 1, 2],
     [4, 1, 3, 2],
     [3, 4, 2, 1],
     [3, 1, 2, 4],
     [3, 1, 4, 2]]
Got:
    [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]
    [[3, 2, 1],
     [1, 3, 2],
     [2, 1, 3],
     [2, 1, 4, 3],
     [1, 3, 2, 4],
     [2, 4, 3, 1],
     [1, 3, 4, 2],
     [2, 3, 1, 4],
     [3, 2, 1, 4],
     [4, 2, 3, 1],
     [1, 4, 3, 2],
     [2, 1, 3, 4],
     [1, 2, 4, 3],
     [3, 2, 4, 1],
     [4, 3, 2, 1],
     [2, 3, 4, 1]]
    [[3, 1, 2, 4],
     [4, 1, 3, 2],
     [4, 3, 1, 2],
     [1, 4, 2, 3],
     [3, 4, 2, 1],
     [4, 2, 1, 3],
     [2, 4, 1, 3],
     [3, 1, 4, 2]]
**********************************************************************
1 item had failures:
   2 of  65 in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
    [579 tests, 2 failures, 69.84 s]
----------------------------------------------------------------------
sage -t --long --random-seed=0 src/sage/combinat/bijectionist.py  # 2 doctests failed
----------------------------------------------------------------------
```

**Comment by mkoeppe** [comment]
@vbraun Very unlikely that this failure is coming from this PR!

**Comment by mkoeppe** [comment]
Probably nondeterministic sort order in #35060, which added this test

**Comment by vbraun** [comment]
yep wrong ticket ;)

**Pull request merged**
