### PR TITLE
GH Actions: Upload PyPI sdists also as GitHub Release Assets

### PR DESCRIPTION
**Pull request by mkoeppe**
To align with common practice.

- Test run https://github.com/mkoeppe/sage/actions/runs/10429172254/job/28886375986
- created release https://github.com/mkoeppe/sage/releases/tag/10.5.beta009

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38517 (merged here to resolve merge conflict)

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
OK.

merge with #38517?

**Comment by mkoeppe** [comment]
Done

**Comment by kwankyu** [comment]
Thanks.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
