### PR TITLE
deprecate some imports

### PR DESCRIPTION
**Pull request by jhpalmieri**
- Head toward deprecation of automatic imports of some dev tools
- Remove unnecessary assignments in tests/benchmark.py

Deprecate the imports of some dev tools

### :books: Description

This is a branch to address #34259, replacing the old trac branch. It doesn't make all of the original changes: the original branch. In particular, the original branch added a bunch of lines like `from sage.misc.misc import cputime` even though the import of `cputime` was not changes, just in case someone wanted to change it later. I skipped all of those additions. The original branch made a few other changes that were not connected to the purposes of this pull request (e.g. the changes to src/sage/combinat/composition.py), and I skipped those, too.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM. Thanks for narrowing this ticket, which made it easier to review.

**Comment by jhpalmieri** [comment]
Thank you!

**Comment by vbraun** [comment]
Tests fail after merging 10.1.beta5

**Comment by jhpalmieri** [comment]
I think that should fix it. (Among the original changes: replacing `from sage.all import *` with specific imports, including imports of `cputime` and `walltime`. When combined with #35816, this led to a deprecation warning and hence a doctest failure.)

**Pull request merged**
