### PR TITLE
ideals of non-maximal orders in number fields

### LINKED ISSUE #34198: ideals of non-maximal orders in number fields
<div id="comment:0"></div>

Currently (Sage 9.6), trying to construct an ideal of a non-maximal order in a number field errors out.

We should at least have a basic implementation that supports the standard ideal operations. This can serve as a foundation to which specialized code (such as for class-group computations, cf. #27413) can later be added as needed.

Component: **number fields**

_Issue created by migration from https://trac.sagemath.org/ticket/34198_

### PR DESCRIPTION
**Pull request by yyyyx4**
Resolves #34198.

### CODE REVIEW

**Comment by yyyyx4** [comment]
I know of some follow-up work under active development that depends on this pull request; hence, it would be very helpful if this could get reviewed quickly in order to minimize the amount of effort spent on rebasing those other changes.

**Comment by pjbruin** [comment]
> I know of some follow-up work under active development that depends on this pull request; hence, it would be very helpful if this could get reviewed quickly in order to minimize the amount of effort spent on rebasing those other changes.

I'm happy to review this. I have one question for now: in doctest changes such as
```diff
--- a/src/sage/rings/number_field/class_group.py
+++ b/src/sage/rings/number_field/class_group.py
@@ -32,13 +32,11 @@ EXAMPLES::
     sage: I * I.ideal()   # ideal classes coerce to their representative ideal
     Fractional ideal (4, 1/2*a + 3/2)
 
-    sage: O = K.OK(); O
-    Maximal Order in Number Field in a with defining polynomial x^2 + 23
-    sage: O*(2, 1/2*a + 1/2)
+    sage: K*(2, 1/2*a + 1/2)
     Fractional ideal (2, 1/2*a + 1/2)
-    sage: (O*(2, 1/2*a + 1/2)).is_principal()
+    sage: (K*(2, 1/2*a + 1/2)).is_principal()
     False
-    sage: (O*(2, 1/2*a + 1/2))^3
+    sage: (K*(2, 1/2*a + 1/2))^3
     Fractional ideal (1/2*a - 3/2)
 """
 

```
could we change `O*(2, 1/2*a + 1/2)` to something more descriptive, like `O.fractional_ideal(2, 1/2*a + 1/2)` or `K.fractional_ideal(2, 1/2*a + 1/2)`, rather than to the less descriptive `K*(2, 1/2*a + 1/2)`?

**Comment by pjbruin** [comment]
I have some proposed further changes that suppress the warnings introduced in `sage.rings.finite_rings`. They are in a new branch at https://github.com/pjbruin/sage/tree/public/ideals_for_non_maximal_orders . What is the correct way to deal with such "reviewer patches"?

**Comment by yyyyx4** [comment]
Thanks! Presumably the easiest way is for me to simply merge in your branch, which is what I just did. Alternatively, I think you could've made a pull request on *my* branch associated to this pull request.

**Comment by tscrim** [comment]
> Thanks! Presumably the easiest way is for me to simply merge in your branch, which is what I just did. Alternatively, I think you could've made a pull request on _my_ branch associated to this pull request.

Yes, merging in the specific commit(s) is the best way. There's no need for doing an overly complicated local fork PR IMO. (This is usually done after my first option: Curse at GH's non-collaborative workflow until I feel slightly better.)

**Review by pjbruin — APPROVED** [review]

**Pull request merged**
