### PR TITLE
`build/pkgs/ecm`: Upgrade to 7.0.6

### PR DESCRIPTION
**Pull request by mkoeppe**
- https://gitlab.inria.fr/zimmerma/ecm/-/releases/git-7.0.6

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38344 (merged here)

### CODE REVIEW

**Comment by kwankyu** [comment]
From the log of `./configure`:
```
ecm:                            using system package; SPKG will not be installed
```
So Build&Test does not actually test sage with the upgraded package. This seems to be a defect in our CI. For real test, we should force installation of the upgraded spkg. Could this be fixed?

**Comment by kwankyu** [comment]
Ah, the upgraded package was tested in CI Linux incremental.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
> So Build&Test does not actually test sage with the upgraded package.

That's right; if on this platform the system package can be used, this is what is done in the test.
This works as designed.

> Ah, the upgraded package was tested in CI Linux incremental.

Yes.

**Comment by mkoeppe** [comment]
Thanks for the review!

**Pull request merged**
