### PR TITLE
Fix several issues in find_hamiltonian

### PR DESCRIPTION
**Pull request by dcoudert**
Part of #35902.

The method `find_hamiltonian` had multiple issues: it was not robust to vertices with incomparable labels, it could loop forever if a vertex has degree 1, a segfault was possible on small graphs, it was not properly working for digraphs, etc.
We fix multiple issues and the method should now be safe. 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by dcoudert** [comment]
Thank you Dima. Can I set to positive review ?

**Comment by dimpase** [comment]
yes, please

**Comment by dcoudert** [comment]
Thank you.

**Comment by vbraun** [comment]
On Ubuntu 18.04 64 bit and 20.04 64 bit:
```
**********************************************************************
File "src/sage/graphs/generic_graph_pyx.pyx", line 1256, in sage.graphs.generic_graph_pyx.?
Failed example:
    fh(G)
Expected:
    (False, ['a', 'b', 'c', 'd'])
Got:
    (False, ['x', 'y', 'd'])
**********************************************************************
```

**Comment by dcoudert** [comment]
I changed the doctest to something more robust for this random heuristic.

**Review by dimpase — APPROVED** [review]
OK

**Comment by dcoudert** [comment]
Thank you Dima. I hope it's ok now.

**Pull request merged**
