### PR TITLE
Update conda lock files

### PR DESCRIPTION
**Pull request by tobiasdiez**
### :memo: Checklist

Update (and minimize) the conda lock files.

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #37138 since the configure script fails for some reason (and it is not needed anyway in conda context)

### CODE REVIEW

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by roed314** [comment]
The Sage Code of Conduct Committee is setting this back to needs review for now based on it being part of @dimpase's reaction to our decision on #36181, #36561, #36676, #36951, #36964, #37351, #36999, and #36941.  It can, of course, be granted positive review at a future date, and will be subject to the policy on disputed PRs as normal.

**Comment by saraedum** [comment]
Unfortunately it's not clear what is "disputed" in this PR. (As one of the people who care a lot about conda, I'd love to cast my vote here but I would like to understand both sides first.)

Btw., I think that the PR description is somehow broken. The actual description of the PR is inside the checklist section. (While you're at it, you might want to check the check list or remove it so it's immediately clear that nothing obvious is missing from that list.)

**Comment by mkoeppe** [comment]
> Unfortunately it's not clear what is "disputed" in this PR.

@saraedum This PR is marked as "disputed" because it bundles the disputed https://github.com/sagemath/sage/pull/37138. The latter sabotages the PyPI distribution strategy (clearly documented in https://pypi.org/project/sage-conf/).

**Comment by mkoeppe** [comment]
Updating the conda-lock file does not require this bundling. Per PR description here "the configure script fails for some reason" -- this should be debugged, not papered over.

**Comment by saraedum** [comment]
Since the dispute is about a dependency that is also explicitly listed as a dependency here, could the "disputed" be removed then? (Otherwise, this is imho confusing for people trying to cast votes, like myself.)

**Comment by saraedum** [comment]
Since there is nothing controversial on this specific PR at the moment but rather its dependency needs a vote, I removed the disputed label.

**Comment by mkoeppe** [comment]
outdated

**Pull request closed without merging**
