### PR TITLE
`build/pkgs/{python3,setuptools}`: Update fedora distro info

### PR DESCRIPTION
**Pull request by mkoeppe**
- Cherry-picked from #36181 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by enriqueartal** [comment]
It seems to be OK but I have a small issue. In Fedora 39 I cannot actually test the changes since the required version for setuptools is bigger than the system version. I have a virtual machine with Fedora 40, where this could be applied but sagelib does not build, I guess there will be no problem anyway.
I have also one comment. The change `python->python3` applies to many other `fedora.txt` files; in other cases the `devel` package should also be added to the file since it contains the required files in order to use the system packages. Finally, some packages do not have `fedora.txt` files while the system packages may exist. Would be interesting to create a PR for this issue?

**Comment by mkoeppe** [comment]
Yes, preparing a PR with such updates would be valuable!

**Review by enriqueartal — APPROVED** [review]

**Comment by enriqueartal** [comment]
LGTM, I will prepare a PR for more updates. Do you know if it will be possible to deal with the problems with `sage/graphs/base/sparse_graph.c`, `sage/graphs/base/dense_graph.c`, `sage/graphs/base/static_sparse_backend.c`, `sage/matroids/lean_matrix.c`, and `sage/plot/plot3d/implicit_surface.c` (see https://github.com/sagemath/sage/pull/37537#issuecomment-2053998291)?

**Comment by mkoeppe** [comment]
Thanks!

**Comment by mkoeppe** [comment]
> Do you know if it will be possible to deal with the problems with `sage/graphs/base/sparse_graph.c`, `sage/graphs/base/dense_graph.c`, `sage/graphs/base/static_sparse_backend.c`, `sage/matroids/lean_matrix.c`, and `sage/plot/plot3d/implicit_surface.c` (see [#37537 (comment)](https://github.com/sagemath/sage/pull/37537#issuecomment-2053998291))?

I'll take a look at this in the coming week

**Pull request merged**
