### PR TITLE
`dist.yml`: Build musllinux wheels, build linux aarch64 wheels via QEMU

### PR DESCRIPTION
**Pull request by mkoeppe**
Other changes:
- Reusing the built wheels for build dependencies. This speeds up the build when no compatible binary wheel is on PyPI yet.
- Separate job steps for the various distributions, to improve readability of the output.

Test run: https://github.com/mkoeppe/sage/actions/runs/9666490294

The aarch64 build takes very long (e.g. 20 minutes for each wheel of **sagemath-objects**, total 2.5 hours for sagemath-objects, total 5 hours for all manylinux platforms) because of the CPU emulation. That's normal.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
I see warnings like
```
  info: This container will host the build for cp39-manylinux_aarch64, cp310-manylinux_aarch64, cp311-manylinux_aarch64, cp312-manylinux_aarch64...
  WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
```
No problem or not fixable?

Would you rerun the test after rebase?

**Comment by mkoeppe** [comment]
> I see warnings like
> 
> ```
>   info: This container will host the build for cp39-manylinux_aarch64, cp310-manylinux_aarch64, cp311-manylinux_aarch64, cp312-manylinux_aarch64...
>   WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
> ```

That's normal. It warns about a slow operation (via CPU emulation), which is exactly what is intended here.

**Comment by mkoeppe** [comment]
> Would you rerun the test after rebase?

Running at https://github.com/mkoeppe/sage/actions/runs/9891680565

**Comment by kwankyu** [comment]
Is it a docker image, a container of which runs on a platform emulated by qemu? The warning means that the target platform of the docker image does not match exactly with the emulated platform?

**Comment by mkoeppe** [comment]
Yes, the host (an amd64 machine) uses qemu to run the arm64 (= aarch64) Linux image. In the container running this image, we build the platform wheels for Linux aarch64.

**Comment by kwankyu** [comment]
If the docker is running on the platform emulated by qemu and the message is from the docker, then the "detected host platform" is the platform emulated by qemu, which is amd64. Then the wheel is built for amd64. No?

If the wheel is verified as built for arm64, then obviously there is some error in the above reasoning. So if you could verify it somehow, just ignore me :-)

**Comment by kwankyu** [comment]
The "detected host platform" seems to mean the host platform running the github workflow. And the platform emulated by qemu is arm64. All as you said. OK.

**Comment by kwankyu** [comment]
ChatGPT says we can avoid the warning message with
```
export CIBW_ENVIRONMENT="DOCKER_DEFAULT_PLATFORM=linux/amd64"
```
I don't know, but you may try if you want...

**Comment by kwankyu** [comment]
From the new run:
```
4 wheels produced in 139 minutes:
  sagemath_objects-10.4rc2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl   14,961 kB
  sagemath_objects-10.4rc2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl   16,116 kB
  sagemath_objects-10.4rc2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl   16,200 kB
  sagemath_objects-10.4rc2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl     15,044 kB
```
Note that repeated "cp...-cp...". Is this correct?

The job name is "[wheels manylinux*_aarch64](https://github.com/mkoeppe/sage/actions/runs/9891680565/job/27322959692#logs)". How about just `wheels manylinux_aarch64`?

**Comment by mkoeppe** [comment]
> Note that repeated "cp...-cp...". Is this correct?

Yes, compare with the files at https://pypi.org/project/numpy/#files for example and https://peps.python.org/pep-0491/#file-name-convention for a description of the file name format.

**Comment by mkoeppe** [comment]
> avoid the warning message with
> 
> ```
> export CIBW_ENVIRONMENT="DOCKER_DEFAULT_PLATFORM=linux/amd64"
> ```

I think I'll pass on that.

**Comment by mkoeppe** [comment]
> The job name is "[wheels manylinux*_aarch64](https://github.com/mkoeppe/sage/actions/runs/9891680565/job/27322959692#logs)". How about just `wheels manylinux_aarch64`?

The `*` expresses that `manylinux` will be followed by a version number

**Comment by kwankyu** [comment]
> > The job name is "[wheels manylinux*_aarch64](https://github.com/mkoeppe/sage/actions/runs/9891680565/job/27322959692#logs)". How about just `wheels manylinux_aarch64`?
> 
> The `*` expresses that `manylinux` will be followed by a version number

I think no one can read that meaning from a single asterisk... Not a big deal, anyway.

**Review by kwankyu — APPROVED** [review]
Otherwise lgtm.

**Comment by mkoeppe** [comment]
Thanks

**Pull request merged**
