### PR TITLE
Add `mypy.ini`

### PR DESCRIPTION
**Pull request by mkoeppe**
Configuration from https://github.com/sagemath/sage/issues/36198#issuecomment-1709521850 @fchapoton @jhpalmieri 

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jhpalmieri** [comment]
Do we need to specify `python_version`?

**Comment by mkoeppe** [comment]
No idea, I don't use this tool

**Comment by jhpalmieri** [comment]
Frédéric, comments?

**Comment by fchapoton** [comment]
- This may be slightly prematurate, as typing annotations are very sparse currently in sage, and nowhere ready for full automatic check.

- I think one should maybe put here the oldest python version that sage currently supports.

**Comment by mkoeppe** [comment]
> * This may be slightly prematurate, as typing annotations are very sparse currently in sage, and nowhere ready for full automatic check.

Well, adding the ini file does not set it up to be checked automatically.

**Review by fchapoton — APPROVED** [review]
ok, well

**Comment by mkoeppe** [comment]
Thanks

**Pull request merged**
