### PR TITLE
Implement twisted affine Lie algebras

### PR DESCRIPTION
**Pull request by tscrim**
### :books: Description

Untwisted affine Lie algebras have been implemented in Sage for some time, but their twisted counterparts have been missing. They are more complicated to implement due to the involvement of a diagram automorphism, third roots of unity, and nonreduced root systems.

Along the way, I made some additional fixes in regards to this enhancement:

- Brings coverage up to 100% in lie_algebras.
- Faster Killing matrix for Chevalley basis (which speeds up untwisted affine brackets).
- Fix bug in creating the affine type from a finite type.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
linter not happy and  doctest failing

**Comment by fchapoton** [comment]
There are still some `Kac1990` so the doc does not build

**Comment by tscrim** [comment]
Right, sorry about that. I didn't grep carefully enough.

**Review by fchapoton — APPROVED** [review]
ok, let it be

**Comment by tscrim** [comment]
Thank you.

**Pull request merged**
