### PR TITLE
`sage.sets.family`: Cythonize; change `MIPVariable` to a subclass of `FiniteFamily`

### LINKED ISSUE #31750: MIPVariable: Change to a subclass of FiniteFamily
<div id="comment:0"></div>

... to give it a richer set of operations, such as `len()` to get the number of components and an implementation of `.inverse_family()` to allow looking up the key of a given component (`LinearFunction` instance).

This requires making `AbstractFamily` and `FiniteFamily` Cython classes.

Depends on #34839

CC:  @yuan-zhou @tscrim @mantepse

Component: **linear programming**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/31750_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description
Fixes #31750

### 📝 Checklist

- [ ] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
LGTM overall except one of the tests is failing. My guess is that this is due to a circular import that was somehow being resolved beforehand. My guess for a simple fix would be to bring the `Family` import in `sage.rings.semirings.non_negative_integer_semiring` to the one method where it is called. I doubt this is being used in any tight loops that the extra import check will have an impact.

**Comment by mkoeppe** [comment]
Do you mean the failing "Build documentation" job?

**Comment by tscrim** [comment]
Yes. I don't know exactly why that isn't failing in the usual tests, but it seems like an import issue.

**Comment by mkoeppe** [comment]
It's just a funny malfunction that happens only here on this PR. The docbuild tries to import sage_docbuild after the Python file family.py has been removed but before family.pyx has been compiled.

**Review by tscrim — APPROVED** [review]
Okay, then let it be so.

Families are used so often in lower-level things they probably should have been cythonized awhile ago.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
