### PR TITLE
`README.md`: Improve PyPI install instructions

### PR DESCRIPTION
**Pull request by mkoeppe**
Based on https://groups.google.com/g/sage-devel/c/1viBzw-ZaoQ/m/ZBbjHXGEAAAJ, we improve the section on installation from PyPI.

We also improve **sage_conf** so that `python3 -m sage_conf` is equivalent to `sage-config`. 
After the next stable release is out, we can use this to simplify these installation instructions.

Blocker because we need this to go in the 10.3 stable release.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Removing blocker as there are problems with other PRs, see https://github.com/sagemath/sage/issues/37428 for more details.

**Comment by mkoeppe** [comment]
Restoring "blocker" -- this PR needs to go into the stable release. 
Same comment as https://github.com/sagemath/sage/pull/37351#issuecomment-1961810481 -- https://github.com/sagemath/sage/issues/37428 has absolutely no details, mass removal of the "blocker" label on 9 PRs is not OK.

**Comment by vbraun** [comment]
shouldn''t really be a blocker, oh well pet PR strikes again

**Comment by mkoeppe** [comment]
Thanks for the review.

In a typical project, I'd say that fixing installation instructions ahead of a release would be considered normal maintainer activity.

**Pull request merged**
