### PR TITLE
src/pyproject.toml: Add 'external' section per draft PEP 725 (unbundled from #37446)

### PR DESCRIPTION
**Pull request by mkoeppe**
This is aspirational decoration for future use by skeleton generators by distributions such as conda, sage-the-distribution, pyodide.

Split out from the disputed #37446, where it is bundled with a number of other changes, including: creating a `pyproject.toml` file in `SAGE_ROOT`, hardcoding versions of Python packages instead of using the existing `sage_bootstrap` infrastructure, etc. @roed314 @vbraun

**The scope of PRs should be chosen to minimize friction, not to maximize friction.**
https://github.com/sagemath/sage/pull/36726#issuecomment-1871441132

Author: @mkoeppe, based on @tobiasdiez's #37446.

### :memo: Checklist

- [X] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
For the record (and summary of my DMs with @roed314 on Zulip), there's absolutely nothing wrong with #37476 cherry-picking one of my commits from #37351 and giving it a positive review.

**Comment by kwankyu** [comment]
This is at this point just a record of external dependencies. LGTM.

**Comment by mkoeppe** [comment]
@roed314 @saraedum @jhpalmieri @VivianePons Someone here is manipulating labels again.

**Comment by roed314** [comment]
Thanks for the pointer.  I'll discuss a response with the committee.

**Comment by roed314** [comment]
@tobiasdiez has objected to this PR, but cannot comment here.  See [the here](https://github.com/sagemath/sage/pull/37446#issuecomment-2063317419) for his reasons.

For now, I've set this PR to disputed, and am recording a -1 from Tobias.

**Comment by mkoeppe** [comment]
Resolved merge conflict caused by #36982.

**Comment by mkoeppe** [comment]
@roed314 @saredum @jipilab The "disputed" should be removed here; there's no review or anything here.

**Comment by saraedum** [comment]
> @roed314 @saredum @jipilab The "disputed" should be removed here; there's no review or anything here.

In my personal opinion, it's @tobiasdiez decision whether to remove the label. As for the missing review, I believe that you blocked him here on GitHub so he cannot go through the normal review process first.

Our rules are imo unclear about what is supposed to happen in this case. The rules ask to set to "Needs Work" and leave a comment first. Since that's not an option I guess it's acceptable to skip to "disputed". If that's not how the rules should be interpreted, then maybe an amended version of the rules should be called for a vote on sage-devel to cover this case.

**Comment by mkoeppe** [comment]
Let's just go through the "disputed PRs" procedure. The PR has carried the "disputed" label since Apr 20.
I'm counting:
- 2 in favor: @kwankyu (per review from Apr 16), @mkoeppe (PR author)
- 1 against: @tobiasdiez

**Pull request merged**
