### PR TITLE
Fix names of Gentoo packages

### PR DESCRIPTION
**Pull request by saraedum**
Gentoo renamed some build tools in late 2023. We update the names here to fix the broken CI runs for Gentoo (that happen e.g. for cypari2.)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion. (Offline discussion at SageDays, i.e., cypari builds are broken.)
- [x] I have created tests covering the changes. (There's already plenty of Gentoo CI in our setup that fails without this.)
- [x] I have updated the documentation accordingly. Nothing to do there.

### CODE REVIEW

**Comment by saraedum** [comment]
Here's the new package: https://packages.gentoo.org/packages/dev-build/make

Here's the old package: https://web.archive.org/web/20230701000000*/https://packages.gentoo.org/packages/sys-devel/make

**Comment by saraedum** [comment]
@fchapoton I am waiting to see if the Gentoo CI manages to install `make`.

**Comment by fchapoton** [comment]
maybe this specific CI needs to be triggered manually ?

**Review by dimpase — APPROVED** [review]
LGTM w.r.t. the package names (checked on a real gentoo box). If something in CI needs fixing then it could be done in a followup.

**Comment by dimpase** [comment]
@kiwifb @orlitzky

**Comment by saraedum** [comment]
@fchapoton, Gentoo tests pass with these changes.

**Review by fchapoton — APPROVED** [review]

**Comment by kiwifb** [comment]
> @kiwifb @orlitzky

LGTM

**Pull request merged**
