### PR TITLE
Replace more `.all` imports

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

This is a follow-up on:
- #35110 

As preparation for #35322, which is changing more packages to implicit namespace packages, we remove `.all` imports from these packages throughout the Sage library.

This is part of:
- #29705 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #35418
- Depends on https://github.com/sagemath/sage/pull/35358

### CODE REVIEW

**Comment by tornaria** [comment]
You are just making my life miserable:
````
ModuleNotFoundError: No module named 'sage.modules.with_basis.all'
```

I did nuke all the empty `__init__.py` files in my system site-packages. Then my system sagemath is broken because I'm missing some `all.py` files. Also, some non-empty `__init__.py` files have to be removed as here. Producing a patch from #35322, #35366 and this to apply to 9.8 is a pain because of the huge amount of churn. Also, patching 9.8 is a moving pain since what has to be done changes depending on which of these three I want to test...

One thing I don't understand is: why on earth are the empty `all.py` files needed? Aren't you repeating python mistakes? It feels crazy that some doctest failures disappear just by adding an empty `__init__.py` or an empty `all.py`.

I would like to argue that the behaviour with or without these empty files should be identical. That's the point of PEP 420: that directories without `__init__.py` are packages just as much as those with `__init__.py` files. Requiring an `all.py` file goes against this.

In any case, as I requested before, it would be better if there is JUST ONE single point of "removing empty files that may break havoc" and then don't do it again.

Even more: could we please have

(1) one PR that introduces all the changes needed to support removing empty `__init__.py` files, but leaves all the empty `__init__.py` files there? The goal is that I get something where I can safely do 
```
find  .../sage/ -name "__init__.py" -size 0 -delete
```
without having any type of trouble and without having to add random `all.py` files.

(2) a separate PR with only removal of empty `__init__.py` files ?

Ideally (1) is merged in one release, and (2) is merged in a later release.

After the move to gh, I was able to contribute a lot more efficiently to sage (both code and reviews). But the last 2 weeks, since this happened with the merge of #35100, I've been stuck unable to do anything at all. I'm getting tempted of pruning all my sage git trees for 6 months to wait until this is over.

**Comment by mkoeppe** [comment]
Kindly rephrase for clarity

**Comment by mkoeppe** [comment]
Rebased away from #35322. Ready for review.

**Comment by mkoeppe** [comment]
Rebased on top of https://github.com/sagemath/sage/pull/35418

**Comment by tornaria** [comment]
Merge conflict with #35358 (see 63c3ab6b7)

**Comment by tornaria** [comment]
FWIW, after fixing the trivial merge conflict, all tests pass for me on void linux.

**Comment by mkoeppe** [comment]
Merged & resolved

**Review by tornaria — APPROVED** [review]

**Comment by tornaria** [comment]
LGTM

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
