### PR TITLE
Reject system gap 4.13

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Thanks, Volker.

**Comment by tornaria** [comment]
-1

Nothing here explains why this should be a blocker, not even why this should happen at all.

**Comment by tornaria** [comment]
https://github.com/sagemath/sage/pull/37884#issuecomment-2183538972 shows that whatever issue you have is not about gap 4.13 but about a particular (broken?) install of gap.

**Comment by mkoeppe** [comment]
> Nothing here explains why this should be a blocker, not even why this should happen at all.

Because we're trying to make a release, and your PR #37884 is not ready.

**Comment by tornaria** [comment]
> > Nothing here explains why this should be a blocker, not even why this should happen at all.
> 
> Because we're trying to make a release, and your PR #37884 is not ready.

Come on, #37884 is 100% ready, blame your #38169. But note that updating 4.12.2 to 4.13.1 doesn't need anything special for us (https://github.com/void-linux/void-packages/pull/49571/files#diff-d5e8ac4c14235608656fe702205ba0e985de306ecc14756391643152370bfbd3).

**Comment by mkoeppe** [comment]
Please @tornaria. As you know, #37884 is not in a shape to be merged because nobody implemented the proposed solutions to support both the old and the new version (see https://github.com/sagemath/sage/pull/37884#issuecomment-2081814558).

**Comment by tornaria** [comment]
> Please @tornaria. As you know, #37884 is not in a shape to be merged because nobody implemented the proposed solutions to support both the old and the new version (see [#37884 (comment)](https://github.com/sagemath/sage/pull/37884#issuecomment-2081814558)).

Please @mkoeppe. As you know, #37884 is 100% ready to run sagemath with gap 4.13.0 or 4.13.1. The reason forhy #38169 is not ready escapes me.

**Comment by tornaria** [comment]
... and there is nothing here that explains the reason to reject system gap 4.13.

**Comment by mkoeppe** [comment]
@tornaria The Release Manager will simply not merge a PR such as #37884 that requires a newer version of a library than what is provided by the Sage distribution -- because he tests with the Sage distribution, the tests will fail, and he'll set it back to "needs work".

So whenever you want to prepare a PR that adds support for a newer version of a library, 
- either find a way to support both the old and the new version (including passing all tests);
- or combine the PR with the upgrade of the library.

But I'm pretty sure that you know all that. So what's with the "Come on" and "Please"?

**Pull request merged**
