### PR TITLE
`sage.modular.hecke`: Deprecate `is_Hecke...` functions

### PR DESCRIPTION
**Pull request by mkoeppe**
Replacing the old-style `is_...` functions by just using `isinstance`.

Also some docstring/doctest cosmetics.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by mkoeppe** [comment]
rebased

**Comment by mkoeppe** [comment]
Tests pass, back to "needs review"

**Comment by kwankyu** [comment]
OK.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
