### PR TITLE
`pkgs/sagemath-{bliss,coxeter3,...}`: Move metadata from `setup.cfg` to `pyproject.toml`

### PR DESCRIPTION
**Pull request by mkoeppe**
- Part of https://github.com/sagemath/sage/issues/33577

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36563

### CODE REVIEW

**Comment by kiwifb** [comment]
Hum, consequence of removing it from sage_setup. Fair enough. I thought I had reviewed this one already. I guess those PR got mixed up in my head.

**Comment by mkoeppe** [comment]
I think we should put this commit on #36562 instead

**Review by kiwifb — APPROVED** [review]
LEt's get this in already. Thought it was done long ago.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by kiwifb** [comment]
We will have to visit the MANIFEST.in again. I noticed a number of sdist includes .m4 files(sagemath-bliss, sagemath-standard for example) and some do include .gitignore (sagemath-standard for example).

**Comment by mkoeppe** [comment]
We can do that as part of #36649

**Pull request merged**
