### PR TITLE
Fix Cygwin CI after #32841

### LINKED ISSUE #35048: Cygwin CI failing
On every CI run, I'm getting a failure from a misconfigured cygwin CI workflow:

```
[Invalid workflow file: .github/workflows/ci-cygwin-standard.yml#L1](https://github.com/roed314/sage/actions/runs/4124660481/workflow)
No steps defined in `steps` and no workflow called in `uses` for the following jobs: cygwin-stage-ii-e
```

I tried fixing the problem in #35005, but gave up since I don't know how to write github workflows.  Some possibly relevant discussion: https://stackoverflow.com/questions/73305126/passing-env-variable-inputs-to-a-reusable-workflow and https://github.com/orgs/community/discussions/26671.

It would be nice to fix this, since I'm getting an email about the failed run every time I push to a PR.

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

Cygwin workflows were mangled by a bad merge, leading to syntax errors even whenever the workflow is parsed.

Here we fix this; note that the Cygwin workflow is still not functional afterward (the first step, installation of Cygwin with choco, fails). But this will only affect builds of releases and does not happen for PR CI runs.

Closes #35048 

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by roed314** [comment]
This is certainly an improvement (since the workflow starts now), but it still seems to be failing: https://github.com/sagemath/sage/actions/runs/4137773690.

**Comment by roed314** [comment]
You should probably also merge develop.

**Comment by mkoeppe** [comment]
> This is certainly an improvement (since the workflow starts now), but it still seems to be failing

Yes, as noted in the PR description.
Fixing the workflow won't be very useful at the moment – I don't plan to work on the Cygwin port any more, and no one else has stepped up. See https://github.com/sagemath/sage/wiki/ReleaseTours-sage-9.7#sources

**Comment by mkoeppe** [comment]
> You should probably also merge develop.

No need; nothing else touches these files.

**Comment by roed314** [comment]
Ok.

**Review by roed314 — APPROVED** [review]
Works for me: I'm no longer getting syntax errors on the workflow.

**Comment by mkoeppe** [comment]
Thanks, David!

**Comment by dimpase** [comment]
Can we have a careful rebase here? I don't want to accidentally destroy `fix-develop`.

**Comment by dimpase** [comment]
We can also merge directly into develop... But pick one way.

**Comment by mkoeppe** [comment]
What is fix-develop?

**Comment by mkoeppe** [comment]
Oh I see, I created the branch in sagemath/sage by accident. Will delete as soon as this PR is merged.

**Comment by tobiasdiez** [comment]
@dimpase If you choose "Squash" in the merge button dropdown, then the branch history of develop is a bit cleaner than with a classical merge.

**Pull request merged**
