### PR TITLE
Fix matrix coercion with numpy 2.1

### PR DESCRIPTION
**Pull request by antonio-rojas**
numpy 2.1 requires a `copy` argument for `numpy.array`. Fixes test failures with numpy 2.1:
```
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/matrix/matrix1.pyx", line 723, in sage.matrix.matrix1.Matrix.numpy
Failed example:
    b = numpy.array(a); b
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 716, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.matrix.matrix1.Matrix.numpy[9]>", line 1, in <module>
        b = numpy.array(a); b
            ^^^^^^^^^^^^^^
      File "sage/matrix/matrix1.pyx", line 673, in sage.matrix.matrix1.Matrix.numpy (build/cythonized/sage/matrix/matrix1.c:14076)
        def numpy(self, dtype=None):
    TypeError: numpy() got an unexpected keyword argument 'copy'
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/matrix/matrix1.pyx", line 727, in sage.matrix.matrix1.Matrix.numpy
Failed example:
    b.dtype
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 716, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.matrix.matrix1.Matrix.numpy[10]>", line 1, in <module>
        b.dtype
        ^
    NameError: name 'b' is not defined
**********************************************************************
File "/usr/lib/python3.12/site-packages/sage/matrix/matrix1.pyx", line 730, in sage.matrix.matrix1.Matrix.numpy
Failed example:
    b.shape
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 716, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.12/site-packages/sage/doctest/forker.py", line 1146, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.matrix.matrix1.Matrix.numpy[11]>", line 1, in <module>
        b.shape
        ^
    NameError: name 'b' is not defined
**********************************************************************
```

### CODE REVIEW

**Comment by kiwifb** [comment]
Is it compatible with numpy 2.0?

**Comment by antonio-rojas** [comment]
> Is it compatible with numpy 2.0?

works locally, I see some CI issues though

**Comment by kiwifb** [comment]
Should it be `copy="copy"`?

**Comment by kiwifb** [comment]
OK, I have read the manual and now I understand your patch. `copy` expect a boolean and the default is `True`. I think that should be the default for the `numpy` function rather than `None` (which I am guessing could be taken as `False` with some casting).

**Comment by antonio-rojas** [comment]
OK, I see the issue is incompatibility with numpy 1, which is still shipped in sage-the-distro. Let's try default to `True`.

**Comment by antonio-rojas** [comment]
Works locally now with 2.1, 2.0 and 1.26

**Review by kiwifb — APPROVED** [review]
LGTM

**Comment by tornaria** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/sagemath/patches/numpy_2.1a.patch

https://github.com/void-linux/void-packages/blob/master/srcpkgs/sagemath/patches/numpy_2.1b.patch

**Comment by user202729** [comment]
Just come across this. While this fixes the tests, it isn't really correct:

* it breaks Liskov substitution principle — `Matrix_numpy_dense` inherits from `Matrix_dense`, yet `Matrix_numpy_dense` doesn't allow passing `copy=True` to `.numpy()` method.
* It doesn't really work correctly (see  https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword and https://github.com/scipy/scipy/pull/20172/files for the proper fix)

Will work on a fix soon.

**Pull request merged**
