### PR TITLE
Use URLs to online Sage documents for JupyterLab

### PR DESCRIPTION
**Pull request by kwankyu**
Sage documents in the Help menu of JupyterLab have stopped working for long time. Those are essentially links to local files, but they don't work for JupyterLab. We replace them with URLs to online documents, to make them functional again.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by egourgoulhon — APPROVED** [review]
LGTM. I've checked that Sage documentation is now available from the Jupyerlab menu.

**Comment by egourgoulhon** [comment]
A side comment: this PR changes the access to Sage documentation for  the Jupyter notebook as well (not only for Jupyterlab): the online documentation is now returned instead of the local one (this access was not broken in the Jupyter notebook,  only in Jupyterlab). Some people may consider this as a kind of regression (one should privilege the locally build doc over the online one), but only a very minor one, IMHO. So I think this is OK.

**Comment by egourgoulhon** [comment]
Thank you for the fix!

**Comment by kwankyu** [comment]
> A side comment: this PR changes the access to Sage documentation for the Jupyter notebook as well (not only for Jupyterlab): the online documentation is now returned instead of the local one (this access was not broken in the Jupyter notebook, only in Jupyterlab). Some people may consider this as a kind of regression (one should privilege the locally build doc over the online one), but only a very minor one, IMHO. So I think this is OK.

Right. I was aware of that. I agree with you about the regression.

By the way, for Jupyter notebook 7 that supersedes classic notebook, I guess that help links to local files might not work anyway just like with JupyterLab, since they say notebook 7 is sharing the core with JupyterLab. I could not confirm this because of the issue

https://github.com/jupyter/notebook/issues/6963

which will be fixed in notebook 7.1. So we will see this later.

Thanks for the review!

**Pull request merged**
