### PR TITLE
invariants are now  linearly independent

### LINKED ISSUE #35684: FinitelyGeneratedMatrixGroup_gap.invariants_of_degree should return a basis of the space of invariants
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Sage Version**: 10.0
```

### Steps To Reproduce

A colleague of mine discovered a bug in FinitelyGeneratedMatrixGroup_gap.invariants_of_degree, and I am not completely sure how to fix it.  Here is the bug:
```
sage: gens = [matrix(QQ, [[-1,1],[-1,0]]), matrix(QQ, [[0,1],[1,0]])]
sage: G = MatrixGroup(gens)
sage: s = Sequence(G.invariants_of_degree(14))
sage: s.coefficient_matrix()[0].rank()
2
sage: len(s)
3
```

### Expected Behavior

The invariants returned should be linearly independent, i.e., the rank of the matrix above should be 3.

### Actual Behavior

The returned invariants are distinct, but not linearly independent.

### Additional Information

Dear all, especially Ben!

A colleague of mine discovered a bug in FinitelyGeneratedMatrixGroup_gap.invariants_of_degree, and I am not completely sure how to fix it.  Here is the bug:

sage: gens = [matrix(QQ, [[-1,1],[-1,0]]), matrix(QQ, [[0,1],[1,0]])]
sage: G = MatrixGroup(gens)
sage: s = Sequence(G.invariants_of_degree(14))
sage: s.coefficient_matrix()[0].rank()
2
Here is a fix, which I am not convinced of.  It does a brute force check, adding invariants only if the rank increases.

This is certainly very inefficient, but also possibly wrong, because it relies on `Sequence` finding the correct universe.

```#diff
diff --git a/src/sage/groups/matrix_gps/finitely_generated.py b/src/sage/groups/matrix_gps/finitely_generated.py
index 0b5f14014e..130d0bf4f1 100644
--- a/src/sage/groups/matrix_gps/finitely_generated.py
+++ b/src/sage/groups/matrix_gps/finitely_generated.py
@@ -1328,12 +1328,15 @@ class FinitelyGeneratedMatrixGroup_gap(MatrixGroup_gap):
        ms = self.molien_series(prec=deg+1,chi=chi)
        if ms[deg].is_zero():
            return []
-        inv = set()
+        inv = []
        for e in IntegerVectors(deg, D):
            F = self.reynolds_operator(R.monomial(*e), chi=chi)
            if not F.is_zero():
                F = F / F.lc()
-                inv.add(F)
-                if len(inv) == ms[deg]:
+                inv.append(F)
+                rk = Sequence(inv).coefficient_matrix()[0].rank()
+                if rk == ms[deg]:
                    break
+                if rk < len(inv):
+                    inv.pop()
        return list(inv)
```

### PR DESCRIPTION
**Pull request by Bruno-TT**
fixes #35684

please read issue for more information

### CODE REVIEW

**Comment by fchapoton** [comment]
the linter is not happy, please fix that

**Comment by fchapoton** [comment]
doctests are not passing

**Comment by mantepse** [comment]
I must say that I feel ignored.  What happened to https://github.com/sagemath/sage/issues/35684#issuecomment-1621349961 ?

The code doesn't even comply with the sage conventions.  Most importantly, it is not at all clear (at least to me) why this check does the right thing.

**Comment by dimpase** [comment]
@mantepse - this PR was opened 2 weeks ago. There was ample time to propose improvements

**Comment by dimpase** [comment]
> Most importantly, it is not at all clear (at least to me) why this check does the right thing.

the invariants in a given degree are generated by the images of the monomials in this degree under the Reynolds operator  $\rho$. The fix just keeps adding linearly independent images of mononials under $\rho$, until there are no more to add.
Actually, it can be sped up by using available info on the invariant ring - e.g. the dimension in this degree may be known in advance, e.g. from the Molien series.
@Bruno-TT - can you look at it?

**Comment by mantepse** [comment]
> @mantepse - this PR was opened 2 weeks ago. There was ample time to propose improvements

And so I did - apparently even before the PR was opened.  Should I have repeated my comment?

**Comment by dimpase** [comment]
Apologies, I thought that our mighty linters would complain about lines being too long. Unfortunately this hasn't happen,
and the 147-chars line just went in...

As to the correctness question, it's IMHO too basic to be added to the docs.

**Comment by dimpase** [comment]
> Should I have repeated my comment?

this certainly would have helped. Anyhow, feel free to open another PR to fix whatever you think needs to be fixed.

**Comment by mantepse** [comment]
> Apologies, I thought that our mighty linters would complain about lines being too long. Unfortunately this hasn't happen, and the 147-chars line just went in...

I think that also 'len(x) == 0' is not according to the style guide.

> As to the correctness question, it's IMHO too basic to be added to the docs.
The code was fixed already at least twice, without comment, so I doubt that it is too basic.

**Pull request merged**
