### PR TITLE
Implement the Potts representation of the partition algebra

### PR DESCRIPTION
**Pull request by tscrim**
The Potts representation is an important representation of the partition algebra $P_n(d)$ (say, over a field of characteristic 0) that corresponds to the Schur-Weyl duality with the symmetric group $S_d$. We provide an implementation of this representation, both as a left $S_d$-module and right $P_n(d)$-module. (If $n$ is a half integer, then we only have a $S_{d-1}$-module.)

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
I allowd myself to add a very small reviewer commit. ok ?

**Comment by tscrim** [comment]
@fchapoton Yes, good with me.

**Review by fchapoton — APPROVED** [review]
then good to go

**Comment by tscrim** [comment]
Merci!

**Pull request merged**
