### PR TITLE
`Animation.ffmpeg`: Shell-quote filenames

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

Fixes https://groups.google.com/g/sage-devel/c/gsMDcsBjk5s

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
If you understand why coverage check `codecov/patch` failed (I don't), could you add a test to satisfy it?

**Comment by mkoeppe** [comment]
These doctests are only run when the `ffmpeg` package is installed; it isn't.

**Comment by kwankyu** [comment]
I see. So codecov doesn't understand our `optional` tag.

**Review by kwankyu — APPROVED** [review]
It works well.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
