### PR TITLE
Bump up actions

### PR DESCRIPTION
**Pull request by gmou3**
Bump up the bumpable actions.
Should be complete in conjunction with #37474. 

Note: `potiuk/get-workflow-origin` is not maintained anymore and throws warnings.

- Depends on #36498 (merged here)

### CODE REVIEW

**Comment by mkoeppe** [comment]
The bump of upload-artifact/download-artifact is not so easy because 
- v3 and v4 are not interoperable
- v4 does not support multiple uploads 
- some of our workflows are reusable workflows #33338 used in other repos

**Comment by gmou3** [comment]
I'll drop those then.

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by mkoeppe** [comment]
This will conflict with #36498 (already on Volker's branch), which splits out the pyright tests into a separate workflow. You may want to rebase preemptively.

**Comment by gmou3** [comment]
Should be fine now.

**Comment by mkoeppe** [comment]
The merge/rebase with #36498 will have to be done.

**Pull request merged**
