### PR TITLE
Normal Python packages: postpone wheel installation to the post-install phase

### LINKED ISSUE #30956: sdh_store_and_pip_install_wheel: Install from the persistent wheel directory
<div id="comment:0"></div>

Python packages no longer use SAGE_DESTDIR except for staging/removing the `.whl` file.

This last bit of staging leads to `sage -pip freeze` showing wheel URLs in temporary build locations:

```
$ ./sage -pip freeze
alabaster @ file:///Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/var/tmp/sage/build/alabaster-0.7.12/src
appdirs==1.4.4
appnope @ file:///Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/var/tmp/sage/build/appnope-0.1.0.p0/src
argon2-cffi==20.1.0
attrs @ file:///Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/var/tmp/sage/build/attrs-19.3.0/src
Babel @ file:///Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/var/tmp/sage/build/babel-2.6.0/src
```

(These locations are recorded in `direct_url.json` according to https://www.python.org/dev/peps/pep-0610/; see https://packaging.python.org/en/latest/specifications/direct-url/)

In this ticket, we remove the staging, writing the `.whl` file directly into `SAGE_VENV/var/lib/sage/wheels`. (Uninstallation of the `.whl` file will be done by adding to the `spkg-piprm` script.) 

Thus, `sage -pip freeze` will show the actual file URLs of the stored wheels.

CC:  @jhpalmieri @tobiasdiez

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/30956_

### PR DESCRIPTION
**Pull request by mkoeppe**
Previously, on `sdh_pip_install`, the wheel file is staged in DESTDIR, but the wheel is installed immediately.
Now we store a new script `spkg-pipinst`, which is run after unloading DESTDIR (and before any `spkg-postinst` script), which does the actual installation of the wheel.

- This resolves #30956 (fixing the wheel URLs shown in `sage -pip freeze`) -- except when `SAGE_SUDO` is set.

Apart from this and some changes to the messages displayed during package installation, this should make no difference for any of our packages.

Just so that it is tested for at least one package in CI, we include a small package update.

Together with 
- #36738 and
- #36740, 

this is preparation for requiring only the build dependencies ("build-system requires") while building a wheel for the package, and to require the runtime dependencies ("install-requires") only later, when the wheel is to be installed.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
In hindsight it's obvious that I should have tested this case...

**Comment by jhpalmieri** [comment]
I don't typically set `SAGE_SUDO`, but to test I set it to `'sudo -E'` and once again, `pip` failed to build:
```
removing /var/folders/7c/bz8vl5tx47ndyy8knwrtg1k00000gp/T/tmp.Y4ofb1qD0R
/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/bin/python3: No module named pip
(ignoring error)
/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/bin/python3: No module named pip
Warning: installing with "python3 -m pip install --verbose --no-index --find-links=/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/lib/sage/wheels --disable-pip-version-check --isolated --no-cache-dir" failed. Retrying, adding "--no-deps --ignore-installed --ignore-requires-python"
/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/bin/python3: No module named pip
Error: installing with pip  failed
********************************************************************************
Error installing
--root=/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/pip-23.3.1/inst
--no-warn-script-location --ignore-installed -r
/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/lib/sage/scripts/pip/spkg-requirements.txt
```

**Comment by jhpalmieri** [comment]
Maybe things with `SAGE_SUDO="sudo -E"` still aren't right. Without this, just building normally, `./sage --pip freeze | grep tmp` returns no hits, but with `SAGE_SUDO="sudo -E"`, I get lots of hits:
```
% ./sage --pip freeze | grep tmp | wc
     140     420   50093
```
This looks like the same as building without this branch. Examples:
```
alabaster @ file:///Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/alabaster-0.7.12/inst/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/lib/sage/wheels/alabaster-0.7.12-py2.py3-none-any.whl#sha256=97a89e510af23283d07834c7760e08086d4f8813597e860b6f855ff3c09e7863
appnope @ file:///Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/appnope-0.1.3/inst/Users/jpalmier/Sage/TESTING/test/sage-10.2.rc5/local/var/lib/sage/venv-python3.11/var/lib/sage/wheels/appnope-0.1.3-py2.py3-none-any.whl#sha256=3a530d0a94cfac4ba3187c16266dbb3d338216726a374c94dcaeb999cfe68b37
```

**Comment by mkoeppe** [comment]
You are right. I do not have a solution for fixing wheel URL for the `SAGE_SUDO` case. I have updated the PR description.

**Review by jhpalmieri — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thank you!

**Comment by mkoeppe** [comment]
At some point we may want to deprecate `SAGE_SUDO`. Introducing it was helpful as it informed restructuring the installation of packages into build vs. install phase. But my own use case for this feature (for use by IT on a shared installation) has gone away, and I'm not sure if this is used by others.

**Pull request merged**
