### PR TITLE
New modularized distributions sagemath-{sirocco,bliss,meataxe,mcqd,coxeter3,tdlib}

### LINKED ISSUE #34346: New modularized distributions sagemath-{sirocco,bliss,meataxe,mcqd,coxeter3,tdlib}
<div id="comment:0"></div>

These are the python extension modules that depend on the optional packages sirocco, bliss, ...
- https://pypi.org/project/sagemath-meataxe
- https://pypi.org/project/sagemath-sirocco
- https://pypi.org/project/sagemath-bliss/
- https://pypi.org/project/sagemath-mcqd/
- https://pypi.org/project/sagemath-coxeter3/
- https://pypi.org/project/sagemath-tdlib/

We also add distros/conda.txt for some of these packages.

We should add this info to https://doc.sagemath.org/html/en/installation/conda.html#installing-all-of-sagemath-from-conda-not-for-development

Depends on #32874
Depends on #34761
Depends on #34858
Depends on #34855

CC:  @saraedum @mkoeppe @slel @kiwifb @antonio-rojas @tornaria @dimpase

Component: **refactoring**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss) @ [`9686423`](https://github.com/sagemath/sagetrac-mirror/commit/96864238fe7712541ec373098bb2f58d607a041c)**

_Issue created by migration from https://trac.sagemath.org/ticket/34346_

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

As reported by @kiwifb in https://groups.google.com/g/sage-release/c/BdHjadsnYUc/m/Qb1SVmn4AAAJ, the sagemath-standard-10.0 distribution does not include the file `src/sage/graphs/bliss.pyx`.
We create separate distributions that ship the missing files:

- https://pypi.org/project/sagemath-tdlib/10.0/
- https://pypi.org/project/sagemath-meataxe/10.0/
- https://pypi.org/project/sagemath-coxeter3/10.0/
- https://pypi.org/project/sagemath-bliss/10.0/
- https://pypi.org/project/sagemath-mcqd/10.0/
- https://pypi.org/project/sagemath-sirocco/10.0/

- Resolves #34346 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kiwifb** [comment]
Looks like we have generic description on pypi:
```
Sage: Open Source Mathematics Software: Graph (iso/auto)morphisms with ....
```
I thought it was believable for `bliss` but for `meataxe`.

In any case, I have a sagemath-bliss ebuild that seem to work and I will release bliss and meataxe because I currently support them. I will take it as an opportunity to add more optional packages. I am just having thoughts about building documentation. These would need to be installed before the documentation is built or trigger a rebuild of the doc (expensive in sage-on-gentoo). I have to think about this more deeply.

**Comment by mkoeppe** [comment]
> Looks like we have generic description on pypi

Thanks, I'll fix this in a moment.

**Comment by mkoeppe** [comment]
> I am just having thoughts about building documentation. These would need to be installed before the documentation is built

I think the modules shipped by these optional distributions do not appear in the index files at all.

**Comment by kiwifb** [comment]
> > I am just having thoughts about building documentation. These would need to be installed before the documentation is built
> 
> I think the modules shipped by these optional distributions do not appear in the index files at all.

Indeed, it looks like it. Well, that was one unnecessary headache.

**Comment by kiwifb** [comment]
Is `SAGE_OPTIONAL_PACKAGES_WITH_EXTENSIONS` only for the sage distribution? Also, I see `fes` in its definition. I thought `fes` support had been removed https://github.com/sagemath/sage/commit/444d3f3f581a0f1cb2f3497664ffb46405182024

Is there a reason why `src/sage/setup.py` doesn't echo the changes from `pkgs/sagemath-standard/setup.py`?

**Comment by mkoeppe** [comment]
> Is there a reason why `src/setup.py` doesn't echo the changes from `pkgs/sagemath-standard/setup.py`?

Yes, `src/setup.py` does not need to know the names of distributions to include because its strategy is to filter out the not-to-be-installed optional files.

**Comment by mkoeppe** [comment]
> I see `fes`

Thanks, fixed in 612ca8f

**Comment by kiwifb** [comment]
> > Is there a reason why `src/setup.py` doesn't echo the changes from `pkgs/sagemath-standard/setup.py`?
> 
> Yes, `src/setup.py` does not need to know the names of distributions to include because its strategy is to filter out the not-to-be-installed optional files.

I guess I have been using this in reverse for quite some time to build some optional packages. That will be one more set of simplifications in my life. But ultimately I think those lines of code in `src/sage/setup.py` will have to die. But that's a battle for another day.

It is shaping up nicely and it is motivating me to add more of those optional packages.

**Comment by mkoeppe** [comment]
> Is `SAGE_OPTIONAL_PACKAGES_WITH_EXTENSIONS` only for the sage distribution?

Yes, and it is only used in the non-editable monolithic install.

**Comment by mkoeppe** [comment]
> ultimately I think those lines of code in `src/sage/setup.py` will have to die. But that's a battle for another day.

Yes, I agree on both.

**Comment by mkoeppe** [comment]
@miguelmarco @enriqueartal With sirocco installed, I am getting two test failures:
```
sage -t --random-seed=39280810521803661632748536288307423766 sage/schemes/curves/zariski_vankampen.py
**********************************************************************
File "sage/schemes/curves/zariski_vankampen.py", line 602, in sage.schemes.curves.zariski_vankampen.braid_in_segment
Failed example:
    B  # optional - sirocco
Expected:
    s5*s3^-1
Got:
    s0^-1*s1^-1*s0^-1*s5*s3^-1
**********************************************************************
1 item had failures:
   1 of  18 in sage.schemes.curves.zariski_vankampen.braid_in_segment
    [118 tests, 1 failure, 8.55 s]

sage -t --random-seed=39280810521803661632748536288307423766 sage/schemes/curves/projective_curve.py
**********************************************************************
File "sage/schemes/curves/projective_curve.py", line 1744, in sage.schemes.curves.projective_curve.ProjectivePlaneCurve_field.fundamental_group
Failed example:
    C.fundamental_group()                         # optional - sirocco
Expected:
    Finitely presented group < x1, x3 | (x3^-1*x1^-1*x3*x1^-1)^2*x3^-1,
                                        x3*(x1^-1*x3^-1)^2*x1^-1*(x3*x1)^2 >
Got:
    Finitely presented group < x1, x3 | x1^-1*x3*x1^-1*(x3^-1*x1)^2*x3, x3^-1*x1^2*x3^-1*x1*x3^3*x1, x3*(x1^-1*x3^-1)^2*x1^-1*(x3*x1)^2 >
**********************************************************************
```
(https://github.com/sagemath/sage/actions/runs/5040848111/jobs/9040057533#step:11:7932)

Do these look familiar to you?

**Comment by enriqueartal** [comment]
I have checked with develop and my branch (both with 10.0). I get the same failure in the develop branch but the test passes in mine (checked in two computers). For the other failure I do not get it in either branch. Actually the result obtained is other presentation of the same finite group.
I will try to understand what happens.

**Comment by miguelmarco** [comment]
> @miguelmarco @enriqueartal With sirocco installed, I am getting two test failures:
> 
> ```
> sage -t --random-seed=39280810521803661632748536288307423766 sage/schemes/curves/zariski_vankampen.py
> **********************************************************************
> File "sage/schemes/curves/zariski_vankampen.py", line 602, in sage.schemes.curves.zariski_vankampen.braid_in_segment
> Failed example:
>     B  # optional - sirocco
> Expected:
>     s5*s3^-1
> Got:
>     s0^-1*s1^-1*s0^-1*s5*s3^-1
> **********************************************************************
> 1 item had failures:
>    1 of  18 in sage.schemes.curves.zariski_vankampen.braid_in_segment
>     [118 tests, 1 failure, 8.55 s]
> 
> sage -t --random-seed=39280810521803661632748536288307423766 sage/schemes/curves/projective_curve.py
> **********************************************************************
> File "sage/schemes/curves/projective_curve.py", line 1744, in sage.schemes.curves.projective_curve.ProjectivePlaneCurve_field.fundamental_group
> Failed example:
>     C.fundamental_group()                         # optional - sirocco
> Expected:
>     Finitely presented group < x1, x3 | (x3^-1*x1^-1*x3*x1^-1)^2*x3^-1,
>                                         x3*(x1^-1*x3^-1)^2*x1^-1*(x3*x1)^2 >
> Got:
>     Finitely presented group < x1, x3 | x1^-1*x3*x1^-1*(x3^-1*x1)^2*x3, x3^-1*x1^2*x3^-1*x1*x3^3*x1, x3*(x1^-1*x3^-1)^2*x1^-1*(x3*x1)^2 >
> **********************************************************************
> ```
> 
> (https://github.com/sagemath/sage/actions/runs/5040848111/jobs/9040057533#step:11:7932)
> 
> Do these look familiar to you?

It looks like a usual problem when you have points in the same vertical precisely at the beginning (or end) of the path. In that case, the braid will depend on subtleties like how two representations of the same number compare. I guess something changed internally that caused this kind of difference (something related to converting algebraic numbers to floating point complexes and/or complex intervals i guess).

To compute a closed braid, it is not a problem, since this differences should cancel between consecutive segments, but the result inside a specific segment could be different.

If this is the problem indeed, we could safely adapt the doctests to the new representation.

**Comment by miguelmarco** [comment]
What kind of machine/OS runs the CI?

**Comment by kiwifb** [comment]
How does pip usually handle duplicate files? I am asking because when installing cython debug files, every single one of these packages (and sagemath-standard) want to provide `sage/cython_debug/interpreter`. In the Gentoo context, the package manager stops complaining of file collisions and refuse to merge the package in the system. I had to go and add instructions to remove it prior to merge.

**Comment by mkoeppe** [comment]
> How does pip usually handle duplicate files? I am asking because when installing cython debug files, every single one of these packages (and sagemath-standard) want to provide `sage/cython_debug/interpreter`.

Thanks for spotting this. We should get rid of this file.

**Comment by mkoeppe** [comment]
> What kind of machine/OS runs the CI?

@miguelmarco The incremental builds run on top of the Docker container image ghcr.io/sagemath/sage/sage-ubuntu-focal-standard-with-targets:dev

**Comment by kiwifb** [comment]
> > How does pip usually handle duplicate files? I am asking because when installing cython debug files, every single one of these packages (and sagemath-standard) want to provide `sage/cython_debug/interpreter`.
> 
> Thanks for spotting this. We should get rid of this file.

I tracked the creation of the file to `Cython/Debugger/DebugWriter.py` where it is created after the other cython debug files. No opt out. We would probably need to include an extra step to strip it in `sage_build_cython` in `sage_setup` or something that wraps it. May be a small helper function would help.

**Comment by mkoeppe** [comment]
@kiwifb I've opened #35725 for this. 

What should I put in `build/pkgs/*/distros/gentoo.txt`?

Anything else that needs changing here?

**Comment by kiwifb** [comment]
> @kiwifb I've opened #35725 for this.
> 
> What should I put in `build/pkgs/*/distros/gentoo.txt`?
> 
> Anything else that needs changing here?

I did not add anything to the main tree related to those. In the overlay I added libsirocco to support sirocco. I looked at the other optional packages (mcqd, coxeter3, tdlib) and cringed. I do not see them leaving "optional" any time soon.

However, `sci-libs/bliss` could be added to `build/pkgs/bliss/distros/gentoo.txt`. We have had bliss for a while.

**Comment by mkoeppe** [comment]
Done in 7c04f4417a.

**Comment by mkoeppe** [comment]
Let's get this in please

**Comment by kiwifb** [comment]
> Let's get this in please

We definitely need this in before 10.1. This is a bit messy at the moment. I can deal with it for now but we have to do something about #35725 - any suggestions besides mine earlier?

**Review by kiwifb — APPROVED** [review]

**Comment by mkoeppe** [comment]
At the moment the modularized distributions do not guarantee disjointness – and there's no mechanism to check it.
I'd postpone worrying about `sage/cython_debug/interpreter` to later, when we have created this mechanism.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by kiwifb** [comment]
I have a problem that I am fairly sure I do not have with 10.0. There may be something I need to adjust. But now that this is merged I have separate sagemath-{bliss,..} package for develop like I have for "release" (10.0). I tried to install the brand new packages and bang:
```
 * Detected file collision(s):
 * 
 *      /usr/lib/python3.11/site-packages/sage/graphs/bliss.pyx
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * sci-mathematics/sage-9999:0::sage-on-gentoo
 *      /usr/lib/python3.11/site-packages/sage/graphs/bliss.pyx
```
Considering that I dealt with another file collision early on for 10.0 release, I am fairly sure I did not have this one before. Did we mess something up when we merged the upgrade for bliss?
The sirocco package has the same issue with `sage/libs/sirocco.pyx` but meataxe seems to have comprehensive collisions with stuff from meataxe, sirocco, coxeter and sagemath_objects????
```
 *      /usr/lib/python3.11/site-packages/sage/libs/all.py
 *      /usr/lib/python3.11/site-packages/sage/libs/all__sagemath_coxeter3.py
 *      /usr/lib/python3.11/site-packages/sage/libs/all__sagemath_meataxe.py
 *      /usr/lib/python3.11/site-packages/sage/libs/all__sagemath_objects.py
 *      /usr/lib/python3.11/site-packages/sage/libs/all__sagemath_sirocco.py
 *      /usr/lib/python3.11/site-packages/sage/libs/meataxe.pxd
 *      /usr/lib/python3.11/site-packages/sage/libs/meataxe.pyx
```
I'll check my other system with 10.0 later today when I have access to it.

**Comment by mkoeppe** [comment]
Yes, there's clearly a mistake in the MANIFEST. I thought I had already fixed all of these, but I'll take another look.

**Pull request merged**
