### PR TITLE
`sage.symbolics`: Remove code deprecated in #18036, #29738, #32386, #32638, #32665, #34215

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dcoudert — APPROVED** [review]
LGTM.

The reported doctest errors are independent (`geng` missing on the system)

**Comment by mkoeppe** [comment]
Thanks!

**Review by dcoudert — APPROVED** [review]
Sorry for not seeing the issue. I tried on a Fedora desktop: passes all tests, documentation builds well.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
