### PR TITLE
Make "[source]" link to develop branch on github

### PR DESCRIPTION
**Pull request by kwankyu**
This is a bug in #37589. I  made other small edits.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
So this simply completes the change that you said you'd do in https://github.com/sagemath/sage/pull/37589#issuecomment-1996568283?

**Comment by mkoeppe** [comment]
By the way, do you think this would this be easy to do:
- #37759

**Comment by kwankyu** [comment]
> So this simply completes the change that you said you'd do in [#37589 (comment)](https://github.com/sagemath/sage/pull/37589#issuecomment-1996568283)?

If you mean Problem 2 mentioned in the comment, no. This PR fixes a bug so that `[source]` opens a github page that allows me to **edit** the source file (previously not worked because the github page is on a tag branch). But still github does not allow me to **commit** the changes because I am in `sagemath/sage`, not on my forked repo.

**Comment by mkoeppe** [comment]
Thanks for the explanation. LGTM.

**Comment by kwankyu** [comment]
>  ideally the banner at the top would give a link to the PR instead of saying that it's for the development version.

For that, the PR number should be available to the doc build process.  Perhaps the PR number could be added to the version...

But I really don't understand how such a link could be useful... The user typically comes to the doc from the PR.

**Comment by kwankyu** [comment]
> ... But still github does not allow me to **commit** the changes because I am in `sagemath/sage`, not on my forked repo.

A manual way to be able to commit is (of course) to patch the url (from "sagemath/sage" to "user/sage" :-) before starting to edit.

**Comment by mkoeppe** [comment]
> But I really don't understand how such a link could be useful... The user typically comes to the doc from the PR.

Consider the scenario of users who tend to have too many tabs open in the browser

**Comment by kwankyu** [comment]
I see. I can also imagine that one opens a doc tab separate from a PR tab, which I often do. In that case, back button does not go to the PR.

**Comment by kwankyu** [comment]
> [#37759] Also the source links should link to the branch of the PR, not the tagged version.

No idea.

**Comment by mkoeppe** [comment]
I've added a link to #37759 to explain where this information is available

**Comment by kwankyu** [comment]
Thanks. Thanks for review!

**Pull request merged**
