### PR TITLE
Allow construct RIF element from question-style string

### PR DESCRIPTION
**Pull request by user202729**
As in the title. It allows you to say e.g. `RIF("1.23?2e-5")`.

Partially handles https://github.com/sagemath/sage/issues/36797. (only for real case. Complex case is not handled yet, but in principle it should not be too difficult.)

(I don't see any disadvantage of allowing this, it's backwards compatible)

Issue: currently 

```
sage: RIF("10", base=37)
37
sage: ZZ("10", base=37)
[error]
```

should this inconsistency be fixed? If so how?

[Edit: actually the rule of conversion should probably follow [string to mpfr conversion rule](https://www.mpfr.org/mpfr-current/mpfr.html#index-mpfr_005fstrtofr) or [string to mpz conversion rule](https://gmplib.org/manual/Assigning-Integers) ]

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview. (there's no documentation change, but should we explicitly mention the feature? I think the feature to construct from `[a..b]` isn't explicitly mentioned either…?)

### :hourglass: Dependencies

https://github.com/sagemath/sage/pull/39001

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
LGTM; does what it says and is well tested.

**Comment by tscrim** [comment]
We can worry about the integer case later on I think.

**Comment by user202729** [comment]
Thanks!

**Comment by vbraun** [comment]
On 32-bit:
```
**********************************************************************
File "src/sage/rings/convert/mpfi.pyx", line 133, in sage.rings.convert.mpfi._from_str_question_style
Failed example:
    x = RIF("1.123456?2e1000000000"); x
Expected:
    1.12346?e1000000000
Got:
    [-infinity .. +infinity]
**********************************************************************
File "src/sage/rings/convert/mpfi.pyx", line 135, in sage.rings.convert.mpfi._from_str_question_style
Failed example:
    x.str(style="question", error_digits=3)
Expected:
    '1.12345600?201e1000000000'
Got:
    '[-infinity .. +infinity]'
**********************************************************************
1 item had failures:
   2 of  50 in sage.rings.convert.mpfi._from_str_question_style
    [57 tests, 2 failures, 0.58s wall]
**********************************************************************
```

**Comment by user202729** [comment]
Most likely the binary exponent in 32-bit is limited to 2^31, and 10^10^9 > 2^2^31.

Fix should be simple.

**Review by tscrim — APPROVED** [review]

**Pull request merged**
