### PR TITLE
Update conda-lock files, rename macOS conda-lock files to match CI Conda, remove unexplained duplicate lock files

### LINKED ISSUE #37997: CI Conda is broken because `macos-latest` is now Apple Silicon
... and the wrong conda-lock file is used.

We should perhaps switch to multi-platform lock files - https://conda.github.io/conda-lock/basic_usage/

### PR DESCRIPTION
**Pull request by mkoeppe**
The renaming is done so that the fix here can take effect on PR runs via the "CI Fix" mechanism (as changes to the workflow files themselves cannot take effect).
- Moreover, making arm64 the default platform for macOS makes sense because all new macOS machines use this platform.

And update by running `.github/workflows/conda-lock-update.py` for all architectures.

- Workflow matrix variables now contain `-latest`, to add tests for the macOS x86_64 platform (runner name: `macos-13`)

- Removes some unexplained duplications (both `arm` and `arm64` files for macOS, both `aarch` and `aarch64` for Linux)

- Fixes #37997

Author: @mkoeppe, @gmou3 

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38033 (split out from here)
- Depends on #38034 (split out from here)
- Depends on #38222 (merged here)

### CODE REVIEW

**Comment by mkoeppe** [comment]
```
  File "sage/algebras/quatalg/quaternion_algebra_cython.pyx", line 1, in init sage.algebras.quatalg.quaternion_algebra_cython
  File "sage/matrix/matrix_integer_dense.pyx", line 1, in init sage.matrix.matrix_integer_dense
ImportError: dlopen(/Users/runner/work/sage/sage/src/sage/libs/linbox/linbox_flint_interface.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6FFPACK8CharPolyIN6Givaro8Poly1DomINS1_7ModularIddvEENS1_5DenseEEEEERNT_7ElementERKS7_S9_mNS7_8Domain_t11Element_ptrEmRNSC_8RandIterENS_19FFPACK_CHARPOLY_TAGEm'
```

**Comment by mkoeppe** [comment]
```
  In file included from /Users/runner/miniconda3/envs/sage/include/giac/giac.h:5:
  In file included from /Users/runner/miniconda3/envs/sage/include/giac/poly.h:26:
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:341:10: error: no template named 'pointer_to_binary_function' in namespace 'std'
      std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> strictly_greater ;
      ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:342:28: error: no template named 'pointer_to_binary_function' in namespace 'std'
      sort_helper(const std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> is_strictly_greater):strictly_greater(is_strictly_greater) {};
                        ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:41: error: no member named 'ptr_fun' in namespace 'std'
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                     ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:49: error: expected expression
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                  ^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:70: error: expected expression
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                                       ^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:343:95: error: expected '(' for function-style cast or type construction
      sort_helper():strictly_greater(std::ptr_fun<const monomial<T> &, const monomial<T> &, bool>(m_lex_is_strictly_greater<T>)) {};
                                                                                            ~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:680:18: error: no template named 'pointer_to_binary_function' in namespace 'std'
               const std::pointer_to_binary_function < const monomial<T> &, const monomial<T> &, bool> m_is_strictly_greater
                     ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:729:44: error: no template named 'pointer_to_binary_function' in namespace 'std'
      typedef std::map< index_t,T,const std::pointer_to_binary_function < const index_m &, const index_m &, bool> > application;
                                        ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:730:30: error: no type named 'ptr_fun' in namespace 'std'
      application produit(std::ptr_fun(is_strictly_greater));
                          ~~~~~^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:737:14: error: 'application' (aka 'int') is not a class, namespace, or enumeration
      typename application::iterator prod_it,prod_itend;
               ^
  /Users/runner/miniconda3/envs/sage/include/giac/monomial.h:754:29: error: use of undeclared identifier 'prod_itend'; did you mean 'prod_it'?
      prod_it=produit.begin(),prod_itend=produit.end();
```

**Comment by mkoeppe** [comment]
That's with `giac                      1.9.0.21             h1c96721_1    conda-forge`

**Comment by mkoeppe** [comment]
https://en.cppreference.com/w/cpp/utility/functional/pointer_to_binary_function
(removed in C++17)

**Comment by mkoeppe** [comment]
```
  building 'sage.matroids.graphic_matroid' extension
  /home/runner/miniconda3/envs/sage/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/runner/miniconda3/envs/sage/include -fPIC -O2 -isystem /home/runner/miniconda3/envs/sage/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/runner/miniconda3/envs/sage/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/runner/miniconda3/envs/sage/include -fPIC -Isage/data_structures -I/home/runner/miniconda3/envs/sage/lib/python3.9/site-packages/cysignals -Isage/cpython -I/home/runner/work/sage/sage/src -I/home/runner/miniconda3/envs/sage/lib/python3.9/site-packages/numpy/core/include -I/home/runner/miniconda3/envs/sage/include/python3.9 -I/home/runner/miniconda3/envs/sage/include/python3.9 -c sage/matroids/graphic_matroid.c -o /tmp/tmpj1q6x7la.build-temp/sage/matroids/graphic_matroid.o
  sage/matroids/graphic_matroid.c: In function '__pyx_f_4sage_8matroids_15graphic_matroid_14GraphicMatroid__has_minor':
  sage/matroids/graphic_matroid.c:23551:234: error: macro "minor" passed 3 arguments, but takes just 1
  23551 |       __pyx_t_2 = ((struct __pyx_vtabstruct_4sage_8matroids_15graphic_matroid_GraphicMatroid *)__pyx_v_self->__pyx_base.__pyx_vtab)->__pyx_base.minor(((struct __pyx_obj_4sage_8matroids_7matroid_Matroid *)__pyx_v_self), 0, &__pyx_t_21); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 610, __pyx_L1_error)
        |                                                                                                                                                                                                                                          ^
  In file included from /home/runner/miniconda3/envs/sage/x86_64-conda-linux-gnu/sysroot/usr/include/sys/types.h:226,
                   from /home/runner/miniconda3/envs/sage/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:320,
                   from /home/runner/miniconda3/envs/sage/include/python3.9/Python.h:34,
                   from sage/matroids/graphic_matroid.c:50:
  /home/runner/miniconda3/envs/sage/x86_64-conda-linux-gnu/sysroot/usr/include/sys/sysmacros.h:66: note: macro "minor" defined here
     66 | # define minor(dev) gnu_dev_minor (dev)
        |
```

**Comment by mkoeppe** [comment]
@gmou3 Here we have run in a strange symbol clash from the Cythonization of GraphicMatroid. See https://stackoverflow.com/questions/22240973/major-and-minor-macros-defined-in-sys-sysmacros-h-pulled-in-by-iterator; would you be able to work around it?

**Comment by vbraun** [comment]
Shouldn't the CI then work on this ticket if this ticket fixes it? Because it seems like @mkoeppe canceled the run. Should it be this way?

**Comment by mkoeppe** [comment]
@vbraun This fixes the "Build&Test using conda": See the green checkmarks.

**Comment by mkoeppe** [comment]
@vbraun I'll update the branch protection rule to make the "Expected -- Waiting for status to be reported" disappear.

**Comment by mkoeppe** [comment]
Thanks, Volker.

**Comment by mkoeppe** [comment]
Tests for the 9 platforms running at https://github.com/mkoeppe/sage/actions/runs/9152977644

**Comment by mkoeppe** [comment]
@vbraun Let's get this in please.

**Comment by mkoeppe** [comment]
Labels are being manipulated again here.

**Comment by saraedum** [comment]
> Labels are being manipulated again here.

I suppose that @tobiasdiez is being blocked by you so he cannot state what he would like to change in this PR?

Apart from that, it would seem to me that he's entitled to set a PR to "needs work" and request changes. Tobias, maybe you can try to share what you would like to change by some other means?

**Comment by mkoeppe** [comment]
He previously communicated in the thread https://groups.google.com/g/sage-devel/c/tw6J8vU7IY0

**Comment by saraedum** [comment]
Apparently he did not feel that his remarks were addressed sufficiently but I can only speculate.

**Comment by saraedum** [comment]
I don't think the "needs work" should have been removed here automatically. @tobiasdiez could not leave a formal review here, so the bot got this wrong I assume.

**Comment by mkoeppe** [comment]
Setting to "needs work" without saying what needs work is not part of our review process.

**Comment by saraedum** [comment]
I understand that he cannot "say" that because he's blocked by you? In any case, probably "disputed" is appropriate here.

**Comment by mkoeppe** [comment]
I've marked it "disputed" because that seems to be once more the situation here.

**Comment by mkoeppe** [comment]
> I understand that he cannot "say" that because he's blocked by you?

He can say what he has to say on sage-devel. 

Necessary public reminder that he is blocked as a reciprocal act for blocking me on GitHub.

**Comment by mkoeppe** [comment]
Redone on top of 
- https://github.com/sagemath/sage/pull/38222, 

which makes the known-test-failures additions unnecessary

**Comment by mkoeppe** [comment]
Test of the 9 platforms https://github.com/mkoeppe/sage/actions/runs/9525719071

**Comment by mkoeppe** [comment]
```
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/number_field/galois_group.py  # 1 doctest failed
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/number_field/number_field.py  # 2 doctests failed
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/qqbar.py  # 1 doctest failed
```

**Comment by mkoeppe** [comment]
Put back some of the `ci-conda-known-test-failures.json` additions.

**Comment by kwankyu** [comment]
If a PR gets "disputed" label, people are expected to vote rather than to review the PR. Hence the author (not the reviewer) should summarize what is the disputed issue so that people can focus on the disputed issue. It is wasteful that all people read the PR, read all changes, read all (likely to be many and lengthy) comments and do detective work to find out the disputed issue. 

The summary describes the disputed issue (what the reviewer objects and pointers to major comments) and could be posted in a visible place, like the PR summary, with heading something like "DIsputed Issue: ..."

**Comment by mkoeppe** [comment]
> If a PR gets "disputed" label, people are expected to vote rather than to review the PR.

I don't think so. No review has happened here yet

**Comment by kwankyu** [comment]
Then remove "disputed" label.

**Comment by kwankyu** [comment]
I did a bit of "detective work". 

Adding "needs work" label without explaining the work is inappropriate. At least copy and paste it **here**.

**Comment by kwankyu** [comment]
Blocking a possible reviewer is also inappropriate. I think it could be a possible action before, but now that CoC is operating, the action has no place anymore.

**Comment by mkoeppe** [comment]
Unfortunately the committee is far from functioning.

**Comment by kwankyu** [comment]
Let's start again, unblocking @tobiasdiez and removing "disputed" (and "needs work") labels, so that the new process applies.

**Comment by roed314** [comment]
> Unfortunately the committee is far from functioning.

While Matthias has every right to disagree with the approach the Code of Conduct Committee is taking, we want to reassure any others reading this thread that we are functional and taking actions (public and private) when warranted.
The SageMath Code of Conduct Committee

**Comment by mkoeppe** [comment]
@roed314 For sure it's not part of the duties of the committee to send out public "corrections" of this kind.

**Comment by saraedum** [comment]
We do not understand our response as a public correction. Rather, we aim to reassure the community that the Code of Conduct Committee is active and committed to addressing concerns both publicly and privately. It is part of our duty to ensure that community members feel confident in reaching out to us with their complaints or issues.
The SageMath Code of Conduct Committee

**Comment by vbraun** [comment]
I've read through all of this and didn't find any downside that even remotely warrants not fixing the macos arm CI. And yes intel macs are dead, we are most likely in the last year of support. So lets get this in.

For the record, Tobia's objections to a previous version of the PR were 
> - Needs to be tested on all 6 os/python version combinations
> - Updates of the conda lock files should never require additions to the "known bugs" exclusions. If a certain version upgrade results in problems, add a version constraint to the conda files to exclude that particular version.
> - The changes related to "-latest" in ci-conda are no improvement
> - The renaming of the macos lock files are now inconsistent with the naming of the linux lock files. We should not orient ourselves on what github actions use as the default, but what is the most common system - these files are primarily intended to be used by users, and not for the ci.

**Comment by mkoeppe** [comment]
Thanks, Volker, for the responsible action.

**Comment by vbraun** [comment]
As Tobias points out, there are three new test failures that, upon cursory glance, seem to be equivalent on ARM but not identical to x86: https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272
```
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/number_field/galois_group.py  # 1 doctest failed
9452
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/number_field/number_field.py  # 2 doctests failed
9453
sage -t --random-seed=133746178035167682710283568786452478190 src/sage/rings/qqbar.py  # 1 doctest faile
``` 
Obviously it would be nice if the "default" osx arch works. Perhaps the doctest just needs to verify that the result is correct instead of being one out of multiple correct answers.

**Comment by mkoeppe** [comment]
I don't have time for "would be nice" work on this.
The fix needs to go in the release.

**Comment by mkoeppe** [comment]
Over in 
- #38265

@tobiasdiez comments:
> The PR https://github.com/sagemath/sage/pull/37998 claims to fix the ARM build of macos but the package updates (commit https://github.com/sagemath/sage/commit/f0e064bdcf8af7b4bc9e568ff553cd51004fdd92) introduce test failures:
> - Test run before this commit: https://github.com/sagemath/sage/actions/runs/9525058035/job/26258729278
> - Test run after this commit: https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272
> Same errors can also be found in https://github.com/sagemath/sage/pull/37998#issuecomment-2169133377

False facts. What Tobias cites as a "test run before this commit" is actually a test run with an earlier version of this PR merged as a CI Fix.

**Comment by mkoeppe** [comment]
@vbraun I've redone the branch so that the conda package update from #35396 is reflected.

**Comment by mkoeppe** [comment]
Tests at https://github.com/mkoeppe/sage/actions/runs/9671105316

**Comment by mkoeppe** [comment]
Tests at https://github.com/mkoeppe/sage/actions/runs/9672092917

**Comment by kwankyu** [comment]
> > * Test run before this commit: https://github.com/sagemath/sage/actions/runs/9525058035/job/26258729278
> > * Test run after this commit: https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272
> >   Same errors can also be found in [Update conda-lock files, rename macOS conda-lock files to match CI Conda, remove unexplained duplicate lock files #37998 (comment)](https://github.com/sagemath/sage/pull/37998#issuecomment-2169133377)
> 
> False facts. What Tobias cites as a "test run before this commit" is actually a test run with an earlier version of this PR merged as a CI Fix.

Confirmed. "Test run before this commit" has the same failures but in the baseline set from this PR merged as a CI Fix.

Tobias' argument is sound but based on false facts.

**Comment by kwankyu** [comment]
Is this
```
sage -t --random-seed=147712982467446710824553287018105912799 src/sage/libs/singular/function.pyx  # 3 doctests failed
```
new?

**Comment by kwankyu** [comment]
As we are here, may I ask (not a thing to do here): Could we put all these environment-xxx files into, say `conda` directory to clean up the sage root directory, and recommend 
```
conda env create --file ./conda/environment-3.11-linux.yml --name sage-build
```
in the developer guide?

**Comment by mkoeppe** [comment]
some restructuring like this could be a good idea, but not for this PR

**Comment by mkoeppe** [comment]
> Is this
> 
> ```
> sage -t --random-seed=147712982467446710824553287018105912799 src/sage/libs/singular/function.pyx  # 3 doctests failed
> ```
> 
> new?

I think this is another sporadic failure, which I've probably seen before.
It does not show in the set of tests https://github.com/mkoeppe/sage/actions/runs/9672092917

**Comment by kwankyu** [comment]
Another question. This is also not a thing to be done here:

It seems that the script `.github/workflows/conda-lock-update.py` is a utility for humans. Why is it in `.github/workflows`?

**Comment by mkoeppe** [comment]
It was said at the time that maybe one day these lock files would be updated automatically by a GH Actions workflow.

**Comment by kwankyu** [comment]
Regarding

> The renaming of the macos lock files are now inconsistent with the naming of the linux lock files. We should not orient ourselves on what github actions use as the default, but what is the most common system - these files are primarily intended to be used by users, and not for the ci.

As far as I can see, there is nothing "oriented by github actions" in naming lock files. But the comment may be to the old version of this PR...

**Comment by kwankyu** [comment]
> It was said at the time that maybe one day these lock files would be updated automatically by a GH Actions workflow.

Yes, I thought something like it. Perhaps `ci-conda.yml` may run the script and deliver the diffs of updated lock files as an artifact or as annotations...

**Review by kwankyu — APPROVED** [review]
I am positive to this PR. We need this PR, ASAP to fix conda ci.

**Comment by mkoeppe** [comment]
Thanks.

**Pull request merged**
