### PR TITLE
Implement symmetry classes of plane partitions

### PR DESCRIPTION
**Pull request by tscrim**
Implement symmetric classes on plane partitions #28244

### CODE REVIEW

**Comment by fchapoton** [comment]
the seems to be a problem with NewType somewhere, see the build & test

**Comment by tscrim** [comment]
> the seems to be a problem with NewType somewhere, see the build & test

Are we sure that is a real error? It is something with `pyright` that I don't really know. I do not know what to even test to try and reproduce locally.

**Comment by fchapoton** [comment]
The second argument of NewType must be a class, not a string. Either remove all annotations with PP (namely `--> PP`), or try using `PP = NewType('PP', PlanePartition)`. Not sure what's best and what will work.

**Comment by tscrim** [comment]
All tests now pass. Thanks @fchapoton

**Comment by tscrim** [comment]
@kevindilks @jessicapalencia @sagetrac-jangsookim Could one of you finish the review for this? It is just checking my last commits.

**Comment by fchapoton** [comment]
one import of ZZ zhould be changed

**Comment by tscrim** [comment]
@fchapoton Thank you. I wasn't aware it was easy to push review changes like that. (In fact, it is somewhat worrisome the default allows such pushes...) Is there anything else that needs to be done?

**Comment by fchapoton** [comment]
I guess I may have been given some super-powers. Maybe I should have not done that, but it was such a simple change..

I think this is ready.

**Comment by tscrim** [comment]
I would be a bit surprised about that since you pushed to the branch on my fork. It might be a normal part of working on GH (I don't recall seeing anything about this on the transition/workflow guide).

Then are you approving the PR? (I can't do this since it is coming from my fork.)

**Comment by fchapoton** [comment]
when creating a pull request, there is a box to tick where you can allow changes on your own fork by the managers of the main repo. 

Yes, let me approve the thing here. I would rather squash all these commits, but it may complicated, no idea about what would happen with the new process..

**Review by fchapoton — APPROVED** [review]
good to go, in my opinion

**Comment by tscrim** [comment]
Ah, I see. It is a bit annoying that it is somewhat limited as well. There are definitely times I wish I could just push a change rather than do the inline comments (and I _really_ do not want to fragment stuff with a separate PR). Well...it it what it is.

Thank you.

Squashing them might be complicated because of the different versions that this has been built with. It probably would be good, but I think something of squashing-all-commits-per-PR should be decided on sage-devel since it can have impacts on bisections and inspecting the change history. (Although this case might still benefit from it.) Anyways, perhaps for another time.

**Pull request merged**
