### PR TITLE
various changes about is_field and is_ring

### PR DESCRIPTION
**Pull request by fchapoton**
just miscellanous changes about not using `is_ring`, replacing some `is_field` by `in Fields`

and having more precise categories in descent algebras

also sorting the imports on the way

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
LGTM assuming tests pass.

**Comment by fchapoton** [comment]
not yet ready for consumption ; I need to add a default `is_field` returning False in the category of commutative rings.

**Comment by fchapoton** [comment]
I have decided just to fix the doctests here.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Pull request merged**
