### PR TITLE
Relativize more header imports

### PR DESCRIPTION
**Pull request by tobiasdiez**
Follow-up to https://github.com/sagemath/sage/pull/36598, relativizing the remaining header imports.

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Build fails. https://github.com/sagemath/sage/actions/runs/6966308614/job/18956298595?pr=36754#step:8:8127

**Comment by tobiasdiez** [comment]
Thanks, should be fixed now.

**Comment by mkoeppe** [comment]
LGTM and also applies cleanly to #35095, which has most of these changes.

The Lint failure is unrelated, fixed in #36822

**Review by mkoeppe — APPROVED** [review]

**Comment by kiwifb** [comment]
It is not working for me. I am not quite sure what it would need to work in fact
```
2023-12-11 19:43:28,114 root INFO x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -O2 -pipe -ggdb -UNDEBUG -fPIC -Isage/modular/arithgroup -I/usr/lib/python3.11/site-packages/cysignals -Isage/cpython -I/home/portage/sci-mathematics/sage-9999/work/sagemath-standard-9999 -I/usr/lib/python3.11/site-packages/numpy/core/include -I/usr/include/python3.11 -I/home/portage/sci-mathematics/sage-9999/work/sagemath-standard-9999-python3_11/build/cythonized -I/usr/include/python3.11 -c sage/modular/arithgroup/farey.cpp -o /home/portage/sci-mathematics/sage-9999/work/sagemath-standard-9999-python3_11/build/temp.linux-x86_64-cpython-311/sage/modular/arithgroup/farey.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1
sage/modular/arithgroup/farey.cpp:33:10: fatal error: farey_symbol.h: No such file or directory
   33 | #include "farey_symbol.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
A fundamental problem seems that the header was moved from the sdist source to the build directory instead of just copied
```
tarazed ~ # ls -la /home/portage/sci-mathematics/sage-9999/work/sagemath-standard-9999-python3_11/build/lib.linux-x86_64-cpython-311/sage/modular/arithgroup/
total 1536
drwxr-xr-x  2 portage portage   4096 Dec 11 19:43 .
drwxr-xr-x 15 portage portage   4096 Dec 11 19:43 ..
-rw-r--r--  1 portage portage    985 Dec 11 19:34 all.py
-rwxr-xr-x  1 portage portage 646032 Dec 11 19:43 arithgroup_element.cpython-311-x86_64-linux-gnu.so
-rw-r--r--  1 portage portage  13317 Dec 11 19:34 arithgroup_element.pyx
-rw-r--r--  1 portage portage  46601 Dec 11 19:34 arithgroup_generic.py
-rw-r--r--  1 portage portage  88288 Dec 11 19:34 arithgroup_perm.py
-rwxr-xr-x  1 portage portage 544352 Dec 11 19:43 congroup.cpython-311-x86_64-linux-gnu.so
-rw-r--r--  1 portage portage  11625 Dec 11 19:34 congroup.pyx
-rw-r--r--  1 portage portage  10426 Dec 11 19:34 congroup_gamma.py
-rw-r--r--  1 portage portage  20546 Dec 11 19:34 congroup_gamma0.py
-rw-r--r--  1 portage portage  22290 Dec 11 19:34 congroup_gamma1.py
-rw-r--r--  1 portage portage  47152 Dec 11 19:34 congroup_gammaH.py
-rw-r--r--  1 portage portage  21387 Dec 11 19:34 congroup_generic.py
-rw-r--r--  1 portage portage   7610 Dec 11 19:34 congroup_sl2z.py
-rw-r--r--  1 portage portage   2497 Dec 11 19:36 farey_symbol.h
-rw-r--r--  1 portage portage  35741 Dec 11 19:34 farey_symbol.pyx
-rw-r--r--  1 portage portage  13428 Dec 11 19:34 tests.py
tarazed ~ # ls -la /home/portage/sci-mathematics/sage-9999/work/sagemath-standard-9999/sage/modular/arithgroup/total 420
drwxr-xr-x  2 portage portage  4096 Dec 11 19:35 .
drwxr-xr-x 15 portage portage  4096 Dec 11 19:35 ..
-rw-r--r--  1 portage portage   985 Dec 11 19:34 all.py
-rw-r--r--  1 portage portage 13317 Dec 11 19:34 arithgroup_element.pyx
-rw-r--r--  1 portage portage 46601 Dec 11 19:34 arithgroup_generic.py
-rw-r--r--  1 portage portage 88288 Dec 11 19:34 arithgroup_perm.py
-rw-r--r--  1 portage portage 11625 Dec 11 19:34 congroup.pyx
-rw-r--r--  1 portage portage 10426 Dec 11 19:34 congroup_gamma.py
-rw-r--r--  1 portage portage 20546 Dec 11 19:34 congroup_gamma0.py
-rw-r--r--  1 portage portage 22290 Dec 11 19:34 congroup_gamma1.py
-rw-r--r--  1 portage portage 47152 Dec 11 19:34 congroup_gammaH.py
-rw-r--r--  1 portage portage 21387 Dec 11 19:34 congroup_generic.py
-rw-r--r--  1 portage portage  7610 Dec 11 19:34 congroup_sl2z.py
-rw-r--r--  1 portage portage 31782 Dec 11 19:35 farey.cpp
-rw-r--r--  1 portage portage  5090 Dec 11 19:34 farey.hpp
-rw-r--r--  1 portage portage 35741 Dec 11 19:34 farey_symbol.pyx
-rw-r--r--  1 portage portage   888 Dec 11 19:34 sl2z.cpp
-rw-r--r--  1 portage portage  5037 Dec 11 19:34 sl2z.hpp
-rw-r--r--  1 portage portage 13428 Dec 11 19:34 tests.py
```
I have no idea why.

**Comment by kiwifb** [comment]
I had not realised that header was generated. The path to it in the build directory would need a `-I...` as well for things to work.

**Comment by kiwifb** [comment]
The only way this work for you, is that you must be cythonising in the source tree instead of the build folder. Otherwise, `farey_symbol.h` cannot be in the same folder as `farey.cpp` for the relative inclusion to work.

**Comment by tornaria** [comment]
I have the same issue as @kiwifb with 10.3.beta2.

I also can't figure out where are the CI checks for this. 

This needs to be reverted!

**Comment by tornaria** [comment]
FWIW:
```
cc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -ffile-prefix-map=/builddir/sagemath-10.3.beta2/pkgs/sagemath-standard=. -fPIC -Isage/modular/arithgroup -I/usr/lib/python3.12/site-packages/cysignals -Isage/cpython -I/builddir/sagemath-10.3.beta2/pkgs/sagemath-standard -I/usr/lib/python3.12/site-packages/numpy/core/include -I/usr/include/python3.12 -Ibuild/cythonized -I/usr/include/python3.12 -c sage/modular/arithgroup/farey.cpp -o build/temp.linux-x86_64-cpython-312/sage/modular/arithgroup/farey.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1
sage/modular/arithgroup/farey.cpp:32:10: fatal error: farey_symbol.h: No such file or directory
   32 | #include "farey_symbol.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
The command line adds `-Ibuild/cythonized` so include paths should be relative to that. I.e. `sage/modular/arithgroup/farey_symbol.h` instead of `farey_symbol.h`.

But here we don't know why you are making this change, since here you invoke #36598 and there you claim you "don't know why". What is wrong with the full path?

**Comment by kiwifb** [comment]
Apparently it is related to the meson work. But the farey_symbol header is the only one for which things do not work in an out of source build. If meson can cope with this, it will have to wait for the switch in my opinion. In the meantime I am patching the latest beta.

**Comment by mkoeppe** [comment]
> I think "python -m build" didn't work last time I tried.

You will typically need `python -m build --no-isolation` because you want to bring your own dependencies instead of pulling from PyPI. (In particular, sage-conf -- as documented in https://github.com/sagemath/sage/tree/develop/pkgs/sage-conf#sage_conf-in-downstream-distributions.)

**Comment by mkoeppe** [comment]
> I don't see how the "meson work" is building sage: sage-the-distro should build sage-the-lib as packages (sagemath-standard, etc)

I agree, and that's the plan for meson sketched in
- #34630

**Comment by mkoeppe** [comment]
> I have the same issue as @kiwifb with 10.3.beta2.
> 
> I also can't figure out where are the CI checks for this.

We don't have a CI check for building a wheel of sagemath-standard currently.

We build wheels only of sagemath-objects and sagemath-categories (and some of the tiny optional distributions):
- https://github.com/sagemath/sage/blob/develop/.github/workflows/dist.yml#L157
- https://github.com/sagemath/sage/blob/develop/.github/workflows/build.yml#L101 (see https://github.com/sagemath/sage/blob/develop/build/make/Makefile.in#L131 for `PYPI_WHEEL_PACKAGES`).

These distributions are not big enough to catch the reported failure in `sage.modular`.

In #35095 (which currently still has ~50K lines of diff against develop), this is covered by the new distribution sagemath-schemes. Any help with upstreaming this work is very welcome.

**Comment by tornaria** [comment]
> > I have the same issue as @kiwifb with 10.3.beta2.
> > I also can't figure out where are the CI checks for this.
> 
> We don't have a CI check for building a wheel of sagemath-standard currently.

This wouldn't be a problem if sage-the-distro would eat its own dogfood. I mean, if sage-the-distro would install sage-the-lib in a standard pythonic way that can be used as an example by other distributions.

As a matter of fact, `build/pkgs/sagelib/spkg-install.in` doesn't look that crazy, except it's building from `src` instead of `pkgs/sagemath-standard` (what is the difference? Why do we have two different ways to build sagelib?)

However, `sdh_pip_install --no-build-isolation .` in `build/pkgs/sagelib/spkg-install.in`, is that `--no-build-isolation` what is making the build process not fail here?

**Comment by mkoeppe** [comment]
> This wouldn't be a problem if sage-the-distro would eat its own dogfood.

It does, just not by default (which is the editable build via `src/setup.py`).

pkgs/sagemath-standard is used if you do `./configure --disable-editable` and/or `./configure --enable-wheels`.

**Comment by mkoeppe** [comment]
> However, `sdh_pip_install --no-build-isolation .` in `build/pkgs/sagelib/spkg-install.in`, is that `--no-build-isolation` what is making the build process not fail here?

Yes, that's that's the same as what I wrote above in https://github.com/sagemath/sage/pull/36754#issuecomment-1856331341 regarding `pip -m build --no-isolation`.

I think in your downstream packaging context, you'll never want to do anything without `--no-build-isolation`/`--no-isolation`.

**Comment by mkoeppe** [comment]
That there are 2 separate build systems for the Sage library is transitional and will go away when the modularization work is merged.

**Comment by mkoeppe** [comment]
One of the next steps in this direction:
- #34209 

(help is welcome)

**Comment by antonio-rojas** [comment]
> > I think "python -m build" didn't work last time I tried.
> 
> You will typically need `python -m build --no-isolation` because you want to bring your own dependencies instead of pulling from PyPI. (In particular, sage-conf -- as documented in https://github.com/sagemath/sage/tree/develop/pkgs/sage-conf#sage_conf-in-downstream-distributions.)

`python -m build` works fine for me as long as I only build `sagemath-standard`. If I try to build some optional packages too, then install fails becuse of conflicting files
```
FileExistsError: File already exists: /build/sagemath/pkg/sagemath/usr/lib/python3.11/site-packages/sage/cython_debug/interpreter
```
This `interpreter` file is included by every optional sagemath-* wheel

**Comment by mkoeppe** [comment]
> This `interpreter` file is included by every optional sagemath-* wheel

Yes, that's #35725

**Comment by tobiasdiez** [comment]
> > Apparently it is related to the meson work. But the farey_symbol header is the only one for which things do not work in an out of source build. If meson can cope with this, it will have to wait for the switch in my opinion. In the meantime I am patching the latest beta.
> 
> The "meson work" should not break building sagemath-standard. Please.

I'm very sorry for the introduced bug. How do you run the compilation "out of the build" folder? Do you have any idea why only the farey symbol header makes problems but none of the other relative files?

> Since I'm already ranting, lets get all the steam out: sage_conf is worse than useless, when I tried "pip install sage_conf" it didn't work because of python 3.12, but also it downloaded the whole sage source code into DOT_SAGE, wtf? I already dislike pip because all the mess it does on my filesystem, but this feels bad even for pip.

You might be happy to hear that neither sage_conf nor sage_setup is needed with the meson compilation at #36524. In fact, it is completely independent of anything in "sage-the-distro". A simple `pip install` should just work if you have all required deps installed. In fact, the possibility that sagelib itself can check for the required libraries and configure itself during build time is one of the big advantages of meson. If you have the time, I would appreciate if you could give it a try (and any feedback towards what makes downstream packaging easier is welcome there as well, of course).

**Comment by kiwifb** [comment]
> > > Apparently it is related to the meson work. But the farey_symbol header is the only one for which things do not work in an out of source build. If meson can cope with this, it will have to wait for the switch in my opinion. In the meantime I am patching the latest beta.
> > 
> > 
> > The "meson work" should not break building sagemath-standard. Please.
> 
> I'm very sorry for the introduced bug. How do you run the compilation "out of the build" folder? Do you have any idea why only the farey symbol header makes problems but none of the other relative files?

That would be because it is the only header that is produced from a cython file. All the other files are present in the source tree. But `farey_symbol.h` as the product of a cythonisation is put in the build tree rather than the source tree.

**Comment by tobiasdiez** [comment]
Thanks, makes sense. I was able to find a workaround for the meson compilation. Sorry for the inconvenience

**Pull request merged**
