### PR TITLE
CI: Handle the "p: CI Fix" label

### PR DESCRIPTION
**Pull request by mkoeppe**
As decided by vote in https://groups.google.com/g/sage-devel/c/OKwwUGyKveo/m/vpyCXYBqAAAJ (2024-03).

The only change here is to change the search from open PRs with "p: blocker / 1" labels to those with "p: CI Fix" labels.

No attempt is made to take any status labels into account. All open PRs with the "p: CI Fix" label are processed. 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by fchapoton** [comment]
Should we also check that the status is "positive review" ?

**Comment by mkoeppe** [comment]
No, that's not really practical. For example in making #37926, I really wanted to test it on the broken workflow runs for the latest beta.

**Comment by fchapoton** [comment]
I understand and mostly agree, but this is what has been voted.

**Comment by mkoeppe** [comment]
No, what has been voted on is that 'Only PRs with positive review should be marked with the "CI Fix" label.'

**Review by fchapoton — APPROVED** [review]
ok, then

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
