### PR TITLE
`sage.plot.animate`: Use FFmpeg.absolute_filename; `sage.features`: Remove deprecated methods

### LINKED ISSUE #35255: `sage.plot.animate`: Use `Executable.absolute_filename`, pass configured FFMPEG via sage-conf
Part of:
- #30818

----
Original issue description:

I have compiled sage with a local version of ffmpeg successfully by issuing these commands before running configure

```
export PATH="$HOME/opt/ffmpeg6/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/opt/ffmpeg6/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$HOME/opt/ffmpeg6/lib/pkgconfig:$PKG_CONFIG_PATH"

```
 Now I would like to make sure that sage respects these environmental variables at run time. Should I put them in .sage/sagerc?
 
 Running sage --sh, I found these two environmental variables 
```
SAGE_ORIG_PATH

SAGE_ORIG_PATH_SET
```
I am trying to find some documentation on these but can't find any. Can someone explain to me what these are?

OS is Ubuntu 22.04, sage 9.8

### PR DESCRIPTION
**Pull request by mkoeppe**
- Fixes #35255

Removes methods deprecated in:
- #31292 (2022)
- #33114 (2022)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
We may use this PR to also remove the deprecated feature:
```
sage: ff.absolute_path()
<ipython-input-6-0917e843ae08>:1: DeprecationWarning: method absolute_path has been replaced by absolute_filename
See https://github.com/sagemath/sage/issues/31292 for details.
```
Yes or no?

**Comment by mkoeppe** [comment]
Good idea, done (also for another deprecated method)

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
