### PR TITLE
CI Linux: Fix `centos-7` after #36435, remove `gentoo-python3.12` for now, use `conda-forge` with `-python3.11`

### PR DESCRIPTION
**Pull request by mkoeppe**
As part of the changes in #36435, we switched from http to https for downloading mirror_list.
This broke centos-7; here we fix it.

gentoo-python3.12 was activated a little bit too early. We remove it to clean up the portability CI workflow.

conda-forge defaults to 3.12 already, and we're not ready for it.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
`tox -e docker-centos-7-standard` doesn't work on mac:
```
...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
...
```
I am running Docker Desktop. Is `tox.ini` supposed to run on linux only?

**Comment by mkoeppe** [comment]
No, I use it on macOS. Check using `which docker` where your Docker client is coming from

**Comment by kwankyu** [comment]
Thanks. Solved by checking `Allow the default Docker socket to be used (requires password)` in Settings.

**Comment by kwankyu** [comment]
Now stuck at
```
SAGE_PKGCONFIG=/sage/local/lib/pkgconfig
SAGE_ROOT=/sage
SAGE_SHARE=/sage/local/share
SAGE_SILENT_BUILD=yes
SAGE_SRC=/sage/src
SHLVL=4
USE_MAKEFLAGS=-k V=0
V=0
_=/usr/bin/env
***********************************************
make[1]: Entering directory `/sage/build/make'
touch /sage/local/var/lib/sage/installed/.dummy
make --no-print-directory toolchain
make --no-print-directory gmp-SAGE_LOCAL-no-deps
make --no-print-directory zlib-SAGE_LOCAL-no-deps
[zlib-1.2.11.p0] installing. Log file: /sage/logs/pkgs/zlib-1.2.11.p0.log
[gmp-6.2.1] installing. Log file: /sage/logs/pkgs/gmp-6.2.1.log
  [zlib-1.2.11.p0] successfully installed.
  [gmp-6.2.1] successfully installed.
make --no-print-directory mpfr-SAGE_LOCAL-no-deps
[mpfr-4.0.1.p0] installing. Log file: /sage/logs/pkgs/mpfr-4.0.1.p0.log
  [mpfr-4.0.1.p0] successfully installed.
make --no-print-directory mpc-SAGE_LOCAL-no-deps
[mpc-1.1.0] installing. Log file: /sage/logs/pkgs/mpc-1.1.0.log
  [mpc-1.1.0] successfully installed.
make --no-print-directory gcc-SAGE_LOCAL-no-deps
[gcc-12.2.0] installing. Log file: /sage/logs/pkgs/gcc-12.2.0.log
(pending forever...)
```

**Comment by kwankyu** [comment]
But that is an issue just with me. Seems not related with what's done here.

**Review by kwankyu — APPROVED** [review]
OK.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
