### PR TITLE
improve checks

### LINKED ISSUE #36253: Safeguards when computing with LazyPowerSeries
### Problem Description

```
sage: L.<z> = LazyPowerSeriesRing(ZZ)
sage: f = L(lambda n: 1 if n else 0)
sage: ~f
1 - z + O(z^7)
```
Thus, a fake inverse of the (non-invertible) power series `z` is returned.

### Proposed Solution

Although this is the expected behaviour - we cannot evaluate terms to check invertibility without jeopardizing our ability to implicitly define lazy power series - we might be able to do much better, and raise an error in many situations.

There are two things we can do:

1. check invertibility for 'initialized'  series.
2. add a per-stream attribute `_allow_evaluation` and check that.

### Alternatives Considered

Live with the current situation.

### Additional Information

_No response_

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### PR DESCRIPTION
**Pull request by mantepse**
We attempt to deduce automatically, when we can check coefficients without breaking implicit definitions and with as little user intervention as possible.

Fixes #36253.

### CODE REVIEW

**Comment by mantepse** [comment]
I believe that we will need an option to bypass the check in `__invert__`, but I could not come up with an example yet.  We can create an uninitialized series `s` with `s._coeff_stream.is_uninitialized()` giving `False` using, for example, using
```
sage: t = L.undefined(0)
sage: s = L.sum(lambda n: t^n, 1)
```
Now I'd like to see an example where `s[0]` must not be evaluated before creating the inverse.

**Review by tscrim — APPROVED** [review]
LGTM. I think until we have an example, I think we are okay assuming the code has been implemented robustly enough. At least, it won't give wrong answers, just raise an error.

**Comment by mantepse** [comment]
@tscrim, I reverted to the old behaviour and left a comment instead.  It should be ready now.  The commit history is a bit strange, because I thought that, for example, 4d5f7bf0c7344caaa8fcf939e993d1c7925e8fbf, is already merged into develop.

**Comment by tscrim** [comment]
Okay, then let it be so.

**Pull request merged**
