### PR TITLE
Replace relative imports by absolute ones in a few packages

### PR DESCRIPTION
**Pull request by tobiasdiez**
As preparation for compiling with meson, we replace relative imports by absolute ones.
Moreover, relative imports are not used consistently in the codebase and result in issues for doctesting with pytest (which admittedly is a limitation of pytest). We normalize the relative imports in a few smaller packages to be absolute imports. Small code-style improvements along the way (mainly to nicely order the imports)

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Same comments as https://github.com/sagemath/sage/pull/36588#issuecomment-1792842988

**Comment by mkoeppe** [comment]
Rebased cleanly -- without need for manual intervention -- on top of https://github.com/sagemath/sage/pull/36666.

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by tobiasdiez** [comment]
Thanks!

**Pull request merged**
