### PR TITLE
Fixes #35804 by computing the DDT of non-square sboxes properly.

### LINKED ISSUE #35804: sage.crypto.sbox: difference_distribution_table
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Not OS related
- **Sage Version**: 10.0
```

### Steps To Reproduce

from sage.crypto.sbox import SBox
S = SBox(0,0,0,1,0,0,1,3)
S.difference_distribution_table()

### Expected Behavior

The correct distribution table.

### Actual Behavior

IndexError                                Traceback (most recent call last)
Cell In [23], line 3
      1 from sage.crypto.sbox import SBox
      2 S = SBox(Integer(0),Integer(0),Integer(0),Integer(1),Integer(0),Integer(0),Integer(1),Integer(3))
----> 3 S.difference_distribution_table()

File /private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/misc/cachefunc.pyx:2300, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:12752)()
   2298 if self.cache is None:
   2299     f = self.f
-> 2300     self.cache = f(self._instance)
   2301 return self.cache
   2302 

File /private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/crypto/sbox.pyx:652, in sage.crypto.sbox.SBox.difference_distribution_table (build/cythonized/sage/crypto/sbox.c:8561)()
    650     si = self._S_list[i]
    651     for di in range(nrows):
--> 652         L[di*nrows + si ^ self._S_list[i ^ di]] += 1
    653 
    654 A = matrix(ZZ, nrows, ncols, L)

IndexError: list index out of range

### Additional Information

It works with a square SBox, but fails with non-square one. I presume the "range(nrows)" in line 651 should be "range(ncols)".

### PR DESCRIPTION
**Pull request by PTK12**
Fixes #35804.

After some investigation, it was found that many non-square sboxes did not work.
In cases where the output size is bigger than the input size (e.g. `SBox(16,16,16,16,16,16,16,16)`), an incorrect DDT is produced.
In cases where where input size is bigger, it leads to an IndexError such as in #35804. 

`di` spans from [0, `nrows`)
When multiplied by `nrows`, a size of `nrows * (nrows - 1)` can be achieved which can be greater than the maximum size of the table when `nrows > ncols` (leading to the behaviour seen earlier).

Changing the multiplication of nrows to ncols fixes the IndexError as well as produce the correct SBox for `SBox(16,16,16,16,16,16,16,16)`.

Tested with doctests along with the following script: 
```sage
import random
from sage.crypto.sbox import SBox

random.seed(b"sbox")

test = lambda x: print(SBox(x).difference_distribution_table())

# Square sbox
test([7,6,0,4,2,5,1,3])
for _ in range(10):
	sbox = random.sample(range(16), 16)
	print(sbox)
	test(sbox)

# Non-square sboxes
for _ in range(10): # input > output
	sbox = random.sample(list(range(4)) * 4, 16)
	print(sbox)
	test(sbox)

for _ in range(10): # input < output
	sbox = random.sample(range(16), 4)
	print(sbox)
	test(sbox)

print("Passed all cases!")
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
@roed314, workflows need approval.

**Comment by PotatoK123** [comment]
@roed314 Sorry for disturbing you but can I get an update on this PR and any changes it would need? Thanks.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by PotatoK123** [comment]
Thanks! 👍

**Review by soehms — APPROVED** [review]

**Pull request merged**
