### PR TITLE
sage.{coding,groups}: Replace imports from sage.*.all for namespace packages

### LINKED ISSUE #34948: sage.{coding,groups}: Replace imports from sage.*.all for namespace packages
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @dimpase @fchapoton

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34948_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description
Fixes #34948 

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
assuming the CI passes, should be good.

**Review by dimpase — APPROVED** [review]
lgtm

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
