### PR TITLE
src/tox.ini (rst): Add missing Sphinx roles

### LINKED ISSUE #37711: RST liner is failing due to RST304 failure
### Steps To Reproduce

```
Jack: sage % ./sage --version                                                           
SageMath version 10.4.beta1, Release Date: 2024-03-31
Jack: sage % ./sage -tox -e rst -- ./src/sage                          
rst: commands[0] /Users/Jack/sage/sage/src> flake8 --select=RST sage
sage/algebras/quantum_groups/quantum_group_gap.py:8:1: RST304 Unknown interpreted text role "gap_package".
sage/combinat/designs/incidence_structures.py:1812:1: RST304 Unknown interpreted text role "gap_package".
sage/groups/cubic_braid.py:272:1: RST304 Unknown interpreted text role "gap".
sage/groups/generic.py:1626:1: RST304 Unknown interpreted text role "gap".
sage/groups/matrix_gps/finitely_generated_gap.py:225:1: RST304 Unknown interpreted text role "gap".
rst: exit 1 (54.79 seconds) /Users/Jack/sage/sage/src> flake8 --select=RST sage pid=9808
  rst: FAIL code 1 (54.86=setup[0.07]+cmd[54.79] seconds)
  evaluation failed :( (55.02 seconds)
```

### Expected Behavior

All listing should pass on the develop branch

### Actual Behavior

Linting has failures on the develop branch

### Additional Information

_No response_

### Environment

```markdown
- **OS**: MacOS 14.3.1
- **Sage Version**: 10.4.beta1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #37711 

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GiacomoPope** [comment]
Looks good to me -- just have to wait for the CI. Thanks for adding the extra comment

**Review by fchapoton — APPROVED** [review]
good, thanks

**Comment by fchapoton** [comment]
this triggers another linter warning...

**Comment by fchapoton** [comment]
I have fixed the new linter warning and set to positive. I do not know if this still needs approval by someone else.

**Comment by mkoeppe** [comment]
Thanks for the fix, LGTM.

**Pull request merged**
