### PR TITLE
Fix ruff issues in `manifolds`

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fix import formatting / ordering in manifolds.

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
Why changing ``` ' ``` to ``` " ``` is an improvement? Personally I prefer ``` ' ``` to ``` " ``` for all strings except plain (English) sentences.

**Comment by tobiasdiez** [comment]
> Why changing `'` to `"` is an improvement? Personally I prefer `'` to `"` for all strings except plain (English) sentences.

I don't have an opinion on what style should be preferred, but it should be used consistently. It looked like that `"` was used most often already in the code, so I went with it. It's also happens to be the default in ruff.

**Comment by tobiasdiez** [comment]
> This is too much to review. The changes about string delimiter would better go in their own dedicated PR.

Okay, have reduced it now to step 1: only reorder imports (and always specify the full import for consistency)

**Review by fchapoton — APPROVED** [review]
ok, but what a boring thing to do.

**Pull request merged**
