### PR TITLE
tentative of free-Algebra functor

### PR DESCRIPTION
**Pull request by fchapoton**
This is trying to create a functor for free Associative unital algebras.

Using as a model the case of free Pre-Lie algebras.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by fchapoton** [comment]
So far, the merge is not working as expected for the coercion

**Comment by fchapoton** [comment]
probably one needs to fix that also :
```
sage: A = algebras.Free(QQ,['x','y'])
sage: B = algebras.Free(QQ,['y'])
sage: A.has_coerce_map_from(B)
False
```

**Comment by tscrim** [comment]
The problem is the `FreeAlgebra` does not like the `Alphabet` input:
```
sage: FreeAlgebra(QQ, ['x','y'], None)
Free Algebra on 2 generators (x, y) over Rational Field
sage: FreeAlgebra(QQ, Alphabet(['x','y']), None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
ValueError: variable name "{'x'" is not alphanumeric
```
So changing
```
-            return AssociativeFunctor(Alphabet(ret))
+            return AssociativeFunctor(tuple(ret))
```
fixes the problem for me.

**Comment by fchapoton** [comment]
oh, damn.. Great ! Thanks a lot. I still have to care a little more for the degrees.

**Comment by tscrim** [comment]
We probably should let the free algebra constructor take an alphabet (or anything list like) with special processing for strings. Well, that is older code IIRC, and might be in need of an overhual...:/

**Review by tscrim — APPROVED** [review]
LGTM.

**Pull request merged**
