### PR TITLE
Remove tag fetching in docker workflow

### PR DESCRIPTION
**Pull request by tobiasdiez**
### :books: Description

It fails in forks (e.g. https://github.com/tobiasdiez/sage/actions/runs/4586854543/jobs/8100123316) and shouldn't be necessary since the tag will be passed anyway via `EXTRA_DOCKER_TAGS`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
Indeed, as @dimpase confirms in https://github.com/sagemath/sage/pull/35571#issuecomment-1523733959

The "fetch tags" does still have a function, namely to make "git describe" more expressive. But let's get rid of this step at least for now. Thanks

**Comment by tobiasdiez** [comment]
Thanks for the review.

The workflow is still broken btw in forks. The docker upload/download doesn't work, so the next level breaks, e.g. https://github.com/tobiasdiez/sage/actions/runs/4586981626/jobs/8106335802

**Comment by mkoeppe** [comment]
For that failure, see the corresponding `minimal-pre` workflow (the 1st stage): https://github.com/tobiasdiez/sage/actions/runs/4586981626/jobs/8103083560#step:10:1671
```
Successfully tagged ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured:aebd2ff067
Successfully tagged ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured:python38
Pushing ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured:aebd2ff067 ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured:python38
The push refers to repository [ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured]
eeb2fe087397: Preparing
238[1673](https://github.com/tobiasdiez/sage/actions/runs/4586981626/jobs/8103083560#step:10:1674)5ef25: Preparing
5f3a7dba7309: Preparing
[...]
30d3c4334a23: Waiting
f2fa9f4cf8fd: Waiting
denied: installation not allowed to Create organization package
(ignoring errors)
The push refers to repository [ghcr.io/tobiasdiez/sage/sage-ubuntu-trusty-toolchain-gcc_9-minimal-configured]
```

**Comment by mkoeppe** [comment]
We discussed this in https://github.com/sagemath/sage/pull/35108#discussion_r1103994185, I'll have to get back to it

**Pull request merged**
