### PR TITLE
Python 3.12.x

### PR DESCRIPTION
**Pull request by mkoeppe**
Continuation of:
- #34788

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36176
- Depends on #36112
- Depends on #36123
- Depends on #36129
- Depends on #36477 
- Depends on #36444
- Depends on #36561
- Depends on #36869
- Depends on #36351
  - which depends on #36775
- Depends on #36945 (absorbed in #36351)
- Depends on #36868 (absorbed here)
- Depends on #37270 (split out from here)
- Depends on #36983
- Depends on #37834 (split out from here, to be merged)
- Depends on #37833 (split out from here)

Related / follow-ups:
- #37402
- https://github.com/yaml/pyyaml/pull/808
- #31295
- #35593

### CODE REVIEW

**Comment by tornaria** [comment]
See: https://github.com/sagemath/cypari2/pull/138 and https://github.com/fplll/fpylll/pull/254.

**Comment by tornaria** [comment]
See also WIP: https://github.com/sagemath/sage/compare/develop...tornaria:sage:py312

With that branch I'm down to ~ 20 test failures (needs to patch fpylll and cypari2 as in the PRs in my comment above)

**Comment by tornaria** [comment]
I'm down to 2 doctest failures (only tested x86_64 for now) and I will do a proper "support python 3.12" PR soon.

Meanwhile, I've split a trivial (but long) part of the necessary changes into #36403, which should be trivial to review.

**Comment by tornaria** [comment]
The branch https://github.com/sagemath/sage/compare/develop...tornaria:sage:py312 seems to be working for me. I'll do some testing overnight, then make a PR tomorrow.

**Comment by mkoeppe** [comment]
From the logs of "CI Linux incremental":

`ubuntu-focal` (https://github.com/sagemath/sage/actions/runs/7199146140/job/19610251776?pr=36181#step:11:1885):
```
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     In file included from src/gmpy2.c:534:
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     src/gmpy2.h:96:4: error: #error "GMPY2 requires MPFR 4.1.0 or later."
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]        96 | #  error "GMPY2 requires MPFR 4.1.0 or later."
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]           |    ^~~~~
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     src/gmpy2.h:104:4: error: #error "GMPY2 requires MPC 1.2.1 or later."
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]       104 | #  error "GMPY2 requires MPC 1.2.1 or later."
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]           |    ^~~~~
  [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by dimpase** [comment]
On Wed, Dec 13, 2023 at 12:32:25PM -0800, Matthias Köppe wrote:
> >From the logs of "CI Linux incremental":
> 
> ```
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]        96 | #  error "GMPY2 requires MPFR 4.1.0 or later."
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]       104 | #  error "GMPY2 requires MPC 1.2.1 or later."
> ```

high time to bump our mpc, mpfr to the latest versions (1.3.1 and
4.2.1).

And bump the versions in spkg-configures to match what's needed by gmpy2
Mpfr does come with pkg-config set up, but mpc not, so that's a bit of
extra work there to figure out how to test mpc.

**Comment by mkoeppe** [comment]
You do realize that I already have done what you describe?

**Comment by tornaria** [comment]
> From the logs of "CI Linux incremental":
> 
> `ubuntu-focal` (https://github.com/sagemath/sage/actions/runs/7199146140/job/19610251776?pr=36181#step:11:1885):
> 
> ```
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     In file included from src/gmpy2.c:534:
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     src/gmpy2.h:96:4: error: #error "GMPY2 requires MPFR 4.1.0 or later."
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]        96 | #  error "GMPY2 requires MPFR 4.1.0 or later."
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]           |    ^~~~~
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     src/gmpy2.h:104:4: error: #error "GMPY2 requires MPC 1.2.1 or later."
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]       104 | #  error "GMPY2 requires MPC 1.2.1 or later."
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]           |    ^~~~~
>   [gmpy2-5ac3746047491cd5508c0705613f75a1636be6a6]     error: command '/usr/bin/gcc' failed with exit code 1
> ```

Both are 3+ years old...

**Comment by mkoeppe** [comment]
See PRs linked in the ticket description.
- #36775 - ready for review

**Comment by mkoeppe** [comment]
32-bit failure (debian-bullseye-i386-standard, https://github.com/sagemath/sage/actions/runs/7213663213/job/19654897670?pr=36181#step:11:10890): 
```
File "src/sage/schemes/elliptic_curves/ell_field.py", line 1029, in sage.schemes.elliptic_curves.ell_field.EllipticCurve_field.division_field
Failed example:
    K = E.division_field(l)
Exception raised:
    Traceback (most recent call last):
      File "sage/rings/finite_rings/integer_mod.pyx", line 382, in sage.rings.finite_rings.integer_mod.IntegerMod_abstract.__init__
        z = integer_ring.Z(value)
      File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        raise
      File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "sage/rings/integer.pyx", line 712, in sage.rings.integer.Integer.__init__
        raise TypeError("unable to coerce %s to an integer" % type(x))
    TypeError: unable to coerce <class 'sage.categories.morphism.IdentityMorphism'> to an integer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/sage/src/sage/structure/sequence.py", line 450, in __init__
        x[i] = universe(x[i])
      File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        raise
      File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "/sage/src/sage/rings/finite_rings/integer_mod_ring.py", line 1175, in _element_constructor_
        return integer_mod.IntegerMod(self, x)
      File "sage/rings/finite_rings/integer_mod.pyx", line 203, in sage.rings.finite_rings.integer_mod.IntegerMod
        return t(parent, value)
      File "sage/rings/finite_rings/integer_mod.pyx", line 390, in sage.rings.finite_rings.integer_mod.IntegerMod_abstract.__init__
        value = sage.rings.rational_field.QQ(value)
      File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        raise
      File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "sage/rings/rational.pyx", line 536, in sage.rings.rational.Rational.__init__
        self.__set_value(x, base)
      File "sage/rings/rational.pyx", line 681, in sage.rings.rational.Rational._Rational__set_value
        raise TypeError("unable to convert {!r} to a rational".format(x))
    TypeError: unable to convert Identity endomorphism of Finite Field of size 996385483 to a rational

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/sage/src/sage/doctest/forker.py", line 709, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_field.EllipticCurve_field.division_field[54]>", line 1, in <module>
        K = E.division_field(l)
      File "/sage/src/sage/schemes/elliptic_curves/ell_field.py", line 1108, in division_field
        h = self.defining_polynomial().change_ring(F_to_K)(x, polygen(K), 1)
      File "sage/rings/polynomial/multi_polynomial.pyx", line 883, in sage.rings.polynomial.multi_polynomial.MPolynomial.change_ring
        R = self.parent().hom(R, self.parent().change_ring(R.codomain()))
      File "sage/structure/parent_gens.pyx", line 304, in sage.structure.parent_gens.ParentWithGens.hom
        return parent.Parent.hom(self, im_gens, codomain, base_map=base_map, category=category, check=check)
      File "sage/structure/parent.pyx", line 1439, in sage.structure.parent.Parent.hom
        return self.Hom(codomain, **Hom_kwds)(im_gens, **kwds)
      File "sage/structure/parent.pyx", line 903, in sage.structure.parent.Parent.__call__
        return mor._call_with_args(x, args, kwds)
      File "sage/structure/coerce_maps.pyx", line 182, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_with_args
        raise
      File "sage/structure/coerce_maps.pyx", line 172, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_with_args
        return C._element_constructor(x, **kwds)
      File "/sage/src/sage/rings/homset.py", line 195, in _element_constructor_
        x = self.domain().base().Hom(self.codomain().base())(x)
      File "/sage/src/sage/rings/finite_rings/homset.py", line 99, in __call__
        return FiniteFieldHomomorphism_prime(self, im_gens, base_map=base_map, check=check)
      File "sage/rings/finite_rings/hom_prime_finite_field.pyx", line 75, in sage.rings.finite_rings.hom_prime_finite_field.FiniteFieldHomomorphism_prime.__init__
        FiniteFieldHomomorphism_generic.__init__(self, parent, im_gens, base_map=base_map,
      File "sage/rings/finite_rings/hom_finite_field.pyx", line 240, in sage.rings.finite_rings.hom_finite_field.FiniteFieldHomomorphism_generic.__init__
        RingHomomorphism_im_gens.__init__(self, parent, im_gens, base_map=base_map, check=check)
      File "sage/rings/morphism.pyx", line 1730, in sage.rings.morphism.RingHomomorphism_im_gens.__init__
        im_gens = sage.structure.all.Sequence(im_gens, parent.codomain(),
      File "/sage/src/sage/structure/sequence.py", line 266, in Sequence
        return Sequence_generic(x, universe, check, immutable, cr, cr_str, use_sage_types)
      File "/sage/src/sage/structure/sequence.py", line 452, in __init__
        raise TypeError("unable to convert {} to an element of {}"
    TypeError: unable to convert Identity endomorphism of Finite Field of size 996385483 to an element of Finite Field of size 996385483
```

**Comment by tornaria** [comment]
> 32-bit failure (debian-bullseye-i386-standard, https://github.com/sagemath/sage/actions/runs/7213663213/job/19654897670?pr=36181#step:11:10890):
> 
> ```
> sage -t --random-seed=262395800206192724689450619630879642173 src/sage/schemes/elliptic_curves/ell_field.py
> **********************************************************************
> File "src/sage/schemes/elliptic_curves/ell_field.py", line 1029, in sage.schemes.elliptic_curves.ell_field.EllipticCurve_field.division_field
> Failed example:
>     K = E.division_field(l)
> Exception raised:
>     Traceback (most recent call last):
>       File "sage/rings/finite_rings/integer_mod.pyx", line 382, in sage.rings.finite_rings.integer_mod.IntegerMod_abstract.__init__
>         z = integer_ring.Z(value)
>       File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
>         return mor._call_(x)
>       File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         raise
>       File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         return C._element_constructor(x)
>       File "sage/rings/integer.pyx", line 712, in sage.rings.integer.Integer.__init__
>         raise TypeError("unable to coerce %s to an integer" % type(x))
>     TypeError: unable to coerce <class 'sage.categories.morphism.IdentityMorphism'> to an integer
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "/sage/src/sage/structure/sequence.py", line 450, in __init__
>         x[i] = universe(x[i])
>       File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
>         return mor._call_(x)
>       File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         raise
>       File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         return C._element_constructor(x)
>       File "/sage/src/sage/rings/finite_rings/integer_mod_ring.py", line 1175, in _element_constructor_
>         return integer_mod.IntegerMod(self, x)
>       File "sage/rings/finite_rings/integer_mod.pyx", line 203, in sage.rings.finite_rings.integer_mod.IntegerMod
>         return t(parent, value)
>       File "sage/rings/finite_rings/integer_mod.pyx", line 390, in sage.rings.finite_rings.integer_mod.IntegerMod_abstract.__init__
>         value = sage.rings.rational_field.QQ(value)
>       File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
>         return mor._call_(x)
>       File "sage/structure/coerce_maps.pyx", line 163, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         raise
>       File "sage/structure/coerce_maps.pyx", line 158, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
>         return C._element_constructor(x)
>       File "sage/rings/rational.pyx", line 536, in sage.rings.rational.Rational.__init__
>         self.__set_value(x, base)
>       File "sage/rings/rational.pyx", line 681, in sage.rings.rational.Rational._Rational__set_value
>         raise TypeError("unable to convert {!r} to a rational".format(x))
>     TypeError: unable to convert Identity endomorphism of Finite Field of size 996385483 to a rational
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "/sage/src/sage/doctest/forker.py", line 709, in _run
>         self.compile_and_execute(example, compiler, test.globs)
>       File "/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
>         exec(compiled, globs)
>       File "<doctest sage.schemes.elliptic_curves.ell_field.EllipticCurve_field.division_field[54]>", line 1, in <module>
>         K = E.division_field(l)
>       File "/sage/src/sage/schemes/elliptic_curves/ell_field.py", line 1108, in division_field
>         h = self.defining_polynomial().change_ring(F_to_K)(x, polygen(K), 1)
>       File "sage/rings/polynomial/multi_polynomial.pyx", line 883, in sage.rings.polynomial.multi_polynomial.MPolynomial.change_ring
>         R = self.parent().hom(R, self.parent().change_ring(R.codomain()))
>       File "sage/structure/parent_gens.pyx", line 304, in sage.structure.parent_gens.ParentWithGens.hom
>         return parent.Parent.hom(self, im_gens, codomain, base_map=base_map, category=category, check=check)
>       File "sage/structure/parent.pyx", line 1439, in sage.structure.parent.Parent.hom
>         return self.Hom(codomain, **Hom_kwds)(im_gens, **kwds)
>       File "sage/structure/parent.pyx", line 903, in sage.structure.parent.Parent.__call__
>         return mor._call_with_args(x, args, kwds)
>       File "sage/structure/coerce_maps.pyx", line 182, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_with_args
>         raise
>       File "sage/structure/coerce_maps.pyx", line 172, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_with_args
>         return C._element_constructor(x, **kwds)
>       File "/sage/src/sage/rings/homset.py", line 195, in _element_constructor_
>         x = self.domain().base().Hom(self.codomain().base())(x)
>       File "/sage/src/sage/rings/finite_rings/homset.py", line 99, in __call__
>         return FiniteFieldHomomorphism_prime(self, im_gens, base_map=base_map, check=check)
>       File "sage/rings/finite_rings/hom_prime_finite_field.pyx", line 75, in sage.rings.finite_rings.hom_prime_finite_field.FiniteFieldHomomorphism_prime.__init__
>         FiniteFieldHomomorphism_generic.__init__(self, parent, im_gens, base_map=base_map,
>       File "sage/rings/finite_rings/hom_finite_field.pyx", line 240, in sage.rings.finite_rings.hom_finite_field.FiniteFieldHomomorphism_generic.__init__
>         RingHomomorphism_im_gens.__init__(self, parent, im_gens, base_map=base_map, check=check)
>       File "sage/rings/morphism.pyx", line 1730, in sage.rings.morphism.RingHomomorphism_im_gens.__init__
>         im_gens = sage.structure.all.Sequence(im_gens, parent.codomain(),
>       File "/sage/src/sage/structure/sequence.py", line 266, in Sequence
>         return Sequence_generic(x, universe, check, immutable, cr, cr_str, use_sage_types)
>       File "/sage/src/sage/structure/sequence.py", line 452, in __init__
>         raise TypeError("unable to convert {} to an element of {}"
>     TypeError: unable to convert Identity endomorphism of Finite Field of size 996385483 to an element of Finite Field of size 996385483
> ```

FWIW, we do check 32 bit systematically on void Linux and I don't remember seeing this. In fact I have a draft PR building 10.3.beta2 with all tests passing: https://github.com/void-linux/void-packages/pull/47712

**Comment by mkoeppe** [comment]
Thanks. Turns out this is the same as: 
- #36832

**Comment by tornaria** [comment]
This is kind of urgent:
```
$ python -m venv SAGE
$ SAGE/bin/pip install sagemath-standard
Collecting sagemath-standard
  Downloading sagemath-standard-9.3rc0.tar.gz (17.7 MB)
...
```
Let's try something newer:
```
$ SAGE/bin/pip install sagemath-standard==10.3b7
...
ERROR: Could not find a version that satisfies the requirement sagemath-standard==10.3b7 (from versions: 9.3b8, 9.3b9, 9.3rc0)
ERROR: No matching distribution found for sagemath-standard==10.3b7
```


OTOH,
```
$ SAGE/bin/pip install sage_conf
Collecting sage_conf
  Downloading sage-conf-10.2.tar.gz (3.0 MB)
...
      -----------------------------------------------------------------------------
      Checking whether SageMath should install SPKG python3...
      checking whether any of bzip2 liblzma libffi zlib is installed as or will be installed as SPKG... no
      checking for python3 >= 3.9.0, < 3.12.0 with modules sqlite3, ctypes, math, hashlib, crypt, socket, zlib, distutils.core, ssl, ensurepip...
      checking for /home/tornaria/SAGE/bin/python... /home/tornaria/SAGE/bin/python
      checking ... whether /home/tornaria/SAGE/bin/python is good... no, Python 3.12.1 is too recent
      configure: error: the python3 selected using --with-python=/home/tornaria/SAGE/bin/python is not suitable
      configure failed; this may be caused by missing build prerequisites.
      You can install the required build prerequisites using the following shell command
      
      sudo xbps-install  bc binutils gcc libgomp-devel m4 make perl python3 tar which bzip2-devel xz libffi-devel
      
      error: configure failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sage_conf
Failed to build sage_conf
ERROR: Could not build wheels for sage_conf, which is required to install pyproject.toml-based projects
```

And `SAGE/bin/pip install sage_conf==10.3.b7` gives the exact same error.

**Comment by mkoeppe** [comment]
Yes

**Comment by tornaria** [comment]
> Yes

FWIW, I've just checked out this PR at 29130ea and run:
```sh
./bootstrap
./configure --disable-doc
MAKE='make -j36' make
./sage -tp 36 --all
./sage -tp 36 --all --long
```
Obtaining:
```
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 222.0 seconds
    cpu time: 6336.1 seconds
    cumulative wall time: 5912.1 seconds
```
and
```
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 383.8 seconds
    cpu time: 11427.0 seconds
    cumulative wall time: 11154.8 seconds
```

**Comment by tornaria** [comment]
OTOH, using `--enable-system-site-packages` is broken:
 - first, the version of `sage_conf` inside the venv is installed in such a crooked way that *it will not override* the one installed in the system site-packages, in spite the sage venv site-packages being listed before the system site-packages in `sys.path`.
 - the version of `sage_conf.py` I have in my system doesn't define `GAP_ROOT_PATHS` (not a thing in 10.2). This results in an incredibly scary-looking error (to simulate try `GAP_ROOT_PATHS=/ sage -c 'gap(1)'` or worse `GAP_ROOT_PATHS=/ sage -c 'libgap(1)'`).
 - I don't know how to fix the search order for `sage_conf` so I just added `GAP_ROOT_PATHS` to the system `sage_conf` (I can't remove it since I don't want to break sage for other users)
 - With that fixed, almost all tests pass except some in `src/sage_docbuild` and the top comment in `src/sage/env.py`

**Comment by mkoeppe** [comment]
> using `--enable-system-site-packages` is broken:
> 
> * first, the version of `sage_conf` inside the venv is installed in such a crooked way that _it will not override_ the one installed in the system site-packages, in spite the sage venv site-packages being listed before the system site-packages in `sys.path`.

Could it be that your `sage-conf/_sage_conf` in your system site-packages has an `__init__.py`?

**Comment by tornaria** [comment]
> > using `--enable-system-site-packages` is broken:
> > 
> > * first, the version of `sage_conf` inside the venv is installed in such a crooked way that _it will not override_ the one installed in the system site-packages, in spite the sage venv site-packages being listed before the system site-packages in `sys.path`.
> 
> Could it be that your `sage-conf/_sage_conf` in your system site-packages has an `__init__.py`?

No, it's just a plain old `sage_conf.py` file. How would `import sage_conf` work otherwise?

**Comment by mkoeppe** [comment]
We have both `sage_conf.py` and `_sage_conf/_sage_conf.py`. The former imports the latter.

**Comment by tornaria** [comment]
> We have both `sage_conf.py` and `_sage_conf/_sage_conf.py`. The former imports the latter.

I have `/usr/lib/python3.12/site-packages/sage_conf.py` which just defines some variables.

In the venv site-packages there's no `sage_conf` package to override the system one. Neither `sage_conf.py` nor `sage_conf/__init__.py` nor `_sage_conf` directory.

This is what I see (with or without `--enable-system-site-packages` is the same):
```
$ ls -d venv/lib/python3.12/site-packages/*sage*conf*
venv/lib/python3.12/site-packages/__editable__.sage_conf-10.3b7.pth
venv/lib/python3.12/site-packages/__editable___sage_conf_10_3b7_finder.py
venv/lib/python3.12/site-packages/sage_conf-10.3b7.dist-info
```

See this:
```
$ venv/bin/python
Python 3.12.1 (main, Dec 26 2023, 18:42:33) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.meta_path
[<_distutils_hack.DistutilsMetaFinder object at 0x7f93a58d6f60>, <class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>, <class '__editable___sage_conf_10_3b7_finder._EditableFinder'>, <class '__editable___sage_setup_10_3b7_finder._EditableFinder'>]
>>> sys.meta_path[3]
<class '_frozen_importlib_external.PathFinder'>
>>> sys.meta_path[3].find_spec("sage_conf", None)
ModuleSpec(name='sage_conf', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f7297d32a20>, origin='/usr/lib/python3.12/site-packages/sage_conf.py')
>>> sys.meta_path[4]
<class '__editable___sage_conf_10_3b7_finder._EditableFinder'>
>>> sys.meta_path[4].find_spec("sage_conf", None)
ModuleSpec(name='sage_conf', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f7297d32d50>, origin='/home/tornaria/src/sage/sage-git/develop/pkgs/sage-conf/sage_conf.py')
```
so the "editable" thingy is placed in `meta_path` too late to override the `sage_conf.py` in system site-packages. The correct sage_conf is found, only too late.

The same thing in an isolated venv works fine because `sys.meta_path[3]` (`== PathFinder`) doesn't find anything and so `sys.meta_path[4]` gets a chance to do its thing.

**Comment by mkoeppe** [comment]
Thanks for investigating. This is interesting. I think this item is installed by https://github.com/pfmoore/editables/blob/2331418af764ef203959327354335c431978e70d/src/editables/redirector.py#L39

**Comment by tobiasdiez** [comment]
@mkoeppe could you please rebase this PR so that it doesn't depend on https://github.com/sagemath/sage/pull/36561. Then we can merge it quicker.

**Comment by mkoeppe** [comment]
This doesn't "need work". It's just another one of these.

**Comment by tobiasdiez** [comment]
There is nothing disputed here. You just choose to base this PR on a disputed PR, without any real technical need (could have easily changed the python version also in the setup.cfg file).

**Comment by mkoeppe** [comment]
As you know, this label marks PRs as affected by your persistent pattern of abuse.

**Comment by dimpase** [comment]
> As you know, this label marks PRs as affected by your persistent pattern of abuse.

Please stop making these unfounded accusations. Disagreeing with you is not "abuse".

**Comment by dimpase** [comment]
@tobiasdiez - can you propose a concrete patch to make this PR agreeable for you?

**Comment by tornaria** [comment]
Since this PR is disputed, I'm moving the "blocker" from this PR to #37270 which solves the main urgency in a very simple and (hopefully) uncontroversial way.

Let's just hope someone is able to step up and take leadership before the ship sinks (@vbraun @williamstein @roed314).

**Comment by tobiasdiez** [comment]
Again, there is nothing "disputed" here. It's our convention that a PR can only be marked as positive review once all its dependencies are marked as such, right? This is not the case here - that's why I removed the positive review label (sorry if this was not clear from my comment above).

> @tobiasdiez - can you propose a concrete patch to make this PR agreeable for you?

https://github.com/sagemath/sage/pull/37270 is pretty much what I had in mind. Thanks @tornaria for opening it.

**Comment by mkoeppe** [comment]
@tobiasdiez As explained elsewhere, the "disputed" label here marks the PR as affected by abusive conduct; specifically by manipulation of labels in its dependencies #36561 (blocked since November), #36951 (blocked since Jan 5).
This is for cross-referencing purposes.

**Comment by roed314** [comment]
This PR was given a positive review by @tornaria, and @tobiasdiez undoing that review is not in accordance with Sage's reviewing practices.  If the vote [here](https://groups.google.com/g/sage-devel/c/IgBYUJl33SQ) succeeds, those involved may act in accordance with the new policy.  In the meantime I'm setting this to positive review.

**Comment by tornaria** [comment]
I actually withdrew my positive review by replacing this with #37270 about a month ago.

**Comment by mkoeppe** [comment]
@roed314: @tornaria is correct; he had removed himself from his role as a reviewer of this PR.

We can revisit this PR after its dependencies are merged.

**Comment by roed314** [comment]
@mkoeppe and @tornaria: thanks for the correction.  As you say, leaving this at needs review seems right for now.

**Comment by jhpalmieri** [comment]
I'm posting to record a vote of -1 on behalf of Tobias Diez.

**Comment by saraedum** [comment]
Since there seems to be no vote needed on this PR (the "disputed" part of this PR refers to one of its dependencies) I am removing the disputed label.

**Comment by tornaria** [comment]
> Since there seems to be no vote needed on this PR (the "disputed" part of this PR refers to one of its dependencies) I am removing the disputed label.

Are 102 commits necessary to switch to python 3.12?

Sagemath works fine with python 3.12 (I shipped 10.2 and now 10.3 using python 3.12).

It should only take a small change in `build/pkg/python/`, I'm sure nobody would oppose to *that*.

**Comment by tornaria** [comment]
Also, a lot of tests fail.

**Comment by mkoeppe** [comment]
> Are 102 commits necessary to switch to python 3.12?

What's your point here, if any? This PR, as I am sure if obvious to you, is an integration PR that has merged numerous PRs where the main work happened.

**Comment by mkoeppe** [comment]
I'm setting to "needs work" for now because of the merge conflict.

**Comment by mkoeppe** [comment]
> I'm sure nobody would oppose to _that_.

I think you would be surprised if you cared to look at the disputed PRs.

**Comment by tornaria** [comment]
> > I'm sure nobody would oppose to _that_.
> 
> I think you would be surprised if you cared to look at the disputed PRs.

-1 vote from me here.

**Comment by mkoeppe** [comment]
Closing as completed

**Pull request closed without merging**
