### PR TITLE
enhancements in infinite polynomial rings

### PR DESCRIPTION
**Pull request by fchapoton**
This make a few little changes, nothing serious.

This catches more precise exceptions, not `Exception`.

### CODE REVIEW

**Comment by mantepse** [comment]
Thank you!  It appears to me that the `all_gens` method is completely new (in Sage), do you have any plans with it?

**Comment by fchapoton** [comment]
well, not really. The problem is that the usual semantic of `gen` and `gens` is not respected in this file. They do not return some elements of the ring. I am not sure what to do. I can remove `all_gens` or call it otherwise or make it hidden..

**Comment by mantepse** [comment]
Do you know whether there is any good reason for not respecting the usual semantics?

**Comment by fchapoton** [comment]
it's because there are infinitely many generators, in a finite number of families

**Comment by mantepse** [comment]
I don't see how that's a good reason. Is this the only infinite dimensional ring in sage which has gen and gens?

**Comment by fchapoton** [comment]
It is also a matter of offering a simple and practical access to the variables.

**Comment by mantepse** [comment]
Can we have both, in case it makes sense?  I find
```
sage: P.<a, b> = InfinitePolynomialRing(QQ)
```
practical, and I do not see why we couldn't have, at the same time
```
sage: [P.gen(i) for i in range(5)]
[a[0], b[0], a[1], b[1], a[2]]
```
I looked at the code: on the plus side, `ParentWithGens` is deprecated, on the minus side, there is no method returning a family of generators.

I think that there are quite a few things that would work better with `gen` returning a proper generator of the ring, for examples substitution and defining homomorphisms.

**Comment by mantepse** [comment]
Old discussion: https://groups.google.com/g/sage-devel/c/-CVdz6H7dTc/m/_x1px4bHAgAJ

**Comment by fchapoton** [comment]
See also #34120

**Comment by fchapoton** [comment]
I do not want to do big things and changes here. So maybe we can keep only the changes that enlarge the possible input of the `gen` method of infinite polynomial rings ? Would you approve that ?

**Comment by mantepse** [comment]
I would rather not modify the semantics before agreeing on the desirable semantics, especially since we seem to agree that the current semantics breaks stuff quite badly. Do you have any concrete plans with your proposed improvement?

**Comment by fchapoton** [comment]
I dot not  have any specific plan about `gen` and  `gens`. I may try to get rid of `ParentWithGens` when I have time.

So we can close the present poule-requete, vielleicht ?

**Comment by fchapoton** [comment]
Ok, I have replaced the branch by a new one only making very simple changes, and not touching anything about gens

**Comment by mantepse** [comment]
Can I assume that the failure in singular is unrelated?
```
File "src/sage/interfaces/singular.py", line 530, in sage.interfaces.singular.Singular._send_interrupt
Failed example:
    2*a
Expected:
    2
Got:
    <BLANKLINE>
```

If so, positive review from my side.

**Review by mantepse — APPROVED** [review]
Thank you!

**Pull request merged**
