### PR TITLE
Refactor sagemath-standard through sagemath-{categories,environment,repl}

### LINKED ISSUE #34587: Refactor sagemath-standard through sagemath-{categories,environment,repl}
<div id="comment:0"></div>

- `src/setup.py` (used when `--enable-editable` is in use) will continue to do a monolithic build as of this ticket
- the direct installation mode (`--disable-wheels --disable-editable`) will use an environment variable so that `pkgs/sagemath-standard/setup.py` falls back to do a monolithic build (or check if it can be done by `src/setup.py`)

Depends on #33812
Depends on #34344
Depends on #32874

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/34587_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

Fixes #34587

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
```
[sagemath_environment-10.0.beta0] Successfully built sagemath-environment-10.0b0.tar.gz and sagemath_environment-10.0b0-py3-none-any.whl
[sagemath_environment-10.0.beta0] WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[sagemath_environment-10.0.beta0] WARNING: Skipping sagemath_environment as it is not installed.
[sagemath_environment-10.0.beta0] ls: cannot access 'Using pip 22.3.1 from /sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/pip (python 3.8)'$'\n''Looking in links: /sage/local/var/lib/sage/venv-python3.8/var/lib/sage/wheels'$'\n''Processing /sage/local/var/lib/sage/venv-python3.8/var/lib/sage/wheels/sagemath_environment-10.0b0-py3-none-any.whl'$'\n''Installing collected packages: sagemath-environment'$'\n''Successfully installed sagemath-environment-10.0b0'$'\n''/sage/local/var/lib/sage/venv-python3.8/var/lib/sage/wheels/sagemath_environment-10.0b0-py3-none-any.whl': No such file or directory
[sagemath_environment-10.0.beta0] using tox.ini: /__w/sage/sage/pkgs/sagemath-environment/tox.ini (pid 25775)
[sagemath_environment-10.0.beta0] using tox-3.27.0 from /sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/tox/__init__.py (pid 25775)
[sagemath_environment-10.0.beta0] Traceback (most recent call last):
[sagemath_environment-10.0.beta0]   File "/sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/py/_error.py", line 66, in checked_call
[sagemath_environment-10.0.beta0]     return func(*args, **kwargs)
[sagemath_environment-10.0.beta0] FileNotFoundError: [Errno 2] No such file or directory: '/__w/sage/sage/pkgs/sagemath-environment/Using'
```

**Comment by mkoeppe** [comment]
```
[sagemath_objects-10.0.beta0] Processing /sage/local/var/lib/sage/venv-python3.8/var/lib/sage/wheels/Cython-0.29.32-cp38-cp38-linux_x86_64.whl
[sagemath_objects-10.0.beta0] ERROR: Could not find a version that satisfies the requirement sage-setup~=10.0b0 (from versions: none)
[sagemath_objects-10.0.beta0] ERROR: No matching distribution found for sage-setup~=10.0b0
```
(sage-setup was not built as a wheel)

**Comment by kwankyu** [comment]
After `make distclean`, `./bootstrap && ./configure && make -j4` failed. It just failed. There is no log that I can report...

**Comment by kwankyu** [comment]
I checked again. By "no log", I mean
```
...
[numpy-1.23.5] Finished installing numpy-1.23.5
make[2]: *** [all-start] Error 2

real	28m53.666s
user	95m30.385s
sys	18m20.515s
***************************************************************
Error building Sage.

The following package(s) may have failed to build (not necessarily
during this run of 'make all-start'):

It is safe to delete any log files and build directories, but they
contain information that is helpful for debugging build problems.
WARNING: If you now run 'make' again, the build directory of the
same version of the package will, by default, be deleted. Set the
environment variable SAGE_KEEP_BUILT_SPKGS=yes to prevent this.

make[1]: *** [all-start] Error 1
make: *** [all] Error 2
```
I don't know what went wrong.

**Comment by mkoeppe** [comment]
Thanks for testing! I'll merge current develop and take a look.

**Comment by mkoeppe** [comment]
Closing; better version in #35095.

**Pull request closed without merging**
