### PR TITLE
`pkgs/sagemath-{bliss,sirocco,tdlib}`: Fix sdists

### PR DESCRIPTION
**Pull request by mkoeppe**
Since 10.2.beta8, likely as a side effect of the setuptools_scm update (#36400), some of our modularized sdists contain way too many files. https://pypi.org/project/sagemath-bliss/10.2b8/#files

We fix this by updating the MANIFEST.in files.
- Cherry-picked from #35095.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kiwifb** [comment]
How bizarre. The sdist that I am generating now for sage-on-gentoo do not have all that extra baggage. I cannot see the difference before and after the patch. I had a long think after some of our previous conversation and came up with something, I am now generating sdist for the develop branch as part of the ebuild, I just had to put my brain cells at work for a bit and now at some point `python -m build -n -x -s` is run.

**Comment by mkoeppe** [comment]
Our GH Actions workflow that builds them just uses `make pypi-sdists` in a freshly configured source tree, which ultimately invokes the same command that you quoted.  setuptools_scm is installed before any of the sdists are built because it is part of `PYTHON_TOOLCHAIN`.

**Comment by kiwifb** [comment]
And I have setuptools-scm too, but I have stayed at 7.1.0 on that system. That may make a difference, I will test that.

**Comment by kiwifb** [comment]
Yes, setuptools-scm-9.0.4 is the guilty party and causes a lot of stuff to be included. The patch does have an impact in that case. Much more reasonable.

**Review by kiwifb — APPROVED** [review]
Does what it says on the box. 
Positive review from me.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by kiwifb** [comment]
I think we need a follow up. The sdist problem did not stop at optional packages. The sagemath-standard sdist contains `sage/libs/sirocco.pyx` which does clash with `sagemath-sirocco`. There is nothing from sagemath-meataxe or sagemath-bliss in the sdist (otherwise emerge would refuse to merge them as it did with sirocco), but I do not know about other sagemath-* optional packages.

**Comment by kiwifb** [comment]
I should add that this is with the current merge branch of Volker which includes this PR.

**Pull request merged**
