### PR TITLE
Move some code from Brandt modules to quaternion algebras

### PR DESCRIPTION
**Pull request by pjbruin**
This moves the following helper functions from Brandt modules to (public or private) methods of quaternion algebras, where they should be easier to access:
- `basis_for_left_ideal()` function: moved to `_left_ideal_basis()` method
- `right_order()` function: moved to `_right_order_from_ideal_basis()` method
- `quaternion_order_with_given_level()` function: moved to `order_with_level()` method

We add deprecations for these functions and also deprecate the function `maximal_order()` in favour of the existing `maximal_order()` method of quaternion algebras.

### CODE REVIEW

**Comment by pjbruin** [comment]
#sd123

**Review by tscrim — APPROVED** [review]
LGTM.

**Comment by vbraun** [comment]
merge conflict

**Comment by vbraun** [comment]
I'm getting lots of errors after merging this, please try it on the newest develop branch

**Pull request merged**
