### PR TITLE
Implement an iterator for absolute number fields

### PR DESCRIPTION
**Pull request by tscrim**
We use the $\mathbb{Q}$ vector space structure. Although because of #37706, we go through `cartesian_product`.

If there is an easy way to implement this in full generality (i.e., all number fields), please let me know.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
Adding potential reviewers who might have some thoughts on this.

**Comment by JohnCremona** [comment]
There's another iterator somewhere which lists elements by height, but a simpler one would also be useful. Sorry I will not be able to look at this for a week, feel free to remind me.

**Comment by tscrim** [comment]
I found the methods `elements_of_bounded_height()` and `elements_of_norm()` (but only integral elements up to units of positive norm), but nothing that would iterate over all elements. I will send a ping if nobody else is able to review this beforehand. Thanks.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by tscrim** [comment]
Thank you.

**Pull request merged**
