### PR TITLE
ci-linux: Remove unmaintained local-conda runs

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

These are jobs that run directly on the GH Actions container instead of using Docker.
We remove them.

These jobs have been failing for a long time.
Newer tests for conda-forge have been added in `ci-conda.yml`, which makes these ones here obsolete.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Shouldn't be then the corresponding part of the tox ini file also be removed? Also, what is the difference between this tox-based conda run and the one in conda-ci?

**Comment by mkoeppe** [comment]
> Shouldn't be then the corresponding part of the tox ini file also be removed?

No, the tox.ini can be used locally.

**Comment by mkoeppe** [comment]
> what is the difference between this tox-based conda run and the one in conda-ci?

The one removed here builds sage-the-distribution on top of conda-forge. But this mode of installation is also tested using `docker-conda-forge`, which is more robust because we have more control over this environment than we do over the github actions container.

In contrast, in conda-ci, we use the "experimental" method of running sagelib directly on top of conda-forge.

**Review by tobiasdiez — APPROVED** [review]
Thanks for the explanation. Makes sense!

**Comment by mkoeppe** [comment]
Thank you!

**Comment by dimpase** [comment]
merging, as it improves CI by removing broken tests

**Pull request merged**
