### PR TITLE
Remove abuse of predefined x in doctests

### LINKED ISSUE #32721: Remove abuse of predefined x in doctests
<div id="comment:0"></div>

For example in `src/sage/rings/number_field/number_field.py`

```
        sage: K.<a> = NumberField(x^2 - 2)
```

This leads to numerous errors when `sage.symbolic` is not available (#32601).

CC:  @tscrim @orlitzky

Component: **refactoring**

_Issue created by migration from https://trac.sagemath.org/ticket/32721_

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

- Fixes https://github.com/sagemath/sage/issues/32721

- See also: #10483

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by fchapoton — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thank you! May I set to "positive review"?

**Comment by mkoeppe** [comment]
Thanks!

> By the way, the diff is too large to be seen easily with github viewer.

Sorry for the megapatch...

> And I do not like all these "internal optional tags" that pollute the doctests.

Yes, it's not pretty. I'm trying to pay for it by reformatting poorly formatted doctests and docstrings in return...

**Comment by vbraun** [comment]
Merge conflict

**Comment by mkoeppe** [comment]
trivial merge

**Review by fchapoton — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks again!

**Pull request merged**
