### PR TITLE
Remove cygwin.txt

### PR DESCRIPTION
**Pull request by mkoeppe**
Split out from #36778 

See https://github.com/sagemath/sage/pull/36778#discussion_r1405502284

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
Please explain the purpose of putting this on hold. You said something about "other projects benefitting". They can just as well be using a branch where the Cygwin is still present.

**Comment by mkoeppe** [comment]
Dima, such calls to "go play on your own branch", like your previous suggestion that I "just fork Sage" (https://github.com/sagemath/sage/pull/35403#issuecomment-1572690868), are most unwelcome. 

https://github.com/sagemath/sage/blob/develop/CODE_OF_CONDUCT.md

**Comment by dimpase** [comment]
You are putting some stuff ripe to removal on hold, without an explanation why this is needed, and when I ask for an explanation you basically start screaming.

**Comment by mkoeppe** [comment]
> without an explanation

As you well know, I explained it in the original discussion. 
The link to it is in the PR description.

**Comment by vbraun** [comment]
#36778 was merged, can this ticket be closed?

**Comment by mkoeppe** [comment]
The cygwin.txt files were not removed in the merged version of #36778. I split that proposed change out from there to this PR because I did not agree with removing them at the time. (I still do not support it because, as I explained, the information system is still useful when I help other projects with my Cygwin expertise.) 

From my side, no action is needed here. It's fine with me to either close it, or to leave it as "pending" indefinitely.

**Pull request closed without merging**
