### PR TITLE
provide a link to mirrors

### PR DESCRIPTION
**Pull request by dimpase**
this will improve the docs, as asked on [sage-devel](https://groups.google.com/d/msgid/sage-devel/52db9220-62b4-4fc5-ac5a-f77bd040a9b7n%40googlegroups.com)
by @JohnCremona

### CODE REVIEW

**Comment by mkoeppe** [comment]
-1, we decided to de-emphasize download of tarballs in favor of telling people to use git.

Just remove the useless Wikipedia link.

**Comment by dimpase** [comment]
the mirrors are still there and are functional, no?

**Comment by mkoeppe** [comment]
They are, but the change done in:
- https://github.com/sagemath/sage/pull/37309

was deliberate.

**Comment by mkoeppe** [comment]
I suggest to close this in favor of:
- #38041

**Comment by gmou3** [comment]
I agree.

**Pull request closed without merging**
