### PR TITLE
CM elliptic curves missing isogenies

### LINKED ISSUE #36780: Elliptic curves with CM over number fields fail to find all isogenies
### Steps To Reproduce

Define an elliptic curve E over a real quadratic number field, where j(E) = 0, compute E.isogeny_class(), and look at the degrees it finds. Example:
sage: L5.<r5> = NumberField(x^2-5)
sage: F = EllipticCurve(L5,[0,-4325477943600\*r5-4195572876000])
sage: F.isogeny_class().matrix()
[1 3]
[3 1]

### Expected Behavior

The matrix should include isogenies of degree 5 (and more).

### Actual Behavior

It only find 3-isogenies (see above).

### Additional Information

As reported to sage-support: https://groups.google.com/g/sage-support/c/1BfJIGIlb0M

The problem is in the function sage.schemes.elliptic_curves.isogeny_class.isogeny_degrees.cm, where the degree bound called n there needs to be multiplied by 3 for j=0, d=-3 (and by 2 for j=1728, d=-4).

A PR is in preparation.  Only curves with j=0 or j=1728 are affected (and not all these).

### Environment

```markdown
- **OS**: any
- **Sage Version**: 10.2rc3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by JohnCremona**
Fixes #36780.

For elliptic curves over number fields, with j-invariant 0 and 1728, the function isogeny_degrees_cm was forgetting to multiply a degree bound by 3 or 2 respectively (half the number of units), resulting in some isogenies being missed.

- [ x] The title is concise, informative, and self-explanatory.
- [ x] The description explains in detail what this PR is about.
- [ x] I have linked a relevant issue or discussion.
- [ x] I have created tests covering the changes.
- [ x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JohnCremona** [comment]
I do not understand what failed or why, and do not know how to find out. Can anyone explain?

**Comment by JohnCremona** [comment]
Thanks. My 3rd commit should have fixed those

**Comment by JohnCremona** [comment]
As far as I can see, the test failures have nothing to do with my changes.

**Comment by JohnCremona** [comment]
I looked ta the failing tests and as far as I can see they have nothing to do with any code changed in my PR.

**Comment by JohnCremona** [comment]
After updating (merge with develop) there are still test failures which have nothing to do with me (the test platform bailed out after not finding mathjax).

**Comment by dimpase** [comment]
You can click on "Details" button of the failing test, and check that tests which fail aren't related to your ticket.

**Comment by JohnCremona** [comment]
> You can click on "Details" button of the failing test, and check that tests which fail aren't related to your ticket.

Yes, I have been doing that for three weeks, after which nothing changes.  Now I cannot even remember what the bug was.

**Review by fchapoton — APPROVED** [review]
ok, looks good enough

**Pull request merged**
