### PR TITLE
Replace relative imports by absolute ones in categories

### PR DESCRIPTION
**Pull request by tobiasdiez**
As preparation for compiling with meson, we replace relative imports by absolute ones.
Relative imports are not used consistently in the codebase and result in issues for doctesting with pytest (which admittedly is a limitation of pytest). We normalize the relative imports in `sage.categories` to be absolute imports. Small code-style improvements along the way (mainly to nicely order the imports)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
You may be interested to know that I have these changes in #35095

**Comment by kwankyu** [comment]
Is this just to satisfy buggy pytest?

So are you recommending no relative imports in our codebase?

**Comment by tobiasdiez** [comment]
> Is this just to satisfy buggy pytest?

And buggy cython (which also has problems with relative imports without `__init__` files)

> So are you recommending no relative imports in our codebase?

Yes.

**Comment by mkoeppe** [comment]
Same comment as https://github.com/sagemath/sage/pull/36588#issuecomment-1792842988

**Comment by mkoeppe** [comment]
Rebased cleanly -- without need for manual intervention -- on top of #36666.

**Comment by tobiasdiez** [comment]
Please revert these changes (and never force push to my PRs again). Thanks.

**Comment by tobiasdiez** [comment]
@mkoeppe please revert the changes you made to this PR. Thanks

**Comment by mkoeppe** [comment]
> Please revert these changes (and never force push to my PRs again).

Tobias, I know that you know that but I'll explain it to the audience:

This PR is marked "Maintainers are allowed to edit this pull request." If you wish your PRs to not undergo normal maintainer actions -- such as constructive rebasing, as discussed in https://github.com/sagemath/sage/pull/36666#issuecomment-1802170137 -- the correct protocol is to just uncheck that checkmark.

And to force-push whatever branch you may have -- the old one or an updated one -- you do not need my assistance to push it to your PR.

This type of aggressive posturing ("never ... again") is most unwelcome here. 

More generally: Your frequent insinuations that my work on PRs is somehow "improper" are also unwelcome conduct; the frequent repetition makes it harassment. The sage-abuse committee has already informed you recently in https://github.com/sagemath/sage/pull/36489#discussion_r1372484615 about the correct procedure: 

>> "If you feel that anybody else's behavior violates the code of conduct, we encourage you to email [2] and explain why. [2] https://groups.google.com/g/sage-abuse"

**Comment by tobiasdiez** [comment]
Your force push results in problems in my normal workflow (and it's generally advised to not force push to any public branch that is shared with other people). Moreover, I don't have a local copy of the original branch since I'm exclusively using codespaces. So yes, I would like you to restore the branch.

**Comment by mkoeppe** [comment]
> Your force push results in problems in my normal workflow

If you need help with rebasing a branch, just ask for help.

**Comment by tobiasdiez** [comment]
> > it's generally advised to not force push to any public branch that is shared with other people
> 
> I know that you know that, but I'll explain it to the audience: Rebasing PR branches is very much standard procedure on GitHub. The general advice to not force push to public branches refers to branches that are referred to by branch name.

Let me update your knowledge by citing the github and gitlab documentation:
> Be very careful when force pushing commits to a pull request. Force pushing changes the repository history and can corrupt your pull request. If other collaborators branch the project before a force push, the force push may overwrite commits that collaborators based their work on.

(https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

> git rebase rewrites the commit history. It can be harmful to do it in shared branches. It can cause complex and hard to resolve [merge conflicts](https://docs.gitlab.com/ee/user/project/merge_requests/conflicts.html). In these cases, instead of rebasing your branch against the default branch, consider pulling it instead (git pull origin master). Pulling has similar effects with less risk compromising the work of your contributors.

(https://docs.gitlab.com/ee/topics/git/git_rebase.html)

But in either case, please respect my workflow.

**Comment by mkoeppe** [comment]
> by citing the github and gitlab documentation:
> 
> > Be very careful when force pushing commits to a pull request.

Yes, one has to be careful.

**Comment by tobiasdiez** [comment]
Matthias, please just revert your changes. Thanks

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by tobiasdiez** [comment]
Thanks!

**Pull request merged**
