### PR TITLE
.github/workflows/docker.yml: Free more disk space

### PR DESCRIPTION
**Pull request by mkoeppe**
Replacing a step of our `docker.yml` with a well-maintained action with the same purpose.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
With this version, get: 
```
/dev/root        84G   58G   27G  69% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  31% /mnt
tmpfs           693M   12K  693M   1% /run/user/1001
```

**Comment by mkoeppe** [comment]
Now 
```
/dev/root                     84G   45G   40G  54% /
tmpfs                        3.4G  172K  3.4G   1% /dev/shm
tmpfs                        1.4G  1.1M  1.4G   1% /run
tmpfs                        5.0M     0  5.0M   0% /run/lock
/dev/sdb15                   105M  6.1M   99M   6% /boot/efi
/dev/sda1                     14G   13G  100M 100% /mnt
tmpfs                        693M   12K  693M   1% /run/user/1001
/dev/mapper/buildvg-buildlv   19G   24K   19G   1% /home/runner/work/sage/sage
```

**Comment by kwankyu** [comment]
Looks nice. 

Where can I see "df -h" in action?

19 gb of the last line is part of 40 gb root space. Right?

**Comment by mkoeppe** [comment]
> 19 gb of the last line is part of 40 gb root space. Right?

No, they are separate

**Comment by mkoeppe** [comment]
> Where can I see "df -h" in action?

In "CI Linux Incremental"

**Comment by kwankyu** [comment]
> > 19 gb of the last line is part of 40 gb root space. Right?
> 
> No, they are separate

But this is not a new space the action saved... Is it?

**Comment by mkoeppe** [comment]
Also no. See https://github.com/marketplace/actions/maximize-build-disk-space#how-it-works

**Comment by kwankyu** [comment]
Thanks. 

The doc seems to say the 19 gb is a logical volume made up of free spaces of 84 gb / space and 14 gb /mnt space. I am puzzled because the 19 gb is not in https://github.com/sagemath/sage/pull/36418#issuecomment-1751509190.

Anyway, it's good to use the action dedicated for this business.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks!

Without my configuration setting `root-reserve-mb:      40000`, the logical volume (now 19G) would be 58G of free space for `/home/runner/work/sage/sage`.

**Comment by vbraun** [comment]
merge conflict

**Comment by tobiasdiez** [comment]
Could it be that this PR is the reason for the out-of-space issues such as https://github.com/sagemath/sage/actions/runs/6529558870/job/17727415989?

**Comment by mkoeppe** [comment]
No, it can't. I made this PR when I saw the out of space conditions in some workflow runs about a week ago.

**Pull request merged**
