### PR TITLE
Miscellaneous system package updates

### PR DESCRIPTION
**Pull request by orlitzky**
Add a few spkg-configure files, skip appnope when not on macOS, add an `# optional` tag, and add a few more packages to `--disable-r` and `--disable-notebook`.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Comment by vbraun** [comment]
merge conflict

**Comment by vbraun** [comment]
merge conflict, please wait for the next beta

**Comment by orlitzky** [comment]
Here's the thing: I'm gonna forget. Any plans to push whatever is conflicting to your vbraun/develop branch?

**Comment by orlitzky** [comment]
Hey, I forgot. Rebase involved dropping three isolated commits that somebody else made first, so I think it's safe to set back to positive review.

**Review by dimpase — APPROVED** [review]
lgtm

**Pull request merged**
