### PR TITLE
Change `ipympl`/`pkgconfig`/`widgetsnbextension` to wheel packages, drop build deps

### PR DESCRIPTION
**Pull request by mkoeppe**
- Cherry-picked from #36129

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36239 (merged here)

### CODE REVIEW

**Comment by orlitzky** [comment]
To save me from looking through the 362 changed files in the notebook-7.x PR... why are we making ipympl standard? Did it become a non-optional dependency of something standard during the notebook upgrade?

Aside from that I'm very happy to see the build dependencies disappear.

**Comment by mkoeppe** [comment]
It was requested in https://github.com/sagemath/sage/pull/36129#issuecomment-1695610551 for added convenience.

**Comment by orlitzky** [comment]
> It was requested in [#36129 (comment)](https://github.com/sagemath/sage/pull/36129#issuecomment-1695610551) for added convenience.

Ok, makes sense I guess. I think it should be added to the `--disable-notebook` list in `configure.ac` now though.

**Comment by mkoeppe** [comment]
OK, I'll merge #36219 for that.

**Comment by orlitzky** [comment]
@egourgoulhon can you propose the new standard package on sage-devel so that no one can accuse us of funny business? (Despite being "standard," it's still pseudo-optional via `--disable-notebook`.)

**Comment by orlitzky** [comment]
Aside from that this LGTM and I can clean up any system package issues afterwards.

**Comment by mkoeppe** [comment]
I've taken out the change of ipympl to standard; we can do that in https://github.com/sagemath/sage/pull/36129

**Comment by orlitzky** [comment]
OK then

**Comment by mkoeppe** [comment]
Thanks!

**Comment by orlitzky** [comment]
I think the `deprecation` package can be removed now as well. Grep and its commit message suggest that it was needed only for `jupyter_packaging`.

**Comment by egourgoulhon** [comment]
> @egourgoulhon can you propose the new standard package on sage-devel so that no one can accuse us of funny business? (Despite being "standard," it's still pseudo-optional via `--disable-notebook`.)

Done in https://groups.google.com/g/sage-devel/c/fRufANUCNdY

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by vbraun** [comment]
merge conflict

**Pull request merged**
