### PR TITLE
`build/pkgs/setuptools_scm`: Update to 8.0.4, add fixes for version 8

### PR DESCRIPTION
**Pull request by mkoeppe**
Version 8 needs some new workarounds when packages that do not use `setuptools_scm` are installed with `--no-build-isolation` in an environment with `setuptools_scm`. This is relevant in particular for conda, see #35593.

`setuptools_scm` inserts itself into the build process of unsuspecting packages via entry points declared by setuptools. One gets a warning:
-   `[sage_conf-10.2.beta5]     WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section` (https://github.com/sagemath/sage/actions/runs/6409373032/job/17400573034?pr=36400#step:8:3978)

These warnings show up at build time, but also in runtime uses of Cython, where it causes doctest failures.

Here we do the update (for no specific reason other than to be up to date) and implement the workarounds.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kiwifb** [comment]
I would consider those warnings an upstream bug. The way you word it ("unsuspecting"), I almost feel like having a conversation on consent in software packaging.

**Comment by mkoeppe** [comment]
Offering these setuptools entry points that modify other packages' build behavior has always seemed like a severe & puzzling misdesign to me, but I may be missing something. In what is now the default in Python dev, using build isolation, it's not a problem any more -- each package just declares its PEP517/518 build environment, and if it does not like to use setuptools_scm, it just doesn't use it. But in flat installations as in Linux distributions, the problem persists.

**Comment by kiwifb** [comment]
I was a bit sarcastic. And I have not looked for that issue in my logs so I cannot tell if it is a big problem. But if if the configuration bits is missing, may be it should be a signal that your tool is not required and that's the end of that. There is plenty of software available on a computer and they do not all jump and down saying "use me! use me!". What's wrong with some people.

**Review by tobiasdiez — COMMENTED** [review]
I don't quite understand the motivation / problem in the context of conda. We don' use `setuptools_scm` so why would we deliberately install it in the conda environment, especially if it causes problems? I'm also not aware that I've seen this error before, so it feels more like an issue with the implementation in https://github.com/sagemath/sage/pull/35593.

**Comment by mkoeppe** [comment]
> I don't quite understand the motivation / problem in the context of conda. 

What's particular about conda (in contrast to normal modern python dev) is that one commonly uses `--disable-build-isolation` -- so that the packages from the conda environment are used.

> We don' use `setuptools_scm` so why would we deliberately install it in the conda environment, especially if it causes problems? 

We wouldn't ideally, but users may (for example and in particular when people switch between different ways of using the same conda environment). It is important that just installing this package does not break stuff.

**Comment by dimpase** [comment]
Can't we get rid of the special treatment of Conda (in particular `--no-build-isolation`) by means of `--enable-system-site-packages` ?

**Review by dimpase — APPROVED** [review]
I'm approving this for the time being, but in general this looks like a less than ideal design.

**Comment by tobiasdiez** [comment]
`no-build-isolation` when installing sagelib is need since you want to use the build dependencies that are already installed by conda in the environment, and not get new ones via `pip`, see eg https://github.com/conda/conda-build/issues/4251#issuecomment-1053460542

But maybe it is sufficient to voice an warning (during configure) that some doctest may break when setuptools_scm is present in the conda environment. If one has more packages installed in the conda env than what we specify, it is logical that this may cause issues. And the setup_scm failure doesn't seem to be that bad.

**Comment by dimpase** [comment]
> `no-build-isolation` when installing sagelib is need since you want to use the build dependencies that are already installed by conda in the environment, and not get new ones via `pip`, see eg [conda/conda-build#4251 (comment)](https://github.com/conda/conda-build/issues/4251#issuecomment-1053460542)
> 

How is this not applicable to the `--enable-system-site-packages` case? Are you saying there is no other way to limit `pip` in its quest to install the latest stuff no matter what? Isn't `pip` here coming from Conda, yet they cannot rein it in? What an OS (e.g. a Linux distro) normally does in such a case, is limiting the  use of `pip` to only do `--user` case - for non-root installs.

**Comment by tobiasdiez** [comment]
> > `no-build-isolation` when installing sagelib is need since you want to use the build dependencies that are already installed by conda in the environment, and not get new ones via `pip`, see eg [conda/conda-build#4251 (comment)](https://github.com/conda/conda-build/issues/4251#issuecomment-1053460542)
> 
> How is this not applicable to the `--enable-system-site-packages` case? 

I guess it is. And if you install sagelib with make it also uses the switch: https://github.com/sagemath/sage/blob/b7c1c8fe5cd0235a8c28d41d18a16dcbb9f10391/build/bin/sage-dist-helpers#L291-L297

> Are you saying there is no other way to limit `pip` in its quest to install the latest stuff no matter what?

As far as I know pip doesn't have a switch to "use build isolation, but take build system dependencies from the global environment if they meet the requirements".

**Comment by mkoeppe** [comment]
> As far as I know pip doesn't have a switch to "use build isolation, but take build system dependencies from the global environment if they meet the requirements".

That's right. It's all or nothing. The isolated build environment is created from scratch; it never takes anything from the site packages (user or system). The only way to control it is via pip's general options regarding index servers. This is what we do when building packages in the Sage distribution; we disallow the use of the PyPI index server (`--no-index`) and only give it our fixed set of wheels in `venv/var/libs/sage/wheels` via `--find-links`.

**Comment by kiwifb** [comment]
Needs rebasing. The CI failures seem unrelated, I'll join Dima in saying we can move forwards with this.

**Comment by mkoeppe** [comment]
it merges cleanly; not a good idea to merge/rebase when it's already in positive review

**Comment by kiwifb** [comment]
Cool, I was interpreting github's message a little bit more severely.

**Comment by tobiasdiez** [comment]
Instead of suppressing the warning, it now shows up in the doctests leading to build errors (also can be seen here on this PR: https://github.com/sagemath/sage/actions/runs/6412079178/job/17409624223). Could you please fix it in a follow-up?

**Comment by kiwifb** [comment]
I honestly think this is an upstream bug. "WARNING" is not the right log level for telling you you are not using an optional feature. "INFO" would be more appropriate.

**Comment by mkoeppe** [comment]
> I honestly think this is an upstream bug

I agree. Nevertheless we should work around it in our runtime use of Cython.

**Comment by mkoeppe** [comment]
> the warning [...] shows up in the doctests 

Indeed this happens when the doctester is invoked from the `src` directory, or probably any directory that contains a setup.cfg or similar.

**Pull request merged**
