### PR TITLE
Remove most `spkg-legacy-uninstall` scripts

### LINKED ISSUE #25140: Add spkg-legacy-uninstall scripts for most standard packages
<div id="comment:0"></div>

This is a followup to #25139 and represents work that was originally done in #22510 to convert most packages to use `spkg-legacy-uninstall` and remove uninstall-related commands from their `spkg-install` scripts.

This work was brought over from an older branch and still needs some adjustment: It should incorporate the changes from the #24024 metaticket which conflict with some of these changes.  There are also some additional optional and experimental packages (and maybe a couple standard packages) that still need to be updated as well.

Probably won't bother with that until and unless #25139 is approved of in some form that still includes the `spkg-legacy-uninstall` feature.

---

To summarize what this is about: Part of the goal in implementing the new installation/uninstallation system for packages is that `spkg-install` should, ideally, not modify `$SAGE_LOCAL` in any way, at least for packages that support `DESTDIR`-based installation.  This allows more separation from the building of packages from their runtime installation target.

However, many packages' `spkg-install` or `spkg-build` include commands (mostly in the form of `rm -rf`'s) to clean up files from previous installs of those packages.  This is no longer necessary for new-style package installations that track exactly what files are installed by a package.  But it is still necessary when upgrading from old installs of packages that don't have a file manifest.  This is what the `spkg-legacy-uninstall` script is for.  It's just taking the `rm -rf`'s from `spkg-install` and moving it into a separate script that is called by the uninstaller if it doesn't have a file manifest for that package.

So this ticket is just creating the `spkg-legacy-uninstall` for many packages that already have `DESTDIR` support.

Component: **build**

Keywords: **uninstall**

Author: **Erik Bray**

Branch/Commit: **[u/embray/build/spkg-uninstall/legacy-uninstallers](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/build/spkg-uninstall/legacy-uninstallers) @ [`e2d2b01`](https://github.com/sagemath/sagetrac-mirror/commit/e2d2b01f15e25c24334d8e6f110c3302d41cdd6f)**

Reviewer: **Julian Rüth**

_Issue created by migration from https://trac.sagemath.org/ticket/25140_

### LINKED ISSUE #30480: Follow-up to #30335: Don't modify $SAGE_LOCAL contents from spkg-install scripts
<div id="comment:0"></div>

By design, spkg-install scripts should not directly touch the contents of `$SAGE_LOCAL`.  If some pre-/post-installation steps need to be taken to modify `$SAGE_LOCAL`, it should go in an `spkg-preinst` script.

I understand #30335 is a workaround, but the same workaround can still be implemented without violating this constraint.

In particular, there are numerous instances of removing bits of previous installations that can be found with

```
grep 'rm .*SAGE_LOCAL' build/pkgs/*/spkg-ins*
```
Most of these lines can probably be removed. For all packages that do DESTDIR staging, the lines would only be needed to clear out bits from ancient, pre-DESTDIR installations.

CC:  @mkoeppe @dimpase @jhpalmieri

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/30480_

### PR DESCRIPTION
**Pull request by mkoeppe**
Most normal SPKGs are installed by staging in `DESTDIR`. When copying to the final install location in `SAGE_LOCAL`, an installation record is created, which is used later in package uninstallation.

However, when SPKG installation was switched to using staging in `DESTDIR` (Meta-ticket #24024), the parts of `spkg-install` scripts that used to be responsible for removing an old version of the installed package were either kept in place or moved to `spkg-legacy-uninstall` scripts. This was done to enable incremental builds from older installations.

By passage of time, this is no longer needed.

Some of the removals are a partial cherry-pick from #25140 by @embray. 

We also switch `frobby` to `DESTDIR` staging and *add* an `spkg-legacy-uninstall` script.

Resolves #25140.
Resolves #30480.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36778 (merged here to resolve merge conflict)

### CODE REVIEW

**Comment by dimpase** [comment]
this probably needs non-incremental testing, to see that all this pkg-config magic still works

**Comment by mkoeppe** [comment]
Testing at 
- https://github.com/mkoeppe/sage/actions/runs/7160379435
- https://github.com/mkoeppe/sage/actions/runs/7160379430

**Comment by dimpase** [comment]
```
sage -t --random-seed=35638309541997713729403828278151397505 src/sage_setup/clean.py
**********************************************************************
File "src/sage_setup/clean.py", line 104, in sage_setup.clean._find_stale_files
Failed example:
    for f in stale_iter:
        if f.endswith(skip_extensions): continue
        if '/ext_data/' in f: continue
        print('Found stale file: ' + f)
Expected nothing
Got:
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/graphtheory_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/lp_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/calculus_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/polynomes_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/nonlinear_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/mpoly_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/numbertheory_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/premierspas_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/graphique_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/__init__.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/recequadiff_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/integration_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/linsolve_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/combinat_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/programmation_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/float_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/linalg_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/domaines_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/graphtheory_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/lp_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/calculus_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/polynomes_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/nonlinear_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/mpoly_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/numbertheory_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/graphique_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/__init__.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/recequadiff_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/integration_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/linsolve_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/combinat_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/float_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/linalg_doctest.py
    Found stale file: sage/tests/books/computational-mathematics-with-sagemath/sol/domaines_doctest.py
    Found stale file: sage/tests/books/judson-abstract-algebra/integers-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/galois-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/normal-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/finite-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/cosets-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/vect-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/actions-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/fields-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/__init__.py
    Found stale file: sage/tests/books/judson-abstract-algebra/homomorph-sage-exercises.py
    Found stale file: sage/tests/books/judson-abstract-algebra/algcodes-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/crypt-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/domains-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/actions-sage-exercises.py
    Found stale file: sage/tests/books/judson-abstract-algebra/sets-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/sylow-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/boolean-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/groups-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/permute-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/vect-sage-exercises.py
    Found stale file: sage/tests/books/judson-abstract-algebra/struct-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/cyclic-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/rings-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/homomorph-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/poly-sage.py
    Found stale file: sage/tests/books/judson-abstract-algebra/cosets-sage-exercises.py
    Found stale file: sage/tests/books/judson-abstract-algebra/isomorph-sage.py
**********************************************************************
1 item had failures:
   1 of  15 in sage_setup.clean._find_stale_files
    [21 tests, 1 failure, 0.31 s]
```

is this something to happen once only, or a real bug?

**Comment by mkoeppe** [comment]
Where do you see this? In a local test or in one of the CI runs?

**Comment by tornaria** [comment]
> Where do you see this? In a local test or in one of the CI runs?

https://github.com/sagemath/sage/actions/runs/7171776285/job/19527492807?pr=36862

**Comment by dimpase** [comment]
> > Where do you see this? In a local test or in one of the CI runs?
> 
> https://github.com/sagemath/sage/actions/runs/7171776285/job/19527492807?pr=36862

```
 sage -t --random-seed=250275786135833388104398129603504270427 src/sage/groups/matrix_gps/finitely_generated_gap.py  # 1 doctest failed
sage -t --random-seed=250275786135833388104398129603504270427 src/sage/tests/gap_packages.py  # 1 doctest failed
sage -t --random-seed=250275786135833388104398129603504270427 src/sage_setup/clean.py  # 1 doctest failed
----------------------------------------------------------------------
```

have nothing to do with this PR.

**Comment by mkoeppe** [comment]
I think that's unrelated noise in the Conda CI

**Comment by mkoeppe** [comment]
So let's get this in?

**Comment by dimpase** [comment]
local tests seem OK.
lgtm

**Comment by dimpase** [comment]
Is there a conflict with #36778 ?

**Comment by mkoeppe** [comment]
#36778 is already merged here

**Comment by dimpase** [comment]
ah, right

**Review by dimpase — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks.

**Pull request merged**
