### PR TITLE
Add "informational: true" to  .codecov.yml

### PR DESCRIPTION
**Pull request by kwankyu**
### :books: Description

Add `informational: true` to `.codecov.yml` to avoid "codecov/project" check failure, as discussed in https://github.com/sagemath/sage/issues/35522#issuecomment-1512287814

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tornaria** [comment]
Can we get this in the main branch please?

It seems impossible to have a PR pass checks otherwise; does somebody care about that? Luckily #35552 seems it will be added to rc2 (but it was added to develop branch before and now just removed, wtf)

**Comment by kwankyu** [comment]
> Can we get this in the main branch please?

Please review.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by tobiasdiez** [comment]
Is this hotfix still needed or can we wait for https://github.com/sagemath/sage/pull/35632?

**Comment by kwankyu** [comment]
If codecov/project fails when codecov/patch passes, would that be a reason to invalidate a PR? I think not.

If there is still, even with #35632, a possibility that codecov/project can fail when codecov/patch passes, then we need the fix of this PR.

If there is no possibility for that, then we can drop this fix. 

As we are not sure about the possibility, we can wait and see if #35632 suffices to remove the possibility. I will put this PR to "needs info" status.

**Comment by tobiasdiez** [comment]
`project` may fail if you remove e.g. doctests or make erroneous changes in the doctest framework (or more generally any change that results in less tests to be run). But in general you want to be notified in such situations.

**Comment by tornaria** [comment]
> Is this hotfix still needed or can we wait for #35632?

Yes. If PR are still failing checks. Please merge this quickly and then if #35632 is shown to fix the underlying issue, this can be reverted.

Having checks pass should be the topmost priority, otherwise the whole CI thing is half-useless.

**Comment by kwankyu** [comment]
> > Is this hotfix still needed or can we wait for #35632?
> 
> Yes. If PR are still failing checks. 

#35632 promises that it won't happen, or so I understand. If it fails us, then we merge this ticket.

**Comment by kwankyu** [comment]
Now that #35632 is merged, PR #35694 still failed in codecov/project, which I cannot understand. 

If other PRs continue to fail in codecov/project, we should consider merging this PR.

**Comment by tobiasdiez** [comment]
That particular PR failed since its base is not the most recent commit to the dev branch (but some older commit). See https://app.codecov.io/gh/sagemath/sage/pull/35694

> Coverage data is based on head [841c4fe(1 uploads)](https://app.codecov.io/gh/sagemath/sage/commit/841c4fe298738c12bc8d88f3325167918fcb802f) compared to base [7404764(2 uploads)](https://app.codecov.io/gh/sagemath/sage/commit/7404764fb2778c484febd83a337af805b72ead91)

**Comment by kwankyu** [comment]
Yes, I saw that. So codecov compares the coverage change between the head and the base. The head is just one commit away from the base, and that one commit contains trivial typo fixes. Then why codecov/project fails?

**Comment by tobiasdiez** [comment]
Because the coverage data for the base was still calculated without the fix of https://github.com/sagemath/sage/pull/35632.

**Comment by kwankyu** [comment]
Ah, that explains it. Thanks. 

OK. We then wait for everything to be on track.

**Comment by kwankyu** [comment]
How about #35562? It failed on codecov/project.

**Comment by tobiasdiez** [comment]
No idea, but there are one or two other PRs that fail with the same indirect coverage changes, compare:
https://app.codecov.io/gh/sagemath/sage/pull/35699/indirect-changes and https://app.codecov.io/gh/sagemath/sage/pull/35562/indirect-changes

So that means that although the random seed is fixed, there are moving parts in the doctests. Not good.

**Comment by kwankyu** [comment]
> So that means that although the random seed is fixed, there are moving parts in the doctests. Not good.

It is not good that the stability of codecov/project was not obtained by the random seed fix. But perhaps we cannot blame that there are moving parts in doctests. 

Then it seems that we will have chronic failing codecov/project. We should consider merging this PR.

**Pull request merged**
