### PR TITLE
avoid using reserved min and max in two files

### PR DESCRIPTION
**Pull request by fchapoton**
and other minor code details in the modified files

also some doctest formatting

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Review by dcoudert — APPROVED** [review]
LGTM.

The lint errors are not related to the changes done here.

**Comment by fchapoton** [comment]
the linter failure is bizarre ; I have not seen it elsewhere..

**Comment by fchapoton** [comment]
du coup, je prefere reparer le linter ici..

**Review by dcoudert — APPROVED** [review]
ok. LGTM.

**Comment by dcoudert** [comment]
May be you should add tad `CI Fix` to this PR to make it applied to other PRs ? this would avoid reporting the same lint errors in all PRs.

**Comment by fchapoton** [comment]
I dare not. Maybe there are now "rules" to do that. I have no idea.

**Pull request merged**
