### PR TITLE
Relative to absolute imports, `del lazy_import` in `.all` files

### PR DESCRIPTION
**Pull request by mkoeppe**
- Split out from #37900

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Already reviewed 6 months ago in https://github.com/sagemath/sage/pull/36676

**Comment by jhpalmieri** [comment]
It looks good. As long as it passes tests, feel free to set a positive review on my behalf. Some all.py files do not have `del lazy_import` but they can be dealt with later as part of #36721.

**Comment by mkoeppe** [comment]
> Some all.py files do not have `del lazy_import` but they can be dealt with later

Yes, here I have only picked those `del lazy_import` additions in files that had other changes already, to keep the PR smaller.

**Comment by mkoeppe** [comment]
Thanks (again) for the review. Tests pass (see Build&Test using Conda -- Build&Test is fixed in #37926 + #37988).

**Comment by jhpalmieri** [comment]
> > Some all.py files do not have `del lazy_import` but they can be dealt with later
> 
> Yes, here I have only picked those `del lazy_import` additions in files that had other changes already, to keep the PR smaller.

Right, but I also meant files like combinat/all.py which are changed here. But again, those can wait.

**Comment by mkoeppe** [comment]
Right, thanks.

**Pull request merged**
