### PR TITLE
PDF docbuild: Reduce verbosity

### LINKED ISSUE #36706: `make doc-pdf`: Reduce output
Building the PDF documentation creates an excessive amount of log output: half a million lines, 55 MB. In particular in the GH Actions CI it is impractical to view the log in the browser, even as a raw log.

We should silence the pdflatex runs so that only errors are displayed.

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #36706

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by grhkm21** [comment]
Do you mind explaining what type of messages are not logged anymore? Comparing the PDF docbuild of this PR compared to one from three weeks ago, the number of lines reduced by 95%, so that's nice.

**Comment by mkoeppe** [comment]
It's using tex's `\batchmode`, which suppresses everything on the terminal. It still goes to the log file. And tex is invoked by latexmk here, which goes through the log and shows the errors.

I haven't really tested what happens if I provoke errors.

**Comment by kwankyu** [comment]
> It's using tex's `\batchmode`, which suppresses everything on the terminal. It still goes to the log file. And tex is invoked by latexmk here, which goes through the log and shows the errors.
> 
> I haven't really tested what happens if I provoke errors.

I did. Errors are reported 
```
...
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'topology.log' for details
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
make: *** [topology.pdf] Error 12
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kwankyu/GitHub/sage-dev/src/sage_docbuild/__main__.py", line 509, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/kwankyu/GitHub/sage-dev/src/sage_docbuild/__main__.py", line 505, in main
    builder()
  File "/Users/kwankyu/GitHub/sage-dev/src/sage_docbuild/builders.py", line 300, in pdf
    raise RuntimeError(error_message % (command, tex_dir))
RuntimeError: failed to run $MAKE all-pdf in /Users/kwankyu/GitHub/sage-dev/local/share/doc/sage/latex/en/reference/topology

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
```
and you can see the errors in the log file `topology.log`.

**Comment by kwankyu** [comment]
These added options not only reduce verbosity but speed up the compiling process. Very nice.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
