### PR TITLE
Remove jupyter_execute directory after doc build finishes

### PR DESCRIPTION
**Pull request by kwankyu**
as discussed in https://groups.google.com/g/sage-devel/c/YbaVbz_y_xY

Along the way, a bug in the doc-build workflow is fixed.

Test: https://doc-pr-38895--sagemath.netlify.app/html/en/jupyter_execute/latex.py (should not exist)

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mantepse** [comment]
How could I check this, or can I just trust?

**Comment by kwankyu** [comment]
The test in the description shows that the fix works well.

**Review by mantepse — APPROVED** [review]
Trusting the bots.

**Comment by kwankyu** [comment]
Thanks!

**Comment by kwankyu** [comment]
rebased and fixed.

**Pull request merged**
