### PR TITLE
Fix index out of range exception (#35031)

### LINKED ISSUE #35031: arrow((0,0), (0,0), linestyle='dashed') raises list index out of range
With SageMath version 9.8.beta1, Release Date: 2022-09-29, this works:

```
sage: arrow((0,0), (0,0))
Launched png viewer for Graphics object consisting of 1 graphics primitive
```

but this is broken:

```
sage: arrow((0,0), (0,0), linestyle='dashed')
/home/slabbe/GitBox/sage/src/sage/repl/rich_output/display_manager.py:610: RichReprWarning: Exception in _rich_repr_ while displaying object: list index out of range
  warnings.warn(
Graphics object consisting of 1 graphics primitive
```

### PR DESCRIPTION
**Pull request by sheerluck**
### 📚 Description
We return False if there is no n-th path

Closes #35031 

### 📝 Checklist

- [X] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [X] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by videlec** [comment]
Thanks for the bug fix. You must add a doctest that shows that the error is indeed corrected. Ideally this would go inside a TESTS block such as this example taken from `complex_mpfr.pyx`
```
         Check that :trac:`14989` is fixed::

            sage: QQi = NumberField(x^2+1, 'i', embedding=CC(0,1))
            sage: i = QQi.order(QQi.gen()).gen(1)
            sage: CC(i)
            1.00000000000000*I
```
See https://doc.sagemath.org/html/en/developer/coding_basics.html for the formatting of docstrings.

**Comment by videlec** [comment]
Your example already "works" fine on sage 9.5 (in the sense that it does return `Launched png viewer for Graphics object consisting of 1 graphics primitive`). On which sage version is it supposed to fail?

**Comment by videlec** [comment]
Do you mean to use `arrow((0,0), (0,0), linestyle='dashed')` as in the issue?

**Comment by sheerluck** [comment]
> Do you mean to use `arrow((0,0), (0,0), linestyle='dashed')` as in the issue?

I made a mistake but then force pushed correct version

**Comment by videlec** [comment]
> > Do you mean to use `arrow((0,0), (0,0), linestyle='dashed')` as in the issue?
> 
> I made a mistake but then force pushed correct version

Looks better now :)

**Comment by videlec** [comment]
Just waiting for the CI before giving a positive review.

**Comment by seblabbe** [comment]
I see that the Build & Test is failing, but the error:
```
----------------------------------------------------------------------
sage -t --random-seed=225549214259244020593978072013798380016 doc/ca/intro/index.rst  # 1 doctest failed
----------------------------------------------------------------------
```
is not related to this ticket.

**Review by seblabbe — APPROVED** [review]
Changes look good to me.

**Pull request merged**
