### PR TITLE
Upgrade pplpy to 0.8.9

### PR DESCRIPTION
**Pull request by videlec**
Upgrade the standard package pplpy to version 0.8.9 (released on PyPI https://pypi.org/project/pplpy/0.8.9/)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Lots of test failures

**Comment by videlec** [comment]
> Lots of test failures

Indeed. I do not know what happens. It looks like that the Cython compilation happened with language_level=2.

**Comment by antonio-rojas** [comment]
The failures have nothing to do with cython, it's an actual bug in pplpy introduced in https://github.com/sagemath/pplpy/commit/5fa3580c31f0c2ebb425073eec9075cf83485539

More precisely, in the `Linear_Expression` constructor with two arguments, there is a bool check for the first argument. If this evaluates to `false` (like it happens, for instance, with `a=Cone([(0,0)])._lattice(0)`), then `space_dimension` is never set, which is what is causing most of the test failures.

**Comment by videlec** [comment]
> Many of the failures have nothing to do with cython, it's an actual bug in pplpy introduced in [sagemath/pplpy@5fa3580](https://github.com/sagemath/pplpy/commit/5fa3580c31f0c2ebb425073eec9075cf83485539)
> 
> More precisely, in the `Linear_Expression` constructor with two arguments, there is a bool check for the first argument. If this evaluates to `false` (like it happens, for instance, with `a=Cone([(0,0)])._lattice(0)`, then `space_dimension` is never set, which is what is causing most of the test failures.

Indeed, `bool([0, 0])` and `bool(vector([0, 0]))` behave differently! Thanks.

**Comment by antonio-rojas** [comment]
The failures in `sage/geometry/lattice_polytope.py`, `sage/geometry/polyhedron/backend_ppl.py`, `sage/geometry/polyhedron/ppl_lattice_polytope.py` and the first failure in `sage/geometry/cone.py` are caused by https://github.com/sagemath/pplpy/commit/3ed9df498c3febd8796716bc647aaca13e8d8044, but not by the change in Cython language level, but rather by the `__mul__` change in the `Variable` class

**Comment by videlec** [comment]
> The failures in `sage/geometry/lattice_polytope.py`, `sage/geometry/polyhedron/backend_ppl.py`, `sage/geometry/polyhedron/ppl_lattice_polytope.py` and the first failure in `sage/geometry/cone.py` are caused by [sagemath/pplpy@3ed9df4](https://github.com/sagemath/pplpy/commit/3ed9df498c3febd8796716bc647aaca13e8d8044), but not by the change in Cython language level, but rather by the `__mul__` change in the `Variable` class

Hmm... this should have been catched by the pplpy doctest (https://github.com/sagemath/pplpy/blob/master/ppl/linear_algebra.pyx#L1192)
```python
>>> from ppl import Variable
>>> from gmpy2 import mpz
>>> x = Variable(0)
>>> mpz(3) * x * mpz(5)
```

**Comment by videlec** [comment]
> 

I indeed misinterpreted https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#arithmetic-methods (which affects `__add__` but not `__mul__`).

**Comment by videlec** [comment]
> > 
> 
> I indeed misinterpreted https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#arithmetic-methods (which affects `__add__` but not `__mul__`).

This was correctly interpreted, but works only with Cython>=3.0.0 which is not the default version in sage. This explains why doctests pass in conda.

**Comment by videlec** [comment]
Hopefully fixed in https://github.com/sagemath/pplpy/pull/27

**Comment by antonio-rojas** [comment]
Can confirm that it fixes all issues in the downstream Arch sage package

**Pull request merged**
