### PR TITLE
Fix conda environments after `build` was removed from conda-forge in favor of `python-build`

### LINKED ISSUE #38550: Conda environment files are outdated after `build` was removed from conda-forge in favor of `python-build`
### Steps To Reproduce

On Ubuntu 22.04 with the recommended Miniforge we get:

```
$ conda env create --file src/environment-dev-3.11-linux.yml --name sage-dev
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - build==0.7.0=pyhd8ed1ab_0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

### Expected Behavior

The SageMath environment is created.

### Actual Behavior

The SageMath environment is not created.

### Additional Information

See

- [Removing build in favor of python-build](https://conda-forge.org/news/2024/08/21/remove-build/)
- https://github.com/conda-forge/conda-forge.github.io/issues/2269

Simply replacing `build` by `python-build` works to fix the environment.

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: `develop`
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by rburing**
- Fixes https://github.com/sagemath/sage/issues/38550

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

None.

### CODE REVIEW

**Comment by mkoeppe** [comment]
The correct way to do this is to first update `build/pkgs/python_build/distros/conda.txt` (and then to run `tox -e update_conda_lock`)

**Comment by rburing** [comment]
@mkoeppe Should all the unrelated changes resulting from that command be included as well, or not?

**Comment by mkoeppe** [comment]
The scope of the PR is up to you, but a general update would certainly be welcome. In any case, it would be a good idea to run the full conda platform test by manually invoking the "CI Conda" GH Actions workflow in your fork.

**Comment by rburing** [comment]
@mkoeppe I'll give it a try. The workflow is running.

**Comment by rburing** [comment]
On second thought (build failures), I would prefer to keep it simple here.

**Comment by mkoeppe** [comment]
No problem, a whole bunch of updates are coming in anyway soon that will require us to update the conda-lock files again.

**Comment by mkoeppe** [comment]
> In any case, it would be a good idea to run the full conda platform test by manually invoking the "CI Conda" GH Actions workflow in your fork.

When there's a successful run, please post a link

**Comment by rburing** [comment]
Here's the current run: https://github.com/rburing/sage/actions/runs/10529188299

I don't see what I can do in this PR to make it succeed, the errors all look unrelated.

**Comment by tobiasdiez** [comment]
Thanks, LGTM.

The version check fail already since https://github.com/sagemath/sage/commit/95428a1c31939d8159fbce8fb0384fa26f0470fe by @mkoeppe. Would be awesome if you could fix it Matthias!

**Comment by tobiasdiez** [comment]
> It's a downstream problem.

Sure, an unnecessarily strict version constraint is a downstream issue 😄. Let me help you: https://github.com/sagemath/sage/pull/38556

**Comment by mkoeppe** [comment]
I'll explain it to you again: The flaw lies in the design of the conda setup, which insists on having suitable conda packages available - which is outside of the scope of the Sage project.

**Comment by mkoeppe** [comment]
What you need to do is work with downstream to package the current version of the package.

**Pull request merged**
