### PR TITLE
Remove the pycygwin package

### PR DESCRIPTION
**Pull request by orlitzky**
It was only needed for Cygwin (to handle path conversions), and we're dropping Cygwin support for real now.

Depends on #36769

### CODE REVIEW

**Review by dimpase — APPROVED** [review]
lgtm

I didn't notice that, so I started removing this on the previous PR, sorry

**Comment by orlitzky** [comment]
No problem, I'm only splitting them to make it easier to review, so if you want to do it all at once with a flaming sword that's OK with me too.

**Comment by tornaria** [comment]
Please rebase on top of #36769.

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by vbraun** [comment]
merge conflict

**Comment by vbraun** [comment]
merge conflict

**Comment by dimpase** [comment]
> merge conflict

 #36769 isn't yet in develop - how am I supposed to deal with this?

**Comment by mkoeppe** [comment]
rebased

**Comment by mkoeppe** [comment]
There's still some leftover cygwin stuff in src/sage/interfaces/jmoldata.py

**Comment by vbraun** [comment]
```
make[1]: *** No rule to make target 'arb'.  Stop.
```

**Comment by dimpase** [comment]
should be ok now

**Pull request merged**
