### PR TITLE
.github/workflows/doc-build.yml: Repair display of changes

### PR DESCRIPTION
**Pull request by mkoeppe**
From https://github.com/sagemath/sage/pull/36473#discussion_r1362509153

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36473 (merged here)
- Depends on #36442 (merged here)

### CODE REVIEW

**Comment by kwankyu** [comment]
As you pointed out, this is due to the change of using mathjax cdns from 10.2.beta1 and, as I understand it, should have been transient hiccups if ci didn't fail to build images of 10.2.beta2~5 (is this also because of the change?). Now that the images of 10.2.beta6 and beta7 are available, the problem will disappear. Then do we need this fix?

**Comment by mkoeppe** [comment]
The change (in #36160) was done by setting an environment variable in the doc-build workflow. 

The Docker images however are built with the default configuration, without this environment variable set. (I don't know if/why that should be changed.)

**Comment by kwankyu** [comment]
I see. This is a tricky situation.

How about comparing the built doc with the previous doc which was built in the previous run of the build doc workflow on the push to develop branch and stored somewhere?

**Comment by kwankyu** [comment]
The current approach is easy and quick but prone to be broken again someday (when we upgrade mathjax).

**Comment by mkoeppe** [comment]
> How about comparing the built doc with the previous doc which was built in the previous run of the build doc workflow on the push to develop branch and stored somewhere?

Sure, another possible solution, but I don't think it would be more robust

**Comment by mkoeppe** [comment]
OK, here's a better version that avoids duplicating that specific CDN URL.

I've also made the change discussed in https://github.com/sagemath/sage/pull/36473#issuecomment-1766872361, which gives a cleaner log

**Review by kwankyu — APPROVED** [review]
LGTM.

I am preparing a PR building on this.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
