### PR TITLE
Revert to non-incremental docbuild

### PR DESCRIPTION
**Pull request by tobiasdiez**
The doc build workflow currently fails because it runs out of space (e.g https://github.com/sagemath/sage/actions/runs/6527955359/job/17723528313?pr=36466). The incremental build before is also not really working, as the sagelib is still built again. We remove the incremental build for now, until https://github.com/sagemath/sage/pull/36459, and use an older image for now.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
@mkoeppe ?

**Comment by mkoeppe** [comment]
That the docbuild rebuilds sagelib from scratch after the incremental build is not a malfunction. It was requested in #35652, where the incremental building was added.

**Comment by mkoeppe** [comment]
The out of space condition was likely triggered by changes in the GitHub runner images, not on our side. 
Our technique to free disk space (before or after #36418) unfortunately does not apply to workflow jobs that use the `container` keyword. 
We probably have to rewrite these jobs using an explicit use of docker instead.

**Comment by kwankyu** [comment]
> That the docbuild rebuilds sagelib from scratch after the incremental build is not a malfunction. It was requested in #35652, where the incremental building was added.

Do you mean this: https://github.com/sagemath/sage/pull/35652#discussion_r1226297344 ?

There I suggested to rebuild doc from scratch, not sagelib from scratch...

**Comment by mkoeppe** [comment]
> Do you mean this: [#35652 (comment)](https://github.com/sagemath/sage/pull/35652#discussion_r1226297344) ?

Yes

> There I suggested to rebuild doc from scratch, not sagelib from scratch...

Re-reading it now, I think I misunderstood what you wanted.

**Comment by kwankyu** [comment]
I didn't know that you misunderstood. From
```
make doc-clean doc-uninstall sagelib-clean && git clean -fx src/sage && ./config.status && make doc-html
```
`sagelib-clean && git clean -fx src/sage` causes rebuilding `sagelib` from scratch?

**Comment by mkoeppe** [comment]
Yes. I'm revising it in #36473

**Comment by tobiasdiez** [comment]
> The out of space condition was likely triggered by changes in the GitHub runner images, not on our side. 

Right, it's still not working even with the old beta 1 image. Any idea how to fix it and what takes up so much space?

Closing this now as https://github.com/sagemath/sage/pull/36473 is a better solution.

**Pull request closed without merging**
