### PR TITLE
Update doctests depending on `sirocco`

### PR DESCRIPTION
**Pull request by mkoeppe**
After #35661 was merged, doctests depending some optional packages are being tested in the Build & Test CI.

This reveals some changes / non-unique results of doctests involving `sirocco`.
Previously discussed in https://github.com/sagemath/sage/pull/35661#issuecomment-1556569925

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by enriqueartal** [comment]
Concerning https://github.com/sagemath/sage/pull/36022/commits/c4ff80b52d40d31105f31fdf238cec30f2e28ff7, the simplification is not completely deterministic, sometimes I had a correct presentation but distinct from the test. I did not find documentation about how `# random` behaves.

It is more subtle for https://github.com/sagemath/sage/pull/36022/commits/d99d0080570d676e24d75de1a84fb0a79bb9e80d. When I started the issue https://github.com/sagemath/sage/issues/34415, some changes provoked this new result. The test works fine in `10.0` and gives the error behind this patch in `10.1beta8`. I wonder if the problem is related with some numeric issues, some change may explain it? 

Anyway, the PR https://github.com/sagemath/sage/pull/35376, merged with the `10.1beta8` does not give the error; the inputs of `braid_in_segment` are now Gauss rational approximations of the algebraic numbers instead of elements in `CC`.

**Comment by tscrim** [comment]
You will have some merge conflicts to resolve.

After that, regarding `# random`; it only fails if the doctest fails. It doesn't check the outputs match. If something is nondeterministic, then you should document this and have a doctest that is testing some behavior that is expected (as opposed to just the output; e.g., the cardinality of a group).

**Comment by enriqueartal** [comment]
This test has been changed in develop. Instead of checking if the presentation is equal, as the result is known and it is a finite group, the isomorphism is checked.

**Comment by mkoeppe** [comment]
If I understand the situation correctly, this PR is not needed any more. Closing it

**Pull request closed without merging**
