### PR TITLE
Implement quick fix for absolute length for non-finite Coxeter groups

### PR DESCRIPTION
**Pull request by thecaligarmo**
Implement a quick fix for absolute length in non-finite Coxeter groups

Puts in a temporary fix for #36174 . The issue of fixing absolute length in sagemath is turning out to be a little more complicated than previously assumed. So until a proper fix can be put in place, this PR removes the ability to calculate the absolute length for Coxeter groups which are not finite (as the number being produced is wrong). 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

#36174

### CODE REVIEW

**Comment by tscrim** [comment]
What about general types? I don't think we should disable this in general, but rather raise a warning to the user to be careful.

**Comment by thecaligarmo** [comment]
I mean, as far as I'm aware, it's only true in finite types (the dimension definition). So (currently) there is no accurate/correct way to give absolute length for elements coming from non-finite groups. By "warning" do you mean like a warning error rather than a not implemented error? (I'm looking at the other comment you had made on the other issue now. This could be null and moot cause it looks like the other option is fast enough that we can just implement that instead without needing a quick fix. I hadn't seen that article)

**Comment by tscrim** [comment]
I was thinking of something like “warning(“don’t trust this”),” albeit with a more descriptive message of course.

As you said, the proposed general fix on #36174 would make this moot. I would keep the current implementation for finite types. Perhaps for “long” words, wrt some reasonable cutoff based on some testing, switching between the two algorithms, but that might be more complicated than needed though (and implementation dependent, which would make the cutoff somewhat arbitrary and require a length computation, making it more expensive than just doing the current implementation).

**Comment by thecaligarmo** [comment]
Closing this pull request as it is no longer needed.

**Pull request closed without merging**
