### PR TITLE
Allow python ints in sage.groups.generic.has_order

### LINKED ISSUE #38708: `has_order()` errors out when the given order has type `int`
### Steps To Reproduce

Example:
```
from sage.groups.generic import has_order
has_order(Mod(2,3),int(2),operation='*')
```

### Expected Behavior

Should work similarly to `has_order(Mod(2,3),ZZ(2),operation='*')`.

### Actual Behavior

It errors out with

> TypeError: object of type 'int' has no len()

### Additional Information

_No response_

### Environment

- **OS**: Ubuntu 24.04.1 LTS
- **Sage Version**:  10.5.beta3

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by DaveWitteMorris**
Fixes #38708.

We revise `sage.groups.generic.has_order` to allow the argument `n` to be any integer (including a python `int`), not only a sage integer.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

None.

### CODE REVIEW

**Comment by DaveWitteMorris** [comment]
This PR causes a doctest failure:
```
sage -t --long --warn-long 30.0 --random-seed=286735480429121101562228604801325644303 src/sage/schemes/elliptic_curves/ell_point.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_point.py", line 589, in sage.schemes.elliptic_curves.ell_point.?.has_order
Failed example:
    E(0).has_order(Factorization([]))
Exception raised:
    Traceback (most recent call last):
      File "/Users/dmorris/development/sage/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dmorris/development/sage/src/sage/doctest/forker.py", line 1136, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_point.?.has_order[12]>", line 1, in <module>
        E(Integer(0)).has_order(Factorization([]))
      File "/Users/dmorris/development/sage/src/sage/schemes/elliptic_curves/ell_point.py", line 596, in has_order
        ret = generic.has_order(self, n, operation='+')
      File "/Users/dmorris/development/sage/src/sage/groups/generic.py", line 1516, in has_order
        n = integer_ring.ZZ(n)
      File "sage/structure/parent.pyx", line 901, in sage.structure.parent.Parent.__call__
        return mor._call_(x)
      File "sage/structure/coerce_maps.pyx", line 164, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        raise
      File "sage/structure/coerce_maps.pyx", line 159, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_
        return C._element_constructor(x)
      File "sage/rings/integer.pyx", line 723, in sage.rings.integer.Integer.__init__
        raise TypeError("unable to coerce %s to an integer" % type(x))
    TypeError: unable to coerce <class 'sage.structure.factorization.Factorization'> to an integer
```

**Comment by DaveWitteMorris** [comment]
The documentation states that the input should be either an integer or in the class `sage.structure.factorization.Factorization`. The original PR required a more specific type of factorization, which caused the doctest failure. My bad.

**Comment by user202729** [comment]
Not sure if `ZZ(...)` is a good idea. Most of the code I can see use `isinstance()` instead.

> Ouch! No, don't do that!! QQ(pi.n()) yields a rational number! Conversion can really mean "is there any way in which you could interpret this as an element of ..."? Perhaps try to coerce in to QQ, but in this case you're really looking at the "action" of QQ via exponentiation. There could be other actions. Can't you just let the coercion system figure out what type your exponent should have?

— https://github.com/sagemath/sage/pull/38362#issuecomment-2325689726

Though for ZZ instead of QQ I'm not sure if there's any bad side effect.

**Comment by DaveWitteMorris** [comment]
I think `ZZ(the input)` is a pretty standard idiom for situations such as this where the input is supposed to be an integer.

**Review by yyyyx4 — APPROVED** [review]
Looks great, thanks!

**Comment by DaveWitteMorris** [comment]
Thanks for the review!

**Pull request merged**
