### PR TITLE
Updated README.md,  added space after -p option

### PR DESCRIPTION
**Pull request by explorest**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
please explain in the PR description why this is an improvement

**Comment by explorest** [comment]
Standard syntax of publishing option is to have a space after --publish or -p and before the subsequent ip or port. [Docker's official documentation is very clear and consistent on this](https://docs.docker.com/reference/cli/docker/container/run/#publish) 
Having a space (or an equality sign) between an option's key and its value are universal best practices -- not just on docker's CLI -- but across the industry. It is very unusual , if not outright buggy, to not have a separator ( either a space or an equality) between the key and value on command line.

**Review by mkoeppe — APPROVED** [review]
Thanks.

**Comment by explorest** [comment]
Sir @mkoeppe  I have no idea what's happening to this pull request. Is it in progress, waiting for something , do I have to do something ??   Sorry to bother you , I am not very fluent with github. Its so confusing.

**Comment by mkoeppe** [comment]
No action needed. The label "s: positive review" means that the release manager will be merging it.

**Pull request merged**
