### PR TITLE
`sage.features`: Add `sage.libs.singular`, features for standard Python packages

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description
This is for the modularization effort, in particular:
- #35095 

We also add missing copyright headers and update existing copyrights in `sage.features`.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
LGTM.

But why these feature files lack the usual heading of sage files?

**Review by kwankyu — APPROVED** [review]

**Comment by kwankyu** [comment]
Thanks. I am waiting for B&T for sanity.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
```
sage -t --long --warn-long 39.2 --random-seed=123 src/sage/interfaces/r.py
**********************************************************************
File "src/sage/interfaces/r.py", line 697, in sage.interfaces.r.R.__reduce__
Failed example:
    rlr, t = r.__reduce__()  # optional - rpy2
Exception raised:
    Traceback (most recent call last):
      File "/home/release/Sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/release/Sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.r.R.__reduce__[0]>", line 1, in <module>
        rlr, t = r.__reduce__()  # optional - rpy2
                 ^^^^^^^^^^^^^^
      File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/copyreg.py", line 76, in _reduce_ex
        raise TypeError(f"cannot pickle {cls.__name__!r} object")
    TypeError: cannot pickle 'LazyImport' object
**********************************************************************
```

**Comment by mkoeppe** [comment]
I don't think this is related to the changes here.

Perhaps you installed R on a test machine and this is the first time that rpy2 tests are tested?

**Comment by mkoeppe** [comment]
Doctest failures because deprecation warnings for the same `lazy_import` are now issued separately for each doctest.

**Comment by mkoeppe** [comment]
I have deferred the work to fix the rpy2 test failures to #35396.

As a quick fix for this PR, 9990302 just removes the `rpy2` feature detection again.

**Pull request merged**
