### PR TITLE
.github/workflows/docker.yml: Interrupt the build before the 6 hour cancellation

### PR DESCRIPTION
**Pull request by mkoeppe**
When a CI Linux workflow is canceled, because we are using `docker build`, no image is written out.

Here we add an input parameter `timeout`, defaulting to 5.5 hours, after which we kill the  `make` process inside of the build container.
Then our script (in tox) writes out and pushes an image (marked as "-failed") to ghcr.io, enabling better diagnostics.

See https://github.com/mkoeppe/sage/actions/runs/6831246509/job/18580446041 for a test run where for demonstration purposes I set the timeout to 6 minutes.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
Is this for workflow that is canceled by timeout? Does this allow to investigate the image (with `-failed`) for the cause of timeout? Is there other (real) use cases?

**Comment by mkoeppe** [comment]
> Is this for workflow that is canceled by timeout? Does this allow to investigate the image (with `-failed`) for the cause of timeout? Is there other (real) use cases?

Yes, the main use case is for debugging these timeouts. But I could also imagine using it to get earlier access to the image of a failing build.

**Review by kwankyu — APPROVED** [review]
OK.

**Comment by mkoeppe** [comment]
Thanks... but it wasn't ready for review; it doesn't work yet

**Comment by kwankyu** [comment]
Ah, sorry. 

> Thanks... but it wasn't ready for review; 

Ah, sorry. 

> it doesn't work yet

The code doesn't work? Or do you plan to do more?

**Comment by mkoeppe** [comment]
This approach works locally as described, but in GH Actions the runner dies too quickly. I'll have to make changes and experiments

**Comment by kwankyu** [comment]
Isn't `always()` for this case?

**Comment by mkoeppe** [comment]
It's possible that I may be making a stupid mistake in setting up the trap in this step. I cannot see any sign of it being triggered.

Help with this is very welcome!

**Comment by mkoeppe** [comment]
I've switched to a simpler approach, suitable for the main use case.

**Review by kwankyu — APPROVED** [review]
OK, if it works for you.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by mkoeppe** [comment]
Rebased onto the proper rc2.

**Comment by mkoeppe** [comment]
Setting to blocker because there are more build hangs, possibly from contourpy, in https://github.com/sagemath/sage/actions/runs/6842945144/job/18611623959#step:11:1932, https://github.com/sagemath/sage/actions/runs/6842945144/job/18611622942#step:11:2109, https://github.com/sagemath/sage/actions/runs/6842945144/job/18611624721

**Pull request merged**
