### PR TITLE
`configure`: Fix "command not found" error after #36776

### PR DESCRIPTION
**Pull request by mkoeppe**
As reported in https://groups.google.com/g/sage-devel/c/8ZsBcHGmn6s @culler

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
@orlitzky Please review

**Comment by orlitzky** [comment]
I'm not wasting an hour testing packages that do nothing. Just delete them already.

**Comment by culler** [comment]
Using this PR I ran ./bootstrap and ./configure on an Intel mac mini running 14.4.1 with autoconf installed.  There were no "command not found" messages.

**Comment by mkoeppe** [comment]
Thanks for testing!

**Pull request merged**
