### PR TITLE
Update numpy to 1.24.3

### LINKED ISSUE #34816: Update numpy to 1.26
<div id="comment:0"></div>

https://github.com/numpy/numpy/releases

1.26.0.b1 is out, with Python 3.12 support and Cython 3 compatibility.

- Depends on #35404 

CC:  @antonio-rojas @kiwifb @tornaria

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/34816_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

NumPy 1.24.x still supports Python 3.8 (see #35404).
https://github.com/numpy/numpy/releases

Closes #34816

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### ⌛ Dependencies

- Depends on #35438

### CODE REVIEW

**Comment by mkoeppe** [comment]
@tornaria #34994 is merged here, but it looks like we need to take care of doctest failures due to `FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.` etc.

**Comment by tornaria** [comment]
> @tornaria #34994 is merged here, but it looks like we need to take care of doctest failures due to `FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.` etc.

I upgraded to numpy 1.24.2 last week and I did not get any of these failures. Also, the backtraces seem to point to pythran, not sagemath, I don't install pythran with sagemath (should I? what am I missing?).

At some point I was starting to like python 3, but they really make an effort to show up. Sometimes it seems half the work is dealing with deprecation sh*t.

**Comment by tornaria** [comment]
I installed pythran (we are on 0.12.1). Now I get stuff like
```
    DeprecationWarning: msvccompiler is deprecated and slated to be removed in the future. Please discontinue use or file an issue with pypa/distutils describing your use case.
```
No, I don't have msvc installed here, thank you very much. Uninstalling pythran.

I abhor programs that change behaviour just because some library is installed.

Also, we have these lines in `src/sage/alll.py`:
```
# Ignore numpy warnings triggered by pythran
warnings.filterwarnings('ignore', category=DeprecationWarning,
                        module='pythran
```
Shouldn't that apply? Btw, that's the only reference to pythran in the sage library. Why is then installing pythran having any effect at all?

**Comment by mkoeppe** [comment]
I'm throwing in an update of pythran to see if that helps

**Comment by mkoeppe** [comment]
Yes, that fixed it.

**Comment by kiwifb** [comment]
This now "conflicts" with #34994 which includes all the doctests fixes I think. That PR is in Volker's current merge tree. I was wondering why I could not see the fortran warnings anymore. I would support the upgrade once #34994 is merged.

**Comment by kiwifb** [comment]
The stuff in here (or #34994)  doesn't fix
```
sage -t --random-seed=208794765845619979520719224489586219359 src/sage/plot/plot_field.py
**********************************************************************
File "src/sage/plot/plot_field.py", line 51, in sage.plot.plot_field.PlotField.__init__
Failed example:
    r.yvec_array
Expected:
    masked_array(data=[0.0, 0.70710678118..., 0.70710678118...,
                       0.89442719...],
                 mask=[False, False, False, False],
           fill_value=1e+20)
Got:
    masked_array(data=[0.        , 0.70710678, 0.70710678, 0.89442719],
                 mask=False,
           fill_value=1e+20)
```
and at least one similar failure in `sage/plot/streamline_plot.py`. Has it been attributed to something else?

**Comment by tornaria** [comment]
> The stuff in here (or #34994) doesn't fix
> 
> ```
> sage -t --random-seed=208794765845619979520719224489586219359 src/sage/plot/plot_field.py
> **********************************************************************
> File "src/sage/plot/plot_field.py", line 51, in sage.plot.plot_field.PlotField.__init__
> Failed example:
>     r.yvec_array
> Expected:
>     masked_array(data=[0.0, 0.70710678118..., 0.70710678118...,
>                        0.89442719...],
>                  mask=[False, False, False, False],
>            fill_value=1e+20)
> Got:
>     masked_array(data=[0.        , 0.70710678, 0.70710678, 0.89442719],
>                  mask=False,
>            fill_value=1e+20)
> ```
> 
> and at least one similar failure in `sage/plot/streamline_plot.py`. Has it been attributed to something else?

I never saw anything like that.

**Comment by mkoeppe** [comment]
I've redone the branch on top of current #34994.

**Comment by kiwifb** [comment]
@tornaria pythran is a dependency of scipy, but it may not be useful at runtime as it is similar to cython as far as I can see. It is possible that the formatting in plot_field.py is coming from something else, but then what? And it was spotted as far back as December.

**Comment by kiwifb** [comment]
`src/sage/plot/plot_field.py` and `sage/plot/streamline_plot.py` formatting issues have disappeared by going from numpy 1.24.0 to 1.24.2. I was still on 1.24.0.

**Comment by tornaria** [comment]
For the record, I pushed #35438 to ignore all the deprecation warnings that I see when installing pythran (python 3.11, setuptools 67.6.1, numpy 1.24.2).

I can't really review the current PR since it's only changing a spkg, but FWIW I've been using 1.24.2 for a while without any trouble after #34994.

**Review by kiwifb — APPROVED** [review]
I have now been using 1.24.2 since the end of February without noticeable problems because of it.

**Comment by mkoeppe** [comment]
I've merged #35438 just in case.

**Comment by mkoeppe** [comment]
1.24.3 is out

**Comment by mkoeppe** [comment]
numpy 1.25.0 is out, which supports Python 3.9–3.11, but not the upcoming 3.12. https://numpy.org/devdocs/release/1.25.0-notes.html
A version 1.26 is promised to provide Python 3.12 support.

**Comment by mkoeppe** [comment]
v1.26.0b1 is out, with Python 3.12 support and Cython 3 compatibility (see #36110).

Let's skip this update and do 1.26

**Pull request closed without merging**
