### PR TITLE
Reduce number of systems test with minimal config

### PR DESCRIPTION
**Pull request by tobiasdiez**
Alternative solution for #36726. Since the purpose of the "minimal" ci runs is to check the documentation of the minimal build requirements, it is overkill to run it for all systems. Thus, we only run it for "ubuntu-focal", which is also the default system for PRs.

This also hugely reduces the load of onto the ci, somewhat leviating the issues introduced by #36616 (see eg https://github.com/sagemath/sage/pull/36616#issuecomment-1821110707).

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dimpase — APPROVED** [review]
lgtm, thanks

**Comment by mkoeppe** [comment]
This is just vandalism.

**Comment by dimpase** [comment]
no, your minimal configurations are vandalism.

**Comment by mkoeppe** [comment]
> no, your minimal configurations are vandalism.

@dimpase How so?

https://github.com/sagemath/sage/pull/36726#issuecomment-1864029069

**Comment by dimpase** [comment]
cause it's vandalism to test on CI 1000s times something big and stable, like building a particular version of gcc/gfortran, on the same systems - on which this gcc/gfortran is absolutely not needed.

This is basically burning money.

**Comment by mkoeppe** [comment]
What you are describing does not fit the definition of "vandalism" at all. 

I'll take it as a reflexive reaction, a "no, you are" comeback.

**Comment by dimpase** [comment]
well, pick up your favourite term for doing meaningless, time-consuming, and potentially expensive stuff, and forcing other people to help you with it.

**Comment by mkoeppe** [comment]
@vbraun Please back this out

**Comment by mkoeppe** [comment]
> well, pick up your favourite term for doing meaningless, time-consuming, and potentially expensive stuff, and forcing other people to help you with it.

@dimpase I called you out clearly for making such denunciations, which are clear CoC violations. https://github.com/sagemath/sage/pull/36726#issuecomment-1864029069
How do you justify this continued misconduct?

**Comment by dimpase** [comment]
@mkoeppe - have you read @jhpalmieri 's email?

**Comment by mkoeppe** [comment]
@dimpase Yes. How do you justify your continued severe misconduct?

**Comment by roed314** [comment]
This PR is an appropriate reaction to #36726.  It removes CI testing for all Linux distros except one version of Ubuntu (which happens to have pkill).  It is an extreme solution to a problem that is already solved.   Reducing testing to only one distro is something that should obviously be discussed and voted on sage-devel.  A civil discussion on sage-devel of the pros and cons of different approaches to CI testing of sage would be valuable; this is not.

**Pull request closed without merging**
