### PR TITLE
To determine GAP_SO sage.env looks for libgap.so but it should look for libgap.so*

### LINKED ISSUE #33446: To determine `GAP_SO` sage.env looks for `libgap.so` but it should look for `libgap.so*`
<div id="comment:0"></div>

My system (void linux) only has

```
$ ls -l /usr/lib/libgap.so*
lrwxrwxrwx 1 root root      15 Jan 14 11:14 /usr/lib/libgap.so.0 -> libgap.so.0.0.0
-rwxr-xr-x 1 root root 2080920 Jan 14 11:14 /usr/lib/libgap.so.0.0.0
```
installed. Indeed, the symlink `/usr/lib/libgap.so -> libgap.so.0.0.0` is shipped in `gap-devel` which is not needed to run sagemath at all.

This is because the implementation of the function `sage.env._get_shared_lib_path()` will look for `libgap.so` instead of `libgap.so*`. The fix is trivial:

```
--- a/src/sage/env.py
+++ b/src/sage/env.py
@@ -293,7 +293,7 @@ def _get_shared_lib_path(*libnames: str) -> Optional[str]:
             if sys.platform == 'darwin':
                 ext = 'dylib'
             else:
-                ext = 'so'
+                ext = 'so*'
 
             if SAGE_LOCAL:
                 search_directories.append(Path(SAGE_LOCAL) / 'lib')
```

Note that this function is only used once in `sage.env` to set `GAP_SO`.

Without the fix above my `GAP_SO` is set to `None` and I get failures like

```
sage: libgap.eval("2+2")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <module>
----> 1 libgap.eval("2+2")
...
TypeError: expected str, NoneType found
```

Depends on #34391

CC:  @dimpase @orlitzky @williamstein

Component: **packages: standard**

Author: **Gonzalo Tornaría**

Branch/commit - see the corr. PR

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/33446_

### PR DESCRIPTION
**Pull request by dimpase**
### 📚 Description

In short, sometimes there is no `lib**.so` available, but only `lib**.so.*`. This breaks GAP and Singular related things.
See #33446 for details. 

Closes #33446

### ⌛ Dependencies
Depends on #35093 #34391 (GAP update to 4.12.2)

### CODE REVIEW

**Comment by dimpase** [comment]
the test failure (yes, just 1) is most probably unrelated:
```
sage -t --random-seed=136480729433508966711661003720220671146 sage/schemes/toric/sheaf/klyachko.py
**********************************************************************
File "sage/schemes/toric/sheaf/klyachko.py", line 951, in sage.schemes.toric.sheaf.klyachko.KlyachkoBundle_class.random_deformation
Failed example:
    Vtilde.cohomology(dim=True, weight=(0,))
Expected:
    (1, 0)
Got:
    (0, 0)
```

**Comment by tornaria** [comment]
@dimpase dont forget to rebase this one as well on top of [dimpase:u/dimpase/packages/gap/4_12_2](https://github.com/dimpase/sage/tree/u/dimpase/packages/gap/4_12_2)

**Review by mkoeppe — APPROVED** [review]

**Comment by tornaria** [comment]
@vbraun @mkoeppe can we please get #35093 and #35094 in? The sooner the better... it almost made it into 9.8. It is the largest and more intrusive patch I'm carrying, and I can't use `develop` branch at all without merging this so testing other PR is a pain.

**Comment by mkoeppe** [comment]
I've now set it to "blocker", which used to be the way to give a ticket priority in merging.
But it seems that @vbraun's new merging script does not take priority into account.
@vbraun is this by intentional design or is it something that should be fixed in https://github.com/sagemath/sage-release-management?

**Pull request merged**
