### PR TITLE
Use "Issue #" for github issue links

### PR DESCRIPTION
**Pull request by kwankyu**
As discussed in https://github.com/sagemath/sage/pull/37390#issuecomment-1953122331, we change how Sphinx role ``:issue:`` is rendered. For example, short
```
By Issue #7797, there is a different implementation ...
``` 
instead of current
```
By github issue #7797, there is a different implementation ...
``` 
Arguments for the short form are 

> Please don't do "Github issue". It is a lot of text with extremely little extra value. 

> In the trac era, it was "trac #7797".

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
LGTM.

**Comment by tscrim** [comment]
This has been on sage-devel for enough time for someone to comment if they opposed. I think we can merge this now, and it is a reasonable simplification.

**Comment by kwankyu** [comment]
Thanks!

**Comment by vbraun** [comment]
merge conflict

**Comment by kwankyu** [comment]
Rebased and fixed.

**Pull request merged**
