### PR TITLE
Upgrade prompt_toolkit to 3.0.43

### LINKED ISSUE #37539: "DeprecationWarning: There is no current event loop" at startup
### Steps To Reproduce

* SageMath version: 10.3.rc2
* OS: Ubuntu 22.04.4 LTS under WSL2
* At sage startup, I get the following message:
```
~/sage$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3.rc2, Release Date: 2024-03-04                │
│ Using Python 3.11.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/home/davidayotte/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/prompt_toolkit/application/application.py:988: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```
* **Note 1**: the script `init.sage` located at `~/.sage/init.sage` does not run anymore. I use this script in order to assign custom variables at startup.
* **Note 2**: I'm still able to use SageMath afterward.

### Expected Behavior

I expect sage to run and the `init.sage` script to assign my variables.

### Actual Behavior

The script `init.sage` does not run and the deprecation warning shows up in the console.

### Additional Information

See also : 
* sage-support thread: https://groups.google.com/g/sage-support/c/uh1g2nkVcyc
* AskSageMath question: https://ask.sagemath.org/question/76321/there-is-no-current-event-loop/
* This StackOverflow question: https://stackoverflow.com/questions/73361664/asyncio-get-event-loop-deprecationwarning-there-is-no-current-event-loop

### Environment

- **OS** : Ubuntu 22.04.4 LTS under WSL2
- **Sage Version** : 10.3.rc2

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #37539.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
According to the upcoming standard, set back to "critical".

**Comment by mkoeppe** [comment]
You mean until "positive review" is set?

**Comment by mkoeppe** [comment]
Unproblematic upgrade, and already reported it #37539 to fix the problem.
So let's get this in.

**Comment by kwankyu** [comment]
Yes. Thanks.

**Pull request merged**
