### PR TITLE
src/tox.ini: Add cython-lint

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

Adding the command `sage --tox -e cython-lint`.
See https://pypi.org/project/cython-lint/

There are many failures, so it is not run by default.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
ERROR: /__w/sage/sage/src/tox.ini:200: duplicate name 'description'

**Comment by fchapoton** [comment]
and the doc does not build

**Comment by mkoeppe** [comment]
@chapoton Should we also add a "cython-lint-minimal" that would be run automatically?

**Comment by fchapoton** [comment]
There is no urgency. I see no way aomng the command-line options to select a subset of checks. It seems that one can only ignore some checks.

**Review by fchapoton — APPROVED** [review]
ok

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
