### PR TITLE
Check input of composition

### PR DESCRIPTION
**Pull request by mantepse**
Fix #14862

### CODE REVIEW

**Comment by mantepse** [comment]
@fchapoton, I think that this is an improvement, so let's get it in.

In the longer run I'd really like to make `Composition` only accept positive integers, and use `IntegerVector` for weak compositions (perhaps `WeakComposition` should be an alias).  However, this can be done incrementally, I am currently doing it for `tableau.py`.

**Review by mantepse — COMMENTED** [review]
Looks good to me.  Perhaps we should have a `check` argument to bypass the checks, but I don't think it is necessary right now.

**Comment by mantepse** [comment]
@fchapoton, I just realised that I cannot approve this formally, because I created the pull request...

**Comment by fchapoton** [comment]
I think it would be good to have Travis' opinion on that. @tscrim what do you think ?

**Comment by tscrim** [comment]
I think it would be good to add a `check` to the `__init__`, but I wouldn't make a requirement for setting this to a positive review.

**Pull request merged**
