### PR TITLE
Remove mention of patchbot, remove 'make buildbot-python3'

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on https://github.com/sagemath/sage/pull/37421

### CODE REVIEW

**Review by fchapoton — APPROVED** [review]
ok, thanks

**Comment by mkoeppe** [comment]
Thanks!

**Comment by vbraun** [comment]
merge conflict

**Review by fchapoton — APPROVED** [review]

**Comment by vbraun** [comment]
merge conflict

**Pull request merged**
