### PR TITLE
pkgs/sagemath-meataxe/README.rst: Remove markup unknown to PyPI

### PR DESCRIPTION
**Pull request by mkoeppe**
This fixes a failure that currently stops our distributions from being published to PyPI:
https://github.com/sagemath/sage/actions/runs/5706565883/job/15462388715#step:7:28

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kiwifb** [comment]
How come there was no problems for the initial 10.0 release you made? Was it because you pushed manually?

**Comment by mkoeppe** [comment]
I probably introduced this markup problem after pushing the 10.0 releases (manually built from the #35661 branch).

**Review by kiwifb — APPROVED** [review]
Looks good to me

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
