### PR TITLE
Add badges to README.md

### PR DESCRIPTION
**Pull request by kwankyu**
for those who want to play with Sage instantly, and also as a preparation for #36245. 

See this [REAME.md](https://github.com/kwankyu/sage/tree/p/add-binder-badge-to-readme).

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
If we want to start with such badges, we should probably also add them for: 
- gitpod as described in https://doc.sagemath.org/html/en/developer/workspace.html#gitpod
- our docker image
- https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces#overview

**Comment by kwankyu** [comment]
binder is completely free of charge.

gitpod seems free for the basic use for gitpod account owners.

codespaces seems free for me since I am a member. Is this free also for casual visitors to our repo?

**Comment by mkoeppe** [comment]
I think Codespaces requires someone to pay for it. I haven't used it. @tobiasdiez may know more about it.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
