### PR TITLE
Remove direct use of "setup.py sdist", add targets "make SPKG-sdist"

### LINKED ISSUE #34855: Remove direct use of "setup.py sdist", add targets "make SPKG-sdist"
<div id="comment:0"></div>

Direct use of "setup.py sdist" is deprecated. Instead we use `build` to create the sdists.

We add new targets `make sagemath_objects-sdist` etc.

We move targets `make pypi-sdists` (which now uses the new targets), `make wheel`, and `make pypi-wheels` from the top-level `Makefile` to `build/make/Makefile.in`. This improves `make pypi-wheels`: It no longer builds the sagemath-objects wheel multiple times (as dependencies of other packages).

Depends on #34858

CC:  @kiwifb

Component: **build**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34855_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description
Fixes #34855

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jhpalmieri** [comment]
On a Mac, it looks like the current version of `make pypi-sdists` is broken: it doesn't produce tarballs for all nine of the listed packages, creating 5 of them and then "UNKNOWN-0.0.0.tar.gz". With the changes here, it looks like it actually works.

I don't know the details of the `python3 -m build --sdist ...` command. Can we remove the various `setup.py` files, or are they still used?

**Comment by mkoeppe** [comment]
I think this is a symptom of not running `./bootstrap`. Related:
- #35268

**Comment by mkoeppe** [comment]
> I don't know the details of the `python3 -m build --sdist ...` command. Can we remove the various `setup.py` files, or are they still used?

No, it still goes through `setuptools`, so `setup.py` is still needed. But `setuptools` has deprecated its entire command-line interface (and issues deprecation warnings); going forward, it will only provide a build backend (this goes by "PEP-517"). `build` is a new frontend for PEP-517 builds that uses the build backend declared in `pyproject.toml`; in our case, setuptools.

**Comment by jhpalmieri** [comment]
> 

Re #35268, running `./bootstrap` fixes the problem. This is with a brand new tarball so I think that shouldn't be necessary, which presumably is what #35268 is about.

**Review by jhpalmieri — APPROVED** [review]
Looks good to me, works in my limited testing.

**Comment by jhpalmieri** [comment]
I wish I knew a way to list all `make` targets. I found https://stackoverflow.com/questions/4219255/how-do-you-get-the-list-of-targets-in-a-makefile, but for example the solution there by Marc.2377 only lists some of the targets, I'm guessing those created by the top-level `Makefile`.

**Comment by jhpalmieri** [comment]
I have a clunky way of listing the `make` targets, and I can see lots of new ones that maybe shouldn't be there, like `texlive-sdist`. Would it be easy to only create those targets for the packages for which `build/pkgs/SPKG/spkg-src` exists?

**Comment by mkoeppe** [comment]
> Would it be easy to only create those targets for the packages for which `build/pkgs/SPKG/spkg-src` exists?

In our system, that would add more code in `./bootstrap` and in `m4/` and a new macro in `build/make/Makefile.in`; I think we shouldn't do that.

Overall, I don't think we should think of the targets of `make` as public API. Some certainly are, and we should probably document them (see for example #35276). But most are just implementation details.

**Comment by mkoeppe** [comment]
Thanks for reviewing!

**Pull request merged**
