### PR TITLE
add access to printlevel in libsingular

### PR DESCRIPTION
**Pull request by fchapoton**
this is adding and using a simplified access to libsingular ``printlevel`` state variable

useful in turning down the comments easily

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by fchapoton** [comment]
maybe we should also create a `set_printlevel` method too ?

**Comment by kwankyu** [comment]
> maybe we should also create a `set_printlevel` method too ?

Good idea.

**Comment by fchapoton** [comment]
done and used

**Review by kwankyu — APPROVED** [review]
Thanks. LGTM.

**Pull request merged**
