### PR TITLE
build/pkgs/pcre: Remove

### LINKED ISSUE #32231: Upgrade pcre to pcre2
<div id="comment:0"></div>

Our "pcre" package exists only as a dependency of R as far as I can tell, and has been replaced by pcre2 (https://www.pcre.org/) both upstream and within R. We should use the newer library instead.

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/32231_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

Remove the spkg `pcre`; it was a dependency of our `r` package, which was reduced to a dummy package recently.

Closes #32231 

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
```
$ git grep pcre
build/pkgs/_prereq/distros/fedora.txt:# Needed for pcre configure, see https://trac.sagemath.org/ticket/29129
...
```
it actually adds `diffutils`, which is fine and can be kept, but this comment looks outdated

**Comment by mkoeppe** [comment]
OK, I've removed the comment

**Comment by mkoeppe** [comment]
Thanks, Dima!

**Comment by vbraun** [comment]
Merge conflict

**Review by dimpase — APPROVED** [review]
lgtm

**Pull request merged**
