### PR TITLE
Fix implicit noexcept warnings

### PR DESCRIPTION
**Pull request by tornaria**
We have about 7k different occurrences of this warning (about 59k with multiplicities). 

It turns out to be easy to fix automatically, which we do. There's only one mistake and one doctest error to fix after the automatic step.

We also fix a few warnings in regards of `nogil` should appear at the end.

Finally, we disable `legacy_implicit_noexcept` option which is no longer necessary.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Comment by tornaria** [comment]
Complete script for the automatic commit:
```sh
#! /bin/sh

jobs=8

set -e

cythonize_all() {

    # bootstrap if not already done
    [ -e src/setup.cfg ] || ./bootstrap sagelib

    make distclean

    ( cd pkgs/sagemath-standard &&
            PYTHONPATH=../sage-setup \
            SAGE_DEBUG=no \
            SAGE_NUM_THREADS=$jobs \
            PYTHONDONTWRITEBYTECODE=yes \
            python setup.py build_cython ) 2> implicit-noexcept.txt
}

if ! [ -d "build/pkgs/sagelib" -a -d "pkgs/sagemath-standard" ]; then
    echo "Must run from a sage source tree"
    exit 1
fi

[ -e implicit-noexcept.txt ] || cythonize_all

cat implicit-noexcept.txt |
grep "Implicit noexcept" |
sort -u |
while read a b c; do
    file=${b%%:*}
    line=${b#*:}
    line=${line%%:*}
    echo $file $line
done |
sed -ne 's|^sage/|src/sage/|p;s|^\./sage/|src/sage/|p' |
while read file line; do
    sed "$file" -ne "$line"p | grep -q -e noexcept -e '<.*>' ||
    sed -i "$file" -e "$line"'s/\(\( \+\(with \|no\)gil *\)\?[:,]\?\( *#.*\)\?\)$/ noexcept\1/'
done
```

**Comment by tornaria** [comment]
CC: @infmagic2047

**Comment by mkoeppe** [comment]
https://github.com/sagemath/sage/actions/runs/6606821883/job/17943444373?pr=36507#step:9:4272
```
[sagemath_bliss-10.2.beta8]   Error compiling Cython file:
  [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
  [sagemath_bliss-10.2.beta8]   ...
  [sagemath_bliss-10.2.beta8]       cdef list gens = []
  [sagemath_bliss-10.2.beta8]       cdef tuple data = (gens, int2vert, Vnr)
  [sagemath_bliss-10.2.beta8] 
  [sagemath_bliss-10.2.beta8]       if directed:
  [sagemath_bliss-10.2.beta8]           d = bliss_digraph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
  [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(d, add_gen, <void*>data, s)
  [sagemath_bliss-10.2.beta8]                                   ^
  [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
  [sagemath_bliss-10.2.beta8] 
  [sagemath_bliss-10.2.beta8]   sage/graphs/bliss.pyx:644:32: no suitable method found
  [sagemath_bliss-10.2.beta8] 
  [sagemath_bliss-10.2.beta8]   Error compiling Cython file:
  [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
  [sagemath_bliss-10.2.beta8]   ...
  [sagemath_bliss-10.2.beta8]           d = bliss_digraph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
  [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(d, add_gen, <void*>data, s)
  [sagemath_bliss-10.2.beta8]           del d
  [sagemath_bliss-10.2.beta8]       else:
  [sagemath_bliss-10.2.beta8]           g = bliss_graph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
  [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(g, add_gen, <void*>data, s)
  [sagemath_bliss-10.2.beta8]                                   ^
  [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
  [sagemath_bliss-10.2.beta8] 
  [sagemath_bliss-10.2.beta8]   sage/graphs/bliss.pyx:648:32: no suitable method found
  [sagemath_bliss-10.2.beta8]   [1/1] Cythonizing sage/graphs/bliss.pyx
```

**Comment by mkoeppe** [comment]
@orlitzky it will probably be a good idea to check if dropping the `legacy_implicit_noexcept` will create troubles with `--enable-system-site-packages`

**Comment by orlitzky** [comment]
It builds OK with all of my system packages. I can run the tests overnight.

**Comment by orlitzky** [comment]
> It builds OK with all of my system packages. I can run the tests overnight.

All passed.

**Comment by tornaria** [comment]
> https://github.com/sagemath/sage/actions/runs/6606821883/job/17943444373?pr=36507#step:9:4272
> 
> ```
> [sagemath_bliss-10.2.beta8]   Error compiling Cython file:
>   [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
>   [sagemath_bliss-10.2.beta8]   ...
>   [sagemath_bliss-10.2.beta8]       cdef list gens = []
>   [sagemath_bliss-10.2.beta8]       cdef tuple data = (gens, int2vert, Vnr)
>   [sagemath_bliss-10.2.beta8] 
>   [sagemath_bliss-10.2.beta8]       if directed:
>   [sagemath_bliss-10.2.beta8]           d = bliss_digraph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
>   [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(d, add_gen, <void*>data, s)
>   [sagemath_bliss-10.2.beta8]                                   ^
>   [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
>   [sagemath_bliss-10.2.beta8] 
>   [sagemath_bliss-10.2.beta8]   sage/graphs/bliss.pyx:644:32: no suitable method found
>   [sagemath_bliss-10.2.beta8] 
>   [sagemath_bliss-10.2.beta8]   Error compiling Cython file:
>   [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
>   [sagemath_bliss-10.2.beta8]   ...
>   [sagemath_bliss-10.2.beta8]           d = bliss_digraph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
>   [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(d, add_gen, <void*>data, s)
>   [sagemath_bliss-10.2.beta8]           del d
>   [sagemath_bliss-10.2.beta8]       else:
>   [sagemath_bliss-10.2.beta8]           g = bliss_graph_from_labelled_edges(Vnr, Lnr, Vout, Vin, labels, partition)
>   [sagemath_bliss-10.2.beta8]           bliss_find_automorphisms(g, add_gen, <void*>data, s)
>   [sagemath_bliss-10.2.beta8]                                   ^
>   [sagemath_bliss-10.2.beta8]   ------------------------------------------------------------
>   [sagemath_bliss-10.2.beta8] 
>   [sagemath_bliss-10.2.beta8]   sage/graphs/bliss.pyx:648:32: no suitable method found
>   [sagemath_bliss-10.2.beta8]   [1/1] Cythonizing sage/graphs/bliss.pyx
> ```

I'm not sure I understand what is going on here.

**Comment by tornaria** [comment]
I understand what is going on. In the previous run I only fixed files in the sagemath-standard distribution, just because we started with a list of warnings produced when cythonizing sagemath-standard because it's the only thing I compile.

Now I figured out a way to cythonize the other distributions (basically I temporarily removed the `# sage_setup: distribution = ...` line and run build_cython with `legacy_implicit_noexcept=True` to produce warnings).

With the new output, apply the same snippet as described before. Hopefully everything is right now.

It seems quite important to merge this since having 60k warnings each time we build sage is a bit too much and kind of obscures anything else.

**Comment by mkoeppe** [comment]
Thanks! I'll take another look when the CI has finished

**Comment by mkoeppe** [comment]
Looking good. Let's merge it.

**Review by mkoeppe — APPROVED** [review]

**Comment by tobiasdiez** [comment]
The conda tests are failing (I've restarted them to see if its only a temporary issue, but since it happened on the last two commits I doubt it). Could you please have a look? Thanks! (Sorry to plague you again with conda 😸 )

**Comment by tornaria** [comment]
> The conda tests are failing (I've restarted them to see if its only a temporary issue, but since it happened on the last two commits I doubt it). Could you please have a look? Thanks! (Sorry to plague you again with conda 😸 )

Copy the failure and the error messages.

**Comment by tobiasdiez** [comment]
Just have a look in the checks below the PR here: https://github.com/sagemath/sage/actions/runs/6646554232/job/18092000599?pr=36507

```
Traceback (most recent call last):
  File "sage/rings/integer.pyx", line 711, in sage.rings.integer.Integer.__init__
TypeError: unable to coerce <class 'tuple'> to an integer
Exception ignored in: 'sage.rings.integer.fast_tp_dealloc'
Traceback (most recent call last):
  File "sage/rings/integer.pyx", line 711, in sage.rings.integer.Integer.__init__
TypeError: unable to coerce <class 'tuple'> to an integer
```

**Comment by tornaria** [comment]
> Just have a look in the checks below the PR here: https://github.com/sagemath/sage/actions/runs/6646554232/job/18092000599?pr=36507
> 
> ```
> Traceback (most recent call last):
>   File "sage/rings/integer.pyx", line 711, in sage.rings.integer.Integer.__init__
> TypeError: unable to coerce <class 'tuple'> to an integer
> Exception ignored in: 'sage.rings.integer.fast_tp_dealloc'
> Traceback (most recent call last):
>   File "sage/rings/integer.pyx", line 711, in sage.rings.integer.Integer.__init__
> TypeError: unable to coerce <class 'tuple'> to an integer
> ```

Hmmm... that looks to me like a problem in one dependency. Is conda tested always with exactly the same versions, or do they change at the whims of conda? If the latter, this is a sure way to mess up... (could we get a list of differences on pkg versions between the last time that this test passed vs. this run?)

Is it possible that you set up some kind of "lock file" that fixes the exact versions of dependencies that will be used, to avoid this?

What I imagine is that maybe some dependency was updated recently in conda, causing trouble.

**Comment by tobiasdiez** [comment]
> Hmmm... that looks to me like a problem in one dependency. Is conda tested always with exactly the same versions, or do they change at the whims of conda? If the latter, this is a sure way to mess up... (could we get a list of differences on pkg versions between the last time that this test passed vs. this run?)

Currently, the latest version (compatible with our constraints) will be installed, and yes this sometimes results in failing tests.
That being said, none of the [other conda runs](https://github.com/sagemath/sage/actions/workflows/ci-conda.yml) show this behavior, so its particular to the changes in this PR.

> Is it possible that you set up some kind of "lock file" that fixes the exact versions of dependencies that will be used, to avoid this?

Yes, proposed at https://github.com/sagemath/sage/pull/35986, which is ready for review.

**Comment by tornaria** [comment]
I've no idea what is going on, and it's impossible to debug whatever is happening in CI.

Let's merge all the warnings-removal changes without disabling the legacy_implicit_noexcept option. That is already a big win (60k warnings solved!) and we can postpone disabling the legacy option to the future.

**Comment by tornaria** [comment]
It seems to be working: can we get positive review back?

As is now, the change should be mostly noop, since we don't change the compilation mode; we only add "noexcept" annotations in lines for which cython claimed to assume it implicitly, so the generated c code should be the same.

Actually changing the compilation mode seems like it might carry some subtlety; we can investigate later (maybe compare the cython output in both modes is a good start point).

**Comment by vbraun** [comment]
merge conflict

**Comment by tobiasdiez** [comment]
> I've no idea what is going on, and it's impossible to debug whatever is happening in CI.

I would argue its actually more convenient to debug conda issues than other build-related problems: just start a codespace at https://github.com/codespaces/new?hide_repo_select=true&ref=develop&repo=597660615&skip_quickstart=true and you have a working dev setup based on the conda environment and can investigate the issue.

> Let's merge all the warnings-removal changes without disabling the legacy_implicit_noexcept option. That is already a big win (60k warnings solved!) and we can postpone disabling the legacy option to the future.

I agree! Thanks for your work on this.

**Comment by tornaria** [comment]
> merge conflict

With what?

**Comment by tornaria** [comment]
> merge conflict

Are we getting merge conflict with a bunch of empty lines? Please... Can you try now?

**Comment by tobiasdiez** [comment]
I think it means that there are merge conflicts with other PRs in the next beta. You can check it out by comparing against vbrauns branch: https://github.com/vbraun/sage/compare/develop...tornaria:sage:cython-implicit-noexcept

**Pull request merged**
