### PR TITLE
`build/pkgs/sphinx` 7.3.7, `docutils` 0.21.2, `furo` 2024.5.6

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by kwankyu** [comment]
Wait a minute. There's something to look at: https://github.com/sagemath/sage/actions/runs/9629901706/job/26562064031?pr=38261

**Comment by kwankyu** [comment]
It seems that the failure is due to some change in the information saved into `environment.pickle` produced by Sphinx. This is just a usual hiccup of incremental doc build. Doc build from scratch is okay.

I think there is no work issue.

**Comment by mkoeppe** [comment]
Thanks for investigating this!

**Pull request merged**
