### PR TITLE
Add as_subscheme() method for rational points

### PR DESCRIPTION
**Pull request by kwankyu**
so that we can do
```sage
sage: A2.<x,y> = AffineSpace(QQ, 2)
sage: p = A2.point([0,0])
sage: P = p.as_subscheme()
sage: P
Closed subscheme of Affine Space of dimension 2 over Rational Field defined by:
  x,
  y
sage: Q = P.projective_closure()
sage: Q
Closed subscheme of Projective Space of dimension 2 over Rational Field defined by:
  x0,
  x1
sage: q, = Q.rational_points()
sage: q
(0 : 0 : 1)
sage: q.as_subscheme()
Closed subscheme of Projective Space of dimension 2 over Rational Field defined by:
  x0,
  x1
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by tscrim — CHANGES_REQUESTED** [review]
LGTM overall. Two minor things:

1. Please add tests for the input-checking errors to make sure they are working properly.
2. Are we certain that removing the fixed-in-place `_NumberFields` will not slow down the code in any meaningful way? It seems like something that could be created often enough that it might matter.

**Comment by kwankyu** [comment]
> 1. Please add tests for the input-checking errors to make sure they are working properly.

I cannot make up tests to invoke them. This tells that I added unnecessary checks. Hence I removed them.

> 2. Are we certain that removing the fixed-in-place `_NumberFields` will not slow down the code in any meaningful way? It seems like something that could be created often enough that it might matter.

I experimented it. Really `_NumberFields` gains a slight speedup. Hence I restored  it.

Thanks for pointing out these.

**Comment by kwankyu** [comment]
No. The (affine and projective) point constructors have the checks so that the `assert` statements would just be duplicates.

**Review by tscrim — APPROVED** [review]
Okay. Then positive review.

**Pull request merged**
