### PR TITLE
`sage.features`: Declare features as "standard" explicitly

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

As discussed in https://github.com/sagemath/sage/pull/35668#issuecomment-1604532130

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #35668 (merged here)

### CODE REVIEW

**Comment by kiwifb** [comment]
Looks promising. I am not even objecting to the term "butchered" :P even if I would prefer "annihilated". In any case, I should plan work on my own follow up. I think with that and some other stuff, getting rid of `sage.misc.package` from doctest is near.

**Comment by mkoeppe** [comment]
I think features for some optional packages are still missing; there may be some open tickets for some of these. When that is fixed, I'm all in favor of eliminating the use of sage.misc.packages from the doctester!

**Comment by soehms** [comment]
Great! Thank you for promptly resolving this issue. It seems like a good solution.

In the logs of the doctests there are some features with missing `standard` declaration (e.g. `libbraiding`, `pplpy`). Unfortunately I can't help at the weekend, sorry.

**Comment by soehms** [comment]
LGTM!

**Review by soehms — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks for reviewing!

**Comment by soehms** [comment]
> I think features for some optional packages are still missing; there may be some open tickets for some of these. When that is fixed, I'm all in favor of eliminating the use of sage.misc.packages from the doctester!

I've opened https://github.com/sagemath/sage/issues/35856 to track the progress on that.

**Pull request merged**
