### PR TITLE
systematically avoid checking of input

### LINKED ISSUE #35212: Permutation(n) doesn't use the cache if there is one.
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: any
- **Sage Version**: 10.0.beta2
```

### Steps To Reproduce

```
sage: %time for x in Permutations(10): pass
CPU times: user 4 s, sys: 0 ns, total: 4 s
Wall time: 4 s
sage: %time for x in Permutations(10).tuple(): pass
CPU times: user 13.2 s, sys: 252 ms, total: 13.5 s
Wall time: 13.5 s
sage: %time for x in Permutations(10).tuple(): pass
CPU times: user 124 ms, sys: 0 ns, total: 124 ms
Wall time: 124 ms
sage: %time for x in Permutations(10): pass
CPU times: user 4.2 s, sys: 0 ns, total: 4.2 s
Wall time: 4.2 s
```

### Expected Behavior

Once the cache of a finite enumerated set is filled, it should be used.

### Actual Behavior

The iterator over permutations doesn't use the cache `self._list`, even if present.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mantepse**
Trusting that the code is correct, there is no reason to check the input.
### 📚 Description
Closes #35212, https://github.com/sagemath/sage/issues/35212#issuecomment-1454235580

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.

### ⌛ Dependencies

### CODE REVIEW

**Comment by mantepse** [comment]
@tmiller, that's part two.

**Comment by mantepse** [comment]
Two questions:
1. should we rename `check_input` to `check`.  `check_input` is only used in three methods:
```
combinat/skew_tableau.py:    def to_ribbon(self, check_input=True):
graphs/generic_graph.py:    def relabel(self, perm=None, inplace=True, return_map=False, check_input=True, complete_partial_function=True, immutable=None):
matrix/matrix2.pyx:    def jordan_form(self, base_ring=None, sparse=False, subdivide=True, transformation=False, eigenvalues=None, check_input=True):
```
2. I'd like to catch future performance regressions.  In particular:
```
sage: P = Permutations(10)
sage: %%time
....: for pi in P:
....:     pass
CPU times: user 14.5 s, sys: 62 µs, total: 14.5 s
Wall time: 14.5 s
```
now gives
```
CPU times: user 8.43 s, sys: 0 ns, total: 8.43 s
Wall time: 8.43 s
```

**Comment by tscrim** [comment]
1. I think `check` is better than `check_input` (and more standard). +1 on changing it (albeit with a slightly annoying deprecation).
2. We can't really doctest our way to catching performance regressions (at least on that scale). We need a separate timings test package/files. I don't think this is worth the time/effort to do anything about it here.

**Comment by mantepse** [comment]
> 1. I think `check` is better than `check_input` (and more standard). +1 on changing it (albeit with a slightly annoying deprecation).
> 
will do!

>     2. We can't really doctest our way to catching performance regressions (at least on that scale). We need a separate timings test package/files. I don't think this is worth the time/effort to do anything about it here.
I know, I was referring to #35046.

**Comment by mantepse** [comment]
There are very many test failures, but I cannot reproduce them locally :-(

**Review by tscrim — APPROVED** [review]
Thank you. LGTM. The tester now seems to be passing without any problems too.

**Comment by mantepse** [comment]
Thank you!  I'm afraid you have to remove the `needs-review` label and add the `positive-review` label manually, right?

**Comment by tscrim** [comment]
Sorry, I forgot to do this. Done.

**Comment by vbraun** [comment]
merge conflict

**Review by tscrim — APPROVED** [review]

**Pull request merged**
