### PR TITLE
CI Build&Test: Split test-long into multiple jobs, repair Coverage.py upload

### PR DESCRIPTION
**Pull request by mkoeppe**
test-long (90 minutes) runs after a successful test-new (10 minutes). This is the critical path (100 minutes), longer than build-docs-pdf (85 minutes). We split it into multiple parallel jobs (33 minutes), merging the coverage files in a job afterwards (6 minutes). 

This also repairs the Coverage.py upload, which apparently got broken.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
Is there an example run?

This is to save 15 minutes. Is it worth the effort? 

Workflow scripts are the second-class citizen. But in the long run, they are still burden of the community. 

The workflow script gets more complicated. Saving 15 minutes is worth it?

**Comment by mkoeppe** [comment]
> Is there an example run?

Yes, right here on the PR

**Comment by mkoeppe** [comment]
> This is to save 15 minutes.

... to completion of all jobs, yes. But the time to completion of test-long is cut in half from 100 minutes to 50 minutes

**Comment by kwankyu** [comment]
From the example run,
```
+ ./sage -python -m coverage combine --rcfile=src/tox.ini .coverage/coverage-src_doc--src_sage_docbuild--src_sage_setup/.coverage .coverage/coverage-src_sage_a-f/.coverage .coverage/coverage-src_sage_g-o/.coverage .coverage/coverage-src_sage_p-z/.coverage
Combined data file .coverage/coverage-src_doc--src_sage_docbuild--src_sage_setup/.coverage
Combined data file .coverage/coverage-src_sage_a-f/.coverage
Combined data file .coverage/coverage-src_sage_g-o/.coverage
Combined data file .coverage/coverage-src_sage_p-z/.coverage
+ ./sage -python -m coverage xml --rcfile=src/tox.ini
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/coverage/report_core.py:115: CoverageWarning: Couldn't parse '/tmp/tmp06qizzie/tmp_fte2alrs.py': No source for code: '/tmp/tmp06qizzie/tmp_fte2alrs.py'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/coverage/report_core.py:115: CoverageWarning: Couldn't parse '/tmp/tmp06qizzie/tmp_ldpu46ob.py': No source for code: '/tmp/tmp06qizzie/tmp_ldpu46ob.py'. (couldnt-parse)
...
```
Could we remove the warnings?

**Comment by kwankyu** [comment]
> ...  the time to completion of test-long is cut in half from 100 minutes to 50 minutes

OK. Certainly nice reward for the effort.

**Comment by mkoeppe** [comment]
> Could we remove the warnings?

Trying in a0262b62771

**Review by kwankyu — APPROVED** [review]
Thanks. LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
