### PR TITLE
Adopt the “time window-based” policy for support of Python versions from Spec-0

### LINKED ISSUE #30384: Adopt the “time window-based” policy for support of Python versions from NEP 29
<div id="comment:0"></div>

The NEP 29 policy (https://numpy.org/neps/nep-0029-deprecation_policy.html) aims to "standardiz[e] a recommendation for project support of minimum Python and NumPy versions [to] improve downstream project planning."
With this ticket, we adopt this deprecation policy of old Python versions for the Sage library.

According to NEP 29 support for Python 3.7 should be dropped in December 2021. Actually doing this will be subject of a new ticket that should be merged at the beginning of the 9.6 release cycle.

Related discussions:
- https://groups.google.com/d/msg/sage-devel/fgsSsJmVVXo/n2BQBSaBAAAJ (2020-05)
- https://groups.google.com/d/msg/sage-devel/aggikzrEfUg/_fIz4W-0BgAJ (2020-08)
- https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU (2023-02)
- on PR #35403 (2023-03–)
- on PR #35404 (2023-03–)
- Vote: https://groups.google.com/g/sage-devel/c/3Zoq0CNE1hE (2023-05–26–2023-06-07)

CC:  @slel @jhpalmieri @orlitzky

Component: **python3**

Author: **Tobias Diez**

Branch/Commit: **[public/python3/nep29](https://github.com/sagemath/sagetrac-mirror/tree/public/python3/nep29) @ [`edf1711`](https://github.com/sagemath/sagetrac-mirror/commit/edf1711828659e3ac6914a9d9f021e9f38a27375)**

_Issue created by migration from https://trac.sagemath.org/ticket/30384_

### PR DESCRIPTION
**Pull request by tobiasdiez**
### :books: Description

Add a short paragraph to the developer guide explaining the Python support schedule. Previously discussed in #30384 and on the [mailing list](https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU). Closes #30384.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
In case you didn't see it - https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU/m/x3qOdPB5BQAJ

**Comment by tobiasdiez** [comment]
No, I've seen your comments. But what you propose essentially comes down to NEP29 + half a year or so, which just feels random. Also your work on the modularization is helping to promote that sage is used more actively in other python packages, so it gets more and more important to sync with the community standards.

**Comment by mkoeppe** [comment]
> I've seen your comments. But what you propose [...]

Tobias, I'm not "proposing" it. I'm describing our actual practice.

> Also your work on the modularization is helping to promote that sage is used more actively in other python packages, 
> so it gets more and more important to sync with the community standards.

You don't need to explain this to me; but it has not happened yet.

**Comment by dimpase** [comment]
our actual practice is not ideal, on many fronts.

**Comment by mkoeppe** [comment]
General comments like this can hardly be a useful contribution to this discussion.

**Comment by dimpase** [comment]
no, you are declining to proceed with this PR on the same kind of grounds as my comment is based upon.

**Comment by mkoeppe** [comment]
Re-read https://github.com/sagemath/sage/pull/34973 and https://github.com/sagemath/sage/pull/35188; it has a detailed discussion, which cannot be dismissed by generalities. If you want to discuss, discuss, don't dismiss.

**Comment by dimpase** [comment]
you can reread my comment in that link, too.
We can have a vote on this... 

I don't understand why Sage must be trailing behind a number of its upstream components.

**Comment by dimpase** [comment]
you can reread my comment in that link, too.
We can have a vote on this... 

I don't understand why Sage must be trailing behind a number of its upstream components.

**Comment by mkoeppe** [comment]
> I don't understand why Sage must be trailing behind a number of its upstream components.

Well, I have explained that it does not. No package relevant for Sage has already dropped Python 3.8 in a released version or will before July.

**Comment by mkoeppe** [comment]
By the way, the numpy update to latest is waiting for review in #35081.

**Comment by dimpase** [comment]
Scipy is definitely dropping 3.8 soon, and they say they do follow NEP 29.
"When dropping support for older Python versions, SciPy takes guidance from NEP 29".

Are we following NEP 29, or not?

**Comment by mkoeppe** [comment]
> Scipy is definitely dropping 3.8 soon, and they say they do follow NEP 29.

I explained the specifics in https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU/m/x3qOdPB5BQAJ

**Comment by mkoeppe** [comment]
> Are we following NEP 29, or not?

No, we don't have this policy

**Comment by tobiasdiez** [comment]
In order to bring this back onto a good discussion platform, let me summarize your arguments for not adopting NEP 29:
- It is the current practice of how sage operates.
- NEP 29 is mostly relevant for packages that are used by other packages.
- No one is forcing us to drop support of a python version until scipy/numpy or other dependencies are doing this.
- Some linux distributions (that are still having lts) are coming with preinstalled python that is not compatible with NEP 29.

Is this correct so far @mkoeppe? Did I miss an argument or misunderstood you?

My response to these points is:
- While there is definitely value in having an organically grown policy, I think its important from time to time question if it still fits well with the current situation. From a users perspective, one could argue that they are used to a certain drop schedule for python support in sage, but since this was never officially documented or communicated (please correct me if I'm wrong), adopting NEP29 provides more clarity for users on what they can expect and aligns sage with the common practice of other packages that they may use.
- Sure, NEP 29 is mainly handy for downstream packages as they can expect what versions are supported. But (as I don't have to tell you) the modularization effort has the goal to make sage useful as an upstream package. So you can see this push towards NEP29 as a helpful step for modularization/pip installable packages which is future proof.
- The disadvantages of taking Linux distributions as reference is addressed in the NEP itself very well in my opinion: https://numpy.org/neps/nep-0029-deprecation_policy.html#default-version-on-linux-distribution. In particular, I completely agree with 
   > By following the versions supported by major Linux distributions, we are giving up technical control of our projects to external organizations that may have different motivations and concerns than we do.

    The same problems occur in my opinion when you take dependencies as your reference point. Say numpy changes their drop schedule to only support the last python version, does sage then follows this as well?

Finally, what makes sage so fundamentally different to scipy that its users should expect sage to support python versions released in the last 48 months, while scipy users are totally fine with support for releases in the last 42 months? Especially given that its very easy to install a new python version (pyenv, conda, ...). From experience, its definitely easier than installing sage itself ;-).

In general, we have two competing view points:
- As a user, I want sage to work with all python versions (since then I don't have to worry about the python version I have installed)
- As a sage developer, I want to only support the latest python version (since then I don't have to test on different versions, can use the latest language features, can reduce the technical dept)

Obviously, there is no objective line where these competing wishes are perfectly balanced. But I think its usually a good idea to align with established policies in the field in such cases, and NEP29 is the defacto most popular one.

**Comment by mkoeppe** [comment]
> * From a users perspective, one could argue that they are used to a certain drop schedule for python support in sage, but since this was never officially documented or communicated (please correct me if I'm wrong), adopting NEP29 provides more clarity for users on what they can expect and aligns sage with the common practice of other packages that they may use.

That's really far fetched. Our users have never asked us anything like that.

**Comment by mkoeppe** [comment]
> So you can see this push towards NEP29 as a helpful step for modularization/pip installable packages

I've already responded to this – yes, I'm aware of it; yes, making (portions of) the Sage library suitable as upstream for other packages is very much the point of the modularization; but no, it is not relevant yet.

**Comment by mkoeppe** [comment]
> > we are giving up technical control of our projects to external organizations [...]
>   The same problems occur in my opinion when you take dependencies as your reference point. Say numpy changes their drop schedule to only support the last python version, does sage then follows this as well?

This is getting dialectical.

**Comment by tobiasdiez** [comment]
> > * From a users perspective, one could argue that they are used to a certain drop schedule for python support in sage, but since this was never officially documented or communicated (please correct me if I'm wrong), adopting NEP29 provides more clarity for users on what they can expect and aligns sage with the common practice of other packages that they may use.
> 
> That's really far fetched. Our users have never asked us anything like that.

What about seeing this as an experiment: we follow NEP29 for this release (i.e. drop python 3.8 support), and if there is a huge backslash by the community we change it to NEP29 + half a year?

**Comment by tobiasdiez** [comment]
> > So you can see this push towards NEP29 as a helpful step for modularization/pip installable packages
> 
> I've already responded to this – yes, I'm aware of it; yes, making (portions of) the Sage library suitable as upstream for other packages is very much the point of the modularization; but no, it is not relevant yet.

Yes, you made this point already. But dismissing something as not relevant without giving reasons is neither constructive nor helpful.

**Comment by mkoeppe** [comment]
> But dismissing something as not relevant without giving reasons

Please, Tobias, that's inappropriate. I have already explained the reason. It's irrelevant now (for 9.0) because the modularization has not happened yet, so there's no real benefit; only an imaginary benefit.

**Comment by mkoeppe** [comment]
> What about seeing this as an experiment

Not interested.

**Comment by tobiasdiez** [comment]
> > > we are giving up technical control of our projects to external organizations [...]
> > > The same problems occur in my opinion when you take dependencies as your reference point. Say numpy changes their drop schedule to only support the last python version, does sage then follows this as well?
> 
> This is getting dialectical.

I'm not sure "dialectical" is the correct word here, but my point here is: you want to select which versions of the dependencies you use based on a policy on supported python versions, and not let this policy be dictated by the dependencies. For example, if by some other constraints sage would need to support all LTS python versions, then this would mean that it cannot upgrade to the most recent numpy version, and that's fine.

**Comment by mkoeppe** [comment]
> > > > we are giving up technical control of our projects to external organizations [...]
> > > > The same problems occur in my opinion when you take dependencies as your reference point. Say numpy changes their drop schedule to only support the last python version, does sage then follows this as well?
> > 
> > 
> > This is getting dialectical.
> 
I'll explain it more directly. You are using a strawman here: You are pretending that I propose (or use) a rigid policy that ties us to numpy -- and attacking that.

**Comment by tobiasdiez** [comment]
> > > > > we are giving up technical control of our projects to external organizations [...]
> > > > > The same problems occur in my opinion when you take dependencies as your reference point. Say numpy changes their drop schedule to only support the last python version, does sage then follows this as well?
> > > 
> > > 
> > > This is getting dialectical.
> 
> I'll explain it more directly. You are using a strawman here: You are pretending that I propose (or use) a rigid policy that ties us to numpy -- and attacking that.

Yes, I'm attacking that the policy of supported python version is tied to numpy (or any other dependency). So we agree that using dependencies as a rigid criteria for determining which python versions to support is not a good idea?

**Comment by dimpase** [comment]
Supporting legacy Python is extra work, and we are much more constrained by the labour shortage than upstreams like scipy. And also we might be hitting limits of what we have available on GitHub Actions.

I think we should proceed with this PR now, it appears to be not 100% straightforward, and whether or not it makes it to 10.0 is another question, up to @vbraun 

If you want to specifically delay it, please open a vote on sage-devel on this matter.

**Comment by mkoeppe** [comment]
> we might be hitting limits of what we have available on GitHub Actions.

No, we aren't. Note that since the upgrade to GH Teams we have many more parallel runners.

**Comment by mkoeppe** [comment]
> If you want to specifically delay it, please open a vote on sage-devel on this matter.

That's not how it works. What is proposed here is a policy change.

**Comment by tobiasdiez** [comment]
> > If you want to specifically delay it, please open a vote on sage-devel on this matter.
> 
> That's not how it works. What is proposed here is a policy change.

It has been discussed on the mailing list, and you have been the only one that raised concerns against it. Moreover, there is no documented policy about supported python version as far as I can see, and the last two drops were in the beginning of May (couldn't find earlier ones); very much in agreement with what NEP29 specifies (April).

**Comment by mkoeppe** [comment]
> there is no documented policy about supported python version as far as I can see

That's right, there's no policy: It's decided based on what makes sense, based on the detailed facts. And I oppose introducing a rigid policy that is based on the vague idea "NEP 29 good".

**Comment by tobiasdiez** [comment]
> > there is no documented policy about supported python version as far as I can see
> 
> That's right, there's no policy: It's decided based on what makes sense, based on the detailed facts. And I oppose introducing a rigid policy that is based on the vague idea "NEP 29 good".

The advantages of a policy are becoming very apparent in #35404. Instead of a discussion based on "detailed facts", it becomes a unnecessary back-and-forth without any real arguments. And let's face it, there is no objectively right moment to drop a given python version. It always comes down to "I feel its the right/not right moment" (and then supplemented with pseudo-arguments). The only scientific way out here, that I see, would be a proper user study. But I don't think we have the resources for that. 

Speaking of developer resources, I think we all invested enough time in this. Matthias, what would be needed that you can agree with such or a similar policy?

**Comment by mkoeppe** [comment]
Please, Tobias, that's a ridiculous spin. Kindly stop.

**Comment by tobiasdiez** [comment]
What's the point of policies other than to resolve situations like this? If one always has the time to discuss everything in detail, then there wouldn't be any need for a policy. From wikipedia:

> Policies used in subjective decision-making usually assist senior management with decisions that must be based on the relative merits of a number of factors, and as a result, are often hard to test objectively

That's exactly what we have here: a subjective decision-making that is hard to "test" objectively.

But please ignore that part, if you feel personally attacked by it (which was not my intention, and I'm sorry if it came across the wrong way). But please reply to:
> Matthias, what would be needed that you can agree with such or a similar policy?

**Comment by mkoeppe** [comment]
Actually no discussion has even happened here. I've analyzed it completely in https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU/m/x3qOdPB5BQAJ; no argument was offered here that wasn't based on a coarser understanding of the facts than what I already explained and substantiated in February.

**Comment by tobiasdiez** [comment]
In this comment, you just rightly point out that NEP29 was not designed for downstream applications. Okay, and? You have not brought forward any points why the content of NEP29 does not fit well our situation and needs.

In particular, you have not responded to Dima's argument concerning the developer resources: scipy/numpy on other projects with many more active developers than sage found it a good compromise to only support the versions according to NEP29. Why should sage still invest resources in keeping backwards compatibility when these other projects say the price is too high?

Another point: what difference do you see in the user base of scipy/numpy vs sage that our users cannot upgrade their python version but scipy users can?

**Comment by dimpase** [comment]
It's a regular fight we have with Matthias - also on dropping packaged Python and gcc all together...

People who don't have Python 3.9 or better as a system python (this 1% of users?) may well just use pyenv.

**Comment by mkoeppe** [comment]
Dima, every single one of your arguments here has had no merit; yet you are insisting that you're right. That's a toxic pattern, and this is what drains energy from the project.

**Comment by mkoeppe** [comment]
> Why should sage still invest resources in keeping backwards compatibility

We aren't. This claim is vague / fictional / unsubstantiated.

It's really very simple. The justification for dropping Python 3.8 in #35404 is extremely weak: One ticket by a beginner; and one ticket where Tobias had to write `Tuple[...]` instead of `tuple[...]`. I support dropping Python 3.8 later this year, when we have actual convincing benefits (upgrades to new minor versions of scipy/numpy).

**Comment by mkoeppe** [comment]
> a big number of hours was sunk in Cygwin support

Dima, I stopped working on the Cygwin issues last summer because you drained my energy with #34152.

**Comment by mkoeppe** [comment]
> It's a regular fight we have with Matthias - also on dropping packaged Python and gcc all together...

Who would be "we" here? The last major discussion of this was in Sep 2021 in https://groups.google.com/g/sage-devel/c/NfUKjAaTcUg/m/S3EDS0odBQAJ, where your position found no support.

**Comment by tobiasdiez** [comment]
> It's really very simple. The justification for dropping Python 3.8 in #35404 is extremely weak: One ticket by a beginner

I'm pretty sure he is motivated to keep contributing to sage in half a year...

> and one ticket where Tobias had to write `Tuple[...]` instead of `tuple[...]`.

Nope, Python 3.8 is not able to correctly parse the `unpack` annotation, which is needed if you want to type kwds:
```
 [sagemath_doc_html-none] [manifolds] WARNING: signature: (self, *coordinates: sage.symbolic.expression.Expression, **kwds: typing_extensions.Unpack[sage.manifolds.chart.ValidateCoordinateOptions]) -> bool
[sagemath_doc_html-none] [manifolds] WARNING: error while formatting signature for sage.manifolds.chart.Chart.valid_coordinates: Handler <function record_typehints at 0x7f1f9b7cbdc0> for event 'autodoc-process-signature' threw an exception (exception: __name__)
[sagemath_doc_html-none] [manifolds] Traceback (most recent call last):
[sagemath_doc_html-none] [manifolds]   File "/sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
[sagemath_doc_html-none] [manifolds]     results.append(listener.handler(self.app, *args))
[sagemath_doc_html-none] [manifolds]   File "/sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/sphinx/ext/autodoc/typehints.py", line 30, in record_typehints
[sagemath_doc_html-none] [manifolds]     annotation[param.name] = typing.stringify(param.annotation, mode)
[sagemath_doc_html-none] [manifolds]   File "/sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/sphinx/util/typing.py", line 363, in stringify
[sagemath_doc_html-none] [manifolds]     return modprefix + '.'.join([annotation.__module__, annotation.__name__])
[sagemath_doc_html-none] [manifolds]   File "/usr/lib/python3.8/typing.py", line 760, in __getattr__
[sagemath_doc_html-none] [manifolds]     raise AttributeError(attr)
[sagemath_doc_html-none] [manifolds] AttributeError: __name__
```

> The justification for dropping Python 3.8 in https://github.com/sagemath/sage/pull/35404 is extremely weak

In the other direction, do you have a stronger justification for keeping support? For example, how many users reported issues with the fact that Sage 9.7 dropped Python 3.7 support and they couldn't find a simple workaround?

**Comment by mkoeppe** [comment]
> > one ticket where Tobias had to write `Tuple[...]` instead of `tuple[...]`.
> 
> Nope, Python 3.8 is not able to correctly parse the `unpack` annotation, which is needed if you want to type kwds:

Again I refer back to https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU/m/x3qOdPB5BQAJ, where I wrote:
> Of course, another argument for dropping support for a Python version (such as Python 3.8) would be that it is missing critical features that hold us back in the development of the Sage library. Issue https://github.com/sagemath/sage/issues/29756 has a bit of this discussion.

So, try to build a stronger case in https://github.com/sagemath/sage/pull/35404. What is the feature that you would like to use; link the references, ... Details matter.

**Comment by tobiasdiez** [comment]
> > > one ticket where Tobias had to write `Tuple[...]` instead of `tuple[...]`.
> > 
> > 
> > Nope, Python 3.8 is not able to correctly parse the `unpack` annotation, which is needed if you want to type kwds:
> 
> Again I refer back to https://groups.google.com/g/sage-devel/c/j1cwbTU8aOU/m/x3qOdPB5BQAJ, where I wrote:
> 
> > Of course, another argument for dropping support for a Python version (such as Python 3.8) would be that it is missing critical features that hold us back in the development of the Sage library. Issue #29756 has a bit of this discussion.
> 
> So, try to build a stronger case in #35404. What is the feature that you would like to use; link the references, ... Details matter.

Sorry, Matthias but you are the one that is blocking this ticket with detailed answers like "Too early for 10.0.". If you want to start a proper discussion, then please make an argument why dropping 3.8 support now is not a good idea and why these reasons outweigh that two PRs are waiting for Python >= 3.9.

**Comment by mkoeppe** [comment]
That's not how it works. You are proposing a change in #35404 (dropping support), so you need to build your case.

And I really need to ask you to use more restraint in these discussions because this is not healthy for our project. I already had to call you out for using a strawman attack earlier; but then you proceeded with labeling my points as "just feelings" and "pseudo-arguments"; you repeatedly claim that I have not substantiated something when I did.

**Comment by tobiasdiez** [comment]
> That's not how it works. You are proposing a change in #35404 (dropping support), so you need to build your case.
> 

You reverted a positive review. Clearly, this should be accompanied by a clear reasoning what is missing for this PR to be merged. Similarly, you are blocking this PR here without replying to any of the arguments brought forward (except labeling them as a irrelevant or dismiss them for some other reason). 

And I already made my point: there are two PRs (three if you count https://github.com/sagemath/sage/pull/35481) that need Python 3.9 or higher. You called this weak, and now what? Are you supporting dropping 3.8 if these two PRs really need 3.9? If not, how many more PRs are needed in your opinion? 

Finally, I'm sorry if my words come across in a wrong way. I'm actually trying very hard to stay positive and find a solution here. I didn't try to discredit your points by calling them "feelings". In the contrary, I thought it would be helpful to realize that we have a situation here were this no clear objective truth, and this is a situation we mathematicans are not very trained at to handle. To cite my wife, mathematicans in general should think higher of their feelings. They are something to appreciate ;-)

**Comment by mkoeppe** [comment]
> find a solution here

I think this is pretty much at the center here. Here on this Issue ("NEP 29"), there is no problem that needs a solution.

**Comment by dimpase** [comment]
Sorry, Matthias, but this is not a personal attack or a speculation about your limitations.
You keep referring to some stuff you wrote, which does not read convincing to me (or other people) at all. 

It's not the 1st time you are stalling on a pretty clear ticket/issue/PR for no good reason, e.g. #32532 (well, show me one project of a similar to Sage scope which ships a copy of C/C++compiler to install, just in case...), and it makes me think that I shoud quit the project all together, just to take care of my nerves.

**Comment by mkoeppe** [comment]
> You keep referring to some stuff you wrote, which does not read convincing to me 

I'm pretty sure that you still haven't read, or you would be able to respond in a more specific way.

> (or other people) 

citation needed.

**Comment by mkoeppe** [comment]
> It's not the 1st time you are stalling on a pretty clear ticket/issue/PR for no good reason, e.g. #32532

"Stalling" presumes that you're right about the timing. "pretty clear ticket" presumes the same thing. And "no good reason" - that's projection; re-read https://groups.google.com/g/sage-devel/c/NfUKjAaTcUg/m/S3EDS0odBQAJ (my post https://groups.google.com/g/sage-devel/c/NfUKjAaTcUg/m/t4X27EefAwAJ gives plenty of detailed reasons). 
The problem with your recurring thing regarding gcc/gfortran is that you have never formulated any plan for the next steps after that. And as I have explained in that thread, in the post https://groups.google.com/g/sage-devel/c/NfUKjAaTcUg/m/GLMxIirPAwAJ:
*  The big problem is that the middle ground between "Complete Sage distribution that works in most use cases" and "No Sage distribution" is worse than both of the extremes. By removing spkgs one by one, we would make the Sage distribution less useful.
But this is off topic in this Issue here, so I won't comment further.

**Comment by mkoeppe** [comment]
> just to take care of my nerves

I have a number of open PRs for which the reviewing process will have a guaranteed calming and satisfying effect~ #35476 #35477 #35306

**Comment by dimpase** [comment]
> you have never formulated any plan for the next steps after that

the plan after any outdated feature removal is "to live happily ever after".

**Comment by vbraun** [comment]
NEP26 already has as suggested text for the development guidelines, which is rather different than the proposed one. NEP26 only talks about "minimum", and not "maximum" suported versions.

**Comment by tobiasdiez** [comment]
We first had the exact same wording of NEP 29 but changed it in https://github.com/sagemath/sage/commit/edf1711828659e3ac6914a9d9f021e9f38a27375. This was done 
- to include the [drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) of NEP 29. This was important to me.
- because we cannot really ensure that sage supports the latest python version the day it is released (thus making the sentence "This project supports all minor versions of Python released 42 months prior to the project" potentially wrong until support for the latest version is established). I remember this clarification was important to Matthias.

Maybe something like the following is incorporating these two points while still being closer to the suggested formulation of NEP 29? What do you think?

> We follow the guidelines outlined in NEP 29 for dropping support for older versions of Python. Specifically, we support all minor versions of Python released 42 months prior to the project, as well as the two latest minor versions. If at the anticipated release date of the next Sage version, a Python version is no longer included in this set, we usually drop support for it early in the release cycle.  

>The drop schedule for Python versions is as follows:

>Support for Python 3.9 (initially released in October 2020) is dropped in April 2024.
>Support for Python 3.10 (initially released in October 2021) is dropped in April 2025.

> While we make our best effort to support the latest version of Python, we cannot guarantee that our software works with the latest version at all times. This is due to the fact that new versions of Python may introduce breaking changes or other issues that we cannot anticipate.
>By following this policy, we aim to provide our users with a stable and reliable software experience, while also keeping up with the latest developments in the Python ecosystem.

**Comment by mkoeppe** [comment]
> We first had the exact same wording of NEP 29 but changed it in [edf1711](https://github.com/sagemath/sage/commit/edf1711828659e3ac6914a9d9f021e9f38a27375). This was done
> 
> * to include the [drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) of NEP 29. This was important to me.
> * because we cannot really ensure that sage supports the latest python version the day it is released (thus making the sentence "This project supports all minor versions of Python released 42 months prior to the project" potentially wrong until support for the latest version is established). I remember this clarification was important to Matthias.

For the record (or rather, summary of the existing record): I have never endorsed any wording that prescribes a drop schedule. 
In https://github.com/sagemath/sage/issues/30384#issuecomment-1418097211 (Dec 2021), I wrote: "I'm -1 on this. I think the experience in this release cycle has confirmed that the project is not in a position to commit to a rigid version support policy."

**Comment by vbraun** [comment]
The "drop schedule" is the earliest time where a version can be dropped, not the time at which a version must be dropped or else.  IMHO NEP 26 could be clearer on that and not just paste in an auto-generated table, but since they are careful to spell out **"at minimum the X latest versions"** elsewhere I think a close reading makes that rather clear.

We can't mathematically prove that Sage supports each Python version the day it is released, but if its not then that is a bug that needs addressing. Really that is what a support policy is, a statement of what you intend.

**Comment by tobiasdiez** [comment]
> The "drop schedule" is the earliest time where a version can be dropped, not the time at which a version must be dropped or else. IMHO NEP 26 could be clearer on that and not just paste in an auto-generated table, but since they are careful to spell out **"at minimum the X latest versions"** elsewhere I think a close reading makes that rather clear.

Fair enough. But I think we all agree that, although it doesn't hurt, there is no real need to formalize the minimum supported Python version for sage (at least no one proposed so far to drop versions still supported by NEP29) while - at least for me - there is real benefit in having a policy that specifies when we usually drop a Python version. Not as a hard requirement to drop it at exactly that day, but as a guideline for when a dropping PR is normally accepted, and there need to be good reasons to delay it.

**Comment by mkoeppe** [comment]
> But I think we all agree that, although it doesn't hurt, there is no real need to formalize the minimum supported Python version for sage

We don't agree on this. For the project to declare that it follows NEP 29 (in the sense that it commits to supporting at least all NEP-29-supported Python versions) has real benefits:
- It declares that the project has the intention/ambition to be part of the scientific Python ecosystem. This is very important because historically it was simply not. Sage was (and to large extent still is!) its own separate community, disconnected from the scientific Python world in various ways.
- It clarifies that the project does not have the goal/obligation to support all Python versions all the way to their end of life. This gives maintainers the discretion to make a good decision on when to drop a particular Python version.

These two points are why I opened https://github.com/sagemath/sage/issues/30384 back in 2020.

**Comment by dimpase** [comment]
there are obvious benefits in becoming a community member. 

Saying that historically Sage was not a member does not mean it has to continue to be so, and if you disagree, you can either call a vote on it, or just fork Sage and be your own boss.

**Comment by vbraun** [comment]
NEP 29 is now superseded by https://scientific-python.org/specs/spec-0000/ so at least that needs updating
* Maybe not mention any particular dates (ages like milk), just link to external documents for time tables
* I don't really see where the disagreement here is, can you just agree on a good enough formulation

**Comment by mkoeppe** [comment]
For this one, we had started a longer discussion on sage-devel. 
There's a page at https://github.com/sagemath/sage/wiki/NEP-29:-Python-version-strategy with many details.

This needs to be resolved by bringing this back to sage-devel, definitely not by just merging a PR.

**Comment by dimpase** [comment]
I'd rather delegate the task of deciding this to @vbraun 

Discussions on any topic Matthias has an opinion deviating from other's people opinions lead to a riot lately.

**Comment by tobiasdiez** [comment]
> NEP 29 is now superseded by https://scientific-python.org/specs/spec-0000/ so at least that needs updating
> 
>     * Maybe not mention any particular dates (ages like milk), just link to external documents for time tables
> 
>     * I don't really see where the disagreement here is, can you just agree on a good enough formulation

Thanks a lot for these suggestions! I've now changed this PR to use Spec-0 and referred to Spec-0 for the specific dates.
Spec-0 is also very clear in its formulation (e.g. it explicitly uses "drop schedule") which should resolve the concerns raised in the past about the NEP29 version. Thus, I think we can remove the "disputed" flag.

**Review by dimpase — APPROVED** [review]

**Pull request merged**
