### PR TITLE
update msolve to 0.4.9

### PR DESCRIPTION
**Pull request by dimpase**
update to a new version

### CODE REVIEW

**Comment by dimpase** [comment]
I've asked them to start uploading configured tarballs: https://github.com/algebraic-solving/msolve/issues/36

**Comment by dimpase** [comment]
I'm hosting configured tarball on a GitHub fork, for the time being.

**Comment by dimpase** [comment]
upstream provided a proper tarball: https://github.com/algebraic-solving/msolve/issues/36

**Comment by mkoeppe** [comment]
Works fine on macOS.

**Review by mkoeppe — APPROVED** [review]

**Pull request merged**
