### PR TITLE
Upgrade scipy to 1.10.1

### LINKED ISSUE #34842: Upgrade scipy to 1.10.x
<div id="comment:0"></div>

1.10.0 is out - https://github.com/scipy/scipy/releases

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/34842_

### PR DESCRIPTION
**Pull request by mkoeppe**
### 📚 Description

The upgrade also includes upgrades of `meson`, `meson_python`, and `pythran`. 

Closes #34842

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
doctest failure in `doc/de/a_tour_of_sage/index.rst` is unrelated

**Comment by kiwifb** [comment]
Looks good to me and scipy 1.10.0 works fine here.

**Review by kiwifb — APPROVED** [review]
Looks good to me.

**Comment by kiwifb** [comment]
Let me know if that was an abuse of the workflow.

**Comment by mkoeppe** [comment]
Starting a review and approving the changes is exactly the right procedure. Thanks!

**Comment by kiwifb** [comment]
It wouldn't be the first time that numpy or scipy gives us a small change in a minor release, so I am doing some more checks.

**Review by kiwifb — APPROVED** [review]
I cannot see any problem with it. Once I removed all the warnings I got from matplotlib 3.7.0.

**Comment by mkoeppe** [comment]
Thanks! Also works without problems on macOS

**Comment by vbraun** [comment]
Doesn't build on OSX for me:
```
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_
process.py", line 144, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_
process.py", line 351, in <module>
      main()
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_
process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_
process.py", line 148, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/meson_python-0.12.1/src/mesonpy/__init__.py"
, line 1054, in wrapper
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/meson_python-0.12.1/src/mesonpy/__init__.py"
, line 1115, in build_wheel
      with _project(config_settings) as project:
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/contextlib.py", line 137, in __enter__
      return next(self.gen)
             ^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/meson_python-0.12.1/src/mesonpy/__init__.py"
, line 1011, in _project
      with Project.with_temp_working_dir(
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/contextlib.py", line 137, in __enter__
      return next(self.gen)
             ^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/meson_python-0.12.1/src/mesonpy/__init__.py", line 785, in with_temp_working_dir
      yield cls(source_dir, tmpdir, build_dir, meson_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/meson_python-0.12.1/src/mesonpy/__init__.py", line 588, in __init__
      arch, *other = filter(None, (x.strip() for x in archflags.split('-arch')))
      ^^^^^^^^^^^^
  ValueError: not enough values to unpack (expected at least 1, got 0)
  error: subprocess-exited-with-error
  
  <C3><97> Preparing metadata (pyproject.toml) did not run successfully.
  <E2><94><82> exit code: 1
  <E2><95><B0><E2><94><80>> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/bin/python3 /Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpz5dlgfng

```

**Comment by mkoeppe** [comment]
I think this is misconfigured on your buildbot. Do you set ARCHFLAGS to the empty string?
https://github.com/mesonbuild/meson-python/blob/release-0.12/mesonpy/__init__.py#L586

**Comment by mkoeppe** [comment]
Anyway I'm working on a PR for meson-python that makes this more robust

**Pull request merged**
