### PR TITLE
Changing the knot theory PD-code convention

### PR DESCRIPTION
**Pull request by soehms**
### :books: Description

According to a discussion following [this comment of last February]( https://github.com/sagemath/sage/issues/17030#issuecomment-1429244168) in https://github.com/sagemath/sage/issues/17030 this PR implements the transition of the PD-code convention from clockwise to anti-clockwise.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by tscrim — APPROVED** [review]
@miguelmarco I am assuming from the positive review you also meant to approve this.

Also LGTM.

**Comment by NathanDunfield** [comment]
What version of Sage is this likely to appear in?  We're about to do a release of SnapPy and want correctly convert from Sage's Link to SnapPy's depending on the Sage version.

**Comment by tscrim** [comment]
@NathanDunfield It almost certainly should get into 10.1, but I couldn't say which beta version (although there is a reasonable possibility it is the next one).

**Comment by soehms** [comment]
> @miguelmarco I am assuming from the positive review you also meant to approve this.
> 
> Also LGTM.

Many thanks to you both!

**Comment by soehms** [comment]
> @NathanDunfield It almost certainly should get into 10.1, but I couldn't say which beta version (although there is a reasonable possibility it is the next one).

I was hoping to do it for version 10.0, but unfortunately too much was preventing me from achieving that goal.

**Comment by NathanDunfield** [comment]
@soehms @tscrim: Thanks for the clarification.  I have future-proofed SnapPy for this change in https://github.com/3-manifolds/Spherogram/commit/d0ce3de3253

**Comment by soehms** [comment]
> > > @soehms @tscrim: Thanks for the clarification. I have future-proofed SnapPy for this change in [3-manifolds/Spherogram@d0ce3de3253](https://github.com/3-manifolds/Spherogram/commit/d0ce3de3253)
> > > Great! Do you already know when it will be released? I think we should upgrade the `SPKG` afterwards to the new version, as well.
> 
> SnapPy 3.1 with Spherogram 2.2 which supports this PD change in Sage was released yesterday on PyPI and Github.

In fact, this was a last minute opportunity. Thanks very much!

**Comment by NathanDunfield** [comment]
> > SnapPy 3.1 with Spherogram 2.2 which supports this PD change in Sage was released yesterday on PyPI and Github.
> 
> In fact, this was a last minute opportunity. Thanks very much!

You're very welcome.

**Comment by vbraun** [comment]
Merge conflict

**Comment by vbraun** [comment]
Sorry, ticket number off by one ;)

**Comment by soehms** [comment]
> > > @soehms @tscrim: Thanks for the clarification. I have future-proofed SnapPy for this change in [3-manifolds/Spherogram@d0ce3de3253](https://github.com/3-manifolds/Spherogram/commit/d0ce3de3253)
> > > Great! Do you already know when it will be released? I think we should upgrade the `SPKG` afterwards to the new version, as well.
> 
> SnapPy 3.1 with Spherogram 2.2 which supports this PD change in Sage was released yesterday on PyPI and Github.

@NathanDunfield, it seems that this commit did not find its way into the Spherogram 2.2 release:


```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1.beta3, Release Date: 2023-06-11              │
│ Using Python 3.8.10. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

sage: import spherogram
sage: spherogram.version()
'2.2'
sage: L = spherogram.Link('K10n11')
sage: L.PD_code()
[(2, 0, 3, 19),
 (0, 6, 1, 5),
...
 (18, 14, 19, 13)]
sage: L.sage_link().pd_code()
[[3, 20, 4, 1],
 [1, 6, 2, 7],
...
 [19, 14, 20, 15]]
sage:
sage: spherogram.Link.sage_link??
Signature: spherogram.Link.sage_link(self)
Docstring:
   Convert to a SageMath Knot or Link:

      sage: L = Link('K10n11')   # Spherogram link
      sage: K = L.sage_link(); K
      Knot represented by 10 crossings
...
        if SageKnot is None:
            raise ValueError('Your SageMath does not seem to have a native link type')
        sage_type = SageKnot if len(self.link_components) == 1 else SageLink
        # Sage's PD_code lists strands *clockwise* not our *anticlockwise*.
        code = [[x[0], x[3], x[2], x[1]] for x in self.PD_code(min_strand_index=1)]
        return sage_type(code)
File:      ~/devel/sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/spherogram/links/invariants.py
Type:      function
```

**Comment by NathanDunfield** [comment]
Sorry, it seems I only fixed one of the directions (sage -> spherogram) and not the other (spherogram -> sage).  I believe I have fixed `sage_link` in [here](https://github.com/3-manifolds/Spherogram/commit/946ee3e8644d08e020147361d6744c5cb8a544da).  Could you please test it out before I release it as 2.2.1?

**Comment by soehms** [comment]
> Sorry, it seems I only fixed one of the directions (sage -> spherogram) and not the other (spherogram -> sage). 

No problem! Indeed, your new code was not contained in the former commit.

> I believe I have fixed `sage_link` [here](https://github.com/3-manifolds/Spherogram/commit/946ee3e8644d08e020147361d6744c5cb8a544da). Could you please test it out before I release it as 2.2.1?

It works! Many Thanks!

**Comment by NathanDunfield** [comment]
@soehms As a final check, could you do the following with `Sage 10.1.beta3`:
```
sage -python -m sphereogram.test
```
You should see:
```
[...]
All doctests:
   0 failures out of 458 tests.
[...]
OK
```
Thanks.

**Comment by soehms** [comment]
> @soehms As a final check, could you do the following with `Sage 10.1.beta3`:

All tests passed, too!

**Comment by NathanDunfield** [comment]
Thanks, I've released Spherogram 2.2.1 on PyPI.

**Comment by soehms** [comment]
> Thanks, I've released Spherogram 2.2.1 on PyPI.

Thanks! Now, some optional doctests concerning SnapPy needs work on Sage side. I will open a corresponding follow up PR soon.

**Comment by soehms** [comment]
> I will open a corresponding follow up PR soon.

This is #35755, now.

**Pull request merged**
