### PR TITLE
`tox.ini`, `.github/workflows`, `.devcontainer`: Remove centos-stream-8 (EOL)

### PR DESCRIPTION
**Pull request by mkoeppe**
This platform reached its EOL on 2024-05-31. https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

It can no longer be tested, as seen in https://github.com/sagemath/sage/actions/runs/9435864412/job/25989853211

We remove it.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
> It can no longer be tested, as seen in https://github.com/sagemath/sage/actions/runs/9435864412/job/25989853211

What should I see there? No python 3 support?

**Comment by mkoeppe** [comment]
Here:
```
#5 [with-system-packages 2/2] RUN  EXISTING_PACKAGES=""; for pkg in python39 python39-devel binutils make m4 python3 perl perl-ExtUtils-MakeMaker tar gcc gcc-c++ findutils which diffutils perl-IPC-Cmd boost-devel brial brial-devel bzip2 bzip2-devel cddlib cliquer cliquer-devel cmake libcurl-devel curl ecl eclib eclib-devel gmp-ecm gmp-ecm-devel fflas-ffpack-devel flint flint-devel libfplll libfplll-devel gap gap-core gap-devel gap-libs libgap gc gc-devel gcc gcc-c++ gcc-gfortran gengetopt gf2x gf2x-devel gfan gcc-gfortran giac giac-devel givaro givaro-devel glpk glpk-devel glpk-utils gmp gmp-devel gsl gsl-devel iml iml-devel texinfo info L-function-devel L-function libatomic_ops libatomic_ops-devel libbraiding-devel libffi libffi-devel gd gd-devel libhomfly-devel xz xz-devel linbox-devel lrcalc-devel m4ri-devel m4rie-devel maxima-runtime-ecl maxima meson libmpc libmpc-devel mpfr-devel nauty ncurses-devel ninja-build ntl-devel openblas-devel openssl openssl-devel palp pari-devel pari-gp --setopt=tsflags= pari-galdata pari-galpol pari-seadata pari-elldata pari-galdata patch patchelf pkg-config planarity planarity-devel ppl ppl-devel primecount primecount-devel primesieve-devel primesieve python3-devel python3-setuptools qhull qhull-devel readline-devel rw-devel Singular Singular-devel sqlite-devel sqlite suitesparse suitesparse-devel symmetrica-devel sympow tachyon tachyon-devel tox xz zeromq zeromq-devel zlib-devel autoconf automake libtool pkg-config python3.9 python3.9-devel autoconf automake libtool pkg-config xz xz-devel bzip2 bzip2-devel libffi libffi-devel zlib-devel; do echo -n .; if 2>/dev/null >/dev/null yum install -y --downloadonly $pkg; then EXISTING_PACKAGES="$EXISTING_PACKAGES $pkg"; echo -n "$pkg"; fi; done; yum install -y $EXISTING_PACKAGES || (echo "Trying again one by one:"; for pkg in $EXISTING_PACKAGES; do echo "Trying to install $pkg"; yum install -y $pkg || echo "(ignoring error)"; done); :
#5 0.175 .........................................................................................................................................................usage: yum install [-c [config 
````
The line with the dots indicates that not any package was found in the package repository.
(Every dot is a package tried; and when a package is found, its name would be printed.)

**Comment by kwankyu** [comment]
I see. So they stopped providing their packages to this distribution. That is very drastic...

**Review by kwankyu — APPROVED** [review]
OK. LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
