### PR TITLE
libatomic_ops: Update to 7.8.0

### PR DESCRIPTION
**Pull request by ivmai**
### :books: Description

This is an update to the latest stable release of libatomic_ops.
I'm the upstream maintainer of the package.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
@ivmai welcome here, and thanks!
Our automatic tests won't build the package, but you can run our full portability test suite by enabling GH Actions in your github fork of sage and then pushing a tag.

**Comment by ivmai** [comment]
> @ivmai welcome here, and thanks! Our automatic tests won't build the package, but you can run our full portability test suite by enabling GH Actions in your github fork of sage and then pushing a tag.

Hello @mkoeppe,
Okay, I will run the full test suite but I see that documentation building is failed but I can't see the details. Could you please advise me how to fix the build?

**Comment by mkoeppe** [comment]
> I see that documentation building is failed but I can't see the details

These are bugs in our CI, unrelated to your change

**Comment by ivmai** [comment]
> Our automatic tests won't build the package, but you can run our full portability test suite by enabling GH Actions in your github fork of sage and then pushing a tag.

If I understood correctly, I did it: https://github.com/ivmai/sagemath-sage/actions/runs/4572075412 - success
Do I need to check anything else?

**Comment by dimpase** [comment]
"merging is blocked" is  standard in this repo, as it's the job of the release manager to actually deal with merging positively reviewer PRs into the mainline.

**Comment by dimpase** [comment]
platform tests: 
https://github.com/dimpase/sage/actions/runs/5266441122 (Linux) and
https://github.com/dimpase/sage/actions/runs/5266451418 (macOS)

**Pull request merged**
