### PR TITLE
Various Python package upgrades

### PR DESCRIPTION
**Pull request by mkoeppe**
and incidental updates to the `sage --package` script 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by vbraun** [comment]
Error message for `exceptiongroup` changed
```
`**********************************************************************
File "src/sage/databases/symbolic_data.py", line 184, in sage.databases.symbolic_data.SymbolicData.__getattr__
Failed example:
    sd.Cyclic5 # optional - database_symbolic_data
Expected:
    Traceback (most recent call last):
    ...
    AttributeError: No ideal matching 'Cyclic5' found in database.
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/databases/symbolic_data.py", line 150, in get_ideal
        open(name)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/buildbot/slave/sage_git/build/local/share/symbolic_data/Data/XMLResources/INTPS/Cyclic5.xml'
    <BLANKLINE>
    During handling of the above exception, another exception occurred:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/databases/symbolic_data.py", line 154, in get_ideal
        open(name)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/buildbot/slave/sage_git/build/local/share/symbolic_data/Data/XMLResources/GenPS//var/lib/buildbot/slave/sage_git/build/local/share/symbolic_data/Data/XMLResources/INTPS/Cyclic5.xml.xml'
    <BLANKLINE>
    During handling of the above exception, another exception occurred:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.symbolic_data.SymbolicData.__getattr__[1]>", line 1, in <module>
        sd.Cyclic5 # optional - database_symbolic_data
        ^^^^^^^^^^
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/databases/symbolic_data.py", line 196, in __getattr__
        return self.get_ideal(name)
               ^^^^^^^^^^^^^^^^^^^^
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/databases/symbolic_data.py", line 156, in get_ideal
        raise AttributeError("No ideal matching '%s' found in database." % orig_name)
    AttributeError: No ideal matching 'Cyclic5' found in database.. Did you mean: 'Cyclic_5'?
**********************************************************************
1 item had failures:
   1 of   4 in sage.databases.symbolic_data.SymbolicData.__getattr__
    [13 tests, 1 failure, 0.08 s]
----------------------------------------------------------------------
sage -t --long --random-seed=0 src/sage/databases/symbolic_data.py  # 1 doctest failed
----------------------------------------------------------------------
```

**Comment by mkoeppe** [comment]
What's this got to do with `exceptiongroup`? Sure you tested this optional package before?

**Comment by mkoeppe** [comment]
Anyway, here's a fix

**Comment by vbraun** [comment]
Yes, that optional package is on one of the buildbots

**Comment by mkoeppe** [comment]
Then what's new is probably that you're testing it with python 3.12

**Pull request merged**
