### PR TITLE
Improve camera positioning for threejs

### LINKED ISSUE #34822: Better position the camera in 3d graphics
<div id="comment:0"></div>

Compare "before" and "after" of 

```sage
var('x,y,z')
implicit_plot3d((sqrt(x*x+y*y)-3)^2 + z*z - 1, (x,-4,4), (y,-4,4), (z,-1,1))
```
by the initial view and rotated views.

Component: **graphics**

Author: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34822_

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #34822.

The template says that we are not yet accepting PRs. But I will just go ahead.

### CODE REVIEW

**Comment by kwankyu** [comment]
I cannot apply labels.

**Comment by dimpase** [comment]
I just added a label (but I have more rights). 

You don't see a list when you click on the wheel, or you do see them, but can't added them?

**Comment by dimpase** [comment]
I'm really not sure why you can't do anything with labels - according to GitHub docs, it does not need more permissions than you already have: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by dimpase** [comment]
oops, sorry, you need a "triage access" to repo to apply labels:
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by kwankyu** [comment]
What the hell is this Codecov comment? Spammer already?

**Comment by kwankyu** [comment]
> You don't see a list when you click on the wheel, or you do see them, but can't added them?

I don't see the wheel.

**Comment by kwankyu** [comment]
This "Codecov Report" is extravagant. I wish that that is moved to the checks, somehow.

**Comment by dimpase** [comment]
How can this be reviewed? Is this visible somewhere in the docs?

**Comment by kwankyu** [comment]
No. We should see interactive 3d graphics "before" and "after".

**Comment by kwankyu** [comment]
As the code is small, you may copy and paste the code directly into your local develop branch, and test the example in the linked issue. No need to compile anything.

**Review by dimpase — APPROVED** [review]
lgtm. I tried the snippet provided, all good.

**Comment by kwankyu** [comment]
Thank you!

**Pull request merged**
