### PR TITLE
activate W293 and E714 in pyx files

### PR DESCRIPTION
**Pull request by fchapoton**
### 📚 Description

This fixes and activate the pycodestyle warnings

W293: blank line contains whitespace

and

E714: Test for object identity should be 'is not'

in all .pyx files inside src/sage

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fchapoton** [comment]
Merci David. Faut approuver, je crois, pour que ça soit fusionné.

**Review by dcoudert — APPROVED** [review]
I agree with these changes

**Comment by vbraun** [comment]
merge conflict

**Comment by fchapoton** [comment]
setting back to positive after trivial merge

**Comment by dcoudert** [comment]
Was about to do it. LGTM.

**Pull request merged**
