### PR TITLE
`src/sage/graphs`: some care with `# optional`

### PR DESCRIPTION
**Pull request by dcoudert**
Unify the syntax and ensure that we have 2 spaces before `# optional`.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by fchapoton — APPROVED** [review]
ok, let's go

**Comment by fchapoton** [comment]
well, there are some failing doctests

**Comment by dcoudert** [comment]
> well, there are some failing doctests that could be related

I suspect this is related to nauty and has nothing to do with this PR. I don't see these errors on macOS or Fedora 35...

**Comment by fchapoton** [comment]
ok, then

**Comment by dcoudert** [comment]
Thanks.

**Pull request merged**
