### PR TITLE
Fix ginac's ratlog method so log(int(0),2) does not hang

### LINKED ISSUE #37794: Computing log(int(0), 2) takes a long time (same as #29164 but with python int)
### Steps To Reproduce

```py
log(int(0), 2)
```

### Expected Behavior

```py
-Infinity
```

### Actual Behavior

Sage runs for a long time and cannot be killed with Ctrl+C (I need to call `kill <sage pid> <python3 pid>`  to stop everything)

### Additional Information

It looks like a duplicate of #29164 but there is a subtle difference: In #29164 the 0 is a Sage integer, here the 0 is a python integer.

Variants that work:
```py
sage: log(ZZ(0), 2)
-Infinity
sage: log(0.0, 2)
-infinity
sage: log(ZZ(0))
-Infinity
sage: log(int(0))
-Infinity
```

### Environment

```markdown
- **OS**: Debian
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by DaveWitteMorris**
Fixes #37794.

It is explained in #37794 that calculating the logarithm of `int(0)` (zero represented as a python integer) can enter an infinite loop, due to a bug in ginac's `numeric::ratlog` method. This PR adds an `if` statement to return negative infinity for this value. (At this point in the code, the base of the logarithm is known to be a positive integer that is greater than 1, so the log of 0 is negative infinity, not positive infinity.)

The PR also adds `log(int(0), 2)` as a doctest and, for good measure, also `log(int(0), 1/2)`.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by user202729** [comment]
Technically this makes the comment of the method incorrect (?)  it says

```
// General log
// Handle special cases here that return MPZ/MPQ
```

an infinity is not a MPZ/MPQ. But then there's also a `py_funcs.py_eval_unsigned_infinity()` returned in the function, so easiest method is probably to modify the comment as well (` and a few other easy cases`?).

**Comment by DaveWitteMorris** [comment]
Good point. I think it makes sense to just add "(or an infinity)" at the end. How does that sound?

**Comment by user202729** [comment]
Sounds good.

**Review by yyyyx4 — APPROVED** [review]
Looks good to me.

**Pull request merged**
