### PR TITLE
`build/pkgs/tdlib`: Update to 0.9.3

### LINKED ISSUE #30813: try to upgrade tdlib
<div id="comment:0"></div>

tdlib appears in development, at https://github.com/freetdi/tdlib - now at version 0.9.

Not sure whether it it easy to upgrade, but one should try.

CC:  @dcoudert @sagetrac-llarisch

Component: **packages: optional**

_Issue created by migration from https://trac.sagemath.org/ticket/30813_

### PR DESCRIPTION
**Pull request by mkoeppe**
- FIxes #30813

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38144 (merged here for testing)

### CODE REVIEW

**Comment by mkoeppe** [comment]
with boost_cropped from SPKG:
```
[tdlib-0.9.1] [spkg-install] checking for boost/tuple/tuple.hpp... yes
[tdlib-0.9.1] [spkg-install] checking for main in -lboost_system... no
[tdlib-0.9.1] [spkg-install] configure: error: Unable to find Boost System library
```

**Comment by mkoeppe** [comment]
with boost from homebrew, boost_system is found but:
```
configure:16743: checking for main in -lboost_thread
configure:16762: g++ -std=gnu++11 -o conftest -g -O2 -std=c++11  -L/Users/mkoeppe/s/sage/sage-rebasing/local/lib -L/Users/mkoeppe/s/sage/sage-rebasing/local/lib  -Wl,-ld_classic conftest.cpp -lboost_thread  -lboost_system  >&5
ld: library not found for -lboost_thread
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by felix-salfelder** [comment]
I am not sure what -mt is, and why the plain one is missing. Are they interchangeable?

The cython bindings should not require boost_thread. Consider removing the test from configure.

**Comment by mkoeppe** [comment]
Do you think we can also get rid of `boost_system`?

**Comment by mkoeppe** [comment]
Wait, is this whole thing header-only?

**Comment by felix-salfelder** [comment]
On Thu, Jun 06, 2024 at 06:30:23PM -0700, Matthias Köppe wrote:
> Do you think we can also get rid of `boost_system`?

Yes. Probably configure should succeed regardless, and tdecomp
compilation should be made conditional on the check.

tdlib should build/link/work either way, please try.

I'll look closer and do the changes when I find the time.

**Comment by mkoeppe** [comment]
Perhaps disable the check for boost_system, boost_thread on `--without-gala`, which turns off TDECOMP?

**Comment by mkoeppe** [comment]
```
From 63a7306e5c8a5904b79497f04139fd1d9c96bf6a Mon Sep 17 00:00:00 2001
From: Matthias Koeppe <mkoeppe@math.ucdavis.edu>
Date: Thu, 6 Jun 2024 19:11:18 -0700
Subject: [PATCH] configure.ac: Only check for boost_system, boost_thread when
 configured --with-gala

---
 configure.ac | 25 +++++++++++++------------
 1 file changed, 13 insertions(+), 12 deletions(-)

diff --git a/configure.ac b/configure.ac
index ea36ffb..a643c50 100644
--- a/configure.ac
+++ b/configure.ac
@@ -133,23 +133,24 @@ CXXFLAGS="-std=c++11 $CXXFLAGS"
 AC_CHECK_HEADERS([boost/tuple/tuple.hpp], [],
                  AC_MSG_ERROR([could not find a boost header])
 )
-AC_CHECK_LIB([boost_system], [main], ,
-             [AC_MSG_ERROR([Unable to find Boost System library])])
-AC_CHECK_LIB([boost_thread], [main], ,
-             [AC_MSG_ERROR([Unable to find Boost Thread library])])
 
 have_gala=no
 
 AC_ARG_WITH([gala], AS_HELP_STRING([--without-gala], [Disable gala]))
 
-AS_IF([test "x$with_gala" != xno], [
-	AC_CHECK_HEADERS([gala/graph.h],
-	                 [ have_gala=yes ],
-	                   AC_MSG_NOTICE([consider installing gala])
-	)
-   AS_IF([test "x$with_gala" = xyes -a x$have_gala = xno], [
-									 AC_MSG_ERROR([gala not found, but set])
-		 ])
+AS_IF([test "x$with_gala" != xno], [dnl
+    AC_CHECK_HEADERS([gala/graph.h],
+                     [have_gala=yes
+                      AC_CHECK_LIB([boost_system], [main], ,
+                                   [AC_MSG_ERROR([Unable to find Boost System library, required when building --with-gala])])
+                      AC_CHECK_LIB([boost_thread], [main], ,
+                                   [AC_MSG_ERROR([Unable to find Boost Thread library, required when building --with-gala])])
+                     ], [dnl
+                      AC_MSG_NOTICE([consider installing gala])
+                     ])
+    AS_IF([test "x$with_gala" = xyes -a x$have_gala = xno], [dnl
+      AC_MSG_ERROR([gala not found, but set])
+    ])
 ])
 
 AM_CONDITIONAL([USE_GALA], [test $have_gala = yes])
-- 
2.42.0

```

@felix-salfelder Or I can send a PR/MR if that's better

**Comment by felix-salfelder** [comment]
On Thu, Jun 06, 2024 at 07:14:10PM -0700, Matthias Köppe wrote:
> >From 63a7306e5c8a5904b79497f04139fd1d9c96bf6a Mon Sep 17 00:00:00 2001
> From: Matthias Koeppe ***@***.***>
> Date: Thu, 6 Jun 2024 19:11:18 -0700
> Subject: [PATCH] configure.ac: Only check for boost_system, boost_thread when
>  configured --with-gala

The checks need to stay independent. I fixed the logic a little --
"develop" might just work for you as well.

I don't like the way LIBS is set globally by AC_CHECK_LIBS. Another
time...

**Comment by mkoeppe** [comment]
Thanks, current `develop` looks fine.
Would you be able to tag a release for us?

**Comment by mkoeppe** [comment]
With the current branch here on the PR, it appears to work well on `fedora-40-standard` (where system boost is sufficiently complete) - https://github.com/sagemath/sage/actions/runs/9409800932/job/25920443039?pr=38163

**Comment by mkoeppe** [comment]
@felix-salfelder We are getting "incomplete" messages from treedec; any hints?
```
#31 1648.0 sage -t --random-seed=337449480174168605145312330960030599944 src/sage/graphs/graph_decompositions/tdlib.pyx
#31 1648.0 **********************************************************************
#31 1648.0 File "src/sage/graphs/graph_decompositions/tdlib.pyx", line 142, in sage.graphs.graph_decompositions.tdlib.treedecomposition_exact
#31 1648.0 Failed example:
#31 1648.0     T = tdlib.treedecomposition_exact(G)
#31 1648.0 Expected nothing
#31 1648.0 Got:
#31 1648.0     incomplete ../../src/exact_cutset.hpp:978:try_it
#31 1648.0 **********************************************************************
#31 1648.0 File "src/sage/graphs/graph_decompositions/tdlib.pyx", line 184, in sage.graphs.graph_decompositions.tdlib.get_width
#31 1648.0 Failed example:
#31 1648.0     T = tdlib.treedecomposition_exact(G)
#31 1648.0 Expected nothing
#31 1648.0 Got:
#31 1648.0     incomplete ../../src/exact_cutset.hpp:978:try_it
#31 1648.0 **********************************************************************
```

**Comment by felix-salfelder** [comment]
On Fri, Jun 07, 2024 at 11:30:50AM -0700, Matthias Köppe wrote:
> @felix-salfelder We are getting "incomplete" messages from treedec; any hints?

That's been added during refactoring for speed in 2017, 54db402c8e614.
Frankly I don't remember in detail.

Chances are, results are unaffected. If the "incomplete" interferes with
testing in sage, ignore stderr or comment out the line. Life is short,
and there are faster algorithms. ex17 is ready, and more is to come...

**Comment by dcoudert** [comment]
I tried on fedora 39 and did `sage -f tdlib`. Unfortunately, I still get
```
sage: G = Graph('I~~}qxxV_')
sage: G.treewidth(algorithm='tdlib')
6
sage: G.treewidth(algorithm='sage')
5
```
Since the graph `G` is a partial $k$-tree with $k=5$, is has treewidth at most 5.

**Comment by mkoeppe** [comment]
Be sure to do `make sagemath_tdlib`; see https://github.com/sagemath/sage/wiki/Sage-10.4-Release-Tour#configuration-changes

**Comment by felix-salfelder** [comment]
On Sat, Jun 08, 2024 at 03:05:26AM -0700, David Coudert wrote:
> I tried on fedora 39 and did `sage -f tdlib`. Unfortunately, I still get
> ```
> sage: G = Graph('I~~}qxxV_')
> sage: G.treewidth(algorithm='tdlib')
> 6
> sage: G.treewidth(algorithm='sage')
> 5
> ```
> Since the graph `G` is a partial $k$-tree with $k=5$, is has treewidth at most 5.

I have undusted cython and added a test to tdlib. see treedec develop
branch.

You might want to try this on fedora ("make -C tdlib check"). It may
need tweaking to expose the bug etc.

thanks

**Comment by dcoudert** [comment]
> Be sure to do `make sagemath_tdlib`; see https://github.com/sagemath/sage/wiki/Sage-10.4-Release-Tour#configuration-changes

It would be kind to have the install/test procedure inside the PR ;)

It's working well without error.

**Review by dcoudert — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by mkoeppe** [comment]
Update PRs are not in charge of adding such tests

**Comment by mkoeppe** [comment]
Just open a PR for adding this.

**Comment by mkoeppe** [comment]
I've removed the claim regarding #38159 from the PR description.
I'll leave investigating this to interested third parties.

**Comment by saraedum** [comment]
It appears that there is disagreement over whether this "needs work" or not. I understand that @dimpase has outlined his points in the comments in https://github.com/sagemath/sage/issues/38192 and https://github.com/sagemath/sage/issues/38190. It appears to me that this is a "disputed" PR now.

**Pull request merged**
