### PR TITLE
`gmp` 6.3.0, `mpc` 1.3.1, `mpfr` 4.2.1, `mpfrcx` 0.6.3

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
```
  [gmp-6.3.0]   OSError: [Errno socket error] [Errno 110] Connection timed out
  [gmp-6.3.0]   
  [gmp-6.3.0]   During handling of the above exception, another exception occurred:
  [gmp-6.3.0]   
  [gmp-6.3.0]   Traceback (most recent call last):
  [gmp-6.3.0]     File "/sage/build/bin/../sage_bootstrap/download/cmdline.py", line 126, in run_safe
  [gmp-6.3.0]       run()
  [gmp-6.3.0]     File "/sage/build/bin/../sage_bootstrap/download/cmdline.py", line 108, in run
  [gmp-6.3.0]       app.download_tarball(args.url_or_tarball, args.destination, args.allow_upstream)
  [gmp-6.3.0]     File "/sage/build/bin/../sage_bootstrap/download/app.py", line 41, in download_tarball
  [gmp-6.3.0]       tarball.download(allow_upstream=allow_upstream)
  [gmp-6.3.0]     File "/sage/build/bin/../sage_bootstrap/tarball.py", line 180, in download
  [gmp-6.3.0]       raise FileNotMirroredError('tarball does not exist on mirror network and neither at the upstream URL')
  [gmp-6.3.0]   sage_bootstrap.tarball.FileNotMirroredError: tarball does not exist on mirror network and neither at the upstream URL
  [gmp-6.3.0]   ************************************************************************
  [gmp-6.3.0]   ************************************************************************
  [gmp-6.3.0]   Error downloading gmp-6.3.0.tar.xz
  [gmp-6.3.0]   ************************************************************************
```

**Comment by mkoeppe** [comment]
Because of the active countermeasures of gmplib.org, I've added the tarball as a release asset to https://github.com/sagemath/sage/releases/tag/10.2

**Comment by mkoeppe** [comment]
rebased

**Comment by dimpase** [comment]
> Because of the active countermeasures of gmplib.org, I've added the tarball as a release asset to https://github.com/sagemath/sage/releases/tag/10.2

so there is now a place tarballs are looked for? Any rules for that (i.e. are tags ignored) ?

**Comment by mkoeppe** [comment]
see https://github.com/sagemath/sage/blob/develop/.upstream.d/20-github.com-sagemath-sage-releases

**Comment by mkoeppe** [comment]
(You reviewed #36435, which added this.)

**Comment by dimpase** [comment]
` ModuleNotFoundError: No module named 'sage.libs.coxeter3.coxeter'` in Test all files

and quite a few failing tests due to it

is this a known error by now? I saw it elsewhere.

**Comment by mkoeppe** [comment]
> ` ModuleNotFoundError: No module named 'sage.libs.coxeter3.coxeter'` in Test all files
> 
> and quite a few failing tests due to it

Fixed in #36900

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by mkoeppe** [comment]
Thanks.

**Comment by vbraun** [comment]
I'm getting lots of testsuite fails on OSX around signs of NaN from the gmpy2 testsuite
```
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 515, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('nan'), a)
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('-nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?        +             +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 519, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('Inf'), G.mpz(0))
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?                     +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 523, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('nan'), G.mpz(0))
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('-nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?        +             +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] 1 items had failures:
[gmpy2-2.1.2]   25 of 230 in test_mpz.txt
[gmpy2-2.1.2] ***Test Failed*** 25 failures.
[gmpy2-2.1.2] Results for:  test_mpz                  Attempted:  230   Failed:   25
[gmpy2-2.1.2] Results for:  test_mpz_create           Attempted:   58   Failed:    0
[gmpy2-2.1.2] Results for:  test_mpz_io               Attempted:   60   Failed:    0
[gmpy2-2.1.2] Results for:  test_mpz_pack_unpack      Attempted:   16   Failed:    0
[gmpy2-2.1.2] 
[gmpy2-2.1.2]                               Summary - Attempted: 3556   Failed:   95
[gmpy2-2.1.2] 
[gmpy2-2.1.2] Running external test programs.
[gmpy2-2.1.2] Running test_pack.py                    successful
[gmpy2-2.1.2] Running test_mpz_args.py                successful
[gmpy2-2.1.2] 
[gmpy2-2.1.2] real	0m1.418s
[gmpy2-2.1.2] user	0m1.349s
[gmpy2-2.1.2] sys	0m0.049s
[gmpy2-2.1.2] ************************************************************************
[gmpy2-2.1.2] Error testing package gmpy2-2.1.2
[gmpy2-2.1.2] ************************************************************************
```

**Comment by mkoeppe** [comment]
I see these test failures in the gmpy2 tests also when just using the homebrew packages (same versions), which our configure scripts already accepts

**Comment by mkoeppe** [comment]
I'll close this PR in favor of doing these upgrades as part of:
- #36775

**Pull request closed without merging**
