### PR TITLE
`igraph`: Update to 0.10.12, fix spkg-check; `python_igraph`: Update to 0.11.5, remove spkg-install workarounds

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- https://github.com/igraph/python-igraph/blob/main/CHANGELOG.md

Increasing the lower bound for system `cmake` to 3.18. This will cause system cmake on ubuntu-focal to be rejected, so cmake will be built from source on this platform. https://repology.org/project/cmake/versions

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- https://github.com/sagemath/sage/pull/38144 (merged here for testing)

### CODE REVIEW

**Review by dcoudert — COMMENTED** [review]
I have igraph 0.10.11 installed via homebrew
```
MAC-04017247:sage dcoudert$ ls -l /opt/homebrew/Cellar/igraph/
total 0
drwxr-xr-x  12 dcoudert  admin  384 17 avr 09:15 0.10.11
```
in a fresh shell session, I did:
```
make distclean
./bootstrap
source .homebrew-build-env
./configure
make build
./sage -i python_igraph
```
For some reason, it installs igraph from source and don't use my homebrew version.
How to fix that ?

**Comment by mkoeppe** [comment]
Thanks for testing! I had forgotten to check/update the spkg-configure file. Fixed now

**Review by dcoudert — APPROVED** [review]
Installation and tests ok on macOS 12.7.4.

LGTM.

**Comment by dcoudert** [comment]
I have some doubts about all the failing CI. That's why I'm not seeing this PR to positive review yet.

**Comment by szhorvat** [comment]
igraph 0.10.12 and python-igraph 0.11.5 are released now. I suggest going directly for these new versions.

**Review by dcoudert — APPROVED** [review]
Works fine on macOS with homebrew igraph.

LGTM.

**Comment by dcoudert** [comment]
Some errors are reported by the CI on the `uninstall` part.

**Comment by mkoeppe** [comment]
Not sure what you mean by the "uninstall part" but there is a problem with cmake.
[test / linux (debian-bullseye, minimal)](https://github.com/sagemath/sage/actions/runs/9377286046/job/25819368423?pr=37819#logs)
```
#29 40.36   [igraph-0.10.12]   No spkg-legacy-uninstall script; nothing to do
#29 40.36   [igraph-0.10.12]   [spkg-install] Configuring igraph-0.10.12 with cmake
#29 40.36   [igraph-0.10.12]   [spkg-install] CMake Error at CMakeLists.txt:8 (cmake_minimum_required):
#29 40.36   [igraph-0.10.12]   [spkg-install]   CMake 3.18 or higher is required.  You are running version 3.17.2
#29 40.36   [igraph-0.10.12]   [spkg-install] 
#29 40.36   [igraph-0.10.12]   [spkg-install] 
#29 40.36   [igraph-0.10.12]   [spkg-install] -- Configuring incomplete, errors occurred!
#29 40.36   [igraph-0.10.12]   [spkg-install] ********************************************************************************
#29 40.36   [igraph-0.10.12]   [spkg-install] Error configuring igraph-0.10.12 with cmake
#29 40.36   [igraph-0.10.12]   [spkg-install] ********************************************************************************
```

**Comment by dcoudert** [comment]
The issue is not yet fixed https://github.com/sagemath/sage/actions/runs/9388680174/job/25854493223?pr=37819#step:11:12925

**Comment by mkoeppe** [comment]
What I see there is this test failure:
```
sage -t --random-seed=302171850113617614625936987131470123946 src/sage/graphs/generators/random.py
#30 2631.5 **********************************************************************
#30 2631.5 File "src/sage/graphs/generators/random.py", line 1605, in sage.graphs.generators.random.RandomPartialKTree
#30 2631.5 Failed example:
#30 2631.5     G.treewidth()
#30 2631.5 Expected:
#30 2631.5     5
#30 2631.5 Got:
#30 2631.5     6
#30 2633.3
```
Do you know somethingm about this test?

**Comment by dcoudert** [comment]
it seems to be 

> What I see there is this test failure:
> 
> ```
> sage -t --random-seed=302171850113617614625936987131470123946 src/sage/graphs/generators/random.py
> #30 2631.5 **********************************************************************
> #30 2631.5 File "src/sage/graphs/generators/random.py", line 1605, in sage.graphs.generators.random.RandomPartialKTree
> #30 2631.5 Failed example:
> #30 2631.5     G.treewidth()
> #30 2631.5 Expected:
> #30 2631.5     5
> #30 2631.5 Got:
> #30 2631.5     6
> #30 2633.3
> ```
> 
> Do you know something about this test?

This seems to be an error from `tdlib`.
```
sage: from sage.graphs.graph_decompositions.tree_decomposition import width_of_tree_decomposition
sage: G = Graph('q~~|~q{mLhUo}?v?EO`{?h`?wo@w?fo?As_?lG?Cp_?Uc??{?_?|???Y_G?@gH??{?_?A{???Dp???Dk???Ax????l????Dh????Qo???GkG???_lG????Q_???I@p?G???uO????As????@@gH????FG??A??AW_??A??d????CG@w?C????PE?@????D@G?C???t?O??????')
sage: G.treewidth(algorithm='sage')
5
sage: G.treewidth(algorithm='tdlib')
6
sage: T = G.treewidth(algorithm='tdlib', certificate=True)
sage: width_of_tree_decomposition(G, T)
6
```
May be we should first try to update tdlib to see if it fixes this issue, and otherwise report upstream.

**Comment by dcoudert** [comment]
I have opened #38159

**Comment by dcoudert** [comment]
This PR looks good to me. Let me know if ready for review (currently in needs work).

**Comment by mkoeppe** [comment]
Thanks. It's ready for review

**Review by dcoudert — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
