### PR TITLE
Implement Chevalley-Eilenberg complexes with module coefficients

### PR DESCRIPTION
**Pull request by tscrim**
We implement the Chevalley-Eilenberg complex of a Lie algebra `L` with coefficients in a general `L` representation.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36169 uses the representations of Lie algebras

### CODE REVIEW

**Comment by tscrim** [comment]
@ adityadwarkesh Here is the code for the CE complex split off as a separate PR. I ended up finding it easier to rewrite the code starting from what I had, but I incorporated some of the tricks that you employed.

**Review by adityadwarkesh — COMMENTED** [review]
A few remarks:

1. The comment on line 1288 seems superfluous.
2. Codecov mentions a number of lines not covered by tests, although I'm not sure how significant this is.
3. When I try running this locally (in particular, computing the example offered), I'm receiving a "Typerror: type 'dict' is not hashable" error. I remember running into this last summer and somehow getting rid of it.

**Comment by tscrim** [comment]
>     1. The comment on line 1288 seems superfluous.

That's not quite true. It is important to distinguish between the two indices.

>     2. Codecov mentions a number of lines not covered by tests, although I'm not sure how significant this is.

Codecov is just wrong here. It isn't smart enough to distinguish the internal function being called by the outer test. I wish there was a way to turn it off.

>     3. When I try running this locally (in particular, computing the example offered), I'm receiving a "Typerror: type 'dict' is not hashable" error. I remember running into this last summer and somehow getting rid of it.

Without knowing what you are doing, I can't respond beyond saying it works for me and the doctests are passing.

**Comment by adityadwarkesh** [comment]
> That's not quite true. It is important to distinguish between the two indices.

Right, my mistake—I should have said that line 1290 seems superfluous? It doesn't seem to refer to anything in particular.

> Codecov is just wrong here. It isn't smart enough to distinguish the internal function being called by the outer test.

OK.

> Without knowing what you are doing, I can't respond beyond saying it works for me and the doctests are passing.

OK, then I think we can conclude that it doesn't have to do with the code. (For what it's worth, it was working fine when I tried it on cocalc.)

I think it seems good to go, then

**Comment by tscrim** [comment]
> > That's not quite true. It is important to distinguish between the two indices.
> 
> Right, my mistake—I should have said that line 1290 seems superfluous? It doesn't seem to refer to anything in particular.

I thought it did, but looking at it again, you're right. Removed.

> > Without knowing what you are doing, I can't respond beyond saying it works for me and the doctests are passing.
> 
> OK, then I think we can conclude that it doesn't have to do with the code. (For what it's worth, it was working fine when I tried it on cocalc.)

It would still be good to see what you're trying. There might be an issue there (with your usage, the code, or both) that I would like to check.

> I think it seems good to go, then

Great; thank you!
Please approve the PR and change the label to positive review. (I can do the latter, but I need you to do the former.)

**Review by adityadwarkesh — APPROVED** [review]

**Comment by tscrim** [comment]
Thank you!

**Pull request merged**
