### PR TITLE
`sage --package create`: Attempt to bring SPKG.rst title to a common style

### PR DESCRIPTION
**Pull request by mkoeppe**
The SPKG.rst titles should not have a final dot. 

For uniformity, we also strip an initial indefinite article and ensure that the title starts with a capital letter.

By running `sage --package create --pypi` for several packages and then using `git add -p`, we update several packages.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by kwankyu** [comment]
Not related: Presently doc preview link opens in the same tab. This is annoying. How about making the preview link to open in a newtab?

**Comment by mkoeppe** [comment]
Thank you!

**Comment by mkoeppe** [comment]
> Presently doc preview link opens in the same tab. This is annoying. How about making the preview link to open in a newtab?

Good idea.

**Comment by kwankyu** [comment]
> > Presently doc preview link opens in the same tab. This is annoying. How about making the preview link to open in a newtab?
> 
> Good idea.

Ah, I forgot again that github prevents this...

**Pull request merged**
