### PR TITLE
Make automatic codecov report less noisy

### LINKED ISSUE #35016: "Codecov Report" automatic comment is extravagant
Currently, a "Codecov Report" is being automatically added to every PR. While most of the time the information from the comment is not that important, the comment takes (almost forces) attention from the readers of the PR.

I wish that that is moved to the checks, if possible, or be turned off until we find a solution that makes it quiet.

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #35016. ~We *turn off automatic codecov comment.*~

~After this PR, someone needs to implement a github action that sends code coverage information as a quiet comment, like the current built-documentation comment.~

### CODE REVIEW

**Comment by kwankyu** [comment]
The location was determined according to https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml

**Comment by tobiasdiez** [comment]
Thanks for looking into this.

Since this is currently the only check we have on github that newly introduced code is covered by checks, it should be clearly visible from the PR. So simply disabling is not an option in my opinion. At least a GH check should be added as well. 

You can also test this in your fork first (simply install the codecov app in your fork: https://github.com/marketplace/codecov)

**Comment by kwankyu** [comment]
> So simply disabling is not an option in my opinion. At least a GH check should be added as well.

I agree. Would you do that, adding a GH check?

**Comment by tobiasdiez** [comment]
This is something that can be configured as well: https://docs.codecov.com/docs/github-checks

**Comment by kwankyu** [comment]
I misunderstood the GH check as something like checks in "Checks" tab. I don't know whether the codecov's GH check you meant is something  developers would like or not. 

What I want is to make the code coverage information available to developers in less intrusive way. The issue of #35016 is that the current automatic codecov comments are distracting. Hence I think we should merge this PR now to stop adding codecov comments to issues.

Then someone, perhaps you, make a new PR either to turn on the codecov's GH check or to turn on the automatic codecov comment again by reconfiguring `codecov.yml`.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
> I misunderstood the GH check as something like checks in "Checks" tab. I don't know whether the codecov's GH check you meant is something developers would like or not.

So this https://docs.codecov.com/docs/commit-status ?

> What I want is to make the code coverage information available to developers in less intrusive way.

As far as I understand it is sage's convention that changes should be covered by tests. The codecov report gives the reviewer a tool to check this convention. I agree that its somewhat annoying to get this comment as someone contributing a PR, but I would value the convenience/time of the reviewer higher.

I'm still of the opinion we should just test it for a bit and disable/change the codecov comment once everyone got used to the new github workflow a bit more.

**Comment by kwankyu** [comment]
> I'm still of the opinion we should just test it for a bit and disable/change the codecov comment once everyone got used to the new github workflow a bit more.

We just have different opinions.

I don't plan to do (and I am not capable of doing) anything more in this PR. Others will decide on it. 

Whether this PR is merged or not, as I said already, I hope that you make a new PR to provide less intrusively code coverage information to reviewers.

**Comment by kwankyu** [comment]
> You can also test this in your fork first (simply install the codecov app in your fork: https://github.com/marketplace/codecov)

I did. It works well, that is, no more codecov reports.

**Comment by mezzarobba** [comment]
I don't understand the technical details of the issue nor what the available options are, but for what it's worth, I've almost immediately started ignoring the codecov comments as visual noise. I don't care at all about coverage statistics; the only thing that matters to me is that new code and especially _conventions that affect multiple functions/files/..._ are covered by _relevant_ tests, and I don't think codecov can help much with that.

**Comment by kwankyu** [comment]
Thanks. I am testing.

**Comment by kwankyu** [comment]
It works perfect!

Screenshot 2023-03-19 at 11 42 39 AM

**Review by tobiasdiez — APPROVED** [review]
Nice, thanks for testing!

**Comment by tobiasdiez** [comment]
@vbraun could this please be merged relatively quickly? It doesn't touch anything else then the codecov config, so it doesn't need to go through extensive testing.

**Pull request merged**
