### PR TITLE
Fix docstring for polyhedron constructor

### PR DESCRIPTION
**Pull request by marco-perin**
In the documentation for polyhedron constructor, there was a typo where `Polyhedron(o)` was used when `Polyhedron(p)` should have been used instead ( the `o` var was from the same code piece, but from the very previous example ).

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Review by fchapoton — APPROVED** [review]
ok

**Comment by fchapoton** [comment]
you should rather avoid touching the branch once it is positive reviewed, please

**Comment by marco-perin** [comment]
I'm sorry, I thought it needed merging the develop branch for the PR to be closed. I will not touch it again.
Should I revert it or leave it like this?

**Comment by fchapoton** [comment]
just do nothing

**Pull request merged**
