### PR TITLE
Fix workflow "Build documentation (PDF)"

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

Follow-up on #35169.

The container `sage-docker-fedora-31-maximal-with-targets` used for the PDF docbuild turned out to be not reliable.
Here we replace it by `ubuntu-focal-standard-with-targets` and install texlive in it.

We also copy over the incremental build from doc-build.yml and the method to get CI fixes from blocker tickets from #36338.

This workflow is currently disabled in sagemath/sage.
Example run: https://github.com/mkoeppe/sage/actions/runs/6318741659/job/17158468016

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36338
- Depends on #36348

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I've disabled the workflow in the main repo now until it is fixed.

**Comment by kwankyu** [comment]
What work does this PR need? Is this still "critical"?

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by mkoeppe** [comment]
Thanks, Dima!

**Pull request merged**
