### PR TITLE
Update system package info for slackware

### PR DESCRIPTION
**Pull request by mkoeppe**
@cduston44

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
If this was tested at least once (since I can't test) and @cduston44 does not respond, then I will set this positive review.

**Comment by kwankyu** [comment]
Could this 

https://github.com/aclemons/slackware-dockerfiles

be used to test this?

By the way, do we have many sage users on slackware linux distro?

**Comment by mkoeppe** [comment]
It can be tested like our other Linux platforms, using `tox -e docker-slackware-current-standard` etc.; see tox.ini

(Note that the goal of this PR is not to make everything work. It just makes it testable.)

**Comment by kwankyu** [comment]
> ... since I can't test

Then what did you mean?

**Comment by kwankyu** [comment]
> If this was tested at least once (since I can't test) and @cduston44 does not respond, then I will set this positive review.

I forgot that I made this comment :-)

OK. With this PR, slackware become testable in the sense that the test by tox proceeds further than before this PR.

For me, the test fails in building sage even with this PR.

**Review by kwankyu — APPROVED** [review]

**Comment by kwankyu** [comment]
> By the way, do we have many sage users on slackware linux distro? Or is @cduston44 the only one as far as known?

Perhaps non answerable...  I asked  because I guess that it is an unpopular linux distro.

**Comment by mkoeppe** [comment]
> do we have many sage users on slackware linux distro?

I don't know any. When I did the initial porting to slackware, I did it only as an illustration of how to do the porting work for Sage using the Docker technology.

**Comment by mkoeppe** [comment]
Thanks for the review!

**Comment by cduston44** [comment]
As far as I know, I am the only Slackware user of Sage, but I don't really use docker so I don't think I can contribute to this discussion. Sorry!

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request merged**
