### PR TITLE
Fix regex to remove spurious diffs in doc preview

### PR DESCRIPTION
**Pull request by kwankyu**
There was an error in the regex, seen in

https://preview-38210--sagemath.netlify.app/changes

Also removed most spurious diffs: see [changes](https://preview-38213--sagemath.netlify.app/changes) of this PR.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by kwankyu** [comment]
Thanks!

**Comment by kwankyu** [comment]
I am trying to understand where the last diff left in "changes" come from.

"changes" is the result of `git diff` between the "new" doc built from the branch of this PR and the "old" doc built for the latest release. Hence the "old" doc should be the doc in `ghcr.io/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:dev` (or 10.4.beta9). 

According to this run of doc-build workflow: 

https://github.com/sagemath/sage/actions/runs/9500068057/job/26182310478?pr=38213

"Build Docker Image" step builds docker image `localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci` from `ghcr.io/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:dev`. But then In the next "Start container" step, 
```
docker run --name BUILD -dit \
             --mount type=bind,src=$(pwd),dst=$(pwd) \
             --workdir $(pwd) \
             localhost:[5](https://github.com/sagemath/sage/actions/runs/9500068057/job/26182310478?pr=38213#step:10:5)000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci /bin/sh
  shell: /usr/bin/bash -e {0}
  env:
    TOX_ENV: docker-ubuntu-jammy-standard-incremental
    BUILD_IMAGE: localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci
    FROM_DOCKER_REPOSITORY: ghcr.io/sagemath/sage/
    FROM_DOCKER_TARGET: with-targets
    FROM_DOCKER_TAG: dev
    EXTRA_CONFIGURE_ARGS: --enable-fat-binary
Unable to find image 'localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci' locally
ci: Pulling from sagemath/sage/sage-ubuntu-jammy-standard-with-targets
```
it seems that it fails to find the image `localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci`, and instead pull `sagemath/sage/sage-ubuntu-jammy-standard-with-targets` with no tag. Thus, I think, it pulls the image with the default `latest` tag. But then `sagemath/sage/sage-ubuntu-jammy-standard-with-targets:latest` would be 10.3. Hence all screws up... Am I right? This explanation is still strange since 10.3 is too old version...

**Comment by mkoeppe** [comment]
The incremental build is always starting from the tag `:dev` (see `FROM_DOCKER_TAG`)

**Comment by mkoeppe** [comment]
> Unable to find image 'localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci' locally
> ci: Pulling from sagemath/sage/sage-ubuntu-jammy-standard-with-targets

This message just means it's pulling what was just built.

**Comment by kwankyu** [comment]
Ah, I see. So `localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci` is just `ghcr.io/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:dev`.

I looked into `ghcr.io/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:dev`, and indeed there are lines:
```
<span class="go">  --sws2rst &lt;sws doc&gt; -- Generates a reStructuredText source file from</span>
<span class="go">                         a Sage worksheet (.sws) document.</span>
<span class="go">                         (not installed currently, run sage -i sage_sws2rst)</span>

<span class="go">Valgrind memory debugging:</span>
```
Hence the diff is genuine. 

On the other hand, looking into the source file of the page https://sagemath.netlify.app/html/en/reference/repl/options, **which I think is uploaded from the doc in `localhost:5000/sagemath/sage/sage-ubuntu-jammy-standard-with-targets:ci`**, I see
```
<span class="go">  --sws2rst &lt;sws doc&gt; -- Generates a reStructuredText source file from</span>
<span class="go">                         a Sage worksheet (.sws) document.</span>
  
<span class="go">Valgrind memory debugging:</span>
```
where, as you see, there is no line
```
<span class="go">                         (not installed currently, run sage -i sage_sws2rst)</span>
``` 
!

**Comment by kwankyu** [comment]
Hmm presently `https://sagemath.netlify.app/html/en/reference/repl/options` is doc for PR #38205! Strange.

**Comment by kwankyu** [comment]
> presently https://sagemath.netlify.app/html/en/reference/repl/options is doc for PR #38205! 

This is fixed by https://github.com/sagemath/sage/pull/38220.

**Pull request merged**
