### PR TITLE
`build/pkgs/cypari` 2.2.0

### PR DESCRIPTION
**Pull request by mkoeppe**
- https://pypi.org/project/cypari2/2.2.0/
- https://github.com/sagemath/cypari2/blob/master/NEWS
- Another step toward #32431

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Some `AlarmInterrupt` is showing up
https://github.com/sagemath/sage/actions/runs/9444170756/job/26009287032?pr=38183#step:11:5841

**Comment by mkoeppe** [comment]
Reduced the PR to only the `cypari` update.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you.

**Pull request merged**
