### PR TITLE
Adding cellular bases for the SymmetricGroupAlgebra over general fields

### PR DESCRIPTION
**Pull request by tscrim**
Currently the SymmetricGroupAlgebra uses the seminormal basis for computing a cell basis, but this only is guaranteed to work over a field where Maschke's theorem holds. However, it is known that the Kazhdan-Lusztig C' basis at q = 1 for the type A Hecke algebra is a cell basis, We implement that as the fallback when we cannot use the seminormal basis.

We also fix a few typos in the doc that were noticed.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
@fchapoton I hope you can do the review for this. Mathematically it is just implementing the KL $C'$ basis at $q=1$. Everything else is handled by the general framework for cellular algebras already implemented.

**Comment by fchapoton** [comment]
there are a few failing doctests, some trivial and other less so

**Comment by tscrim** [comment]
This should fix all of the failing doctests. They were all trivial coming from the fact that the cell poset was in the reverse order.

**Comment by fchapoton** [comment]
testing wihtout coxeter3 does not work:
```
KLG = SymmetricGroup(self.n)
    UnboundLocalError: local variable 'SymmetricGroup' referenced before assignment
```

**Comment by tscrim** [comment]
Good catch. This should fix it.

**Review by fchapoton — APPROVED** [review]
works with and without coxeter3, ok

**Comment by tscrim** [comment]
Merci

**Pull request merged**
