### PR TITLE
.github/workflows/doc-build-pdf.yml: Do not build HTML documentation, fix upload of PDFs

### PR DESCRIPTION
**Pull request by mkoeppe**
Our `make` target `doc-pdf` depends on `doc-html` only to avoid concurrency bugs when updating the inventory files.

To speed up the Build Documentation (PDF) workflow, we skip the HTML build.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36601 (to resolve merge conflict, merged here)

### CODE REVIEW

**Comment by kwankyu** [comment]
Where can I see the built pdf docs?

**Comment by mkoeppe** [comment]
The upload step was being skipped. Fixed now, it should be available as an artifact.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by kwankyu** [comment]
On the other hand, it would be nice to publish the built pdf doc in the same place where html doc is published so that html and pdf docs are available together in the doc preview. pdf docs may be published later after html docs so that developers can examine html docs first. But I am not sure if Tobias' netlify account allows that much space...

**Comment by mkoeppe** [comment]
I agree that it would be nice, but I have no experience with the netlify upload, so if at all possible, it will have to be done in a separate PR.

**Comment by kwankyu** [comment]
Yes, of course.

**Comment by kwankyu** [comment]
@tobiasdiez ?

**Comment by vbraun** [comment]
merge conflict

**Comment by tobiasdiez** [comment]
> On the other hand, it would be nice to publish the built pdf doc to the same place where html doc is published so that html and pdf docs are available together in the doc preview. pdf docs may be published later after html docs so that developers can examine html docs first. But I am not sure if Tobias' netlify account allows that much space...

Space is not the issue, but I don't think its possible to only add the pdf later (so you would need to download the build artifact from the html build, add the pdf, then upload everything).

**Comment by kwankyu** [comment]
> > On the other hand, it would be nice to publish the built pdf doc to the same place where html doc is published so that html and pdf docs are available together in the doc preview. pdf docs may be published later after html docs so that developers can examine html docs first. But I am not sure if Tobias' netlify account allows that much space...
> 
> Space is not the issue, but I don't think it's possible to only add the pdf later (so you would need to download the build artifact from the html build, add the pdf, then upload everything).

It may not be worth while for PRs. But for pushes to develop, it may be worth another workflow. After #36601, the netlify site will have this

html/(en/...)
index.html 

By the new workflow (perhaps doc-publish-pdf), it would be

html/(en/...)
pdf/
index.html

The two workflows should publish to the same url, of course.

**Comment by kwankyu** [comment]
I suspect that the change of this PR triggered failures like https://github.com/sagemath/sage/actions/runs/6811957358/job/18523428561?pr=36592

From the log,
```
2023-11-09T13:28:20.2254069Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/schemes/searchindex.js
2023-11-09T13:28:20.2254851Z [sagemath_doc_pdf-none] [reference]     semirings:
2023-11-09T13:28:20.2255695Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/semirings/searchindex.js
2023-11-09T13:28:20.2256474Z [sagemath_doc_pdf-none] [reference]     sets:
2023-11-09T13:28:20.2257257Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/sets/searchindex.js
2023-11-09T13:28:20.2258166Z [sagemath_doc_pdf-none] [reference]     spkg: 4399 js index entries
2023-11-09T13:28:20.2258671Z [sagemath_doc_pdf-none] [reference]     stats:
2023-11-09T13:28:20.2259469Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/stats/searchindex.js
2023-11-09T13:28:20.2260236Z [sagemath_doc_pdf-none] [reference]     structure:
2023-11-09T13:28:20.2261068Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/structure/searchindex.js
2023-11-09T13:28:20.2261978Z [sagemath_doc_pdf-none] [reference]     tensor_free_modules: 1379 js index entries
2023-11-09T13:28:20.2262631Z [sagemath_doc_pdf-none] [reference]     topology: 2090 js index entries
2023-11-09T13:28:20.2263165Z [sagemath_doc_pdf-none] [reference]     valuations:
2023-11-09T13:28:20.2264011Z [sagemath_doc_pdf-none] [reference] WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/valuations/searchindex.js
2023-11-09T13:28:20.2264897Z [sagemath_doc_pdf-none] [reference] ... done (65918 js index entries)
2023-11-09T13:28:20.2265577Z [sagemath_doc_pdf-none] [reference] dumping search index in English (code: en)... done
2023-11-09T13:28:20.2266410Z [sagemath_doc_pdf-none] [reference] The HTML pages are in ../../local/share/doc/sage/html/en/reference.
2023-11-09T13:28:20.2267178Z [sagemath_doc_pdf-none] Error building the documentation.
2023-11-09T13:28:20.2267697Z [sagemath_doc_pdf-none] Traceback (most recent call last):
2023-11-09T13:28:20.2268302Z [sagemath_doc_pdf-none]   File "<frozen runpy>", line 198, in _run_module_as_main
2023-11-09T13:28:20.2268941Z [sagemath_doc_pdf-none]   File "<frozen runpy>", line 88, in _run_code
2023-11-09T13:28:20.2269716Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/__main__.py", line 508, in <module>
2023-11-09T13:28:20.2270366Z [sagemath_doc_pdf-none]     sys.exit(main())
2023-11-09T13:28:20.2270760Z [sagemath_doc_pdf-none]              ^^^^^^
2023-11-09T13:28:20.2271399Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/__main__.py", line 504, in main
2023-11-09T13:28:20.2272000Z [sagemath_doc_pdf-none]     builder()
2023-11-09T13:28:20.2272626Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/builders.py", line 645, in pdf
2023-11-09T13:28:20.2273394Z [sagemath_doc_pdf-none]     getattr(get_builder('reference_top'), 'html')()
2023-11-09T13:28:20.2274154Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/builders.py", line 162, in f
2023-11-09T13:28:20.2274754Z [sagemath_doc_pdf-none]     runsphinx()
2023-11-09T13:28:20.2275429Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/sphinxbuild.py", line 327, in runsphinx
2023-11-09T13:28:20.2276128Z [sagemath_doc_pdf-none]     sys.stderr.raise_errors()
2023-11-09T13:28:20.2276945Z [sagemath_doc_pdf-none]   File "/sage/pkgs/sage-docbuild/sage_docbuild/sphinxbuild.py", line 263, in raise_errors
2023-11-09T13:28:20.2277660Z [sagemath_doc_pdf-none]     raise OSError(self._error)
2023-11-09T13:28:20.2278590Z [sagemath_doc_pdf-none] OSError: WARNING: Unable to fetch /sage/local/share/doc/sage/html/en/reference/history_and_license/searchindex.js 
2023-11-09T13:28:20.2279460Z [sagemath_doc_pdf-none] 
2023-11-09T13:28:20.2279989Z [sagemath_doc_pdf-none]     Note: incremental documentation builds sometimes cause spurious
2023-11-09T13:28:20.2280765Z [sagemath_doc_pdf-none]     error messages. To be certain that these are real errors, run
2023-11-09T13:28:20.2281481Z [sagemath_doc_pdf-none]     "make doc-clean doc-uninstall" first and try again.
```

**Pull request merged**
