### PR TITLE
get rid of one sage_eval in complex numbers

### PR DESCRIPTION
**Pull request by fchapoton**
this is parsing in a simple way the string input for complex number constructor, avoiding usage of `sage_eval` there

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by user202729** [comment]
Depends on how much external code uses the string constructor of ℂ, this may break badly.

Here are some examples

```
sage: CC("e")
2.71828182845905
sage: CC("e**j")
0.540302305868140 + 0.841470984807897*I
sage: CC("3+I")
3.00000000000000 + 1.00000000000000*I
sage: CC("I**2")
-1.00000000000000
sage: CC("12 34")
1234.00000000000
```

**Comment by fchapoton** [comment]
This parser is not supposed to perform computations ; it should only accept inputs that are already just one complex number in full explicit form.

**Comment by fchapoton** [comment]
after
```
sage: %timeit CC('13.67788e26+1.20958686e-14*I')
2.83 µs ± 7.93 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
versus before
```
sage: %timeit CC('13.67788e26+1.20958686e-14*I')
27.3 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Review by mkoeppe — APPROVED** [review]
LGTM. Thanks for working on this!

**Pull request merged**
