### PR TITLE
make sure .division_points() returns the correct result for m=-1

### LINKED ISSUE #38796: elliptic-curve points' .division_points() method returns wrong result for m=-1
```sage
sage: E = EllipticCurve(GF(127), [1,1])
sage: P = E(72, 24)
sage: [-1*Q for Q in P.division_points(-1)]
[(72 : 103 : 1)]
```
In this example, the returned value is the negative of what it should be.

### PR DESCRIPTION
**Pull request by yyyyx4**
Fixes #38796: The solution is to simply take the sign of $m$ into account when $m \in \{\pm1\}$.

### CODE REVIEW

**Comment by DaveWitteMorris** [comment]
Thanks for fixing the bug!

Please add "Fixes #38796" to the PR description (or just change the word "See" to "Fixes"), so the linked issue will close when this is merged.

**Comment by yyyyx4** [comment]
That's in the commit message, which I think should work as well?

**Comment by DaveWitteMorris** [comment]
I think you are probably right that the commit message will work (though I didn't realize that before). However, the PR does not show up in the "Development" sidebar of the issue. If you look at #38784 (for example), the sidebar says there is a pull request that may close the issue, and I think it is helpful for this information to be displayed clearly, so, although putting the reference in the commit message may work, I don't think it works literally "as well" as putting it in the PR description. As an alternative, I think you may be able to manually link the PR to the issue by clicking on the PR's Development sidebar.

**Comment by yyyyx4** [comment]
I see, thanks for your explanation. I changed it.

**Pull request merged**
