### PR TITLE
Add reflection_index_set() and reflection() methods for permutations

### PR DESCRIPTION
**Pull request by tscrim**
These methods are general optional methods for complex reflections groups. We provide an implementation for two implementations of the symmetric group.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by tscrim** [comment]
@25shriya

**Comment by amritanshu-prasad** [comment]
Pulled and checked. Looks good.

**Comment by tscrim** [comment]
@amritanshu-prasad You should now be able to approve this PR and set the label to positive review.

**Review by amritanshu-prasad — APPROVED** [review]
Pulled and tested. Works fine.

**Comment by tscrim** [comment]
Thank you. Since the doc builds locally individually for both of us and the bot's failure doesn't seem to be because of this PR, I am setting a positive review.

**Pull request merged**
