### PR TITLE
ntl 11.5.1

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #37252

### CODE REVIEW

**Comment by kwankyu** [comment]
Which CI workflow really tests the new ntl? On all platforms that I looked into, ntl is already available from the system or from the previous install.

**Comment by mkoeppe** [comment]
(Should we add something like this to the developer guide?)

**Comment by kwankyu** [comment]
> (Should we add something like this to the developer guide?)

Perhaps no. As you explained, I was confused by the first message in the minimal build workflow. Your explanation seems too much detail to be included in the developer guide.

I tested the package on my system with "--with-system-ntl=no". We may give this tip somewhere in the developer manual, if this is not obvious to others. 

For a package upgrade PR, I imagine Build & Test workflow running with ""--with-system-xxx=no". But I don't know if this is doable...

**Review by kwankyu — APPROVED** [review]
It works well. LGTM

**Comment by mkoeppe** [comment]
> For a package upgrade PR, I imagine Build & Test workflow running with ""--with-system-xxx=no". But I don't know if this is doable...

I hope to merge "Build & Test" with "CI Linux Incremental" soon. (Follow-up after #36498)

**Comment by mkoeppe** [comment]
Thanks for the review!

**Pull request merged**
