### PR TITLE
doctester: Check for consistency of `# optional` annotations

### LINKED ISSUE #35401: Doctest `# optional` / `# long` annotation dataflow checker
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

It is easy to make mistakes when using `# optional - FEATURE` and `# long time` annotations in doctests.

For example, in the following doctests, a `# long time` annotation is missing, causing a failure when `sage -t` is used without `--long`.
```
src/sage/coding/ag_code_decoders.pyx:    sage: code = codes.EvaluationAGCode(pls, G)  # long time
src/sage/coding/ag_code_decoders.pyx:    sage: code                                   # long time
src/sage/coding/ag_code_decoders.pyx-    [26, 15] evaluation AG code over GF(9)
src/sage/coding/ag_code_decoders.pyx:    sage: decoder = code.decoder('K')
src/sage/coding/ag_code_decoders.pyx:    sage: tau = decoder.decoding_radius()        # long time
src/sage/coding/ag_code_decoders.pyx:    sage: tau                                    # long time
```

As part of 
- #29705 

we expect to add many more `# optional` annotations corresponding to "standard" packages such as `# optional - scipy` and corresponding to subset distributions such as `# optional - sage.libs.pari`.

### Proposed Solution

The Sage doctester has a rudimentary data flow analyzer for the globals involved in the lines of a doctest, [`globs: RecordingDict`](https://doc.sagemath.org/html/en/reference/doctest/sage/doctest/util.html#sage.doctest.util.RecordingDict), which is used for determining dependencies for parallelization purposes. 

We can extend this mechanism to track the set of features (`# optional` tags) and the pseudo-feature `long` associated with each doctest line. For each `variable` in `RecordingDict.got` of a `doctest_line`, we check that the set of required features 
- is a superset of the set of required features of a `predecessor` of `doctest_line` that has `variable` in `predecessor.globs.set`,
- or a proper generalization of this.

### Alternatives Considered

N/A

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

For example:
```
sage -t --long --random-seed=52927571004392838159040103596363721016 src/sage/rings/function_field/function_field.py
**********************************************************************
File "src/sage/rings/function_field/function_field.py", line 40, in sage.rings.function_field.function_field
Warning: Variable 'L' referenced here was set only in doctest marked '# optional - sage.rings.finite_rings sage.rings.function_field'
    S.<t> = L[]                                                                   # optional - sage.rings.finite_rings
```

Resolves  #35401

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
It works well. 

I was a bit concerned that this would slowdown doctesting slightly, but the concern seems imaginary.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Test fail

It seems that ` # long time` tests are not covered by the CI, is that true?

**Comment by mkoeppe** [comment]
> Test fail

Sorry about this, will fix.

> It seems that ` # long time` tests are not covered by the CI, is that true?

Yes, that's currently true. 

#35652 changes this (by first running a fast incremental build/test, then running a full build of the Sage and ptest --long)

**Comment by vbraun** [comment]
Tests still fail. Thats two strikes. Please don't make it three.

**Comment by mkoeppe** [comment]
Sorry about this. Fixed now.

**Pull request merged**
