### PR TITLE
update qepcad to B 1.74

### LINKED ISSUE #36831: Error installing package qepcad-B.1.72
### Environment

```markdown
- **OS**: Using Ubuntu 20.04 inside Docker in Mac M2
- **Sage Version**: 10.2
```

### Steps To Reproduce

I tried to install sage using the commands mentioned as a solution to a previous issue raised [here](https://github.com/sagemath/sage/issues/36825#issue-2028157350).

I get the following error:
```
[qepcad-B.1.72] ****************************************************
[qepcad-B.1.72] Package 'qepcad' is currently not installed
[qepcad-B.1.72] No legacy uninstaller found for 'qepcad'; nothing to do
[qepcad-B.1.72] Making the optimized libraries ...
[qepcad-B.1.72] cd extensions; make   opt "CCo=g++" "FLAGSo=-g -O2 -Wl,-rpath,/root/Desktop/sage_git/sage-10.2/local/lib" "CCd=g++" "FLAGSd=-g" "MAKE=make  " "SUBMAKEFLAGS=-j1" -j1
[qepcad-B.1.72] Making the optimized libraries ...
[qepcad-B.1.72] cd sfext; make   -j1
[qepcad-B.1.72] g++ -g -O2 -Wl,-rpath,/root/Desktop/sage_git/sage-10.2/local/lib -I/root/Desktop/sage_git/sage-10.2/local/lib/saclib/include -I/root/Desktop/sage_git/sage-10.2/local/var/tmp/sage/build/qepcad-B.1.72/src/source/ -I. -c addpol/BPOLSETS.c
[qepcad-B.1.72] In file included from /root/Desktop/sage_git/sage-10.2/local/lib/saclib/include/saclib.h:11,
[qepcad-B.1.72]                  from /root/Desktop/sage_git/sage-10.2/local/var/tmp/sage/build/qepcad-B.1.72/src/source/qepcad.h:12,
[qepcad-B.1.72]                  from addpol/BPOLSETS.c:23:
[qepcad-B.1.72] /root/Desktop/sage_git/sage-10.2/local/lib/saclib/include/hfloats.h:12:10: fatal error: sysdep.h: No such file or directory
[qepcad-B.1.72]    12 | #include "sysdep.h"
[qepcad-B.1.72]       |          ^~~~~~~~~~
[qepcad-B.1.72] compilation terminated.
[qepcad-B.1.72] make[7]: *** [Makefile:242: BPOLSETS.o] Error 1
[qepcad-B.1.72] make[6]: *** [Makefile:11: opt] Error 2
[qepcad-B.1.72] make[5]: *** [Makefile:32: opt] Error 2
[qepcad-B.1.72] Error building qepcad.
[qepcad-B.1.72] 
[qepcad-B.1.72] real	0m0.148s
[qepcad-B.1.72] user	0m0.119s
[qepcad-B.1.72] sys	0m0.030s
[qepcad-B.1.72] ************************************************************************
[qepcad-B.1.72] Error installing package qepcad-B.1.72
[qepcad-B.1.72] ************************************************************************
[qepcad-B.1.72] Please email sage-devel (http://groups.google.com/group/sage-devel)
[qepcad-B.1.72] explaining the problem and including the log files
[qepcad-B.1.72]   /root/Desktop/sage_git/sage-10.2/logs/pkgs/qepcad-B.1.72.log
[qepcad-B.1.72] and
[qepcad-B.1.72]   /root/Desktop/sage_git/sage-10.2/config.log
[qepcad-B.1.72] Describe your computer, operating system, etc.
[qepcad-B.1.72] If you want to try to fix the problem yourself, *don't* just cd to
[qepcad-B.1.72] /root/Desktop/sage_git/sage-10.2/local/var/tmp/sage/build/qepcad-B.1.72 and type 'make' or whatever is appropriate.
[qepcad-B.1.72] Instead, the following commands setup all environment variables
[qepcad-B.1.72] correctly and load a subshell for you to debug the error:
[qepcad-B.1.72]   (cd '/root/Desktop/sage_git/sage-10.2/local/var/tmp/sage/build/qepcad-B.1.72' && '/root/Desktop/sage_git/sage-10.2/sage' --buildsh)
[qepcad-B.1.72] When you are done debugging, you can type "exit" to leave the subshell.
[qepcad-B.1.72] ************************************************************************
make[4]: *** [Makefile:3211: qepcad-SAGE_LOCAL-no-deps] Error 1
make[3]: *** [Makefile:3211: /root/Desktop/sage_git/sage-10.2/local/var/lib/sage/installed/qepcad-B.1.72] Error 2
make[2]: *** [Makefile:2840: all-start] Error 2
make[2]: Leaving directory '/root/Desktop/sage_git/sage-10.2/build/make'

real	10m59.143s
user	6m33.123s
sys	0m47.424s
***************************************************************
Error building Sage.

The following package(s) may have failed to build (not necessarily
during this run of 'make all-start'):

* package:         qepcad-B.1.72
  last build time: Dec 6 19:36
  log file:        /root/Desktop/sage_git/sage-10.2/logs/pkgs/qepcad-B.1.72.log
  build directory: /root/Desktop/sage_git/sage-10.2/local/var/tmp/sage/build/qepcad-B.1.72

It is safe to delete any log files and build directories, but they
contain information that is helpful for debugging build problems.
WARNING: If you now run 'make' again, the build directory of the
same version of the package will, by default, be deleted. Set the
environment variable SAGE_KEEP_BUILT_SPKGS=yes to prevent this.

make[1]: *** [Makefile:40: all-start] Error 1
make[1]: Leaving directory '/root/Desktop/sage_git/sage-10.2'
make: *** [Makefile:13: all] Error 2
```

When I open the `qepcad-B.1.72.log` file I see the following error:
```
Attempting to download package qepcad-B.1.72.tar.gz from mirrors
https://github.com/sagemath/sage/releases/download/10.2/qepcad-B.1.72.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno 404] Not Found: '//github.com/sagemath/sage/releases/download/10.2/qepcad-B.1.72.tar.gz'
https://github.com/sagemath/sage/releases/download/10.1/qepcad-B.1.72.tar.gz
[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ERROR [transfer|run:135]: [Errno 404] Not Found: '//github.com/sagemath/sage/releases/download/10.1/qepcad-B.1.72.tar.gz'
http://files.sagemath.org/spkg/upstream/qepcad/qepcad-B.1.72.tar.gz
[......................................................................]
qepcad-B.1.72
```

Is the `qepcad-B.1.72.tar.gz` not being downloaded the issue, is there any way to resolve this?

Thanks
Best Regards

### Config log

[config.log](https://github.com/sagemath/sage/files/13594912/config.log)

### Package logs

[qepcad-B.1.72.log](https://github.com/sagemath/sage/files/13594914/qepcad-B.1.72.log)

### Additional Information

I hope these log files do not contain any sensitive data.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### LINKED ISSUE #36835: update qepcad to B 1.74, add spkg-configure
Debian and Ubuntu 22 carry qepcad B 1.74, from 2021. It's newer than ours, and might work better e.g, on arm64, cf. #36831

the canonical source is [chriswestbrown/qepcad](https://github.com/chriswestbrown/qepcad) and B.1.74 was introduced in https://github.com/chriswestbrown/qepcad/commit/185cd845bbd8b4ccb79958b101dc0fd68fe5352e

Debian and Fedora fixed more bugs, cf e.g. https://bugs.debian.org/996561 and https://github.com/chriswestbrown/qepcad/pulls

So we can use Debian's tarball from https://packages.debian.org/sid/qepcad

### PR DESCRIPTION
**Pull request by dimpase**
As noted in #36835, we missed an update to qepcad done in 2021. It has made it into Debian and Fedora,
and we use Debian's tarball and patches (most of the latter are updated versions of our B 1.72 patches)

We removed 'B' from the version number to accommodate the tarfile name from Debian.

We also update saclib to the latest version

Fixes #36831
Fixes #36835

### CODE REVIEW

**Comment by dimpase** [comment]
qepcad tests pass on x86_64 Linux and on macOS M1  (arm64)

**Comment by dimpase** [comment]
I took the liberty to promote qepcad to optional. It's in a reasonably good shape on all platforms, sort of maintained upstream, etc.

**Comment by mkoeppe** [comment]
Trivial doctest failure can be seen in the CI Linux Incremental runs, e.g. ubuntu-focal-standard https://github.com/sagemath/sage/actions/runs/7141754593/job/19449654300?pr=36837#step:11:7027
```
ile "src/sage/interfaces/qepcad.py", line 1092, in sage.interfaces.qepcad.Qepcad._parse_answer_stats
Failed example:
    stats
Expected:
    '-----------------------------------------------------------------------------\r\n0 Garbage collections, 0 Cells and 0 Arrays reclaimed, in 0 milliseconds.\r\n492514 Cells in AVAIL, 500000 Cells in SPACE.\r\n\r\nSystem time: 16 milliseconds.\r\nSystem time after the initialization: 4 milliseconds.\r\n-----------------------------------------------------------------------------\r\n'
Got:
    '-----------------------------------------------------------------------------\r\n0 Garbage collections, 0 Cells and 0 Arrays reclaimed, in 0 milliseconds.\r\n492273 Cells in AVAIL, 500000 Cells in SPACE.\r\n\r\nSystem time: 5 milliseconds.\r\nSystem time after the initialization: 2 milliseconds.\r\n-----------------------------------------------------------------------------\r\n'
**********************************************************************
1 item had failures:
   1 of   6 in sage.interfaces.qepcad.Qepcad._parse_answer_stats
    [343 tests, 1 failure, 30.35 s]
```

**Comment by mkoeppe** [comment]
> We removed 'B' from the version number to accommodate the tarfile name from Debian.

Good idea, that also matches how the versions are commonly represented according to repology.

**Comment by dimpase** [comment]
you most probably don't have to change the OS, but you need to check out the branch of that PR and build it. It will install version.1.74 of qepcad

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Comment by dimpase** [comment]
with a later develop branch, I see
```
sage -t --warn-long 14.2 --random-seed=42485267800152194636581559978378394047 src/sage/interfaces/qepcad.py
**********************************************************************
File "src/sage/interfaces/qepcad.py", line 833, in sage.interfaces.qepcad.Qepcad.?
Failed example:
    qepcad(conds, memcells=2000000) # optional - qepcad
Expected:
    2 x - 1 > 0 /\ z > 0 /\ z - y < 0 /\ 3 z + 3 y + x - 1 < 0
Got:
    finish  &
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of   6 in sage.interfaces.qepcad.Qepcad.?
```

which can be fixed by 
```diff
--- a/src/sage/interfaces/qepcad.py
+++ b/src/sage/interfaces/qepcad.py
@@ -833,7 +833,7 @@ class Qepcad:
                            x^2 + x*y + 3*x*z + 2*y*z + 2*z^2 - x - z < 0, \
                            -2*x + 1 < 0, -x*y - x*z - 2*y*z - 2*z^2 + z < 0, \
                            x + 3*y + 3*z - 1 < 0]
-            sage: qepcad(conds, memcells=2000000) # optional - qepcad
+            sage: qepcad(conds, memcells=3000000) # optional - qepcad
             2 x - 1 > 0 /\ z > 0 /\ z - y < 0 /\ 3 z + 3 y + x - 1 < 0
         """
         self._cell_cache = {}
```

**Comment by dimpase** [comment]
doctest to be fixed in #36895

**Pull request merged**
