### PR TITLE
`gmp` 6.3.0, `mpc` 1.3.1, `mpfr` 4.2.1, `mpfrcx` 0.6.3, `gmpy2` 2.2.0a1

### PR DESCRIPTION
**Pull request by mkoeppe**
The unreleased 2.2.x series has work on support for Python 3.12

https://github.com/aleaxit/gmpy

The new version makes it necessary to tighten the requirements for MPC and MPFR.
We do the version check without pkg-config as before; changing it to pkg-config is #31348.

(The upgrade of the packages was previously done in #36775, but has now been merged here.)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tornaria** [comment]
FWIW, we are shipping 2.2.0a1 in void linux since september. This supports python 3.12 and is available on pypi: https://pypi.org/project/gmpy2/2.2.0a1/

**Comment by mkoeppe** [comment]
Thanks @tornaria, I'll try switching to this release!

**Comment by mkoeppe** [comment]
Full tests at https://github.com/mkoeppe/sage/actions/runs/7205490817

`debian-bullseye` has MPC 1.2.0, which passes my test in spkg-configure but is rejected by gmpy2 (it needs 1.2.1).

**Comment by dimpase** [comment]
we can as we often do get the MPC version from mpc.h - akin to what we do for NTL 😭 
```c
/* Define MPC version number */
#define MPC_VERSION_MAJOR 1
#define MPC_VERSION_MINOR 3
#define MPC_VERSION_PATCHLEVEL 1
#define MPC_VERSION_STRING "1.3.1"

/* Macros dealing with MPC VERSION */
#define MPC_VERSION_NUM(a,b,c) (((a) << 16L) | ((b) << 8) | (c))
#define MPC_VERSION                                                     \
  MPC_VERSION_NUM(MPC_VERSION_MAJOR,MPC_VERSION_MINOR,MPC_VERSION_PATCHLEVEL)
```

**Comment by mkoeppe** [comment]
I'm just copying the test from gmpy.h

**Comment by dimpase** [comment]
Do you mean `AC_RUN_` and not `AC_LINK_`?!

**Comment by mkoeppe** [comment]
No

**Comment by mkoeppe** [comment]
This is a compile-time test

**Comment by dimpase** [comment]
It's `AC_COMPILE_` then.

**Comment by mkoeppe** [comment]
I'll get back to it later when I have a bit more time. Feel free to push a fix

**Comment by dimpase** [comment]
ready now, I think

**Comment by mkoeppe** [comment]
Thanks. I've switched the lib test to use a newer function, like I did previously in 109671e66768e90ed19a88d62472e56915d85be7

**Comment by mkoeppe** [comment]
Thanks.

**Comment by tobiasdiez** [comment]
Conda tests fail for this PR.

**Comment by mkoeppe** [comment]
I explained the principle to you in https://github.com/sagemath/sage/pull/35593#discussion_r1405603999

**Comment by tobiasdiez** [comment]
Since when do we have the principle to just ignore tests when they don't suit you?

There is no need for sagelib to require a unreleased version of gmpy2.

**Comment by mkoeppe** [comment]
Tobias, stop this nonsense.

**Comment by dimpase** [comment]
if conda tests fail, we need to make sure this gmpy2 version (released on PyPI) makes it to Conda quickly.

I am not sure it is feasible to maintain support for two seriously different versions of gmpy2 and a bunch of libraries - unless it all just works on Conda, and the test in question breaks it for no good reason.

**Comment by vbraun** [comment]
Tests fail because of missing hypothesis, is this intentional?
```
[gmpy2-2.2.0a1] ImportError while importing test module '/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.2.0a1/src/test/test_mpz.py'.
[gmpy2-2.2.0a1] Hint: make sure your test modules/packages have valid Python names.
[gmpy2-2.2.0a1] Traceback:
[gmpy2-2.2.0a1] ../../../../../../../lib/python3.11/importlib/__init__.py:126: in import_module
[gmpy2-2.2.0a1]     return _bootstrap._gcd_import(name[level:], package, level)
[gmpy2-2.2.0a1] test_mpz.py:6: in <module>
[gmpy2-2.2.0a1]     from hypothesis import assume, given, example, settings
[gmpy2-2.2.0a1] E   ModuleNotFoundError: No module named 'hypothesis'
[gmpy2-2.2.0a1] ______________________ ERROR collecting test/test_mpq.py _______________________
```

**Comment by mkoeppe** [comment]
> Tests fail because of missing hypothesis, is this intentional?

Sorry about this, I'll fix it.

**Comment by mkoeppe** [comment]
> we need to make sure this gmpy2 version (released on PyPI) makes it to Conda quickly.

It's a downstream activity.

#35593 removes the friction by enabling pip packages to be used where necessary to provide the missing standard packages. Needs review.

**Comment by orlitzky** [comment]
I think I'm with Tobias on this one. Do we have to _require_ the alpha version, rather than just bundle and support it? Sage isn't the only thing people use their computers for.

**Comment by mkoeppe** [comment]
We can certainly adjust the `install-requires` to require this version only for Python 3.12.

**Comment by mkoeppe** [comment]
I'll move the handling of the Python 3.12 requirement to #36181, to simplify the present PR.

**Comment by mkoeppe** [comment]
```
  [sagemath_objects-10.3.beta3] ERROR: Could not find a version that satisfies the requirement gmpy2>=2.1.0 (from versions: 2.2.0a1)
  [sagemath_objects-10.3.beta3] ERROR: No matching distribution found for gmpy2>=2.1.0
  [sagemath_objects-10.3.beta3] 
 ```

**Comment by mkoeppe** [comment]
This is ready, let's get it in please.

**Comment by vbraun** [comment]
I'm getting lots of testsuite fails on OSX around signs of NaN
```
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 515, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('nan'), a)
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('-nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?        +             +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 519, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('Inf'), G.mpz(0))
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?                     +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] File "/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.11.1/var/tmp/sage/build/gmpy2-2.1.2/src/test/test_mpz.txt", line 523, in test_mpz.txt
[gmpy2-2.1.2] Failed example:
[gmpy2-2.1.2]     divmod(mpfr('nan'), G.mpz(0))
[gmpy2-2.1.2] Differences (ndiff with -expected +actual):
[gmpy2-2.1.2]     - (mpfr('nan'), mpfr('nan'))
[gmpy2-2.1.2]     + (mpfr('-nan'), mpfr('-nan'))
[gmpy2-2.1.2]     ?        +             +
[gmpy2-2.1.2] **********************************************************************
[gmpy2-2.1.2] 1 items had failures:
[gmpy2-2.1.2]   25 of 230 in test_mpz.txt
[gmpy2-2.1.2] ***Test Failed*** 25 failures.
[gmpy2-2.1.2] Results for:  test_mpz                  Attempted:  230   Failed:   25
[gmpy2-2.1.2] Results for:  test_mpz_create           Attempted:   58   Failed:    0
[gmpy2-2.1.2] Results for:  test_mpz_io               Attempted:   60   Failed:    0
[gmpy2-2.1.2] Results for:  test_mpz_pack_unpack      Attempted:   16   Failed:    0
[gmpy2-2.1.2] 
[gmpy2-2.1.2]                               Summary - Attempted: 3556   Failed:   95
[gmpy2-2.1.2] 
[gmpy2-2.1.2] Running external test programs.
[gmpy2-2.1.2] Running test_pack.py                    successful
[gmpy2-2.1.2] Running test_mpz_args.py                successful
[gmpy2-2.1.2] 
[gmpy2-2.1.2] real	0m1.418s
[gmpy2-2.1.2] user	0m1.349s
[gmpy2-2.1.2] sys	0m0.049s
[gmpy2-2.1.2] ************************************************************************
[gmpy2-2.1.2] Error testing package gmpy2-2.1.2
[gmpy2-2.1.2] ************************************************************************
```

**Comment by dimpase** [comment]
how come this is something which precludes merge?

Does anyone use signs of `nan`?

Ought to be reported upstream.

Is it arm or x86_64 ?

**Comment by dimpase** [comment]
and, this is gmpy2 already in Sage?!

we're trying to get gmpy2 version 2.2.0* in.

**Comment by vbraun** [comment]
I guess this is due to 36775 instead.

Maybe both should be merged together? Please **test** before setting to positive review.

The buildbot is x86_64 for the record

**Comment by dimpase** [comment]
#36775 ought to be merged 1st

**Comment by dimpase** [comment]
although it says that #36775 is merged in this branch

**Comment by mkoeppe** [comment]
With the gmpy2 upgrade here, passes all tests on the same machine where I reproduced the failures reported in https://github.com/sagemath/sage/pull/36775#issuecomment-1868490746 with the old gmpy2.

**Comment by mkoeppe** [comment]
All tests passed, let's get this in.

**Comment by saraedum** [comment]
> if conda tests fail, we need to make sure this gmpy2 version (released on PyPI) makes it to Conda quickly.

Note that conda usually does not package alphas. Is the alpha absolutely necessary now? Does anything break badly if I just install sagelib with gmpy 2.1.x?

**Comment by mkoeppe** [comment]
Check what's declared in `build/pkgs/gmpy2/install-requires.txt`.

**Comment by saraedum** [comment]
It says gmpy2 ~=2.1.b999.  Which means yes. Though that `.` before the `b` confuses me.

**Comment by mkoeppe** [comment]
This should accept all 2.1.x versions, or at least so I claimed in the 4bdb76dacac904fd2a9791cec728055cb5a4467e commit.

**Pull request merged**
