### PR TITLE
implement E_polynomial of hypergeometric motive

### PR DESCRIPTION
**Pull request by fchapoton**
This is adding a new method tp hypergeometric motives.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by xcaruso** [comment]
Don't you want to give the possibility to the user to choose different variable names?

**Comment by fchapoton** [comment]
bof, pas vraiment. utiliser `u` et `v` est relativement standard, je crois

**Comment by xcaruso** [comment]
Well, in the paper you cite, I cannot see any occurrence of u and v :-)

**Comment by xcaruso** [comment]
Thanks!
I won't complain that there is no doctest showing an example with different variable names...

**Comment by fchapoton** [comment]
merci !

**Pull request merged**
