### PR TITLE
Introduce negated optional tag

### PR DESCRIPTION
**Pull request by kwankyu**
motivated by https://github.com/sagemath/sage/pull/38764#issuecomment-2408715647

fixes https://github.com/sagemath/sage/pull/38764#issuecomment-2408523957

example:
```sage
      sage: SloaneEncyclopedia[60843]    # optional - sloane_database
      [1, 6, 21, 107, 47176870]

      sage: SloaneEncyclopedia[60843]    # optional - !sloane_database
      Traceback (most recent call last):
      ...
      OSError: The Sloane Encyclopedia database must be installed. Use e.g.
      'SloaneEncyclopedia.install()' to download and install it.
```
along the way, we

- define `sloane_database` feature (I wonder why it was missing)
- fix `SloaneEncyclopedia` with the code by @sheerluck: https://github.com/sheerluck)https://github.com/sagemath/sage/issues/34655#issuecomment-1418189098
- fix the problem of `solve()` for rubiks cube of silently choosing the gap algorithm even when an algorithm is explicitly specified.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
The ci failures are unrelated.

**Comment by kwankyu** [comment]
I forgot to commit the new features for `dot2tex` and `sloane_database`...

**Comment by kiwifb** [comment]
@kwankyu sorry if it is at cross-purpose, we have just noted that you are introducing a `dot2tex` feature here. Do you think we can use it to help with stuff like #33947 and https://github.com/cschwan/sage-on-gentoo/issues/796 ?

**Comment by kwankyu** [comment]
Yes, of course.

Both issues seem to be fixed with this PR or helped by this PR.

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
