### PR TITLE
Fix sync labels issues for step 2 going live

### PR DESCRIPTION
**Pull request by soehms**
This is a follow up PR of https://github.com/sagemath/sage/pull/35172. It addresses the issues observed in the second step of going live (https://github.com/sagemath/sage/issues/35927#issuecomment-1664313362) of the label sync bot, which had to be disabled after a day (https://github.com/sagemath/sage/issues/35927#issuecomment-1704023077). As observed in https://github.com/sagemath/sage/pull/36177#issuecomment-1704022893, this was caused by a bug concerning the `reviewDecision` in case the reviewer does not have appropriate access rights to the repository. In this case `gh pr view` returns None as `reviewDecision` which has been mapped to `COMMENTED` by caching reasons. The bug is that comparisons with `reviewDecision` have not been adapted to the cached value.

Furthermore, the log-file sequence displayed in https://github.com/sagemath/sage/pull/36177#issuecomment-1704022893 shows another unexpected behavior:

```
> INFO:root:Proper reviews after 2023-09-02T07:55:03Z for pull request #36177: [{'id': 'PRR_kwDOI5-Tx85f2_5f', 'author': {'login': 'dcoudert'}, 'authorAssociation': 'CONTRIBUTOR', 'body': 'LGTM.', 'submittedAt': '2023-09-02T13:23:57Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'APPROVED', 'commit': {'oid': '626b764283b5005ab3a64661f7cc74efcd31adb9'}}, {'id': 'PRR_kwDOI5-Tx85f3sRb', 'author': {'login': 'tobiasdiez'}, 'authorAssociation': 'CONTRIBUTOR', 'body': "Let's see if its works when admins approve a PR", 'submittedAt': '2023-09-03T06:08:30Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'APPROVED', 'commit': {'oid': '626b764283b5005ab3a64661f7cc74efcd31adb9'}}]
```

Here I had expected `'authorAssociation': 'MEMBER'` instead of `'authorAssociation': 'CONTRIBUTOR'` as it is shown when I do the query on my local command-line:

```
gh pr view https://github.com/sagemath/sage/pull/36177 --json reviews
{
  "reviews": [
    {
      "author": {
        "login": "dcoudert"
      },
      "authorAssociation": "MEMBER",
      "body": "LGTM.",
      "submittedAt": "2023-09-02T13:23:57Z",
      "includesCreatedEdit": false,
      "reactionGroups": [],
      "state": "APPROVED"
    },
    {
      "author": {
        "login": "tobiasdiez"
      },
      "authorAssociation": "MEMBER",
      "body": "Let's see if its works when admins approve a PR",
      "submittedAt": "2023-09-03T06:08:30Z",
      "includesCreatedEdit": false,
      "reactionGroups": [],
      "state": "APPROVED"
    }
  ]
}
```

As described in https://github.com/flutter/flutter/issues/101012 this is caused since the github bot is not a member of the sagemath organisation and most of our members (me too) have set the private role which makes their membership just visible to other members.

This is relevant in the `approve_allowed` method:

```
    def approve_allowed(self):
        r"""
        Return if the actor has permission to approve this PR.
        """
        revs = self.get_reviews(complete=True)
        if not any(rev['authorAssociation'] in ('MEMBER', 'OWNER') for rev in revs):
            info('PR %s can\'t be approved because of missing member review' % (self._issue))
            return False
        ....
```

where the bot checks if it should set the `approved` state by itself. This did also fail in the example (from the [log-file](https://github.com/sagemath/sage/actions/runs/6060223064/job/16444158489)):

```
INFO:root:PR pull request #36177 doesn't have positve review (by decision)
INFO:root:PR pull request #36177 can't be approved because of missing member review
```

I think we can eliminate the check for a member review entirely as it is an unnecessary restriction. The check is only relevant if an `s: positive review` label is added, which can only be done by Triage members who know what they are doing. Even if we just added `CONTRIBUTOR` to the list, it would still be restrictive, as it would not be possible to set `s: positive review` when there is no review (this would be annoying for trivial PR that just has some PEP8 fixes).

This PR changes the following flowchart from https://github.com/sagemath/sage/pull/35172 :

```mermaid
---
title: approve allowed?
---
flowchart LR

%% vertices

    trigger([approve\n allowed?])
    true([true])
    false([false])
    review_of_others_request_changes{changes\n requested by\n someone\n else exists?}
    actor_valid[[actor valid?]]

%% edges

    trigger --> review_of_others_request_changes
    review_of_others_request_changes -- yes ---> false
    review_of_others_request_changes -- no ---> actor_valid
    actor_valid -- yes ---> true
    actor_valid -- no ---> false
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]
LGTM.

From my point of view, we can simply merge this and test it live once it's in the develop branch.

**Comment by soehms** [comment]
> LGTM.
> 
> From my point of view, we can simply merge this and test it live once it's in the develop branch.

I hesitated because I discovered another gap. It is not relevant to the `labeled` event, but to the `synchronized` event. Maybe we can do this in a separate PR. It's the following scenario: 

If a PR has a `positive review` and the developer rebases the branch to a new beta version (for whatever reason, perhaps accidentally), then the PR would revert to `needs review` (by the current code). 

Is there a way to distinguish whether the `synchronized` event was triggered by a code change in the branch or by a rebase? If not, I think we should better ignore the `synchronized` event for positve reviewed PR's.

**Comment by tobiasdiez** [comment]
Isn't this a good thing (it's similar to github feature that resets positive reviews if the PR branch is updated)? Something could go wrong during a rebase so it doesn't hurt to have a second pair of eyes double checking it. If the rebase was trivial it should be possible however to set it back to positive review.

Anyway, let's do this as a follow-up!

**Comment by soehms** [comment]
> Isn't this a good thing (it's similar to github feature that resets positive reviews if the PR branch is updated)? Something could go wrong during a rebase so it doesn't hurt to have a second pair of eyes double checking it. If the rebase was trivial it should be possible however to set it back to positive review.
> 
> Anyway, let's do this as a follow-up!

Good Point! Then we leave it as it is until someone objects.

Thanks for the review!

**Comment by tobiasdiez** [comment]
I've activated the label event again...

**Comment by soehms** [comment]
> I've activated the label event again...

@tobiasdiez can you please disable the trigger again. I've analysed a case where there is still a bug in the `get_review_decision`-method (it does still return `UNCLEAR` on the first call).

**Comment by tobiasdiez** [comment]
okay done!

**Comment by kwankyu** [comment]
Please post a message in sage-devel when you activate a label event.

**Comment by soehms** [comment]
> can you please disable the trigger again. I've analyzed a case where there is still a bug in the `get_review_decision`-method (it does still return `UNCLEAR` on the first call).

I've opened https://github.com/sagemath/sage/pull/36292 for a fix.

**Comment by soehms** [comment]
> Please post a message in sage-devel when you activate a label event.

I updated the comment https://github.com/sagemath/sage/issues/35927#issuecomment-1664313362 which has am mention for the Triage team. Didn't you get a notification?

**Comment by kwankyu** [comment]
I don't remember exactly. Anyway, I noticed it first while I was interacting with 

https://github.com/sagemath/sage/pull/36020

which is still in an awful state.

**Comment by soehms** [comment]
> I don't remember exactly. Anyway, I noticed it first while I was interacting with
> 
> #36020
> 
> which is still in an awful state. I couldn't remove "needs review" label. Could I do it now?

As soon as @tobiasdiez  has disabled the `unlabeled` trigger (which obviously has been activated accidentially) you can remove the state label there.

**Pull request merged**
