### PR TITLE
`build/pkgs/python_build`: Make it a standard wheel package

### PR DESCRIPTION
**Pull request by mkoeppe**
Vote: https://groups.google.com/g/sage-devel/c/MIU-xo9b7pc

Vote again: https://groups.google.com/g/sage-devel/c/EMeTJ6Hwgns (approved)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
The failures in CI Linux incremental are the unrelated #37786.

**Review by kiwifb — APPROVED** [review]
The addition has been approved and really nothing in here has any consequence on sagemath apart from the sudden availability of it in standard install.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by mkoeppe** [comment]
Once again, someone is manipulating labels here.

**Comment by jplab** [comment]
@tobiasdiez: I am trying to understand the removal on the label "positive review" here. Could you help me out? Carefully checking the timestamp of every vote on sage-devel and checking the time of the removal of the "positive review", I can infer two things:

- The negative votes were recorded after that the author expressed the approval.
- Once the negative votes reached the threshold of "it shouldn't be a positive review yet", you removed the "positive review" tag.

Perhaps I am missing something: on the related sage-devel discussion, a vote has taken place. The author expressed the approval before others did put their vote in writing. Then, you changed the label 12 hours after, without explanation (which leaves me trying to figure out what happened here). Then, the discussion on sage-devel continues, and so do the votes, and as of right now, I count 5-2.

What I can see, is first that the current decision process on PRs requiring a vote has to be improved. This shall be reported on sage-devel, for a discussion with the community.

Second, the trace left on the development thread here is not what I, personally, qualify as constructive or transparent (as I am trying to understand what is going on, I am struggling!).

My suggestion, as a member of the Code of Conduct Committee, is that for transparency and constructiveness sake, I would suggest that changing labels should always be done with a justification (just like I was always used to on "trac" since 2010).

**Comment by mkoeppe** [comment]
I'm restoring the "positive review" label.

**Comment by saraedum** [comment]
@dimpase it is my understanding that this is not a "disputed" PR. There is a regular vote on sage-devel about this PR. The vote has now been open for a week and a majority is in favor if I read it correctly. (Maybe the vote has been called a bit too quickly initially, btw.)

**Pull request merged**
