### PR TITLE
Update `conway_polynomials`, `database_cubic_hecke`, `database_knotinfo`, `matroid_database`

### PR DESCRIPTION
**Pull request by mkoeppe**
Using `sage --package update-latest ... --commit`.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by gmou3 — APPROVED** [review]

**Comment by kwankyu** [comment]
As "CI Linux incremental" is all broken, we cannot test package upgrades. Would it be fixed sooner or later?

**Comment by mkoeppe** [comment]
> As "CI Linux incremental" is all broken, we cannot test package upgrades.

It does reveal already:
```
#30 518.4   [conway_polynomials-0.10]   sage_bootstrap.tarball.FileNotMirroredError: tarball does not exist on mirror network and neither at the upstream URL
#30 518.4   [conway_polynomials-0.10]   ************************************************************************
#30 518.4   [conway_polynomials-0.10]   Error downloading tarball of conway_polynomials
#30 518.4   [conway_polynomials-0.10]   ************************************************************************
```

**Comment by mkoeppe** [comment]
But I hope to fix the workflow soon, on top of #36730

**Comment by kwankyu** [comment]
> > As "CI Linux incremental" is all broken, we cannot test package upgrades.
> 
> It does reveal already:
> 
> ```
> #30 518.4   [conway_polynomials-0.10]   sage_bootstrap.tarball.FileNotMirroredError: tarball does not exist on mirror network and neither at the upstream URL
> #30 518.4   [conway_polynomials-0.10]   ************************************************************************
> #30 518.4   [conway_polynomials-0.10]   Error downloading tarball of conway_polynomials
> #30 518.4   [conway_polynomials-0.10]   ************************************************************************
> ```

I meant that package upgrades need  portability checks, unless they are python packages.

**Comment by kwankyu** [comment]
OK. They are all python packages:
```
$ sage --package properties conway_polynomials database_cubic_hecke database_knotinfo matroid_database
conway_polynomials:
        path:                        /Users/kwankyu/GitHub/sage-dev/build/pkgs/conway_polynomials
        version_with_patchlevel:     0.8
        type:                        standard
        source:                      normal
        trees:                       SAGE_VENV
        purl:                        pkg:pypi/conway-polynomials
database_cubic_hecke:
        path:                        /Users/kwankyu/GitHub/sage-dev/build/pkgs/database_cubic_hecke
        version_with_patchlevel:     2022.3.1
        type:                        optional
        source:                      normal
        trees:                       SAGE_VENV
        purl:                        pkg:pypi/database-cubic-hecke
database_knotinfo:
        path:                        /Users/kwankyu/GitHub/sage-dev/build/pkgs/database_knotinfo
        version_with_patchlevel:     2024.2.1
        type:                        optional
        source:                      normal
        trees:                       SAGE_VENV
        purl:                        pkg:pypi/database-knotinfo
matroid_database:
        path:                        /Users/kwankyu/GitHub/sage-dev/build/pkgs/matroid_database
        version_with_patchlevel:     0.2
        type:                        optional
        source:                      wheel
        trees:                       SAGE_VENV
        purl:                        pkg:pypi/matroid-database
```

**Comment by kwankyu** [comment]
By the way, I wonder why "matroid_database" is named inconsistently with other database packages named "database_..."...

**Comment by mkoeppe** [comment]
It's true though that the optional database packages are only being tested by the "CI Linux Incremental" workflow, not the "Build & Test" workflow.

**Review by kwankyu — APPROVED** [review]
OK. The optional package upgrades work well on my system.

**Comment by mkoeppe** [comment]
Thanks!

**Comment by gmou3** [comment]
> By the way, I wonder why "matroid_database" is named inconsistently with other database packages named "database_..."...

Donno why all others are named `database_*`, but `matroid_database` is a fine name in my opinion. It is an external package, not only for sage.

**Comment by kwankyu** [comment]
Yes. I understand that now.

**Comment by mkoeppe** [comment]
@vbraun Missing file: conway_polynomials-0.10-py3-none-any.whl
https://github.com/sagemath/sage/actions/runs/9333677038/job/25690937943#step:4:3359

**Comment by vbraun** [comment]
should be live now

**Pull request merged**
