### PR TITLE
Deprecate `is_Ideal`, `is_LaurentSeries`, `is_MPolynomialIdeal`, `is_MPolynomialRing`, `is_MPowerSeries`, `is_PolynomialQuotientRing`, `is_PolynomialRing`, `is_PolynomialSequence`, `is_PowerSeries`, `is_QuotientRing`

### PR DESCRIPTION
**Pull request by mkoeppe**
Part of:
- #32414

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38151 (merged here)

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Tests fail with #38151

**Comment by mkoeppe** [comment]
The test failure is a well-known sporadic timeout.
Back to positive.

**Pull request merged**
