### PR TITLE
Allow completion() to return a lazy series for infinite precision

### PR DESCRIPTION
**Pull request by tscrim**
### 📚 Description

We allow the `completion()` methods of polynomial rings to take infinite precision, in which case they return the corresponding lazy object. This also implements a `completion()` method to graded algebras and set a default equivalent to by degree for some general compatibility. (Full compatibility is not attempted due to general differences in the current implementation. This can be done on a later ticket.)

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mantepse** [comment]
There seems to be a problem with the docbuild, could you check?
```
[sagemath_doc_html-none] [polynomia] docstring of sage.rings.polynomial.multi_polynomial_ring_base.MPolynomialRing_base.completion:10: WARNING: Bullet list ends without a blank line; unexpected unindent.
[sagemath_doc_html-none] [polynomia] docstring of sage.rings.polynomial.multi_polynomial_ring_base.MPolynomialRing_base.completion:11: WARNING: Block quote ends without a blank line; unexpected unindent.
```

Unrelated: allowing `prec=oo` everywhere is a different ticket, right?  Here are some examples:
```
categories/number_fields.py\0125:        def zeta_function(self, prec=53,
categories/lie_algebras.py\0609:        def bch(self, X, Y, prec=None):
groups/matrix_gps/finitely_generated.py\0831:    def molien_series(self, chi=None, return_series=True, prec=20, variable='t'):
modular/modsym/space.py\0607:    def q_expansion_basis(self, prec=None, algorithm='default'):
```

**Comment by tscrim** [comment]
I didn't check locally for the docbuild. I will fix that.

I can do those here too as it is a slight but very natural expansion of the scope.

**Comment by tscrim** [comment]
The `modform/modsym/space.py` needs to do linear algebra over an infinite dimensional space. So it might be possible to make it work, it is a much more complicated and somewhat unrelated problem.

**Comment by tscrim** [comment]
The `zeta_function` has to do with the precision of the underlying real number field. So it is irrelevant.

The `bch` requires doing computations in a set (generally non-graded) Lie algebra. It is possible that the computation could be modified for a graded Lie algebra and then done in the completion (in perhaps some special cases), but it is not really a computation that could be done lazily.

I changed the Molien series to handle infinite precision. This led to a natural extension of the conversion from the fraction field of the corresponding (Laurent) polynomial ring. For the Laurent series ring, this could be promoted to a coercion, but we cannot do that for a power series over a ring (although it should be fine over a field). I just did the easiest thing here that was natural and didn't bother with changing the coercions.

Something I noticed, there is a bit of an annoying thing about differentiating between sparse and dense polynomials. I am not sure of a good way to easily fix this, and that deserves its own issue/PR.

**Comment by mantepse** [comment]
Thank you for going through this!

At first I was puzzled that you don't try to convert `x` into a rational function immediately (instead of trying to convert it into a polynomial), but I guess it's easier the way you did it.

Thank you again!

**Review by mantepse — APPROVED** [review]

**Comment by tscrim** [comment]
Thank you.

We would run into problems if we tried to make a rational function first as we would then have to analyze the denominator. Plus the polynomial to fraction field conversion could be another source of subtleties, and I felt the polynomial conversion should be prioritized in the code.

**Review by mantepse — APPROVED** [review]

**Comment by tscrim** [comment]
Thank you!

**Comment by vbraun** [comment]
Merge conflict

**Comment by tscrim** [comment]
Trivial rebase (the Laurent polynomial ring implementation had moved files).

**Pull request merged**
