### PR TITLE
cylint: remove unused imports in folders [s-z]*

### PR DESCRIPTION
**Pull request by fchapoton**
### :books: Description

remove unused imports found by cython-lint in all folders from s* to z*

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
Someone did a bad import:
```
  File "/__w/sage/sage/src/sage/structure/formal_sum.py", line 76, in <module>
    from sage.structure.coerce import LeftModuleAction, RightModuleAction
```
This is causing the build to fail. `:3`

**Review by tscrim — APPROVED** [review]
LGTM assuming all tests pass. If they do, then set a positive review.

**Comment by fchapoton** [comment]
thanks, Travis. Now setting to positive. Maybe you should approve the code, as I have squashed the branch.

**Review by tscrim — APPROVED** [review]
The approval seem to carry over regardless if there are further changes pushed... Anyways, better to reapprove than to have this bitrot.

**Pull request merged**
