### PR TITLE
`openblas`: Update to 0.3.23

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.23

- fixes the build on `fedora-38-minimal`
- the known build errors on `archlinux-latest-minimal` (#34899) and `opensuse-tumbleweed-minimal` persist after this update

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Testing on macOS, I'm getting a bunch of errors like this:
```
sage -t --random-seed=88906055599883703380957581517190276719 src/sage/matrix/matrix_double_dense.pyx
**********************************************************************
File "src/sage/matrix/matrix_double_dense.pyx", line 476, in sage.matrix.matrix_double_dense.Matrix_double_dense.condition
Failed example:
    id.condition(p=1)
Expected:
    1.0
Got:
    +Infinity
**********************************************************************
File "src/sage/matrix/matrix_double_dense.pyx", line 521, in sage.matrix.matrix_double_dense.Matrix_double_dense.condition
Failed example:
    c = A.norm(2)*A.inverse().norm(2)
Exception raised:
    Traceback (most recent call last):
      File "sage/matrix/matrix_double_dense.pyx", line 345, in sage.matrix.matrix_double_dense.Matrix_double_dense.__invert__
        M._matrix_numpy = scipy.linalg.inv(self._matrix_numpy)
      File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/scipy/linalg/_basic.py", line 975, in inv
        raise LinAlgError("singular matrix")
    numpy.linalg.LinAlgError: singular matrix

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.matrix.matrix_double_dense.Matrix_double_dense.condition[35]>", line 1, in <module>
        c = A.norm(Integer(2))*A.inverse().norm(Integer(2))
      File "sage/matrix/matrix2.pyx", line 9964, in sage.matrix.matrix2.Matrix.inverse
        return ~self
      File "sage/matrix/matrix_double_dense.pyx", line 347, in sage.matrix.matrix_double_dense.Matrix_double_dense.__invert__
        raise ZeroDivisionError("input matrix must be nonsingular")
    ZeroDivisionError: input matrix must be nonsingular
```

**Comment by mkoeppe** [comment]
Updating numpy to 1.24.2 (via #35081) does not help with this.

**Comment by dimpase** [comment]
What do scipy people do about it? They depend on OpenBLAS.

**Comment by jhpalmieri** [comment]
Independently of this ticket, I made my own branch with an upgrade of `openblas`. For what it's worth, the documentation built for me (didn't see the error that arose using homebrew's `openblas`) but I do see the doctest failures.

**Comment by tornaria** [comment]
openblas 0.3.23 was released, and all doctests in sage pass now.

**Comment by jhpalmieri** [comment]
Using the latest `openblas` 0.3.23 on homebrew works for me on a machine that gave me problems before (as noted on #35377).

**Comment by mkoeppe** [comment]
Test at https://github.com/mkoeppe/sage/actions/runs/4918364447

**Comment by jhpalmieri** [comment]
Does `spkg-configure.m4` need to be changed to allow the use of version 0.3.23 from the system? I don't know `m4` syntax so I don't know if only 0.3.22 is being rejected or all versions 0.3.22 and later.

**Comment by mkoeppe** [comment]
That was done in #35524 (already merged)

**Comment by mkoeppe** [comment]
I've tested it on a few platforms in https://github.com/mkoeppe/sage/actions/runs/4922782397 (using #35380). It seems fine.

**Comment by jhpalmieri** [comment]
Let's proceed with this.

**Review by jhpalmieri — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
