### PR TITLE
polymake 4.11

### LINKED ISSUE #36023: old Polymake incompatibility with system Perl 5.38 (Fedora 39) - update to polymake 4.11
https://forum.polymake.org/viewtopic.php?t=1914

Polymake recommends installing suitable Perl via perlbrew:
https://polymake.org/doku.php/install/install#perlbrew

Polymake also provides BinaryBuilder.org/JLL-based binaries that ship a suitable Perl (and all libraries include gmp, ...). 
- https://polymake.org/doku.php/install/jll
- ... made using https://github.com/JuliaPackaging/JLLPrefixes.jl and https://github.com/benlorenz/pmjll
- ... from https://github.com/JuliaBinaryWrappers/Perl_jll.jl (built from https://github.com/JuliaPackaging/Yggdrasil/tree/master/P/Perl/bundled)
- ... from https://github.com/JuliaBinaryWrappers/polymake_jll.jl 
- etc.

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #36023

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36930

### CODE REVIEW

**Comment by kwankyu** [comment]
"CI Linux incremental" all failed. Is that related with this PR? Or rerunning the test will fix itself after rebase?

**Comment by mkoeppe** [comment]
It's because it was trying to install dummy packages perl_cpan_polymake_prereq, libxml2.

I think I fixed this recently in the workflows

**Comment by mkoeppe** [comment]
Rebased, let's see.

**Comment by kwankyu** [comment]
My system has polymake 4.11. So I ran `make polymake`, which failed 
```
...
[perl_term_readline_gnu-1.35] Successfully installed perl_term_readline_gnu-1.35
[perl_term_readline_gnu-1.35] Deleting temporary build directory
[perl_term_readline_gnu-1.35] /Users/kwankyu/GitHub/sage-dev/local/var/tmp/sage/build/perl_term_readline_gnu-1.35
[perl_term_readline_gnu-1.35] Finished installing perl_term_readline_gnu-1.35
make --no-print-directory perl_cpan_polymake_prereq-SAGE_LOCAL-no-deps
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Note: perl_cpan_polymake_prereq is a dummy package that the Sage distribution uses
[perl_cpan_polymake_prereq-none] to provide information about equivalent system packages.
[perl_cpan_polymake_prereq-none] It cannot be installed using the Sage distribution.
[perl_cpan_polymake_prereq-none] Please install it manually, for example using the system packages
[perl_cpan_polymake_prereq-none] recommended at the end of a run of './configure'
[perl_cpan_polymake_prereq-none] See below for package-specific information.
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] perl_cpan_polymake_prereq: Represents all Perl packages that are prerequisites for polymake
[perl_cpan_polymake_prereq-none] ===========================================================================================
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Description
[perl_cpan_polymake_prereq-none] -----------
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] This script package represents all Perl packages that are prerequisites
[perl_cpan_polymake_prereq-none] for polymake.
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] License
[perl_cpan_polymake_prereq-none] -------
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Various free software licenses
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Type
[perl_cpan_polymake_prereq-none] ----
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] optional
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Dependencies
[perl_cpan_polymake_prereq-none] ------------
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Version Information
[perl_cpan_polymake_prereq-none] -------------------
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Equivalent System Packages
[perl_cpan_polymake_prereq-none] --------------------------
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] alpine:
[perl_cpan_polymake_prereq-none]     $ apk add perl-term-readkey perl-dev perl-file-slurp perl-json \
[perl_cpan_polymake_prereq-none]           perl-xml-writer perl-xml-libxslt
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] cpan:
[perl_cpan_polymake_prereq-none]     $ cpan -i XML::Writer XML::LibXML XML::LibXSLT File::Slurp JSON SVG \
[perl_cpan_polymake_prereq-none]           Term::ReadKey
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Debian/Ubuntu:
[perl_cpan_polymake_prereq-none]     $ sudo apt-get install libxml-libxslt-perl libxml-writer-perl libxml2-dev \
[perl_cpan_polymake_prereq-none]           libperl-dev libfile-slurp-perl libjson-perl libsvg-perl \
[perl_cpan_polymake_prereq-none]           libterm-readkey-perl libterm-readline-gnu-perl
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Fedora/Redhat/CentOS:
[perl_cpan_polymake_prereq-none]     $ sudo yum install perl-ExtUtils-Embed perl-File-Slurp perl-JSON \
[perl_cpan_polymake_prereq-none]           perl-Term-ReadLine-Gnu perl-TermReadKey perl-XML-Writer \
[perl_cpan_polymake_prereq-none]           perl-XML-LibXML perl-XML-LibXSLT
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] freebsd:
[perl_cpan_polymake_prereq-none]     $ sudo pkg install textproc/p5-XML-Writer textproc/p5-XML-LibXML \
[perl_cpan_polymake_prereq-none]           textproc/p5-XML-LibXSLT devel/p5-File-Slurp converters/p5-JSON \
[perl_cpan_polymake_prereq-none]           textproc/p5-SVG devel/p5-Term-ReadKey
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] gentoo:
[perl_cpan_polymake_prereq-none]     $ sudo emerge XML-Writer XML-LibXML XML-LibXSLT File-Slurp \
[perl_cpan_polymake_prereq-none]           dev-perl/Term-ReadLine-Gnu dev-perl/TermReadKey JSON SVG
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] void:
[perl_cpan_polymake_prereq-none]     $ sudo xbps-install perl-File-Slurp perl-JSON perl-SVG perl-Term-ReadKey \
[perl_cpan_polymake_prereq-none]           perl-XML-LibXML perl-XML-LibXSLT perl-XML-Writer
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] If the system package is installed, ./configure will check if it can be used.
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] 
[perl_cpan_polymake_prereq-none] Error: perl_cpan_polymake_prereq is a dummy package and 
[perl_cpan_polymake_prereq-none] cannot be installed using the Sage distribution.
make[2]: *** [perl_cpan_polymake_prereq-SAGE_LOCAL-no-deps] Error 1
make[1]: *** [/Users/kwankyu/GitHub/sage-dev/local/var/lib/sage/installed/perl_cpan_polymake_prereq-none] Error 2
```

**Comment by mkoeppe** [comment]
What does config.log say about perl_cpan_polymake_prereq?

**Comment by kwankyu** [comment]
```
## -------------------------------------------------------------------------- ##
## Checking whether SageMath should install SPKG perl_cpan_polymake_prereq... ##
## -------------------------------------------------------------------------- ##
configure:46263: checking for perl module XML::Writer
configure:46269: result: no
configure:46263: checking for perl module XML::LibXML
configure:46269: result: no
configure:46263: checking for perl module XML::LibXSLT
configure:46269: result: no
configure:46263: checking for perl module File::Slurp
configure:46269: result: no
configure:46263: checking for perl module JSON
configure:46269: result: no
configure:46263: checking for perl module SVG
configure:46269: result: no
configure:46263: checking for perl module Term::ReadKey
configure:46269: result: no
configure:46312: no suitable system package found for SPKG perl_cpan_polymake_prereq   
```

**Comment by kwankyu** [comment]
So this is normal. I should first install `perl_cpan_polymake_prereq` by homebrew...

**Comment by kwankyu** [comment]
After installing prerequisite perl modules, `make polymake` is making polymake 4.11 on my system.

Some observations:

1. "CI Linux incremental" is still failing. But I think this is normal because optional dependencies (dummy packages: `perl_cpan_polymake_prereq` and `libxml2`) are missing.

2. `libxml2` is a dependency of `perl_cpan_polymake_prereq`. Hence I think `libxml2` should be placed before `perl_cpan_polymake_prereq` in `dependencies`. But because they are all dummy packages, this point may be meaningless.

3. `lrslib` is both in `dependencies_optional` and `dependencies`. Is this ok?

4. `perl_cpan_polymake_prereq` is called a "script package" in `SPKG.rst` of `polymake`. Isn't this a "dummy package"?

**Comment by mkoeppe** [comment]
> * "CI Linux incremental" is still failing. But I think this is normal because optional dependencies (dummy packages: `perl_cpan_polymake_prereq` and `libxml2`) are missing.

You are right. We don't have a mechanism for that in the CI.

> * `libxml2` is a dependency of `perl_cpan_polymake_prereq`. Hence I think `libxml2` should be placed before `perl_cpan_polymake_prereq` in `dependencies`. But because they are all dummy packages, this point may be meaningless.

I don't think the order of the packages in our `dependencies` has any meaning.

I have made the other suggested changes.

**Comment by kwankyu** [comment]
> > * `libxml2` is a dependency of `perl_cpan_polymake_prereq`. Hence I think `libxml2` should be placed before `perl_cpan_polymake_prereq` in `dependencies`. But because they are all dummy packages, this point may be meaningless.
> 
> I don't think the order of the packages in our `dependencies` has any meaning.

Right. But the messages from `./configure` are in the same order as the packages are listed in `dependencies`. So, following the messages, the user will try to install `perl_cpan_polymake_prereq` first and then `libxml2`. But in the end, the user is forced to install `libxml2` first and then `perl_cpan_polymake_prereq`.

This is a trivial point. No action is not required.

> I have made the other suggested changes.

Thanks.

**Comment by mkoeppe** [comment]
OK, thanks. Done

**Review by kwankyu — APPROVED** [review]
It works well on mac, and perhaps on linux too 🤞

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
