### PR TITLE
build/pkgs/attrs: Change to wheel package, update dependencies

### LINKED ISSUE #36428: attrs depends on hatchling
### Steps To Reproduce

Might be related to update to attrs 23.1.0 565dddb6b226773588fa4e028802f158d11064c6
```
[attrs-23.1.0]   Preparing metadata (pyproject.toml): finished with status 'done'
[attrs-23.1.0] ERROR: Exception:
[attrs-23.1.0] Traceback (most recent call last):
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
[attrs-23.1.0]     status = run_func(*args)
[attrs-23.1.0]              ^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
[attrs-23.1.0]     return func(self, options, args)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/commands/wheel.py", line 147, in run
[attrs-23.1.0]     requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
[attrs-23.1.0]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
[attrs-23.1.0]     collected = self.factory.collect_root_requirements(root_reqs)
[attrs-23.1.0]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
[attrs-23.1.0]     req = self._make_requirement_from_install_req(
[attrs-23.1.0]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
[attrs-23.1.0]     cand = self._make_candidate_from_link(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
[attrs-23.1.0]     self._link_candidate_cache[link] = LinkCandidate(
[attrs-23.1.0]                                        ^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
[attrs-23.1.0]     super().__init__(
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
[attrs-23.1.0]     self.dist = self._prepare()
[attrs-23.1.0]                 ^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
[attrs-23.1.0]     dist = self._prepare_distribution()
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
[attrs-23.1.0]     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
[attrs-23.1.0]     return self._prepare_linked_requirement(req, parallel_builds)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
[attrs-23.1.0]     dist = _get_prepared_distribution(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
[attrs-23.1.0]     abstract_dist.prepare_distribution_metadata(
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
[attrs-23.1.0]     self.req.prepare_metadata()
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 562, in prepare_metadata
[attrs-23.1.0]     self.metadata_directory = generate_metadata(
[attrs-23.1.0]                               ^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
[attrs-23.1.0]     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
[attrs-23.1.0]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 718, in prepare_metadata_for_build_wheel
[attrs-23.1.0]     return super().prepare_metadata_for_build_wheel(
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
[attrs-23.1.0]     return self._call_hook('prepare_metadata_for_build_wheel', {
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
[attrs-23.1.0]     raise BackendUnavailable(data.get('traceback', ''))
[attrs-23.1.0] pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
[attrs-23.1.0]     obj = import_module(mod_path)
[attrs-23.1.0]           ^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "/home/release/Sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
[attrs-23.1.0]     return _bootstrap._gcd_import(name[level:], package, level)
[attrs-23.1.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[attrs-23.1.0]   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
[attrs-23.1.0] ModuleNotFoundError: No module named 'hatchling'
[attrs-23.1.0] 
```

### Expected Behavior

attrs depends on hatchling

### Actual Behavior

Parallel build fails

### Additional Information

_No response_

### Environment

```markdown
- Linux 
- Sage Version 10.2.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #36428

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
Locally this is what I get
```
[attrs-23.1.0] Attempting to download package attrs-23.1.0-py3-none-any.whl from mirrors
[attrs-23.1.0] https://mirrors.aliyun.com/sagemath/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl
[attrs-23.1.0] [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
[attrs-23.1.0] ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirrors.aliyun.com/sagemath/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl'
[attrs-23.1.0] https://mirrors.mit.edu/sage/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl
[attrs-23.1.0] [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
[attrs-23.1.0] ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: 
...
[attrs-23.1.0] https://mirror.yandex.ru/mirrors/sage.math.washington.edu/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl
[attrs-23.1.0] [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
[attrs-23.1.0] ERROR [transfer|run:135]: [Errno socket error] [Errno 404] Not Found: '//mirror.yandex.ru/mirrors/sage.math.washington.edu/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl'
[attrs-23.1.0] https://mirrors.nju.edu.cn/sagemath/spkg/upstream/attrs/attrs-23.1.0-py3-none-any.whl
(seemingly hangs here forever...)
```

**Comment by kwankyu** [comment]
Should it be attempted to install attrs by pip?

**Comment by kwankyu** [comment]
attrs was installed anyway by `make -j4`. Just that there is no log about when and how it was installed.

**Comment by mkoeppe** [comment]
> ```
> seemingly hangs here forever...)
> ```
> 
> from `make attrs` after `configure`.

The upstream tarballs of various packages updated in this beta have not been uploaded to the Sage mirrors - https://github.com/sagemath/sage/pull/36381#issuecomment-1752268975, so the Sage installer tries all mirrors including unreliable ones

**Comment by dimpase** [comment]
are we now installing wheels as if it's normal?

**Comment by mkoeppe** [comment]
Platform-independent wheels, yes; any objections?

**Comment by dimpase** [comment]
Can't platform-independent wheels, upon being installed, pull binary wheels of its dependencies?

**Comment by mkoeppe** [comment]
No. Both for normal and wheel packages, use of PyPI is disabled.

**Comment by kwankyu** [comment]
> The upstream tarballs of various packages updated in this beta have not been uploaded to the Sage mirrors - [#36381 (comment)](https://github.com/sagemath/sage/pull/36381#issuecomment-1752268975), so the Sage installer tries all mirrors including unreliable ones

Yes. I know it. It is normal that sage fails in pulling the wheel from the sage mirrors. But after failing in that, sage (pip) successfully installed the wheel (from pypi). 

Still I could not find any lines in the build log showing pip installing attrs, which puzzles me. Naturally I want to see those lines in the log to check that sage installs attrs of version 23.1.0, instead of existence of that after sage is built. Perhaps just my mistake...

**Comment by kwankyu** [comment]
> No. Both for normal and wheel packages, use of PyPI is disabled.

Then where does sage obtain the wheel after failing in getting it from the mirrors?

**Comment by mkoeppe** [comment]
from checksums.ini upstream_url

**Comment by mkoeppe** [comment]
> Still I could not find any lines in the build log showing pip installing attrs

It was probably installed as a side effect of installing a "pip" package (those packages have a file "requirements.txt" in their build/pkgs/SPKG/ directory.

**Comment by kwankyu** [comment]
I tried again, and saw the log :-)
```
...
[attrs-23.1.0] Finished installing attrs-23.1.0
```
All's well.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
