### PR TITLE
add macports environment to tox.ini

### LINKED ISSUE #31505: Extend system package scripts to handle macports; tox.ini: Add macports environment
<div id="comment:0"></div>

Based on #30504, which added MacPorts package information, we update the system package scripts to include support for MacPorts.

Current Sage builds just fine on a system with MacPorts. 
To test this, we add `local-macports` environments to `tox.ini`:

```
tox -e local-macports-minimal
```
or

```
tox -e local-macports-standard             # uses /usr/bin/python3
```
or 

```
tox -e local-macports-standard-python3.10  # uses python3.10 from macports
```

Each of these commands creates an isolated installation of MacPorts in a subdirectory of `.tox` (using https://guide.macports.org/#installing.macports.source.multiple
); it will not use or modify `/opt/local`.  

(There is also `tox -e local-macports-optlocal-standard`, which uses `sudo` to install things into the default location -- use at your own risk.)

Requested at

- [Ask Sage question 54790: Use OpenSSL from /opt/local/](https://ask.sagemath.org/question/54790)
- [sage-support, 2020-12](https://groups.google.com/g/sage-support/c/_cfY37nFF84/m/1biGwJetBgAJ)
- [sage-devel, 2022-04](https://groups.google.com/g/sage-devel/c/qTcF8tlWLcE/m/9QRODrv0CgAJ)

Upstream: **Not yet reported upstream; Will do shortly.**

CC:  @slel @kliem @jhpalmieri @dimpase @seblabbe @vbraun @zlscherr

Component: **porting**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/tox_ini__add_macports_environment](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini__add_macports_environment) @ [`476fa33`](https://github.com/sagemath/sagetrac-mirror/commit/476fa33e16780466a04556f1c87532465dbde898)**

_Issue created by migration from https://trac.sagemath.org/ticket/31505_

### PR DESCRIPTION
**Pull request by dimpase**
this is the branch from #31505, rebased over Sage 10.0 branch

Resolves #31505 

- Depends on #36910 (merged here)

### CODE REVIEW

**Comment by mkoeppe** [comment]
Rebased but not tested

**Comment by mkoeppe** [comment]
@dimpase Let's merge it?

**Comment by dimpase** [comment]
well, I don't mind if it's still in the works.

**Comment by mkoeppe** [comment]
OK. Already the warning message "Use of MacPorts is experimental" is certainly an improvement and better than just silently using people's MacPorts installation.

**Pull request merged**
