### PR TITLE
Update the year in README.md

### PR DESCRIPTION
**Pull request by kwankyu**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
I wonder if this can be automated... or not worth it.

**Review by fchapoton — APPROVED** [review]
thanks

**Comment by kwankyu** [comment]
Could this be a blocker? To be merged before the next release?

**Comment by fchapoton** [comment]
I do no think so. This can wait.

**Comment by kwankyu** [comment]
OK.

**Pull request merged**
