### PR TITLE
Replaced # optional by footnote symbols (Issue #35726)

### LINKED ISSUE #35726: PDF documentation: Replace `# optional` by footnote symbols
Currently, lines wrap.

Approach suggested by @tobiasdiez: https://github.com/sagemath/sage/pull/35719#issuecomment-1578001519

Such transformations can be done in `SagecodeTransform`
https://github.com/sagemath/sage/blob/develop/src/sage_docbuild/conf.py#L911

### PR DESCRIPTION
**Pull request by AdwitiyaS**
I have made several improvements to the documentation:

**Hyperlink Errors:**  I corrected broken hyperlinks and replaced them with proper references throughout the documentation. This ensures that all links are correctly linked and functional.

**Replacing #optional:** Replace instances of "#optional" with footnote symbols where applicable to enhance readability and consistency in the documentation.

**Title Underline:** Fixed instances where the title underline or overline was too short, ensuring uniformity and readability across the documentation.

**REMAINING ISSUES:** 

Despite efforts to resolve all errors, there are still a few remaining challenges:

**Indentation Errors**: Some indentation errors persist and may require further investigation and correction.

**Hyperlink Referencing:** Certain hyperlinks were not properly referenced and need to be reviewed and fixed as needed, like "PyT". 

Overall, these changes significantly improve the documentation, but additional refinements may be necessary.

**RELATED ISSUE:**

Fixes #35726

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AdwitiyaS** [comment]
I've submitted this pull request with improvements to the documentation. However, it seems that the pull request includes two commits instead of one. The first commit (80a0afc) is causing problems when trying to commit from a new branch. The second commit (#35726) contains the actual changes and should be considered for review.

Please note that the relevant changes are contained in the second commit.  Apologies for any inconvenience caused by the extra commit.

Related to: #35726

**Comment by mkoeppe** [comment]
The idea of #35726 is to have this transformation take place automatically when *formatting* the PDF documentation (and only there); not by changing the source code! These `# optional` comments in the tests have a meaning in our doctesting framework.

**Comment by tscrim** [comment]
+1 on @mkoeppe's comment. I believe this PR should be closed.

**Comment by AdwitiyaS** [comment]
Thanks for the feedback @mkoeppe and @tscrim. I understand the concern about the approach taken here.

I'm open to exploring alternatives that better align with the project's standards. Any suggestions on how I could handle this differently?

**Comment by mkoeppe** [comment]
Such transformations can be done in `SagecodeTransform`
https://github.com/sagemath/sage/blob/develop/src/sage_docbuild/conf.py#L911

**Pull request closed without merging**
