### PR TITLE
`sage.sets`: Doctest cosmetics

### PR DESCRIPTION
**Pull request by mkoeppe**
Cherry-picked from #35095.

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mantepse** [comment]
I am against replacing short `lambda` expressions with two line `def` in docstrings: they are a pain to copy into the repl.

**Comment by mkoeppe** [comment]
> I am against replacing short `lambda` expressions with two line `def` in docstrings: they are a pain to copy into the repl.

Are you referring to copying from the source code or from the formatted HTML documentation? Where exactly does it hurt?

**Comment by mantepse** [comment]
> > I am against replacing short `lambda` expressions with two line `def` in docstrings: they are a pain to copy into the repl.
> 
> Are you referring to copying from the source code or from the formatted HTML documentation? Where exactly does it hurt?

Copying from source code.    It does work, but it is a painful.   For example, modifying does not work as well, and also emacs doesn't offer autocompletion for functions defined in this way.

Also, I don't see a good reason for the replacement.  What is the purpose?

**Comment by mkoeppe** [comment]
> What is the purpose?

Coding style. In library code, such lambda assignments are flagged by pycodestyle, and they have been replaced already. Best to use a consistent style also in code examples.

**Comment by mkoeppe** [comment]
> Copying from source code.

You know that you can copy the whole lines including prompts, yes?

**Comment by mantepse** [comment]
> > What is the purpose?
> 
> Coding style. In library code, such lambda assignments are flagged by pycodestyle, and they have been replaced already. Best to use a consistent style also in code examples.

I would agree that in very many cases the assignment is unnecessary, and could simply be inlined.

Otherwise, you could simply use the one-line form of `def`:
```
def f(x): return 2*x 
```
works just fine.

> > Copying from source code.
> 
> You know that you can copy the whole lines including prompts, yes?

Is there an editor that would not let you copy full lines?

**Comment by mkoeppe** [comment]
We appear to be miscommunicating. What's the exact problem that you are facing when copying multi-line definitions?

**Comment by mkoeppe** [comment]
> use the one-line form of `def`:
> 
> ```
> def f(x): return 2*x 
> ```

Codestyle linters also don't like that

**Comment by mantepse** [comment]
It is a bit hard to explain if you do not use emacs.

I can go to the first line of the test in the documentation buffer, and press `C-d`, to run the snippet in the attached sage session.  It will look as follows:
```
sage: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:def rotate_permutation(p):
:    cycle = Permutation(tuple(range(1, len(p)+1)))
:    return Permutation([cycle.inverse()(p(cycle(i))) for i in range(1, len(p)+1)])
:--
```
If I do it this way (rather than copy-pasting), I at least get tab completion.  However, if I now want to modify the definition slightly, it gets a bit cumbersome, at least for me.

I also find that the increased verbosity is another drawback.

I do see the point of using pycodestyle, but I would rather turn off that particular recommendation for doctests, or relax it to allow single line `def` statements.

**Comment by mkoeppe** [comment]
Is this `sage-shell-mode`?

**Comment by mantepse** [comment]
Yes

**Comment by mkoeppe** [comment]
I've reduced this PR to the subset of the changes that do not involve changing `lambda` assignments to `def`s.

**Review by mantepse — APPROVED** [review]
LGTM, thank you!

**Comment by mkoeppe** [comment]
Thanks.

**Pull request merged**
