### PR TITLE
Deprecate `is_SchemeMorphism`, `is_SchemeTopologicalPoint`

### PR DESCRIPTION
**Pull request by mkoeppe**
Part of:
- #32414

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
The lint failures are unrelated and come from the release of ruff 0.5.0 (https://pypi.org/project/ruff/#history)

**Comment by tscrim** [comment]
Here is an interesting case of a place where it might be good to leave the `is_SchemeMorphism` (possibly renamed) as the second class to test doesn't fit the naming scheme (pun intended) one would expect. It's not so clear-cut to me to remove it. I'm not opposed, but just want to see if you have any second thoughts as well.

**Comment by mkoeppe** [comment]
Well, what could be useful here: a new ABC. But I definitely don't want to wait with the removal of `is_Class` functions until ABCs for all situations have been figured out.

**Comment by mkoeppe** [comment]
... or, alternatively, whether what is intended in the uses of `is_SchemeMorphism` could be replaced by using `instance(..., Morphism) and ....category_for() .... `.

**Comment by kwankyu** [comment]
```
sage: from sage.schemes.elliptic_curves.ell_point import EllipticCurvePoint_field
sage: from sage.schemes.generic.morphism import SchemeMorphism
sage: issubclass(EllipticCurvePoint_field, SchemeMorphism)
True
```
This is also mathematically sound.

**Comment by mkoeppe** [comment]
Thanks. So I can actually simplify many `isinstance` calls.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Merge conflict

**Pull request merged**
