### PR TITLE
Build CI: Fix configuration of coverage upload action

### LINKED ISSUE #36620: Upload coverage fails/takes very long since beta.6
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/6712342128/job/18241914417

### Expected Behavior

Be quick (10sec)

### Actual Behavior

Takes about 1.5h

### Additional Information

Seems to be the case since beta 6. In particular, the PR https://github.com/sagemath/sage/pull/36367 seems to be the earliest case where the upload takes so long (which I don't quite understand, maybe an issue with a symlink?!). Alternatively, it may have been https://github.com/sagemath/sage/pull/36348 (the only other PR that touched the build & test workflow in that release cycle).

### Environment

```markdown
CI
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #36620

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Seems to work fine. Thanks. Any idea about what's the issue? Do you add any symlinks in the worktree folder? The underlying issue here might be the same one that also gives the "out of space" exception.

**Comment by mkoeppe** [comment]
> Seems to work fine. Thanks. 

So let's get it in.

> Any idea about what's the issue?

The config was asking to search the whole worktree-image for coverage files.

**Review by fchapoton — APPROVED** [review]
seems to be reasonable

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
