### PR TITLE
Added two missing difference sets, updated URLs

### PR DESCRIPTION
**Pull request by dmgordo**
### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by dimpase — APPROVED** [review]
Nice. Can you perhaps add the info on the groups in the non-cyclic examples?

**Comment by dmgordo** [comment]
> Nice. Can you perhaps add the info on the groups in the non-cyclic examples?

I added some information. Let me know if that's what you had in mind.

**Comment by dimpase** [comment]
looks good, let's wait for CI to finish.

**Review by dimpase — APPROVED** [review]

**Comment by dmgordo** [comment]
Can anyone shed light on the failed check? codecov says that line 519 isn't covered by a test, but it is, and all that changed was what the url variable was set to; I can't see how that would make the code go from passing to failing the check.

Could codecov be wrong? A similar issue came up here: [https://github.com/ballerina-platform/ballerina-lang/issues/31348
](url).

**Comment by dimpase** [comment]
codecov is too strict. If it's an innocent place, no need to add a test.

**Pull request merged**
