### PR TITLE
set reverse=True by default in basis_for_quaternion_lattice()

### LINKED ISSUE #34880: set reverse=True by default in basis_for_quaternion_lattice()
<div id="comment:0"></div>

The `reverse=True` flag is recommended (and set by default) for quaternion orders, but I think it is also the better choice for all other quaternion lattices: Among other things, setting `reverse=True` makes the returned basis contain the norm of an ideal (very usefully generalizing the fact that the returned basis for an order contains `1`).

Component: **algebra**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34880_

### PR DESCRIPTION
**Pull request by yyyyx4**
Fixes #34880.

### CODE REVIEW

**Comment by kwankyu** [comment]
@tornaria

**Comment by kwankyu** [comment]
I agree that this is a good change. 

But this is an API change of the function `basis_for_quaternion_lattice`. So a deprecation warning seems required.

**Comment by kwankyu** [comment]
Deprecation period is one year.

**Comment by kwankyu** [comment]
```sage
sage -t --warn-long 65.7 --random-seed=172242929068586131357270719533848860749 src/sage/schemes/elliptic_curves/heegner.py
**********************************************************************
File "src/sage/schemes/elliptic_curves/heegner.py", line 4906, in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.right_ideals
Failed example:
    heegner_points(11).reduce_mod(3).right_ideals()
Expected:
    (Fractional ideal (2 + 2*j + 28*k, 2*i + 26*k, 4*j + 12*k, 44*k),
     Fractional ideal (2 + 2*j + 28*k, 2*i + 4*j + 38*k, 8*j + 24*k, 88*k))
Got:
    (Fractional ideal (4, 44*i, 2 + 8*i + 2*j, 34*i + 2*k),
     Fractional ideal (8, 88*i, 2 + 52*i + 2*j, 4 + 78*i + 2*k))
**********************************************************************
File "src/sage/schemes/elliptic_curves/heegner.py", line 5137, in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.cyclic_subideal_p1
Failed example:
    sorted(H.cyclic_subideal_p1(I, 3).items())
Expected:
    [((0, 1),
      Fractional ideal (2 + 2*j + 32*k, 2*i + 8*j + 82*k, 12*j + 60*k, 132*k)),
     ((1, 0),
      Fractional ideal (2 + 10*j + 28*k, 2*i + 4*j + 62*k, 12*j + 60*k, 132*k)),
     ((1, 1),
      Fractional ideal (2 + 2*j + 76*k, 2*i + 4*j + 106*k, 12*j + 60*k, 132*k)),
     ((1, 2),
      Fractional ideal (2 + 10*j + 116*k, 2*i + 8*j + 38*k, 12*j + 60*k, 132*k))]
Got:
    [((0, 1), Fractional ideal (12, 132*i, 10 + 76*i + 2*j, 4 + 86*i + 2*k)),
     ((1, 0), Fractional ideal (12, 132*i, 2 + 32*i + 2*j, 8 + 130*i + 2*k)),
     ((1, 1), Fractional ideal (12, 132*i, 10 + 32*i + 2*j, 8 + 86*i + 2*k)),
     ((1, 2), Fractional ideal (12, 132*i, 2 + 76*i + 2*j, 4 + 130*i + 2*k))]
**********************************************************************
File "src/sage/schemes/elliptic_curves/heegner.py", line 5269, in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.kolyvagin_cyclic_subideals
Failed example:
    H.kolyvagin_cyclic_subideals(I, 5, alpha_quaternion)
Expected:
    [(Fractional ideal (2 + 2/3*i + 364*j + 231928/3*k,
                        4/3*i + 946*j + 69338/3*k,
                        1280*j + 49920*k, 94720*k), 0),
     (Fractional ideal (2 + 2/3*i + 108*j + 31480/3*k,
                        4/3*i + 434*j + 123098/3*k,
                        1280*j + 49920*k, 94720*k), 1),
     (Fractional ideal (2 + 2/3*i + 876*j + 7672/3*k,
                        4/3*i + 434*j + 236762/3*k,
                        1280*j + 49920*k, 94720*k), 2),
     (Fractional ideal (2 + 2/3*i + 364*j + 61432/3*k,
                        4/3*i + 178*j + 206810/3*k,
                        1280*j + 49920*k, 94720*k), 3),
     (Fractional ideal (2 + 2/3*i + 876*j + 178168/3*k,
                        4/3*i + 1202*j + 99290/3*k,
                        1280*j + 49920*k, 94720*k), 4),
     (Fractional ideal (2 + 2/3*i + 1132*j + 208120/3*k,
                        4/3*i + 946*j + 183002/3*k,
                        1280*j + 49920*k, 94720*k), 5)]
Got:
    [(Fractional ideal (2560, 1280 + 47360*i, 1146 + 37678*i + 4*j, 212 + 54664/3*i + 2*j + 2/3*k),
      0),
     (Fractional ideal (2560, 1280 + 47360*i, 2426 + 9262*i + 4*j, 2004 + 83080/3*i + 2*j + 2/3*k),
      1),
     (Fractional ideal (2560, 1280 + 47360*i, 1914 + 9262*i + 4*j, 1748 + 111496/3*i + 2*j + 2/3*k),
      2),
     (Fractional ideal (2560, 1280 + 47360*i, 2170 + 18734*i + 4*j, 212 + 111496/3*i + 2*j + 2/3*k),
      3),
     (Fractional ideal (2560, 1280 + 47360*i, 890 + 28206*i + 4*j, 1748 + 54664/3*i + 2*j + 2/3*k),
      4),
     (Fractional ideal (2560, 1280 + 47360*i, 634 + 37678*i + 4*j, 2516 + 83080/3*i + 2*j + 2/3*k),
      5)]
**********************************************************************
3 items had failures:
   1 of   5 in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.cyclic_subideal_p1
   1 of   8 in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.kolyvagin_cyclic_subideals
   1 of   2 in sage.schemes.elliptic_curves.heegner.HeegnerQuatAlg.right_ideals
    [1110 tests, 3 failures, 36.95 s]
----------------------------------------------------------------------
sage -t --warn-long 65.7 --random-seed=172242929068586131357270719533848860749 src/sage/schemes/elliptic_curves/heegner.py  # 3 doctests failed
----------------------------------------------------------------------
```
```sage
sage -t --warn-long 65.7 --random-seed=172242929068586131357270719533848860749 src/sage/modular/quatalg/brandt.py
**********************************************************************
File "src/sage/modular/quatalg/brandt.py", line 142, in sage.modular.quatalg.brandt
Failed example:
    B.right_ideals()
Expected:
    (Fractional ideal (2 + 2*j, 2*i + 2*k, 4*j, 4*k), Fractional ideal (2 + 2*j, 2*i + 6*k, 8*j, 8*k), Fractional ideal (2 + 10*j + 8*k, 2*i + 8*j + 6*k, 16*j, 16*k))
Got:
    (Fractional ideal (4, 4*i, 2 + 2*j, 2*i + 2*k),
     Fractional ideal (8, 8*i, 2 + 2*j, 6*i + 2*k),
     Fractional ideal (16, 16*i, 10 + 8*i + 2*j, 8 + 6*i + 2*k))
**********************************************************************
File "src/sage/modular/quatalg/brandt.py", line 805, in sage.modular.quatalg.brandt.BrandtModule_class.cyclic_submodules
Failed example:
    B.cyclic_submodules(I, 2)
Expected:
    [Fractional ideal (1/2 + 3/2*j + k, 1/2*i + j + 1/2*k, 2*j, 2*k),
     Fractional ideal (1/2 + 1/2*i + 1/2*j + 1/2*k, i + k, j + k, 2*k),
     Fractional ideal (1/2 + 1/2*j + k, 1/2*i + j + 3/2*k, 2*j, 2*k)]
Got:
    [Fractional ideal (2, 2*i, 3/2 + i + 1/2*j, 1 + 1/2*i + 1/2*k),
     Fractional ideal (2, 1 + i, 1 + j, 1/2 + 1/2*i + 1/2*j + 1/2*k),
     Fractional ideal (2, 2*i, 1/2 + i + 1/2*j, 1 + 3/2*i + 1/2*k)]
**********************************************************************
File "src/sage/modular/quatalg/brandt.py", line 809, in sage.modular.quatalg.brandt.BrandtModule_class.cyclic_submodules
Failed example:
    B.cyclic_submodules(I, 3)
Expected:
    [Fractional ideal (1/2 + 1/2*j, 1/2*i + 5/2*k, 3*j, 3*k),
     Fractional ideal (1/2 + 3/2*j + 2*k, 1/2*i + 2*j + 3/2*k, 3*j, 3*k),
     Fractional ideal (1/2 + 3/2*j + k, 1/2*i + j + 3/2*k, 3*j, 3*k),
     Fractional ideal (1/2 + 5/2*j, 1/2*i + 1/2*k, 3*j, 3*k)]
Got:
    [Fractional ideal (3, 3*i, 1/2 + 1/2*j, 5/2*i + 1/2*k),
     Fractional ideal (3, 3*i, 3/2 + 2*i + 1/2*j, 2 + 3/2*i + 1/2*k),
     Fractional ideal (3, 3*i, 3/2 + i + 1/2*j, 1 + 3/2*i + 1/2*k),
     Fractional ideal (3, 3*i, 5/2 + 1/2*j, 1/2*i + 1/2*k)]
**********************************************************************
File "src/sage/modular/quatalg/brandt.py", line 1254, in sage.modular.quatalg.brandt.BrandtModule_class.right_ideals
Failed example:
    B.right_ideals()
Expected:
    (Fractional ideal (2 + 2*j, 2*i + 2*k, 4*j, 4*k),
     Fractional ideal (2 + 2*j, 2*i + 6*k, 8*j, 8*k),
     Fractional ideal (2 + 10*j + 8*k, 2*i + 8*j + 6*k, 16*j, 16*k))
Got:
    (Fractional ideal (4, 4*i, 2 + 2*j, 2*i + 2*k),
     Fractional ideal (8, 8*i, 2 + 2*j, 6*i + 2*k),
     Fractional ideal (16, 16*i, 10 + 8*i + 2*j, 8 + 6*i + 2*k))
**********************************************************************
3 items had failures:
   1 of  14 in sage.modular.quatalg.brandt
   2 of   6 in sage.modular.quatalg.brandt.BrandtModule_class.cyclic_submodules
   1 of   7 in sage.modular.quatalg.brandt.BrandtModule_class.right_ideals
    [165 tests, 4 failures, 4.34 s]
----------------------------------------------------------------------
sage -t --warn-long 65.7 --random-seed=172242929068586131357270719533848860749 src/sage/modular/quatalg/brandt.py  # 4 doctests failed
----------------------------------------------------------------------
```

**Review by kwankyu — APPROVED** [review]
Thanks. LGTM.

**Comment by yyyyx4** [comment]
Thank you!

**Pull request merged**
