### PR TITLE
update openssl to 3.0.8

### PR DESCRIPTION
**Pull request by dimpase**
from sage-devel by Thierry: I took his branch and made this PR from it.

Sage's current openssl version (3.0.5) hass several "High severity"
vulnerabilities, see https://www.openssl.org/news/vulnerabilities.html

It would be nice to have the fixes included in the next Sage release. I am not
using github, here is a pull request (literally) to fix this :

  git pull https://lipn.univ-paris13.fr/~monteil/hebergement/sage/sage.git openssl.3.0.8

(commit hash : 997a6bd35a17f5511bb12552bd676597b09f1eaf)
I checked the hash of the tarballs against the GPG signatures by upstream developers.

Tarball at : https://www.openssl.org/source/openssl-3.0.8.tar.gz

Ciao,
Thierry

P.S. Note that 3.1.0. has been very recently released, however 3.0.x is LTS and will
not have structural changes. Just in case, here is a verified branch :

  git pull https://lipn.univ-paris13.fr/~monteil/hebergement/sage/sage.git openssl.3.1.0

(commit hash : 9229a2be66dc0e4f2e3f677aa515a33bfe72a873)
Tarball at : https://www.openssl.org/source/openssl-3.1.0.tar.gz

### CODE REVIEW

**Comment by mkoeppe** [comment]
Run ci-linux workflow?

**Comment by dimpase** [comment]
> Run ci-linux workflow?

I don't know how to do this - it's not a named branch, I don't see how to trigger it (at least not from the browser)

**Comment by dimpase** [comment]
OK, running  https://github.com/dimpase/sage/actions/runs/4810927760
(I know that some of our workflows on work here, not in forks)

**Comment by dimpase** [comment]
needless to say, it works otherwsie...

**Comment by mkoeppe** [comment]
Try with #35417 merged

**Comment by dimpase** [comment]
> Try with #35417 merged

I understand it still won't fly.

**Comment by mkoeppe** [comment]
Depends on your config; it sure works for *me*

**Comment by dimpase** [comment]
well, as it all happens on GitHub, I have no idea how our forks are different.

**Comment by mkoeppe** [comment]
No problem because I know. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#managing-github-actions-permissions-for-your-repository

**Comment by dimpase** [comment]
> No problem because I know. [...]

this link has pages and pages of verbose instructions. Presumably you figured it out - then it should go to a wiki or to a manual, what precisely has to be set.

**Comment by mkoeppe** [comment]
> it should go to a wiki or to a manual, what precisely has to be set

yes, that's #35108

**Comment by mkoeppe** [comment]
I've tested it on a few platforms in https://github.com/mkoeppe/sage/actions/runs/4922782397 (using https://github.com/sagemath/sage/pull/35380). It seems fine.

**Pull request merged**
