### PR TITLE
Fix build of meataxe extension with meson

### PR DESCRIPTION
**Pull request by antonio-rojas**
meataxe is not a library, the library is called mtx and is already searched for

### CODE REVIEW

**Comment by antonio-rojas** [comment]
tdlib and mcqd are also not found because they are header-only, so `find_library` doesn't work.

**Review by tobiasdiez — APPROVED** [review]
Thanks!

**Comment by tobiasdiez** [comment]
> tdlib and mcqd are also not found because they are header-only, so `find_library` doesn't work.

They also don't seem to provide pkg-config info. So just using `cc.has_header` to check for the required headers, and if then set the dependency object to `disabler()` if not found?

**Comment by antonio-rojas** [comment]
> > tdlib and mcqd are also not found because they are header-only, so `find_library` doesn't work.
> 
> They also don't seem to provide pkg-config info. So just using `cc.has_header` to check for the required headers, and if then set the dependency object to `disabler()` if not found?

Done in https://github.com/sagemath/sage/pull/38984

**Comment by antonio-rojas** [comment]
Setting back to positive review, it was a simple rebase

**Pull request merged**
