### PR TITLE
fix many pep8 E302 warnings in repl,rings,schemes,sat,etc

### PR DESCRIPTION
**Pull request by fchapoton**
mostly scripted with `autopep8` except for a few files handled by hand 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Review by vincentmacri — APPROVED** [review]
LGTM

**Review by dcoudert — APPROVED** [review]
LGTM.

**Review by dcoudert — APPROVED** [review]
Indeed, I missed that issue.

LGTM.

**Comment by fchapoton** [comment]
setting back to positive after auto-rebase (I should not have done that, sigh)

**Comment by dcoudert** [comment]
> setting back to positive after auto-rebase (I should not have done that, sigh)

I was about to do it anyway.

**Pull request merged**
