### PR TITLE
Deprecate `is_LaurentSeriesRing`, `is_MPowerSeriesRing`, `is_PowerSeriesRing`

### PR DESCRIPTION
**Pull request by mkoeppe**
Part of 
- #32414

### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #38266 (merged here)

### CODE REVIEW

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Merge conflict

**Comment by kwankyu** [comment]
```
sage -t --warn-long 60.7 --random-seed=319961221341491227066743967340860018910 src/sage/dynamics/arithmetic_dynamics/projective_ds.py
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8391, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    f.normal_form()
Expected:
    Traceback (most recent call last):
    ...
    NotImplementedError: map is not a polynomial
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[2]>", line 1, in <module>
        f.normal_form()
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8403, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    g,m,psi = f.normal_form(return_conjugation=True); m
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[7]>", line 1, in <module>
        g,m,psi = f.normal_form(return_conjugation=True); m
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8406, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    f.change_ring(psi).conjugate(m) == g
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[8]>", line 1, in <module>
        f.change_ring(psi).conjugate(m) == g
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/generic_ds.py", line 305, in change_ring
        F = f.change_ring(R)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/schemes/generic/morphism.py", line 1519, in change_ring
        T = self.domain().change_ring(R)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/schemes/projective/projective_space.py", line 935, in change_ring
        return ProjectiveSpace(self.dimension_relative(), R,
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/schemes/projective/projective_space.py", line 278, in ProjectiveSpace
        raise TypeError("R (=%s) must be a commutative ring" % R)
    TypeError: R (=<function psi at 0x1659a65e0>) must be a commutative ring
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8413, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    f.normal_form()                                                       # needs sage.libs.pari
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[11]>", line 1, in <module>
        f.normal_form()                                                       # needs sage.libs.pari
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8424, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    f.normal_form()
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[15]>", line 1, in <module>
        f.normal_form()
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8434, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    g,m,psi = f.normal_form(return_conjugation=True); psi                 # needs sage.rings.finite_rings
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[18]>", line 1, in <module>
        g,m,psi = f.normal_form(return_conjugation=True); psi                 # needs sage.rings.finite_rings
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
File "src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8444, in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
Failed example:
    f.normal_form()
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form[21]>", line 1, in <module>
        f.normal_form()
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/dynamics/arithmetic_dynamics/projective_ds.py", line 8476, in normal_form
        if is_MPolynomialRing(G.parent()):
    NameError: name 'is_MPolynomialRing' is not defined
**********************************************************************
1 item had failures:
   7 of  23 in sage.dynamics.arithmetic_dynamics.projective_ds.?.normal_form
    [1536 tests, 7 failures, 83.49 s]
----------------------------------------------------------------------
sage -t --warn-long 60.7 --random-seed=319961221341491227066743967340860018910 src/sage/dynamics/arithmetic_dynamics/projective_ds.py  # 7 doctests failed
```

**Pull request merged**
