### PR TITLE
Implement the Jordan decomposition of a matrix and is_semisimple() test

### PR DESCRIPTION
**Pull request by tscrim**
We implement the Jordan decomposition of a matrix $A = S + N$, where $S$ is a semisimple matrix and $N$ is a nilpotent matrix. We also implement a check for the matrix being semisimple by using the `minpoly()` being square-free.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #37703 For a doctest about the decomposition

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM.

For inexact fields, that `while` loop looks a bit scary, but that can be the concern of specialized implementations.

**Comment by tscrim** [comment]
Thanks.

Indeed, that is a good point about the inexact fields. I have now forbidden it. I also made the checks a bit better for things over nonfields.

Actually, I found something that could actually make this a bit better even:

https://acl.inf.ethz.ch/people/chrisw/projects/felix/thesis.pdf

**Comment by tscrim** [comment]
This seems to be the best possible algorithm. Sorry for a bit of noise.

**Review by mkoeppe — APPROVED** [review]
Nice, thanks for working on this improvement.

**Comment by vbraun** [comment]
merge conflict

**Comment by tscrim** [comment]
Rebased (although I found no merge conflict).

**Pull request merged**
