### PR TITLE
Prepare sage for sphinx 8

### PR DESCRIPTION
**Pull request by kiwifb**
This PR prepares sage for sphinx 8. An update for sage_autodoc.py is needed and is provided in this PR.
The minimum known version of sphinx supporting the updated sage_autodoc.py is 7.4.7. So, sphinx is updated from 7.3.7 (which is known not to work) to 7.4.7.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Working well, thanks!

**Comment by mkoeppe** [comment]
@kiwifb This has broken Python 3.9 compatibility:
```
  [sagemath_doc_html-none]   [spkg-install] sage --docbuild --no-pdf-links reference/sets inventory 
  [sagemath_doc_html-none]   [spkg-install] [rings_sta] Exception occurred:
  [sagemath_doc_html-none]   [spkg-install] [rings_sta]   File "/sage/src/sage_docbuild/ext/sage_autodoc.py", line 1653, in import_object
  [sagemath_doc_html-none]   [spkg-install] [rings_sta]     if isinstance(self.object, NewType | TypeVar):
  [sagemath_doc_html-none]   [spkg-install] [rings_sta] TypeError: unsupported operand type(s) for |: 'function' and 'type'
  [sagemath_doc_html-none]   [spkg-install] [rings_sta] The full traceback has been saved in /tmp/sphinx-err-bp5a5o66.log, if you want to report the issue to the developers.
```
https://github.com/sagemath/sage/actions/runs/10691572625/job/29638354837#step:11:7433

**Comment by kiwifb** [comment]
OK, that came up before, how far do we go in python support?

**Comment by mkoeppe** [comment]
3.9 is oldest supported

**Comment by mkoeppe** [comment]
#37006 will drop 3.9, but that's likely Sage 10.6 territory

**Comment by kiwifb** [comment]
Looking back at sphinx 8, from which I based the work on, they have dropped support for py3.9 https://github.com/sphinx-doc/sphinx/blob/04381789db7466d56d9eb29d23d979fc16604acc/pyproject.toml#L16
so it is not surprising. Support for 3.9 will require reintroducing quite a few things in a follow up ticket.

**Comment by mkoeppe** [comment]
> Looking back at sphinx 8, from which I based the work on, they have dropped support for py3.9

Yes, that's why I have the Sphinx 8 upgrade in #37006

**Comment by kiwifb** [comment]
OK #38619 is ready for you to test, I hope that's the only change back that is needed but I cannot test it myself.

**Pull request merged**
