### PR TITLE
Make the key polynomials know their degree

### PR DESCRIPTION
**Pull request by tscrim**
### 📚 Description

Key polynomials know they are graded, but they do not know how to compute their degree.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
@trevorkarn Here is the fix we discussed.

**Review by fchapoton — APPROVED** [review]
Looks good. Hope that the TestSuite passes.

**Comment by tscrim** [comment]
Thank you!

**Comment by trevorkarn** [comment]
Thanks for taking care of this @tscrim!

**Review by fchapoton — APPROVED** [review]

**Pull request merged**
