### PR TITLE
Add issue and PR templates

### LINKED ISSUE #86: Set up Issue Templates, PR Templates
Issue and PR templates:
[​https://github.com/sagemath/sage-gh-templates-sandbox](https://github.com/sagemath/sage-gh-templates-sandbox)
[​https://github.com/sagemath/sage-gh-templates-sandbox/issues/new/choose](https://github.com/sagemath/sage-gh-templates-sandbox/issues/new/choose)
See [​https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Discussion: [​https://groups.google.com/g/sage-devel/c/2dKvRwdwVQM](https://groups.google.com/g/sage-devel/c/2dKvRwdwVQM) (2022-10)

### PR DESCRIPTION
**Pull request by tobiasdiez**
### 📚 Description

Improved version based on https://github.com/sagemath/sage-gh-templates-sandbox
Fixes https://github.com/sagemath/trac-to-github/issues/86.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
@tobiasdiez - can you enable issues and PRs on your fork, just to see how this looks like in production?

**Comment by tobiasdiez** [comment]
@dimpase Sure, good idea, should have done this directly. For the PR template, this PR already uses it and you can test it now at https://github.com/tobiasdiez/sage/compare/develop...tobiasdiez:sage:fix-netlify. For a new issue, have a look at https://github.com/tobiasdiez/sage/issues/new/choose

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by dimpase** [comment]
I took the liberty to remove @mkoeppe from the reviewers list - just to streamline this one.

**Comment by roed314** [comment]
Lgtm; just fixed a typo.

**Comment by dimpase** [comment]
I'm merging this too - it makes creation of PRs and issues more meaningful and documented. Nothing else is affected.

**Comment by tobiasdiez** [comment]
Thanks!

Do you think we should also give hints for good PR titles, e.g. "Fix build error of scipy" instead of `Fixes #<number>`?

**Comment by dimpase** [comment]
> Do you think we should also give hints for good PR titles, e.g. "Fix build error of scipy" instead of `Fixes #<number>`?

indeed, can you fix this?

**Comment by tobiasdiez** [comment]
Sure: https://github.com/sagemath/sage/pull/35022

By the way, if you "squash" a PR instead of merging it, you normally get a nicer more linear commit history in the `develop` branch.

**Comment by mezzarobba** [comment]
Some approved PRs, e.g., sagemath/sage#35064, don't show as such in the [list](https://github.com/sagemath/sage/pulls). I wonder if this is because of the checklist in the PR template, which github interprets as a list of tasks.

**Comment by tobiasdiez** [comment]
You mean the missing "Approved" in the list? This comes from the fact that github only takes reviews from people with write/maintainer rights into account. And in https://github.com/sagemath/sage/pull/35064, Travis has "only" triage rights. This is also the reason why his review is only a gray tick, while Matthias review at https://github.com/sagemath/sage/pull/35060 is a green tick.

**Comment by mezzarobba** [comment]
Yes, that's what I meant. Thanks for the explanation, and sorry for the noise.

**Pull request merged**
