### PR TITLE
docbuild: If `MATHJAX_DIR` does not contain mathjax, use CDN

### LINKED ISSUE #35528: Installation manual: In all-conda install, explain how to docbuild
In this mode, `make` is not used, so there will be no initial build of the documentation as part of `make all`.

https://doc.sagemath.org/html/en/developer/sage_manuals.html does not explain how to run a full build of the documentation.

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description

Short of a proper configuration mechanism for `MATHJAX_DIR` (#30296), we should at least not configure our docbuild to use it without checking first that something is there.

Fixes https://github.com/sagemath/sage/issues/35528#issuecomment-1532246523

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
mathjax is a dependency of sage documentation at build time. Why check its existence?

**Comment by kwankyu** [comment]
Then instead of this obscure circumvention, why not check conda environment explicitly?

Perhaps we can check if Sage PREFIX equals CONDA_PREFIX?

**Comment by mkoeppe** [comment]
> Then instead of this obscure circumvention, why not check conda environment explicitly?

Because this is not conda-specific but rather affects any environment outside of Sage-the-distribution

**Comment by kwankyu** [comment]
> > Then instead of this obscure circumvention, why not check conda environment explicitly?
> 
> Because this is not conda-specific but rather affects any environment outside of Sage-the-distribution

Sorry, but what is the outside environment except conda? 

I think we have assumed the environment explicitly. It was only Sage-the-distribution before and then we allowed conda. Now you are going to abandon the assumption about the environment. If we abandon the assumption, it will affect much more widely than the docbuild part of sage, and we also should be explicit about that (we may also need a discussion in sage-devel too...)

**Comment by mkoeppe** [comment]
As #30296 has been implemented, we can close this.

**Pull request closed without merging**
