### PR TITLE
Combinat/sga murphy basis

### PR DESCRIPTION
**Pull request by tscrim**
We implement the Murphy basis of the symmetric group algebra (as defined by Dipper-James-Mathas) and make this the default cellular basis over positive characteristic since it is (significantly) faster to compute the change of basis necessary.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36718 Uses the KL basis implementation

### CODE REVIEW

**Comment by fchapoton** [comment]
please resolve the conflicts

**Comment by tscrim** [comment]
> please resolve the conflicts

Fixed.

**Comment by fchapoton** [comment]
looks good. Maybe add two doctests for the `raise ValueError` that `codecov` complains about ?

**Comment by tscrim** [comment]
Done, with making the input have more explicit checking that it is working with standard tableaux.

**Review by fchapoton — APPROVED** [review]
looks good now, thanks

**Comment by tscrim** [comment]
Merci!

**Pull request merged**
