### PR TITLE
Remove conda patchelf distro

### PR DESCRIPTION
**Pull request by tobiasdiez**
Does not exists in conda-forge: https://github.com/sagemath/sage/pull/36234#discussion_r1367772696

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]

**Comment by tobiasdiez** [comment]
Thanks for the review.

**Comment by isuruf** [comment]
patchelf should now be available on macos too if you want to manipulate ELF files on macos.

**Comment by mkoeppe** [comment]
Thanks! We only have it as a package because meson-python needs it (on Linux). 
We just don't have a mechanism for only including it in the conda environment on Linux...

**Comment by mkoeppe** [comment]
Removing "blocker", but as this PR is already on Volker's branch, we'll revert it in a follow-up.

**Pull request merged**
