### PR TITLE
upgrade cypari2 to 2.1.4

### PR DESCRIPTION
**Pull request by dimpase**
routine upgrade for Cython 3 and Python 3.12 compatibility

using github URL for the tarball, for the time being

### CODE REVIEW

**Comment by dimpase** [comment]
The upgrade was here: https://github.com/sagemath/cypari2/pull/142

**Comment by himanshu-sharmav** [comment]
Hello @dimpase I am currently new to open source and would love to contribute something. My techstack includes java,Django,python,mysql,apache,phpmyadmin. 
Please suggest me how to contribute furthur.
Thank you

**Comment by dimpase** [comment]
On Mon, Oct 16, 2023 at 09:00:45PM -0700, himanshu-sharmav wrote:
> Hello @dimpase I am currently new to open source and would love to contribute something. My techstack includes java,Django,python,mysql,apache,phpmyadmin. 
> Please suggest me how to contribute furthur.

The right forum to ask such questions is 
https://groups.google.com/g/sage-devel

**Comment by mkoeppe** [comment]
Tested ([with some other update PRs](https://github.com/mkoeppe/sage/commits/ci-10.2.beta8%2Bupdates-1)) in https://github.com/mkoeppe/sage/actions/runs/6622955701

**Review by mkoeppe — APPROVED** [review]

**Pull request merged**
