### PR TITLE
FiniteRankFreeModule.isomorphism_with_fixed_basis: Make it an actual isomorphism

### PR DESCRIPTION
**Pull request by mkoeppe**
For this we define a new class `SetIsomorphism`, which knows its inverse.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GiacomoPope** [comment]
Failure here is known and fixed in the following PR https://github.com/sagemath/sage/pull/37489

**Review by tscrim — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Thank you!

**Review by egourgoulhon — APPROVED** [review]
LGTM. Thanks for this improvement.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
