### PR TITLE
Updates to linbox-1.7.0, givaro-4.2.0, fflas-ffpack-2.5.0

### LINKED ISSUE #32959: Upgrade to givaro-4.2.0 fflas-ffpack-2.5.0 linbox-1.7.0
<div id="comment:0"></div>

New packages are available here (with the corresponding checksums):

givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0

fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0

linbox: https://github.com/linbox-team/linbox/releases/tag/v1.7.0

The new versions require "a C++ compiler supporting C++11 standard. More precisely g++ v5 or greater, clang++ v3.4 or greater".
So this ticket depends on dropping support for some systems, see #32074.

Depends on #33316

CC:  @kiwifb @orlitzky

Component: **packages: standard**

Branch/Commit: **[u/cpernet/upgrade_to_givaro_4_2_0_fflas_ffpack_2_5_0_linbox_1_7_0](https://github.com/sagemath/sagetrac-mirror/tree/u/cpernet/upgrade_to_givaro_4_2_0_fflas_ffpack_2_5_0_linbox_1_7_0) @ [`4006e10`](https://github.com/sagemath/sagetrac-mirror/commit/4006e105dea890308f5b1d14366ecd779ca10b38)**

_Issue created by migration from https://trac.sagemath.org/ticket/32959_

### PR DESCRIPTION
**Pull request by vbraun**
### 📚 Description

Draft PR taken from #35148. I rebased on top of 10.4 and added two more patches taken from upstream

@ClementPernet

closes #32959
closes #35148

### CODE REVIEW

**Comment by vbraun** [comment]
Does not build on 32-bit, but imho its much more urgent to fix Fedora 40 than to spend a lot of time on that. We can always do that later. Either way something is broken, but given the choice I'd rather have 32-bit broken.

**Comment by mkoeppe** [comment]
Fine with me too to temporarily break `*-i386-minimal`

**Comment by mkoeppe** [comment]
But i386 is just some one of several portability bugs that I reported to https://github.com/linbox-team/fflas-ffpack/issues and that are still open

**Comment by tornaria** [comment]
FWIW, I'm packaging i686 without trouble, but we are on gcc 13.2.0. We regularly build and check sagemath on a few architectures including i686 (currently 10.4.beta5 at https://github.com/void-linux/void-packages/pull/49571)

I've just rebuilt and checked givaro / fflas-ffpack / linbox from scratch (on i686) to make sure they are still working, and they seem fine.

BTW, when we switched to gcc 13 I had to add https://github.com/linbox-team/givaro/pull/218, maybe you want to add that one too? (see: https://github.com/void-linux/void-packages/pull/47712#issuecomment-1977817390)

That is the only patch I have you don't (the other differences are: I don't have givaro 226 and I don't have linbox 310-backport, those seem to be needed for gcc 14).

**Comment by vbraun** [comment]
So anyone wants to set it to positive review?

**Comment by mkoeppe** [comment]
Reducing from blocker to critical because blockers still take effect as CI Fixes until this is merged:
- #37950

**Comment by mkoeppe** [comment]
Testing at https://github.com/mkoeppe/sage/actions/runs/8995091991

**Comment by erentar** [comment]
See https://github.com/sagemath/sage/issues/37698#issuecomment-2099790744 , for some reason sage cannot detect installed givaro.
Might be relevant

**Comment by enriqueartal** [comment]
> See [#37698 (comment)](https://github.com/sagemath/sage/issues/37698#issuecomment-2099790744) , for some reason sage cannot detect installed givaro. Might be relevant

It happens for both givaro and fflas-ffpack. In the cited `config.log`, system packages givaro and fflas-ffpack are marked as suitable (it is not the case for linbox, since flint is used as a package); but in the final summary they are marked as not suitable (there are the only switches).

**Comment by mkoeppe** [comment]
> It happens for both givaro and fflas-ffpack. In the cited `config.log`, system packages givaro and fflas-ffpack are marked as suitable (it is not the case for linbox, since flint is used as a package); but in the final summary they are marked as not suitable (there are the only switches).

See https://github.com/sagemath/sage/issues/37348#issuecomment-1947612546

**Comment by mkoeppe** [comment]
> Testing at https://github.com/mkoeppe/sage/actions/runs/8995091991

It builds OK on all Linux platforms except i386.
Let's merge it as suggested and sort out the breakage later.

**Comment by enriqueartal** [comment]
For me, it works, the only issue is the strange situation with the system packages

**Comment by kwankyu** [comment]
I get
```
...
[fflas_ffpack-2.5.0] [spkg-install] libtool: link: g++ -std=gnu++11 -std=gnu++11 -dynamiclib  -o .libs/libfflas_c.1.dylib  .libs/fflas_lvl1.o .libs/fflas_lvl2.o .libs/fflas_lvl3.o .libs/fflas_sparse.o   -L/Users/kwankyu/GitHub/sage-dev/local/lib ./.libs/libfflas.dylib -lopenblas  -O2 -march=native -g -O2 -Wl,-rpath -Wl,/Users/kwankyu/GitHub/sage-dev/local/lib -Wl,-rpath -Wl,/Users/kwankyu/GitHub/sage-dev/local/lib   -install_name  /Users/kwankyu/GitHub/sage-dev/local/lib/libfflas_c.1.dylib -compatibility_version 2 -current_version 2.0 -Wl,-single_module
[fflas_ffpack-2.5.0] [spkg-install] Undefined symbols for architecture x86_64:
[fflas_ffpack-2.5.0] [spkg-install]   "Givaro::Integer::operator%(unsigned long long) const", referenced from:
[fflas_ffpack-2.5.0] [spkg-install]       Givaro::Modular<double, double, void>::init(double&, Givaro::Integer const&) const in fflas_lvl1.o
[fflas_ffpack-2.5.0] [spkg-install]       Givaro::Modular<double, double, void>::init(double&, Givaro::Integer const&) const in fflas_lvl2.o
[fflas_ffpack-2.5.0] [spkg-install]       Givaro::Modular<double, double, void>::init(double&, Givaro::Integer const&) const in fflas_lvl3.o
[fflas_ffpack-2.5.0] [spkg-install] ld: symbol(s) not found for architecture x86_64
[fflas_ffpack-2.5.0] [spkg-install] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[fflas_ffpack-2.5.0] [spkg-install] make[7]: *** [libfflas_c.la] Error 1
[fflas_ffpack-2.5.0] [spkg-install] make[7]: *** Waiting for unfinished jobs....
[fflas_ffpack-2.5.0] [spkg-install] make[6]: *** [all-recursive] Error 1
[fflas_ffpack-2.5.0] [spkg-install] make[5]: *** [all-recursive] Error 1
[fflas_ffpack-2.5.0] [spkg-install] make[4]: *** [all-recursive] Error 1
[fflas_ffpack-2.5.0] [spkg-install] make[3]: *** [all] Error 2
[fflas_ffpack-2.5.0] [spkg-install] ********************************************************************************
[fflas_ffpack-2.5.0] [spkg-install] Error building fflas_ffpack-2.5.0
```
on mac with 3.5 GHz 6-Core Intel Xeon E5. 

[fflas_ffpack-2.5.0.log](https://github.com/sagemath/sage/files/15290506/fflas_ffpack-2.5.0.log)

Any help?

**Comment by vbraun** [comment]
There is a `-lgivaro` missing, possibly intel mac only? New ticket, please

**Pull request merged**
