### PR TITLE
adding support for subschemes in _is_preperiodic

### LINKED ISSUE #32338: adding support for subschemes in _is_preperiodic
<div id="comment:0"></div>

Currently _is_preperiodic does not support dynamical systems defined on subschemes. This ticket aims to add support for morphisms of projective space defined over a subscheme.

CC:  @bhutz

Component: **dynamics**

Keywords: **gsoc2021**

Author: **Alexander Galarraga**

Branch/Commit: **[u/gh-EnderWannabe/is_preperiodic](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-EnderWannabe/is_preperiodic) @ [`faf2b23`](https://github.com/sagemath/sagetrac-mirror/commit/faf2b23e9fa2d925b30e61ce8cf8717335eaf972)**

Reviewer: **Ben Hutz**

_Issue created by migration from https://trac.sagemath.org/ticket/32338_

### PR DESCRIPTION
**Pull request by MatheMagicianPi**
Added and fixed documentation

### :books: Description

 Fixes #32338 

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by EnderWannabe — APPROVED** [review]

**Comment by kwankyu** [comment]
You do not review your own code. Please read [Sage Developer Guide](https://sagemath-tobias.netlify.app/developer/index.html).

**Comment by EnderWannabe** [comment]
> You do not review your own code. Please read [Sage Developer Guide](https://sagemath-tobias.netlify.app/developer/index.html).

Sorry about that - I forgot I contributed. Let me find another reviewer.

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by kwankyu** [comment]
Would you fix the broken link in the PR description?

**Comment by MatheMagicianPi** [comment]
Fixed.

**Pull request merged**
