### PR TITLE
build/pkgs/{gcc,gfortran}/spkg-configure.m4: Allow 14.x

### LINKED ISSUE #37698: Fedora 40 and gcc 14
### Environment

```markdown
- **OS**: Fedora 40beta
- **Sage Version**: 10-4beta0
```

### Steps To Reproduce

Fedora 40beta has just arrived, I wanted to check if sage can be built. The first problem is that Fedora 40 is using gcc 14. Instead of using gcc package, I changed `spkg-configure.m4` in `build/pkgs/gcc` and `build/pkgs/gfortran` to allow gcc 14. 

The compilation gave an error for `givaro`; the patch in https://github.com/linbox-team/givaro/issues/226 works for this. Next problem was with linbox. As a bypass, I used the changed files in https://github.com/sagemath/sage/pull/35148. The three packages have been successfully built.

But I stuck at the compilation of `sagelib`, apparently with `ginac` but not sure, see the package log

### Config log

[config.log](https://github.com/sagemath/sage/files/14812017/config.log)

### Package logs

[sagelib-10.4.beta0.log](https://github.com/sagemath/sage/files/14812018/sagelib-10.4.beta0.log)

### Additional Information

_No response_

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### Dependencies

* https://github.com/sagemath/sage/pull/37537
* https://github.com/sagemath/sage/pull/37584
* https://github.com/sagemath/sage/pull/37938
* https://github.com/sagemath/sage/pull/37939

### PR DESCRIPTION
**Pull request by mkoeppe**
Fedora 40 already ships GCC 14

Fixes #37698

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on https://github.com/sagemath/sage/pull/37646

### CODE REVIEW

**Comment by enriqueartal** [comment]
After last beta, 'sagelib` is not built. I attach the log (of an incremental build); those files and lines are to blame, apparently:
[sagelib-10.4.beta3.log](https://github.com/sagemath/sage/files/14970195/sagelib-10.4.beta3.log)
```
sage/graphs/base/sparse_graph.c:17473:94: error: passing argument 1 of 
'__pyx_f_4sage_6graphs_4base_12sparse_graph_11SparseGraph_add_arc_label_unsafe'
from incompatible pointer type [-Wincompatible-pointer-types]```
```
```
sage/graphs/base/dense_graph.c:18268:103: error: passing argument 1 of 
'__pyx_f_4sage_6graphs_4base_11dense_graph_17DenseGraphBackend__has_labeled_edge_unsafe' 
from incompatible pointer type [-Wincompatible-pointer-types]
```
Same file in `18319:94`.
```
sage/graphs/base/sparse_graph.c:21822:105: error: passing argument 1 of 
'__pyx_f_4sage_6graphs_4base_12sparse_graph_18SparseGraphBackend__has_labeled_edge_unsafe' 
from incompatible pointer type [-Wincompatible-pointer-types]
```
Same file `21879:96`, `22605:97`. `22668:90`
```
sage/graphs/base/static_sparse_backend.c:15831:116: error: passing argument 1 of 
'__pyx_f_4sage_6graphs_4base_21static_sparse_backend_18StaticSparseCGraph_next_out_neighbor_unsafe' 
from incompatible pointer type [-Wincompatible-pointer-types]
```
Same file `19644:109` (arguments 1 and 4), `20154:116`, `24845:119`
```
sage/matroids/lean_matrix.c:36372:83: error: passing argument 1 of 
'__pyx_f_4sage_8matroids_11lean_matrix_13TernaryMatrix_is_nonzero' 
from incompatible pointer type [-Wincompatible-pointer-types]
```
Smae file `43136:86`
```
 sage/plot/plot3d/implicit_surface.c:11783:21: error: assignment to 'PyObject *' {aka 'struct _object *'} 
from incompatible pointer type 'struct __pyx_obj_4sage_4plot_6plot3d_16implicit_surface_VertexInfo 
*' [-Wincompatible-pointer-types]
```
Same file `12340:21`, `13593:21`

**Comment by erentar** [comment]
> I am still testing gcc 14 with no success. Besides these changes, I needed to use #35148 and some patches in fedora 40 for linbox. The problems are in sagelib, maybe here:
> 
> ```
> [spkg-install]     sage/graphs/base/static_sparse_backend.c:15899:75: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]
> [spkg-install]     15899 |     __pyx_t_1 = (((__pyx_v_self->g_rev->neighbors[__pyx_v_u])[__pyx_v_i]) != __pyx_v_v);
> [spkg-install]           |                                                                           ^~
> [spkg-install]     sage/graphs/base/dense_graph.c: In function '__pyx_pf_4sage_6graphs_4base_11dense_graph_17DenseGraphBackend_6has_edge':
> [spkg-install]     sage/graphs/base/dense_graph.c:18267:103: error: passing argument 1 of '__pyx_f_4sage_6graphs_4base_11dense_graph_17DenseGraphBackend__has_labeled_edge_unsafe' from incompatible pointer type [-Wincompatible-pointer-ty
> pes]
> [spkg-install]     18267 |   __pyx_t_2 = __pyx_f_4sage_6graphs_4base_11dense_graph_17DenseGraphBackend__has_labeled_edge_unsafe(((struct __pyx_obj_4sage_6graphs_4base_7c_graph_CGraphBackend *)__pyx_v_self), __pyx_v_u_int, __pyx_v_v_int,
>  Py_None); if (unlikely(__pyx_t_2 == ((int)-1))) __PYX_ERR(0, 702, __pyx_L1_error)
> ```

i can attest that givaro fails. will try with https://github.com/sagemath/sage/pull/35148

**Comment by vbraun** [comment]
Lets merge this and work on fixing the breakage in separate PRs

**Comment by enriqueartal** [comment]
For the record, I summarize my tests, not yet successul, but with some progress:

- Apply this PR
- The givaro problems were gone using https://github.com/sagemath/sage/pull/35148 with an additional upstream patch for givaro, I guess everything is contain in the new https://github.com/sagemath/sage/pull/37938
- Some of the above problems for `sagelib` are gone with `cython-3.0.10`, using https://github.com/sagemath/sage/pull/37584

The remaining errors in sagelib come from `sage/plot/plot3d/implicit_surface.c`.

Thanks for the work.

**Pull request merged**
