### PR TITLE
Reintroducing tight complex interval inverse

### LINKED ISSUE #37963: Reintroduce tight enclosure of interval inversion
In #37941 the `__invert__` implementation of complex intervals was reverted to the straightforward implementation. This issue stands for reintroducing tight reversion (hopefully correct this time).

@miguelmarco @mezzarobba

### PR DESCRIPTION
**Pull request by unhyperbolic**
This provides a (hopefully) correct implementation of computing a tight enclosure for the inverse of a complex interval. It fixes #37963.

There is some history to this:
Commit 84ab655 from #19964 introduced a tight enclosure but had some bugs such as ticket #37927.
Thus, the that commit (and the subsequent partial fixes) were reverted in commit 8d59b12, see pull request #37941.
This is a new implementation of Rokne-Lancaster that I wrote from scratch.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

#37941

### CODE REVIEW

**Comment by NathanDunfield** [comment]
I looked at the two tests that aren't successful.  The `test-long (src/sage/[g-o]*)` looks like it might just have been a network glitch, perhaps just try rerunning.

The one for conda on macos-latest was at:
```
sage -t --random-seed=200494939963004474640346975500698724805 src/sage/rings/number_field/galois_group.py  # 1 doctest failed 
                 [failed in baseline: unreported failure on macOS (sort order) in GaloisGroup_v2.artin_symbol, 
                  https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272?pr=37998]
sage -t --random-seed=200494939963004474640346975500698724805 src/sage/rings/number_field/number_field.py  # 2 doctests failed 
                 [failed in baseline: unreported failure on macOS (sort order) in NumberField_absolute.[optimized_]subfields, 
                  https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272?pr=37998]
sage -t --random-seed=200494939963004474640346975500698724805 src/sage/rings/qqbar.py  
                # 1 doctest failed [failed in baseline: unreported failure on macOS seen in 
                https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272?pr=37998]
sage -t --random-seed=200494939963004474640346975500698724805 src/sage/schemes/cyclic_covers/charpoly_frobenius.py  # 1 doctest failed
```
It does involve QQbar, so possibly that's related to this PR (I'm not sure how one is supposed to interpret `failed in baseline`).

**Comment by NathanDunfield** [comment]
I double-checked that all the strange behavior from #37927 is gone.  Then I wrote a naive test script ([attached](https://github.com/user-attachments/files/16228805/stress.txt)) that just computes 1/z for z a sampling of points on the boundary of a random box Z at quad-double precision and makes sure they are in 1/Z.   With Sage 10.3, the test fails 20-25% of the time; with this PR, I have seen no issues with 10^5 trials (Linux on Intel).

My only comment on the code is that is the reference [LR1971] actually expanded somewhere?

**Comment by culler** [comment]
It was expanded in Matthias' earlier PR that was reverted.

J. Rokne, P. Lancaster. Complex interval arithmetic.  Communications of the ACM 14. 1971.

**Comment by culler** [comment]
Nathan, did you also check for memory leaks with your many inversions?

**Comment by NathanDunfield** [comment]
> Nathan, did you also check for memory leaks with your many inversions?

Just now looking in `top`, memory usage of Sage as a whole stays steady throughout the test. I also another test that calls the new invert function more rapidly (10^6 times).  Just creating a list of 10^6 elements of CIF is visible in the `top` output, so everything seems good.

**Comment by culler** [comment]
I am sold.

**Review by NathanDunfield — APPROVED** [review]
After playing around with [the shader demo](https://www.shadertoy.com/view/M3VXWG) of the PR, I'm also convinced.

**Comment by unhyperbolic** [comment]
> My only comment on the code is that is the reference [LR1971] actually expanded somewhere?

I noticed that the full reference was in complex_interval.pyx and got abbreviated to [RL1971] sometime later - so I assumed that the style now is to just give, e.g., [RL1971] with the full reference being in src/doc/en/reference/references/index.rst.

That does make sense for doc strings because we should get a hyperlink for [RL1971]. But what about citations within the code?

**Comment by NathanDunfield** [comment]
@unhyperbolic That makes sense.  I don't think the docstring for `__invert__` makes into the html version of docs, though the reference [RL1971] is [where it should be](https://doc.sagemath.org/html/en/reference/references/index.html#ref-r).  I imagine things are fine as is, then.

**Review by culler — APPROVED** [review]
Approving this PR.

**Pull request merged**
