### PR TITLE
remove obsolete .zenodo.json* files, update CITATION.cff to fix zenodo/DOI

### LINKED ISSUE #35659: zenodo broken again, since Sage 9.8
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
all
```

### Steps To Reproduce

_No response_

### Expected Behavior

zenodo (e.g. here: https://zenodo.org/search?page=1&size=20&q=sagemath) points to the latest release, 10.0

### Actual Behavior

it points to 9.7

### Additional Information

probably related to `CITATION.cff` being outdated, see https://github.com/citation-file-format/citation-file-format/issues/374

### PR DESCRIPTION
**Pull request by dimpase**
Our DOI creation/update via zenodo is broken again.

`CITATION.cff` overrides `.zenodo.json`, cf.

https://github.com/citation-file-format/citation-file-format/issues/374

This will fix https://github.com/sagemath/sage/issues/35659

### CODE REVIEW

**Comment by dimpase** [comment]
perhaps the version in CITATION.cff should be the upcoming version 10.1, not the current one.

**Comment by dimpase** [comment]
perhaps we should generate `CITATION.cff` from a template, like we did for `.zenodo.json`

**Comment by fchapoton** [comment]
> perhaps the version in CITATION.cff should be the upcoming version 10.1, not the current one.

**Comment by fchapoton** [comment]
sorry,  wrong click, now undone. Yes, I would say crating the .cff file in the script would be nice.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by vbraun** [comment]
Merge conflict

**Comment by dimpase** [comment]
I've rebased on top of 10.1.beta1.

**Comment by dimpase** [comment]
@vbraun - Please merge this manually, if needed. The conflict you got is due to `.zenodo.json` generated and pushed automatically by the release script, so indeed you'll always get a merge conflict if you try doing this automatically, as this branch removes `.zenodo.json` completely.

An alternative is to split this into 2 PRs - the fist one removing automatic generation of `zenodo.json`, the second doing the rest. Please tell me your preference.

**Comment by vbraun** [comment]
This breaks the tarball creation script
```
Creating upstream/configure-24ed284171ade0dc8de01fda1b2d5f9eeedf1520.tar.gz...
Updating checksum of configure (tarball configure-24ed284171ade0dc8de01fda1b2d5f9eeedf1520.tar.gz)
error: pathspec '/home/release/Sage/src/CITATION.cff' did not match any file(s) known to git
Error committing to the repository.
Traceback (most recent call last):
  File "/home/release/opt/bin/git-releasemgr", line 16, in <module>
    cmdline.launch()
  File "/home/release/opt/git-trac-command/git_trac/releasemgr/cmdline.py", line 189, in launch
    app.release(args.version, check=args.check)
  File "/home/release/opt/git-trac-command/git_trac/releasemgr/app.py", line 409, in release
    update_version(version)
  File "/home/release/opt/git-trac-command/git_trac/releasemgr/make_release.py", line 12, in update_version
    check_call(['sage', '-sh', '-c', 'sage-update-version {0}'.format(version)])
  File "/home/release/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sage', '-sh', '-c', 'sage-update-version 10.1.beta2']' returned non-zero exit status 1
```

**Comment by dimpase** [comment]
oops, 
```
    "$SAGE_SRC/CITATION.cff" \
```

should be  SAGE_ROOT, not SAGE_SRC

**Comment by dimpase** [comment]
@vbraun - should be fixed now.

**Review by fchapoton — APPROVED** [review]

**Comment by vbraun** [comment]
Merge conflict

**Comment by dimpase** [comment]
@vbraun - rebased again. Please merge manually, cf https://github.com/sagemath/sage/pull/35666#issuecomment-1566082635

**Pull request merged**
