### PR TITLE
CI: Remove ci-wsl, ci-cygwin-standard

### PR DESCRIPTION
**Pull request by mkoeppe**
These workflows have been failing for a long time and provide no value.

ci-cygwin-standard was already disabled in sagemath/sage - see https://github.com/sagemath/sage/actions/workflows/ci-cygwin-standard.yml

The failures of ci-wsl can be seen here: https://github.com/sagemath/sage/actions/workflows/ci-wsl.yml

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dimpase** [comment]
It's OK to remove the Cygwin CI. But
IMHO we should investigate and fix the WSL failure. How about just not calling it, with an appropriate comment, rather than removing?

**Comment by dimpase** [comment]
There is https://github.com/marketplace/actions/setup-wsl which looks up to date and less verbose than our CI

**Comment by mkoeppe** [comment]
It's fine if someone would like to fix the WSL one, but is has been broken for a very long time and I don't remember if we ever gained any useful information from it.

**Review by dimpase — APPROVED** [review]
OK, fine

**Pull request merged**
