### PR TITLE
Fix sqrt(sqrt(2)) memory leak in ginac numeric.cpp

### LINKED ISSUE #33074: Update valgrind suppressions
<div id="comment:0"></div>

from https://github.com/python/cpython/blob/main/Misc/valgrind-python.supp

also see https://github.com/python/cpython/blob/main/Misc/README.valgrind#L9

CC:  @kliem @dimpase @orlitzky

Component: **user interface**

_Issue created by migration from https://trac.sagemath.org/ticket/33074_

### PR DESCRIPTION
**Pull request by vbraun**
Fix the memory leak when computing the outer sqrt in `sqrt(sqrt(2))`, as reported on sage devel at https://groups.google.com/g/sage-devel/c/6zpxQKXtJgk

The unit test is a WIP and depends on https://github.com/tekknolagi/valgrind/pull/1

- Resolves #33074

### CODE REVIEW

**Comment by vbraun** [comment]
Note to self: the numeric::numeric ctor transfers ownership of the mpz_t, so no clear in that one code path. Tests pass now! 

Setting this to needs review for now, a better valgrind integration needs the pypi/valgrind PR that will be tracked there.

**Comment by mkoeppe** [comment]
Use the new .supp file to `src/bin/sage-valgrind` too?

**Comment by vbraun** [comment]
`sage-valgrind` has bigger problems than the suppression file, it instruments the shell launching python and not python itself. I'd rather leave fixing it for a separate ticket.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by tornaria** [comment]
Works for me, thanks!

**Pull request merged**
