### PR TITLE
Use `magick` command instead of the deprecated `convert` if available

### PR DESCRIPTION
**Pull request by antonio-rojas**
The `convert` command is deprecated and throws a warning at runtime.

### CODE REVIEW

**Comment by dimpase** [comment]
why not rename `convert` to `magick` ?

**Comment by dimpase** [comment]
more precisely, ImageMagick version 7 provides `magick`, earlier versions only provide `convert`

**Comment by antonio-rojas** [comment]
If we want to drop support for IM6 then we shold replace all uses of `convert` throughout sage source, which would be a much larger change. I'm fine with that, but in the meantime this will fix the test failure. Changing to `magick` only for this particular instance doesn't seem right to me.

**Comment by jhpalmieri** [comment]
From a quick glance at imagemagick.org, it seems like we could replace `convert ...` with `magick convert ...` — the latter has been supported since version 6 of ImageMagick. Unfortunately I can't tell when version 6 was released and whether it is reasonable to expect version 6 or later to be supported on our standard platforms. Judging from https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=32622, it looks like version 6 is pretty old and should be well-established.

I guess my question is, should we switch away from the deprecated `convert` instead of just hiding the deprecation warning with `...`?

**Comment by antonio-rojas** [comment]
> From a quick glance at imagemagick.org, it seems like we could replace `convert ...` with `magick convert ...` — the latter has been supported since version 6 of ImageMagick. 

ImageMagick 6 doesn't install any `magick` executable. And in any case, `magick convert` throws the same deprecation warning as `convert` in 7.1.1.33, so it wouldn't solve anything.

**Comment by dimpase** [comment]
we can test for `magick` in spkg-configure. And instead of `convert` use something we'd set up there, to be either `convert` or `magick`.

**Review by dimpase — CHANGES_REQUESTED** [review]
sage.features for ImageMagick, and spkg-configure, should be updated
(I can help with this, if needed)

**Comment by dimpase** [comment]
> it seems like we could replace `convert ...` with `magick convert ...`
Isn't the correct and stable new  syntax merely `magick ...`, not `magick convert ...` ?
I tried `magick foo.jpg foo.pdf`, it works fine with `magick` version 7.1.1-33.
(and if I use `convert` instead, I get the warning)

**Comment by jhpalmieri** [comment]
> > it seems like we could replace `convert ...` with `magick convert ...`
> 
> Isn't the correct and stable new syntax merely `magick ...`, not `magick convert ...` ? I tried `magick foo.jpg foo.pdf`, it works fine with `magick` version 7.1.1-33. (and if I use `convert` instead, I get the warning)

I'm sure you're right. As I said, I just took a quick glance at the website, and I guess I misunderstood what they meant by "supporting subcommands for compatibility with ... version 6" (https://imagemagick.org/script/command-line-tools.php).

**Comment by antonio-rojas** [comment]
I haven't (and don't plan to) touched anything outside `src`, in particular `spkg-configure.m4`. This will keep working fine until the `convert` command is removed, so it can be fixed in a later ticket.

**Comment by dimpase** [comment]
it seems that your patch assumes presence of `magick` - but it's not there if an old version of ImageMagick is installed. There you only have `convert`.

**Comment by antonio-rojas** [comment]
> it seems that your patch assumes presence of `magick` - but it's not there if an old version of ImageMagick is installed. There you only have `convert`.

No, it falls back to `convert` if `magick` is not available. This has been tested with both IM 6 and 7.

**Review by dimpase — APPROVED** [review]

**Comment by dimpase** [comment]
OK, sorry, I misread the diff.

**Comment by dimpase** [comment]
please rebase over the latest develop branch (it goes cleanly)

**Comment by GMS103** [comment]
FWIW, positive review for SageMath 10.4.beta9 on an Apple Silicon Mac M1 Pro with Homebrew up to date, on macOS 12.7.5 (Xcode 14.2).

**Comment by mkoeppe** [comment]
CI failures are unrelated. Let's merge it, although a cleaner implementation as discussed in #38173 would be preferable.

**Comment by GMS103** [comment]
Thanks.

**Pull request merged**
