### PR TITLE
Revert cif fast inversion 84ab655

### LINKED ISSUE #37927: right_kernel_matrix is wrong over QQbar
As reported in [this sage-devel thread](https://groups.google.com/g/sage-devel/c/B39dHJYkeho) an explicit matrix over `QQbar` that claims to have no kernel but there is a very explicit integral vector in it...
```py
from sage.all import PolynomialRing, QQ, QQbar, RIF, CIF, matrix, I

R = PolynomialRing(QQ, 'y')
y = R.gen()

v1 = QQbar.polynomial_root(y**2 + 1, CIF(0, -1))
v2 = -QQbar(2).sqrt()

M = matrix(QQbar, [[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                   [-4, 2*v1, 1, 64, -32*v1, -16, 8*v1, 4, -2*v1, -1],
                   [4*v1, 1, 0, -192*v1, -80, 32*v1, 12, -4*v1, -1, 0],
                   [2, 0, 0, -480, 160*v1, 48, -12*v1, -2, 0, 0],
                   [-4, 2*I, 1, 64, -32*I, -16, 8*I, 4, -2*I, -1],
                   [4*I, 1, 0, -192*I, -80, 32*I, 12, -4*I, -1, 0],
                   [2, 0, 0, -480, 160*I, 48, -12*I, -2, 0, 0],
                   [0, 0, 0, 8, 4*v2, 4, 2*v2, 2, v2, 1],
                   [0, 0, 0, 24*v2, 20, 8*v2, 6, 2*v2, 1, 0],
                   [0, 0, 0, 8, 4*v2, 4, 2*v2, 2, -v2, 1],
                   [0, 0, 0, 24*v2, 20, 8*v2, 6, 2*v2, 1, 0],
                   [0, 0, 0, -4096, -1024*I, 256, 64*I, -16, -4*I, 1],
                   [0, 0, 0, -4096, 1024*I, 256, -64*I, -16, 4*I, 1]])

assert not M.right_kernel_matrix()
v = matrix(QQbar, 10, 1, [-108, 0, 0, 1, 0, 12, 0, -60, 0, 64])
assert (M * v).is_zero()
```

### PR DESCRIPTION
**Pull request by videlec**
The tight reversion of complex intervals introduced in 84ab655 from #19964 made complex intervals wrong... and hence unreliable. This remained unnoticed until an apparently unrelated bug involving QQbar #37927. As an emergency measure we simply revert the tight reversion.

Fixes #37927

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mezzarobba** [comment]
OK, though of course it would be better to debug the inversion routine if somebody has time for that.

**Review by mezzarobba — APPROVED** [review]

**Comment by mezzarobba** [comment]
Sorry for the multiple label changes. I agree with the revert, but the tests currently fail, tough I don't think this is due to the changes made here.

Also, you might want to add a test based on https://github.com/sagemath/sage/issues/37927#issuecomment-2094960688.

**Comment by fchapoton** [comment]
For a tentative to repair the currently very broken CI , see #37926

**Comment by videlec** [comment]
> Sorry for the multiple label changes. I agree with the revert, but the tests currently fail, tough I don't think this is due to the changes made here.
> 
> Also, you might want to add a test based on [#37927 (comment)](https://github.com/sagemath/sage/issues/37927#issuecomment-2094960688).

Isn't that enough?
```diff
diff --git a/src/sage/rings/qqbar.py b/src/sage/rings/qqbar.py
index 4e4454988c..773853ec67 100644
--- a/src/sage/rings/qqbar.py
+++ b/src/sage/rings/qqbar.py
@@ -552,6 +552,28 @@ Check that :issue:`28530` is fixed::
      (0.999999587? + 0.?e-11*I, 1),
      (0.999999999? + 0.?e-11*I, 1)]
 
+Check that issue:`37927` is fixed::
+
+    sage: y = polygen(QQ, 'y')
+    sage: v1 = QQbar.polynomial_root(y**2 + 1, CIF(0, -1))
+    sage: v2 = -QQbar(2).sqrt()
+    sage: M = matrix(QQbar, [[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
+    ....:              [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
+    ....:              [-4, 2*v1, 1, 64, -32*v1, -16, 8*v1, 4, -2*v1, -1],
+    ....:              [4*v1, 1, 0, -192*v1, -80, 32*v1, 12, -4*v1, -1, 0],
+    ....:               [2, 0, 0, -480, 160*v1, 48, -12*v1, -2, 0, 0],
+    ....:               [-4, 2*I, 1, 64, -32*I, -16, 8*I, 4, -2*I, -1],
+    ....:               [4*I, 1, 0, -192*I, -80, 32*I, 12, -4*I, -1, 0],
+    ....:               [2, 0, 0, -480, 160*I, 48, -12*I, -2, 0, 0],
+    ....:               [0, 0, 0, 8, 4*v2, 4, 2*v2, 2, v2, 1],
+    ....:               [0, 0, 0, 24*v2, 20, 8*v2, 6, 2*v2, 1, 0],
+    ....:               [0, 0, 0, 8, 4*v2, 4, 2*v2, 2, -v2, 1],
+    ....:               [0, 0, 0, 24*v2, 20, 8*v2, 6, 2*v2, 1, 0],
+    ....:               [0, 0, 0, -4096, -1024*I, 256, 64*I, -16, -4*I, 1],
+    ....:               [0, 0, 0, -4096, 1024*I, 256, -64*I, -16, 4*I, 1]])
+    sage: M.right_kernel_matrix()
+    [   1.000000000000000? + 0.?e-16*I                                 0                                 0 -0.00925925925925926? + 0.?e-19*I               0.?e-35 + 0.?e-18*I -0.11111111111111111? + 0.?e-18*I               0.?e-34 + 0.?e-17*I   0.5555555555555555? + 0.?e-16*I                                 0  -0.5925925925925926? + 0.?e-17*I]
+
 AUTHOR:
 
 - Carl Witty (2007-01-27): initial version
```

**Comment by miguelmarco** [comment]
As I mentioned in [#37927](https://github.com/sagemath/sage/issues/37927#issuecomment-2098037747), I think there is another underlying problem with mpfr not being able to find the difference between two different numbers:

```
sage: c = CIF(0,31)
sage: ci = 1/c
sage: ci.real().endpoints()
(0.000000000000000, -0.000000000000000)
sage: ci.imag().endpoints()
(-0.0322580645161291, -0.0322580645161290)
sage: ci.diameter()
0.000000000000000
sage: ci.imag().endpoints()[1]-ci.imag().endpoints()[0]
0.000000000000000
```

My guess is that in that particular case, the difference is in the last bit, but one of the numbers uses a higher exponent (both examples I have seen involve the inverses of powers of 2 or powers of two minus one,  which are where you would expect to find this kind corner cases), so the precision of the result is set to the bigger exponent, and that last bit of difference is lost.

This problem is exposed in this case because the result of the inversion method is too tight, but I think it would be worth detecting this kind of problems and fixing them, because there are important performance advantages in using tight results.

**Comment by videlec** [comment]
> As I mentioned in [#37927](https://github.com/sagemath/sage/issues/37927#issuecomment-2098037747), I think there is another underlying problem with mpfr not being able to find the difference between two different numbers:
> 
> ```
> sage: c = CIF(0,31)
> sage: ci = 1/c
> sage: ci.real().endpoints()
> (0.000000000000000, -0.000000000000000)
> sage: ci.imag().endpoints()
> (-0.0322580645161291, -0.0322580645161290)
> sage: ci.diameter()
> 0.000000000000000
> sage: ci.imag().endpoints()[1]-ci.imag().endpoints()[0]
> 0.000000000000000
> ```
> 
> My guess is that in that particular case, the difference is in the last bit, but one of the numbers uses a higher exponent (both examples I have seen involve the inverses of powers of 2 or powers of two minus one, which are where you would expect to find this kind corner cases), so the precision of the result is set to the bigger exponent, and that last bit of difference is lost.
> 
> This problem is exposed in this case because the result of the inversion method is too tight, but I think it would be worth detecting this kind of problems and fixing them, because there are important performance advantages in using tight results.

Contrarily to the `(sign, mantissa, exponent)` triple, the decimal representation does not tell you the actual value.
```
sage: x_down = RealField(53, rnd='RNDD')(4648877034705029 * 2**-57)
sage: x_down
0.0322580645161290
sage: x_up = RealField(53, rnd='RNDU')(4648877034705029 * 2**-57)
sage: x_up
0.0322580645161291
sage: x_down == x_up  # these are actually equal!
True
sage: x_down.sign_mantissa_exponent()
(1, 4648877034705029, -57)
sage: x_up.sign_mantissa_exponent()
(1, 4648877034705029, -57)```
```
The two floating points above are the one appearing in our example
```
sage: c = CIF(0,31)
sage: ci = 1/c
sage: [x.sign_mantissa_exponent() for x in ci.imag().endpoints()]
[(-1, 4648877034705029, -57), (-1, 4648877034705029, -57)]
```

**Comment by videlec** [comment]
@mezzarobba some doctest failures were due to the reversion. They are fixed in [c687feb](https://github.com/sagemath/sage/pull/37941/commits/c687febc17f701971710f25a7c4cbb516dc6d28e).

**Comment by mkoeppe** [comment]
Reducing to "critical" because "blocker" still doubles as "CI Fix" until this is merged:
- #37950

**Comment by videlec** [comment]
> Reducing to "critical" because "blocker" still doubles as "CI Fix" until this is merged:
> 
>     * [CI: Handle the "p: CI Fix" label #37950](https://github.com/sagemath/sage/pull/37950)

Thanks for taking care of this. I would really appreciate this PR to be part of the next beta as it does fix a critical bug!

**Comment by mezzarobba** [comment]
> Isn't that enough?

Sure, I somehow missed the first of the two tests, sorry!

**Pull request merged**
