### PR TITLE
Fix flaky simplicial set test

### LINKED ISSUE #38888: Random test failure in `simplicial_sets`
### Steps To Reproduce

_No response_

### Expected Behavior

Tests pass

### Actual Behavior

```
sage -t --warn-long 5.0 --random-seed=52078804102925852962925524043712901488 src/sage/categories/simplicial_sets.py
**********************************************************************
File "src/sage/categories/simplicial_sets.py", line 538, in sage.categories.simplicial_sets.SimplicialSets.Pointed.ParentMethods.cover
Failed example:
    C.face_data()
Expected:
    {(*, ()): None,
     (*, (1,2,3)): None,
     (*, (1,3,2)): None,
     (sigma_1, ()): ((*, (1,2,3)), (*, ())),
     (sigma_1, ()): ((*, (1,3,2)), (*, ())),
     (sigma_1, (1,2,3)): ((*, (1,3,2)), (*, (1,2,3))),
     (sigma_1, (1,2,3)): ((*, ()), (*, (1,2,3))),
     (sigma_1, (1,3,2)): ((*, ()), (*, (1,3,2))),
     (sigma_1, (1,3,2)): ((*, (1,2,3)), (*, (1,3,2)))}
Got:
    {(*, ()): None,
     (*, (1,2,3)): None,
     (*, (1,3,2)): None,
     (sigma_1, ()): ((*, (1,3,2)), (*, ())),
     (sigma_1, ()): ((*, (1,2,3)), (*, ())),
     (sigma_1, (1,2,3)): ((*, ()), (*, (1,2,3))),
     (sigma_1, (1,2,3)): ((*, (1,3,2)), (*, (1,2,3))),
     (sigma_1, (1,3,2)): ((*, (1,2,3)), (*, (1,3,2))),
     (sigma_1, (1,3,2)): ((*, ()), (*, (1,3,2)))}
```

### Additional Information

_No response_

### Environment

Linux: https://github.com/sagemath/sage/actions/runs/11589629492/job/32265510963

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by user202729**
Fixes https://github.com/sagemath/sage/issues/38888 .

This test has been failing sporadically recently e.g. https://github.com/sagemath/sage/actions/runs/11733902583/job/32689016794?pr=38938 .

From my understanding of simplicial set, the two `sigma_1` are actually representing two different cells (the wedge looks like a "8" shape), but because they both come from `S1` (the 1-sphere i.e. circle), they get the same name.

SageMath does some magic during doctest so that dict entries are sorted, but the problem is

```
        At this point, comparison between v and w is random, based on
        their location in memory. ::
```

so with some chance it fails.

This change should make it deterministic --- since the two faces are named `sigma_1` and `sigma_1'`, the comparison should be by custom name…?

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes. (not applicable)
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by user202729** [comment]
The failed test is

```
2024-11-08T15:09:09.5768206Z **********************************************************************
2024-11-08T15:09:09.5893109Z File "src/sage/groups/finitely_presented_named.py", line 489, in sage.groups.finitely_presented_named.AlternatingPresentation
2024-11-08T15:09:09.5894783Z Failed example:
2024-11-08T15:09:09.5895452Z     A1.is_isomorphic(A2), A1.order()
2024-11-08T15:09:09.5896032Z Expected:
2024-11-08T15:09:09.5896389Z     (True, 1)
2024-11-08T15:09:09.5896732Z Got:
2024-11-08T15:09:09.5897089Z     #I  Forcing finiteness test
2024-11-08T15:09:09.5897589Z     (True, 1)
2024-11-08T15:09:11.2068744Z **********************************************************************
```

This is obviously https://github.com/sagemath/sage/issues/38889 instead.

By the way, GitHub Actions doesn't seem to be able to report test failure to the GitHub interface?

**Comment by orlitzky** [comment]
> This is obviously #38889 instead.

Potential solution: https://github.com/sagemath/sage/pull/38956

**Review by tobiasdiez — APPROVED** [review]
Thanks! The change looks good to me, as far as I understand the problem. But it would be good if someone more familiar with the code has a look at well.

Marking it already as "ci fix" so that other PRs don't keep falling because of this issue.

**Comment by miguelmarco** [comment]
Since there is no actual code being changed (just doctests), I see no risk in accepting it.

**Comment by user202729** [comment]
There's always the risk of accidentally telling the user "this is the right way to do things" while it actually relies on dangerous internal implementation detail e.g. are you sure that the 1-cell is not shared between different objects, and mutate it is safe?

**Comment by jhpalmieri** [comment]
It looks okay to me (after a quick glance).

**Comment by tobiasdiez** [comment]
I didn't see these test failures pop up again, so this PR is definitely achieving its goal. Since there were no objections, let's get it in.

**Pull request merged**
