### PR TITLE
build/pkgs/openblas/spkg-configure.m4: Reject version 0.3.22

### PR DESCRIPTION
**Pull request by mkoeppe**
### :books: Description
openblas 0.3.22 is broken, see:
- #35371 
- https://github.com/scipy/scipy/issues/18208
- https://github.com/xianyi/OpenBLAS/issues/3976

We reject it.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Shouldn't the conda version be restricted as well, otherwise this will lead to problems once 0.3.22 is released on conda (which happens with https://github.com/conda-forge/openblas-feedstock/pull/150)

**Comment by mkoeppe** [comment]
Trusting the packagers to not package a broken version

**Comment by jhpalmieri** [comment]
With this branch applied to 10.0.beta6, I ran `./bootstrap` and `./configure` and it rejected the system's version of `openblas`, which is good. I am seeing doctest failures, though. For example:
```
File "src/sage/tests/books/computational-mathematics-with-sagemath/float_doctest.py", line 402, in sage.tests.books.computational-mathematics-with-sagemath.float_doctest
Failed example:
    NearlySingularMatrix(RDF,n).det() == 0.0
Expected:
    True
Got:
    False
```
and
```
File "src/sage/matrix/matrix_integer_dense.pyx", line 3722, in sage.matrix.matrix_integer_dense.Matrix_integer_dense.determinant
Failed example:
    A.determinant(algorithm='linbox',proof=False) == d
Expected:
    True
Got:
    False
```
The full list of failures:
```
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/plot/plot3d/plot3d.py  # Killed due to segmentation fault
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/geometry/polyhedron/library.py  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/modular/modform_hecketriangle/readme.py  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/modular/modform_hecketriangle/abstract_space.py  # 3 doctests failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/tests/books/computational-mathematics-with-sagemath/float_doctest.py  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/graphs/generators/families.py  # 2 doctests failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/matrix/matrix_integer_dense.pyx  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/modular/modform_hecketriangle/space.py  # 2 doctests failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/graphs/graph_generators.py  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/combinat/posets/posets.py  # Killed due to abort
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/stats/time_series.pyx  # 8 doctests failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/doc/en/thematic_tutorials/numerical_sage/scipy.rst  # Killed due to segmentation fault
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/geometry/polyhedron/base7.py  # 1 doctest failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/doc/it/faq/faq-usage.rst  # Killed due to segmentation fault
sage -t --long --random-seed=244469894400536995489090131539290714853 src/doc/en/faq/faq-usage.rst  # Killed due to segmentation fault
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/matrix/matrix_double_dense.pyx  # 2 doctests failed
sage -t --long --random-seed=244469894400536995489090131539290714853 src/sage/numerical/sdp.pyx  # 2 doctests failed
```
Some of these are known issues being tracked elsewhere, but some are new.

**Comment by dimpase** [comment]
could you try uninstalling brew's openblas and see if it helps these tests?

**Comment by jhpalmieri** [comment]
First a clarification: I haven't run full tests on an Apple M2 machine, but I don't see any failures in `src/sage/matrix`, for example: I'm only seeing the failures on an Intel machine. 

Second, I uninstalled homebrew's openblas and I got the same failures. (I did `brew uninstall --ignore-dependencies openblas`, for what it's worth.) These must be old failures and not due to this ticket, but it's a problem if Sage's `openblas` doesn't work well.

**Comment by GMS103** [comment]
- SageMath 10.0.beta7
- Apple Silicon Macs ("M" series)
- macOS 11.7.5, macOS 12.6.4, macOS 13.3
- Homebrew up to date but without OpenBLAS (still at version 0.3.22 which is buggy).

```make``` installs OpenBLAS SPKG version 0.3.21.
```make ptestlong``` succeeds (except for unrelated issues).

**Comment by jhpalmieri** [comment]
My earlier problems are probably just dependent on that particular machine. On another Intel mac, all relevant tests pass.

**Review by jhpalmieri — APPROVED** [review]

**Comment by dimpase** [comment]
I gather that 0.3.23, fixing this bug, is out

**Comment by GMS103** [comment]
Yes and no Dima, see
https://github.com/xianyi/OpenBLAS/issues/3976

Guillermo

**Comment by jhpalmieri** [comment]
Even if a later version fixes this bug, we still need to black-list 0.3.22.

**Pull request merged**
