### PR TITLE
Various improvements to Weyl character rings

### PR DESCRIPTION
**Pull request by tscrim**
### 📚 Description

We provide a number of improvements to the Weyl character ring:

1. We make it know that it is commutative (along with its ambient ring).
2. We speedup the `_demazure_helper` method by only doing operations based upon the support of the simple roots.
   ```
   sage: F = FusionRing(['B',10], 2, base_ring=QQ)
   sage: dd = {(1,0,0,1,0,0,0,0,0,0): 1}
   sage: %time X = F._demazure_helper(dd)
   CPU times: user 3.1 s, sys: 12 ms, total: 3.11 s
   Wall time: 3.11 s
   ```
   Previously took `~6s`.
3. We don't set the `FusionRing` as a subobject of the `WeightRing`.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tscrim** [comment]
@bump @willieab Here are some improvements to the WCR which also improves the fusion rings.

**Comment by tscrim** [comment]
Someone with sufficient powers (e.g., @mkoeppe @dimpase) needs to approve the PR request (and also upgrade @dwbump to the triage team since he is a long-term contributor).

**Review by dimpase — APPROVED** [review]
as requested by @tscrim

**Comment by dimpase** [comment]
@dwbump is a member of triage team

**Comment by tscrim** [comment]
Thank you @dimpase!

**Pull request merged**
