### PR TITLE
`sage --package properties`

### PR DESCRIPTION
**Pull request by mkoeppe**
For example:
```
$ ./sage -package properties --format shell gap ecl                                                                                                                               git:sage_package_properties
path_ecl='/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/build/pkgs/ecl'
version_with_patchlevel_ecl='21.2.1'
type_ecl='standard'
source_ecl='normal'
trees_ecl='SAGE_LOCAL'
path_gap='/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/build/pkgs/gap'
version_with_patchlevel_gap='4.12.2'
type_gap='standard'
source_gap='normal'
trees_gap='SAGE_LOCAL'
```
The output is suitable as input for `eval` in Bourne shell. (The default output format is more human-friendly.)

Split out from:
- #36740

where this new interface is used to eliminate direct references to `build/pkgs/` from various scripts and reduce code duplication and complexity in reading SPKG metadata.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kwankyu** [comment]
It would be natural to print like
```
$ ./sage -package properties gap                                                                                                                              
path='/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/build/pkgs/gap'
version_with_patchlevel='4.12.2'
type='standard'
source='normal'
trees='SAGE_LOCAL'
```
Why accept multiple `pac` and add `_pac`?

**Comment by mkoeppe** [comment]
> Why accept multiple `pac` and add `_pac`?

So that a shell script can request this information in bulk instead of invoking this script many times.
(In #36740, this gives a speedup in running ./configure)

**Comment by kwankyu** [comment]
Would you point where the suffixed string is used?

**Comment by mkoeppe** [comment]
In https://github.com/sagemath/sage/pull/36740/files#diff-b1f0deab6b85906bd925c4fceb337406ebea20bdc199c63996977328d24cf5c5R347, take a look at:
- m4/sage_spkg_collect.m4 line 155 `SPKG_VERSION=$[version_with_patchlevel_]SPKG_NAME`
- bootstrap line 58 `eval DIR=\$path_$pkgname pkgtype=\$type_$pkgname pkgsource=\$source_$pkgname` and similar

**Comment by kwankyu** [comment]
I see. You use the output directly to define variables...

**Comment by kwankyu** [comment]
How about adding an option `--output=list` and `--output=vars` with default the former. Thus 
```
$ ./sage -package properties gap
gap:                                                                                                                              
  path='/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/build/pkgs/gap'
  version_with_patchlevel='4.12.2'
  type='standard'
  source='normal'
  trees='SAGE_LOCAL'
```

```
$ ./sage -package properties --output=vars gap                                                                                                                              
path_gap='/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/build/pkgs/gap'
version_with_patchlevel_gap='4.12.2'
type_gap='standard'
source_gap='normal'
trees_gap='SAGE_LOCAL'
```

**Comment by mkoeppe** [comment]
I'm open to creating output format options when needed (as you may have seen in #36740, `sage --package dependencies` has an option `--format={plain,shell}`), but I'm reluctant to add them without a specific use case

**Comment by kwankyu** [comment]
`--format` is okay.

A use case is just to read `./sage -package properties gap` by human eyes. This use is not expected?

**Comment by mkoeppe** [comment]
We already have a tool that formats package info for human inspection, that's `sage -info SPKG`...

**Comment by kwankyu** [comment]
But `./sage -package properties gap` intends to provide other info (about installed packages) oriented for developers. That is a sage command, and developers may use them. If the command is only for shells, then why provide it as a sage command?

**Comment by kwankyu** [comment]
> But `./sage -package properties gap` intends, as far as I understand, to provide other info (about installed packages) oriented for developers. That is a sage command, and developers may use them. If the command is only for shells, then why provide it as a sage command?

**Comment by mkoeppe** [comment]
`./sage -package` just delegates to `sage-package`, and `./sage -info` just delegates to `sage-spkg-info`; both a provided by the Sage distribution. (But I feel I'm missing your point)

**Comment by kwankyu** [comment]
If the command is internal and not exposed to developers, I won't care the output format. But it is exposed and human developers may use it, then the output should be in a readable format. Currently the format is only suitable to shells. (I wonder I misunderstand something...)

**Comment by mkoeppe** [comment]
OK, that makes sense, I'll add an option.

**Comment by mkoeppe** [comment]
How's this?

**Comment by kwankyu** [comment]
Thanks. Looks good to me.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
Do all supported platforms use python3 as the "default" python? I'm getting:
```
Traceback (most recent call last):
  File "/var/lib/buildbot/slave/sage_git/build/build/bin/sage-package", line 40, in <module>
    from sage_bootstrap.cmdline import run
  File "/var/lib/buildbot/slave/sage_git/build/build/bin/../sage_bootstrap/cmdline.py", line 31, in <module>
    from sage_bootstrap.app import Application
  File "/var/lib/buildbot/slave/sage_git/build/build/bin/../sage_bootstrap/app.py", line 80
    def properties(self, *package_classes, props=['path', 'version_with_patchlevel', 'type', 'source', 'trees'],
                                               ^
SyntaxError: invalid syntax
************************************************************************
Error downloading tarball of ecl
************************************************************************
```

**Pull request merged**
