### PR TITLE
Speedup of the method to reduce ternary quadratic forms in the class TernaryQF

### LINKED ISSUE #16965: Speedup of the method to reduce ternary quadratic forms in the class TernaryQF
<div id="comment:0"></div>

Speedup of the method to reduce ternary quadratic forms in the class TernaryQF.

Component: **quadratic forms**

Author: **Gustavo Rama**

Branch/Commit: **[u/gdrama/speedup_of_the_method_to_reduce_ternary_quadratic_forms_in_the_class_ternaryqf](https://github.com/sagemath/sagetrac-mirror/tree/u/gdrama/speedup_of_the_method_to_reduce_ternary_quadratic_forms_in_the_class_ternaryqf) @ [`091cbbd`](https://github.com/sagemath/sagetrac-mirror/commit/091cbbdf6eed2c8bccca407addd07ff08e429c17)**

_Issue created by migration from https://trac.sagemath.org/ticket/16965_

### PR DESCRIPTION
**Pull request by tornaria**
PR from #16965 (rebased from https://github.com/sagemath/sagetrac-mirror/commit/091cbbdf6eed2c8bccca407addd07ff08e429c17)

Resolves #16965

Author: Gustavo Rama

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Linter is failing

**Comment by tornaria** [comment]
> Linter is failing

Thanks for catching it. I took this old commit and rebased, run checks etc. but I didn't think about code style. It should be ok now.

**Comment by tornaria** [comment]
I checked the linter locally with `tox -e pycodestyle-minimal` which passes everything except some E401 for `src/sage/misc/persist.pyx` (which is fixed in #36522).

OTOH, `tox -e pycodestyle` gives tons of failures...

**Comment by tobiasdiez** [comment]
> I checked the linter locally with `tox -e pycodestyle-minimal` which passes everything except some E401 for `src/sage/misc/persist.pyx` (which is fixed in #36522).

Thanks! Feel free to set it back to positive review once the linter/tests pass.

> OTOH, `tox -e pycodestyle` gives tons of failures...

Yes, there is still quite a bit work to do 😄

**Pull request merged**
