### PR TITLE
CI: Create doc directory regardless of develop or PR

### PR DESCRIPTION
**Pull request by kwankyu**
Fix a problem seen in: https://doc-develop--sagemath.netlify.app/html/en/index.html

Tested in https://github.com/kwankyu/sage/actions/runs/9966461690. 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by kwankyu** [comment]
This should have been in the blocker PR #38353. At the time, I noticed the problem but didn't scrutinize the root cause, expecting things to be sorted out in the next release. Sigh...

**Comment by kwankyu** [comment]
@vbraun I didn't set this PR as a blocker, wishing not to delay the release. But it would be nice to include this PR with the release of 10.4.

**Review by mkoeppe — APPROVED** [review]
LGTM.

**Comment by mkoeppe** [comment]
Let's please merge it in 10.4. This is a "CI Manager" type fix and does not need another rc.

**Comment by mkoeppe** [comment]
Let's please merge it in 10.4. This is a "CI Manager" type fix and does not need another rc.

**Comment by mkoeppe** [comment]
Let's please merge it in 10.4. This is a "CI Manager" type fix and does not need another rc.

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
