### PR TITLE
build/pkgs: drop obsolete simplegeneric package

### PR DESCRIPTION
**Pull request by orlitzky**
This package was a dependency of ipython, but has not been required for some time:

  https://github.com/ipython/ipython/commit/6d9a28a2

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]
LGTM

**Comment by vbraun** [comment]
merge conflict

**Comment by vbraun** [comment]
merge conflict

**Comment by orlitzky** [comment]
rebased

**Pull request merged**
