### PR TITLE
Added "base_ring" keyword to the matrix constructor

### PR DESCRIPTION
**Pull request by SandwichGouda**
The ``matrix`` constructor only accepts ``ring`` as (positional) argument. 
It is now possible to specify the base ring of matrices using the ``base_ring`` (keyword only) argument.

This solves @mkoeppe's #33380 issue.

The first commit adds some code to the ``MatrixArgs`` class defined in ``src/sage/matrix/constructor.pyx``.
The second commit adds appropriate documentation (with tests and examples) accordingly. 

If the user specifies both arguments (``ring`` and ``base_ring``), everything's fine as long as their values are the same.
(The value of ``base_ring`` is then discarded.)
If the user specifies only one or none of them, no problem. 
If the user specifies both ``ring`` and ``base_ring`` arguments with different values, 
``TypeError: positional argument ring and keyword argument base_ring have different values`` is raised. 

Note : I could have chosen to prioritize ``ring`` over ``base_ring`` if case both arguments are given.
I have chosen not to since this is not the expected usage of these arguments. 
If a user mistakenly specifies both arguments with different values, it is most likely an error, and they better
be informed directly, preventing unnecessary debugging. 

This is my first contribution to sage, I hope it works out !

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mantepse** [comment]
Why not simply rename the parameter (along with deprecation)? Also, what's wrong with ring in the first place?

**Comment by SandwichGouda** [comment]
Nothing's wrong with ``ring``, but @mkoeppe asked to implement this in #33380 so I tackled it :)

I'm not sure I understand what you mean exactly my "renaming the parameter along with deprecation". :O
The idea is to allow the user to use _either_  ``ring`` or ``base_ring``. If I rename the parameter ``ring`` to ``base_ring`` in ``__init__``, users wouldn't be able to use ``ring`` anymore (which would probably be a huge problem, as many existring sage scripts wouldn't work anymore). This is probably not what you meant but then I don't get it.

**Comment by mantepse** [comment]
@mkoeppe, could you please clarify?  I am assuming that this is about unification - class factories should take `base_ring` as argument, not `ring`, right?

**Comment by SandwichGouda** [comment]
I think @mkoeppe is okay with this because he accepted the pull request.
Unfortunately there were errors so I had to push another version (I hope it'll work out this time).

**Comment by mantepse** [comment]
> I think @mkoeppe is okay with this because he accepted the pull request.

I don't understand what you are saying here.  Could you please clarify?

**Comment by SandwichGouda** [comment]
I'm just saying he's okay with my pull request and that he's not againt adding my contribution to the code source.
My PR is currently awaiting approval ("5 workflows awaiting approval") so if you have the possibility to approve it it would be cool

**Comment by mantepse** [comment]
> I'm just saying he's okay with my pull request and that he's not againt adding my contribution to the code source. My PR is currently awaiting approval ("5 workflows awaiting approval") so if you have the possibility to approve it it would be cool

I am actually against inclusion, if there is no explanation for why it is needed.  Moreover, I am quite sure that ad-hoc aliasing of argument names is not a good idea.

**Comment by mkoeppe** [comment]
> @mkoeppe, could you please clarify? I am assuming that this is about unification - class factories should take `base_ring` as argument, not `ring`, right?

@mantepse Exactly. `base_ring` is what users expect from their experience with virtually every other class. Apologies for the overly telegraphic style in #33380. I also didn't specify whether I want the old name `ring` deprecated or not. I would be in favor of doing deprecation.

**Comment by SandwichGouda** [comment]
Closing this since it I had not understood mkoeppe's intentions in his issue. 
I will open another PR soon enough with different and appropriate changes.

**Pull request closed without merging**
