### PR TITLE
fix quadratic_defect

### PR DESCRIPTION
**Pull request by nbruin**
should resolve Fix quadratic_defect #37656 

changes suggested on issue are implemented

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nbruin** [comment]
I've made a pull request with the minimal changes implemented as a start.  It would be a nice `easy` ticket for someone to do further testing and improve test coverage of this routine.
(searching the source, this routine isn't actually used elsewhere in sage, but as the report shows, the routine is apparently used by people who use sage!)

**Comment by mkoeppe** [comment]
@nbruin note https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

**Comment by rburing** [comment]
A doctest can be taken from the original report on Ask SageMath: https://ask.sagemath.org/question/76622/bug-in-quadratic_defect/

**Comment by nbruin** [comment]
question raised in https://groups.google.com/g/sage-devel/c/KfvLDTqf4rk/m/Vlj6D1AtAwAJ : would the method be more at home as a method on an element rather than on the parent (the number field)? The latter is a `pyx` file, so it could be that the author wasn't comfortably writing cython and therefore opted to put it in a "python" file.

**Comment by fchapoton** [comment]
looks good enough to me. Could somebody please confirm, so we can move forward here ?

**Comment by fchapoton** [comment]
@nbruin ? @rburing ? a simple approval would be welcome

**Pull request merged**
