### PR TITLE
using ruff for UP004, UP008, UP028

### PR DESCRIPTION
**Pull request by fchapoton**
this was scripted using

`ruff check --fix --select UP004,UP008,UP028 src/sage`

here is the link to `ruff` documentation: https://docs.astral.sh/ruff/rules/

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Comment by fchapoton** [comment]
not sure that the changes to super will work ; I think I kept them as they were breaking something ; let's see

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by kwankyu** [comment]
Do you plan to add ruff to our linter fleet?

**Comment by fchapoton** [comment]
maybe, but the CI si such a mess for the moment...

**Comment by mkoeppe** [comment]
@fchapoton At least add ruff to the developer documentation please. https://doc.sagemath.org/html/en/developer/tools.html

**Comment by kwankyu** [comment]
> not sure that the changes to super will work ; I think I kept them as they were breaking something ; let's see

I worried that `super()` replacing `super(CLASS, cls)` would work. It seems that `super()` works as expected in a static method.

**Comment by fchapoton** [comment]
bakc to positive after trivial merge

**Pull request merged**
