### PR TITLE
Iterator over the minimal distance k dominating sets

### LINKED ISSUE #35461: Iterator over the distance-k dominating sets
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

[Question 67263 ](https://ask.sagemath.org/question/67263/is-there-any-code-to-list-all-minimal-k-distance-dominating-sets-of-a-simple-graph-g-in-sagemath/) on [ask.sagemath.org](https://ask.sagemath.org/) asks for a method to list all minimal distance-k dominating sets of a graph.

### Proposed Solution

To iterate over the minimal distance k dominating sets, we can modify the working copy of the graph in method `minimal_dominating_sets`, adding edges between vertices at distance at most k.

To iterate over minimum distance k dominating set, we can create a new method `dominating_sets` and use constraints generation to prevent finding twice a minimum dominating set.

### Alternatives Considered

None.

### Additional Information

The default value of parameter `work_on_copy` is `True`, and so by default the input graph is modified. This is a bad choice. We should at least change the default value to `False`.

### PR DESCRIPTION
**Pull request by dcoudert**
Fixes #35461. 

### :books: Description

Add parameter `k` to method `minimal_dominating_sets` to specify the domination distance to consider.

On the way, we 
- Change the default value of parameter `work_on_copy` to `False` to avoid modifying the graph by default
- Fix the behavior when some vertices specified in parameter `to_dominate` are not in the graph

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies
None

### CODE REVIEW

**Comment by tscrim** [comment]
Can we also add a doctest showing the corner case of `k=0`? LGTM otherwise.

**Comment by dcoudert** [comment]
I added a doctest for `k=0`.

**Review by tscrim — APPROVED** [review]
Thank you.

**Comment by dcoudert** [comment]
Thanks for the review.

**Pull request merged**
