### PR TITLE
Preparation for Sphinx 7

### PR DESCRIPTION
**Pull request by kwankyu**
Based on #37129, we adjust sage for Sphinx 7. Mainly,

- (once again) `sage_autodoc` is updated based on the source file of Sphinx 7.

Before the arrival of Sphinx 8, hopefully, we should remove `sage_autodoc`! 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #37129

### CODE REVIEW

**Comment by mkoeppe** [comment]
Can the upgrade https://github.com/sagemath/sage/pull/37129 be merged without the changes here? 
If not, please feel free to just rebase on the current version of #37129, and I can close #37129

**Comment by kwankyu** [comment]
> Can the upgrade #37129 be merged without the changes here? 

Yes. But this PR should also be merged before release, of course.

**Comment by kwankyu** [comment]
I looked over the generated doc. I see no significant changes. Looks good to me.

**Comment by kwankyu** [comment]
To keep our beta a little more stable, this PR is better to be merged together with #37129.

**Comment by kwankyu** [comment]
I found one nontrivial change
```diff
 <section id="id2">
-<h2>Sageで力まかせに計算<a class="headerlink" href="#id2" title="この見出しへのパーマリンク">#</a></h2>
+<h2>Sageで力まかせに計算<a class="headerlink" href="#id2" title="Link to this heading">#</a></h2>
 <p>まず要素値が乱数で与えられる <span class="math notranslate nohighlight">\(500 \times 500\)</span> 行列を作っておく．</p>
```
There may be other small changes perhaps due to Sphinx 7. In my opinion, these can be investigated with later.

**Comment by mkoeppe** [comment]
Let's merge it. I also looked at the diff a bit and at the formatting of some chapters. All good.

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
