### PR TITLE
Make `sage -b` equivalent to `make sagelib-no-deps` regarding parallelism

### PR DESCRIPTION
**Pull request by mkoeppe**
After `export MAKE='make -j16'`:
- the secret command for building the Sage library without dependencies, `make sagelib-no-deps` uses 4 threads for cythonizing and 16 threads for compiling extension modules
- the advertised command for doing the same, `./sage -b` uses 4 threads for cythonizing and 1 thread for compiling extension modules.

This longstanding discrepancy is from the strange handling of `SAGE_NUM_THREADS` when passing from the runtime environment to the build environment, already noticed in https://github.com/sagemath/sage/issues/34328#issuecomment-1418182391

Here we
- avoid this problem by handling all `sage -b...` commands as `sage -i` is already handled: Enter the build environment directly without going through the runtime environment first;
- replace the hardcoded 4 by the same mechanism that obtains the (default) number of threads for compiling extension modules;
- also remove some unnecessary use of internals of the build system.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by grhkm21 — APPROVED** [review]
Looks good, and it works locally from what I can tell

**Comment by mkoeppe** [comment]
Thank you!

**Comment by vbraun** [comment]
merge conflict

**Comment by mkoeppe** [comment]
Trivial rebase.

**Comment by grhkm21** [comment]
(lint CI fixed in #37672)

**Pull request merged**
