### PR TITLE
`CODE_OF_CONDUCT.md`: Add examples of problematic conduct, describe sage-abuse committee's procedures and sanctions

### PR DESCRIPTION
**Pull request by mkoeppe**
We add examples to the Code of Conduct that explain that even well-intended conduct can be problematic.

Related sage-devel discussions:
- https://groups.google.com/g/sage-devel/c/rDM3WDHnJkM/m/Z5Bqxyv1AQAJ (Policy for disputed PRs: discussion) (2023-11
- https://groups.google.com/g/sage-devel/c/486wXmJu2pI (Revisions of the Reviewing Code and Code of Conduct) (2023-12)
- https://groups.google.com/g/sage-devel/c/XON6NTJa33o (Disputed Pull Requests / Role Sage-Abuse and the Code of Conduct) (2024-01)

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by williamstein** [comment]
I think it would be useful to have a proposal about consequences for violating the code of conduct, and how to decide whether or not something is a violation.  For deciding, sage-abuse could have an internal vote.  For consequences, they could include deleting the relevant messages, lowering or removal of privileges, etc.  This was never formalized.

**Comment by mkoeppe** [comment]
I agree that this would be very useful. As a first draft, we could just add a list of types of sanctions that have been used in the past 10 years, if you are able to provide this.

Going forward, there probably also should be a description of an appointment procedure for the sage-abuse committee.

**Comment by mkoeppe** [comment]
@roed314 Examples of CoC with clear enforcement protocols: 
- https://numfocus.org/code-of-conduct, https://numfocus.org/code-of-conduct/response-and-enforcement-events-meetups, 
- https://numpy.org/code-of-conduct/,
- https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html

**Comment by jhpalmieri** [comment]
I don't think that proposed lines 72-86 in CODE_OF_CONDUCT.md belong there. They are not useful for the general Sage  community, only for members of the Sage abuse committee. They read like a critique of the functioning of that committee, perhaps deserved, but they don't belong in this document.

**Comment by mkoeppe** [comment]
Have you looked at the link https://numfocus.org/code-of-conduct/response-and-enforcement-events-meetups or the other links I shared? Spelling out such details is very much part of the best practices for CoC enforcement.

**Comment by jhpalmieri** [comment]
This is a "code of conduct," not a "code of conduct response and enforcement manual." The two have different purposes and different audiences. Anyway, I did take a quick look, and my impression is that if there is such content, it is much less than half of the material on the possible responses. In my opinion the current draft puts too much emphasis on the analysis of the responses (with a critical tone, in my opinion) rather than the responses themselves. I don't see language with the same tone in the numfocus document that you linked. I may very well be missing it, but that's because the bulk of that document doesn't have that tone or that content or that intent. I think that language like the section on "Response and Potential Consequences" in https://numfocus.org/code-of-conduct would be more suitable for this document. 

(By the way, if we just wanted to, for example, adopt the numfocus response and enforcement manual, I would have no objections. Maybe it needs modification to address online interactions, since it is focused on in-person events.)

In any case, I think that these proposed changes need buy-in from someone like William or David R, since they establish policies and a tone related to the Sage abuse committee.

**Comment by mkoeppe** [comment]
> In any case, I think that these proposed changes need buy-in [...]

Of course! All of such changes need writing and editing, discussion, ratification, etc. and obviously cannot be put in place by just the normal PR review process.

**Comment by mkoeppe** [comment]
> This is a "code of conduct," not a "code of conduct response and enforcement manual." The two have different purposes and different audiences.

Making them separate documents can make sense, but not because one should be public and the other should not.

**Comment by mkoeppe** [comment]
> if we just wanted to, for example, adopt the numfocus response and enforcement manual, I would have no objections. 
> Maybe it needs modification to address online interactions, since it is focused on in-person events.

Yes, the NumFOCUS one does have the focus on in-person interactions. I shared other links too, though. The SciPy one leads you to https://docs.scipy.org/doc/scipy/dev/conduct/report_handling_manual.html

The process of "adopting" a prefab manual will certainly have to involve more than just to declare that it is now in force. It will require reflection on how what is described relates to past practices.

**Comment by mkoeppe** [comment]
Documenting the types of sanctions that the committee has used in the past (as suggested above https://github.com/sagemath/sage/pull/36844#issuecomment-1872605554 in response to William's comment) serves the purpose of making it known to the community that enforcement happens and is not just a "theoretical possibility". It can also document the continuity of the committee's mandate.

Including an analysis of what specific *possible* sanctions do -- and don't do -- as part of the resolution process may be helpful for future enforcement.

Right now in this early draft, these two things (past sanctions, possible sanctions) happen in the same place. There's no need for this. I'll rewrite it.

**Comment by jhpalmieri** [comment]
I have a "competing" proposal for changes to the code of conduct, along with a new document about how to handle violations, based heavily on SciPy's similar document. Should I open a separate PR or push changes here (in place of yours, not on top of them)?

**Comment by mkoeppe** [comment]
Either way is fine with me

**Comment by jhpalmieri** [comment]
See #37501.

**Comment by mkoeppe** [comment]
Closing in favor of #37501.

@jhpalmieri I still think including examples of conduct that is intended to be helpful but can be offensive to others would be valuable

**Pull request closed without merging**
