### PR TITLE
Properly check dimension in curve constructor

### PR DESCRIPTION
**Pull request by kwankyu**
fix a bug reported in https://groups.google.com/g/sage-devel/c/qiUQEnRGGag

Along the way, we improve computation of dimension of ideals of multi-variate polynomial rings for principal ideals (this is needed to soothe elliptic curve code that complains of slow dimension computation).

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by nbruin** [comment]
Thanks for that correction!

A question: did the doctest you fixed already find this bug?

I'm wondering if the design is flawed: currently, we have `Curve_generic -> AffineCurve->AffineCurve_field`. The problem arises on `Curve_generic`: there the constructor just quietly does whatever the parent constructor does and yet `dimension` is overridden to a hardcoded `1`. Hence, `Curve_generic` seems flawed to me: it silently accepts non-curves and then overrides `dimension`. That sounds like a flawed design to me. I guess the problem is that `Curve_generic` doesn't have the means to check the validity of its input, but then it should perhaps be an abstract class (so that it cannot be instantiated) and/or it shouldn't override `dimension`: if we want to support curves over rings, then I'm not so sure they should be of dimension 1. Relative dimension 1 surely, but if you have a curve over `Spec(QQ[t])` then the resulting scheme has (absolute) dimension 2.

**Comment by kwankyu** [comment]
> Thanks for that correction!
> 
> A question: did the doctest you fixed already find this bug?

Yes. But I will add a new test (from the report in sage-devel).

> I'm wondering if the design is flawed: currently, we have `Curve_generic -> AffineCurve->AffineCurve_field`. The problem arises on `Curve_generic`: there the constructor just quietly does whatever the parent constructor does and yet `dimension` is overridden to a hardcoded `1`. Hence, `Curve_generic` seems flawed to me: it silently accepts non-curves and then overrides `dimension`. That sounds like a flawed design to me. I guess the problem is that `Curve_generic` doesn't have the means to check the validity of its input, but then it should perhaps be an abstract class (so that it cannot be instantiated) and/or it shouldn't override `dimension`.

 `Curve_generic` is an "abstract class" in the sense that always its subclass is instantiated. As you say, the dimension check should happen in a subclass. `Curve_generic` does not override `dimension` since there is no `dimension` in the subclass. 

This prompts me a better way to fix the bug. Thanks. I will work more.

> if we want to support curves over rings, then I'm not so sure they should be of dimension 1. Relative dimension 1 surely, but if you have a curve over `Spec(QQ[t])` then the resulting scheme has (absolute) dimension 2.

For curves over rings, surely relative dimension should be used. Now we are dealing with curves over fields. So no difference.

**Comment by nbruin** [comment]
> `Curve_generic` does not override `dimension` since there is no `dimension` in the subclass.

It does: https://github.com/kwankyu/sage/blob/b4ec7f65df42e5f7e1df24e468da136511c817fd/src/sage/schemes/curves/curve.py#L119

**Comment by kwankyu** [comment]
> > `Curve_generic` does not override `dimension` since there is no `dimension` in the subclass.
> 
> or do you mean that on `AlgebraicScheme_subscheme` there is no method `dimension` so `Curve_generic` doesn't override a method but instead defines it for the first time? 

Yes.

> It's there, it's just raising "NotImplemented". So ... indeed not a very useful method, but it does make me think that Curve_generic should perhaps also no override it 

That is not relevant to our problem.

Anyway, removing `dimension` method from `Curve_generic` would fix the bug. But this is not to correct a design flaw. Objects of `Curve_generic` are curves, and curves have dimension 1 by definition. So there is nothing wrong with the method. It feels wrong to remove `dimension` just to fix the bug. 

> and leave it to subclasses that can actually test their input.

As a "better way", I thought of adding `dimension` method to the subclasses of `Curve_generic` so that `dimension` of `Curve_generic` is overridden. But this does not seem to be actually a better way, because if we use `dimension` in `__init__` (note that they are defined in the same class), we are making a circular dependency, at least conceptually.

Another way might be to reverse the order of superclasses in the class definition:
```sage
class AffineCurve_field(AlgebraicScheme_subscheme_affine_field, AffineCurve)
```
instead of
```sage
class AffineCurve_field(AffineCurve, AlgebraicScheme_subscheme_affine_field):  
```
But the original order of superclasses seems right: `AffineCurve` seems to be more concrete than `AlgebraicScheme_subscheme_affine_field`. I didn't try this method, but I guess there will be lots of unexpected doctest failures.

The current method to fix the bug seems to be the simplest.

**Comment by kwankyu** [comment]
This seems to be the case where `super()` was introduced for. A little bit more intuitive now.

**Comment by kwankyu** [comment]
anything else?

**Pull request merged**
