### PR TITLE
Make sure #26968 is not unfixed after #35707

### PR DESCRIPTION
**Pull request by tornaria**
Calling initialize-runtime-globals will run set-pathnames and be subject
to the issue described in #26968.

Thus the workaround introduced in #35195 has to be done before anything
that may call set-pathnames (e.g. initialize-runtime-globals).

### :hourglass: Dependencies

- #35707 (included).

### CODE REVIEW

**Comment by tornaria** [comment]
@vbraun @antonio-rojas please make sure this is included when #35707 is merged.

**Comment by antonio-rojas** [comment]
> @vbraun @antonio-rojas please make sure this is included when #35707 is merged.

wouldn't it make more sense to make a PR on #35707's branch?

**Comment by tornaria** [comment]
> > @vbraun @antonio-rojas please make sure this is included when #35707 is merged.
> 
> wouldn't it make more sense to make a PR on #35707's branch?

Indeed, but I still find this a bit unnatural. a PR on #35707 branch is associated to your fork of sage, but it's not associated to sage main repo. E.g. workflows in my PR to your repo won't run (see https://github.com/antonio-rojas/sage/pull/2).

Also, there's no notice in #35707 about my PR to your PR...

As an alternative, you can always fetch my branch and replace yours in #35707 making this PR superfluous (and I think you  can close this PR).

**Comment by tornaria** [comment]
Closed as this is now included in #35707 .

**Pull request closed without merging**
