### PR TITLE
Maxima from the OS

### PR DESCRIPTION
**Pull request by dimpase**
This will take care of #32867 (the rebased branch is from there)

### CODE REVIEW

**Comment by antonio-rojas** [comment]
As mentioned in https://github.com/sagemath/sage/issues/32867#issuecomment-1418153571 we should deal with the 5.46 update first. The release is over a year old and many distros are shipping it by now, this will make a few tests fail in those

**Comment by dimpase** [comment]
On Gentoo with system maxima 5.46.0 I get few test errors. One of them is "noise" from 5.46 apparently converting floats in integrals to rationals:
```
File "src/sage/symbolic/integration/integral.py", line 750, in sage.symbolic.integration.integral.integrate
Failed example:
    res = integral(f,x,0.0001414, 1.); res
Expected:
    2*y*arctan(1.0/y) - 2*y*arctan(0.0001414/y) + 1.0*log(1.0*y^2 + 1.0) - 0.0001414*log(1.0*y^2 + 1.9993959999999997e-08) - 1.9997172
Got:
    -2*y*arctan(1/196559360927*sqrt(196559360927)*sqrt(3930)/y) + 2*y*arctan(1/y) - 1/196559360927*sqrt(196559360927)*sqrt(3930)*log(y^2 + 3930/196559360927) + 2/196559360927*sqrt(196559360927)*sqrt(3930) + log(y^2 + 1) - 2
```
similarly, one can't use floats in limit computations:
```
File "src/sage/calculus/calculus.py", line 1190, in sage.calculus.calculus.limit
Failed example:
    f.limit(x=1.2)
Expected:
    2.06961575467...
Got:
    und 
```
But it's actually a regression of sorts, as 
```
sage: f.limit(x=12/10)
und
```
On the other hand, some limits done better than before:
```
File "src/sage/calculus/calculus.py", line 1219, in sage.calculus.calculus.limit
Failed example:
    limit(x^a,x=0)
Expected:
    Traceback (most recent call last):
    ...
    ValueError: Computation failed since Maxima requested additional
    constraints; using the 'assume' command before evaluation *may* help
    (example of legal syntax is 'assume(a>0)', see `assume?` for
     more details)
    Is a an integer?
Got:
    0

File "src/sage/calculus/calculus.py", line 1228, in sage.calculus.calculus.limit
Failed example:
    limit(x^a, x=0)
Expected:
    Traceback (most recent call last):
    ...
    ValueError: Computation failed since Maxima requested additional
    constraints; using the 'assume' command before evaluation *may* help
    (example of legal syntax is 'assume(a>0)', see `assume?` for
     more details)
    Is a an even number?
Got:
    0
```
some output formats got better:
```
**********************************************************************
File "src/sage/calculus/calculus.py", line 2255, in sage.calculus.calculus.symbolic_expression_from_maxima_string
Failed example:
    solve([x != 5], x)
Expected:
    [[x - 5 != 0]]
Got:
    [[x < 5], [5 < x]]
**********************************************************************
File "src/sage/calculus/calculus.py", line 2257, in sage.calculus.calculus.symbolic_expression_from_maxima_string
Failed example:
    solve([2*x==3, x != 5], x)
Expected:
    [[x == (3/2), (-7/2) != 0]]
Got:
    [[x == (3/2)]]
```
some outputs are equivalent, but swapped around:
```
File "src/sage/symbolic/relation.py", line 1790, in sage.symbolic.relation.solve_ineq_fourier
Failed example:
    solve_ineq_fourier([x+y<9,x-y>4],[y,x])
Expected:
    [[y < min(x - 4, -x + 9)]]
Got:
    [[y < min(-x + 9, x - 4)]]
```

as above, but in another file:
```
sage -t --warn-long 66.5 --random-seed=238159399368936496605278695210462135284 src/sage/interfaces/maxima_lib.py
**********************************************************************
File "src/sage/interfaces/maxima_lib.py", line 937, in sage.interfaces.maxima_lib.MaximaLib.sr_limit
Failed example:
    limit(f,x = 1.2)
Expected:
    2.06961575467...
Got:
    und
**********************************************************************
File "src/sage/interfaces/maxima_lib.py", line 950, in sage.interfaces.maxima_lib.MaximaLib.sr_limit
Failed example:
    limit(x^a,x=0)
Expected:
    Traceback (most recent call last):
    ...
    ValueError: Computation failed ...
    Is a an integer?
Got:
    0
```

A format change:
```
File "src/sage/functions/exp_integral.py", line 604, in sage.functions.exp_integral.Function_log_integral_offset
Failed example:
    Li(x).integrate(x,2.0,4.5)
Expected:
    -2.5*log_integral(2) + 5.799321147411334
Got:
    -Ei(2*log(9/2)) + Ei(2*log(2)) + 9/2*log_integral(9/2) - 4.5*log_integral(2)
```
(can just test the numerical value)

**Comment by dimpase** [comment]
Should we just merge this, and would on updating Sage's maxima to 5.46.0 ?

**Comment by dimpase** [comment]
```
File "src/sage/calculus/calculus.py", line 1190, in sage.calculus.calculus.limit
Failed example:
    f.limit(x=1.2)
Expected:
    2.06961575467...
Got:
    und 
```
is a regression in Sage interface to maxima - computing this limit at maxima console works just fine.

**Comment by dimpase** [comment]
@nbruin - do you have any idea why  with maxima 5.46.0 the following breaks
```
sage: f(x)=(1+1/x)^x
sage: f.limit(x=6/5)
L= [<ECL: ((MEXPT) ((MPLUS) ((MEXPT) |$_SAGE_VAR_x| -1) 1) |$_SAGE_VAR_x|)>, <ECL: |$_SAGE_VAR_x|>, <ECL: ((RAT) 6 5)>]
   eval result:  $UND 

x |--> und
```
(this is with prints() added:
```
--- a/src/sage/interfaces/maxima_lib.py
+++ b/src/sage/interfaces/maxima_lib.py
@@ -993,8 +993,12 @@ class MaximaLib(MaximaAbstract):
                 L.append(max_plus)
             elif dir == "minus":
                 L.append(max_minus)
+            print("L=", L)
+            eva=maxima_eval(([max_limit], L))
+            print("   eval result: ", eva,"\n")
             return max_to_sr(maxima_eval(([max_limit], L)))
         except RuntimeError as error:
+            print("oops, error:", str(error))
             s = str(error)
             if "Is" in s: # Maxima asked for a condition
                 self._missing_assumption(s)
```

for integer values the limit is computed just fine
```
sage: f.limit(x=6)
L= [<ECL: ((MEXPT) ((MPLUS) ((MEXPT) |$_SAGE_VAR_x| -1) 1) |$_SAGE_VAR_x|)>, <ECL: |$_SAGE_VAR_x|>, <ECL: 6>]
   eval result:  ((RAT SIMP) 117649 46656) 

x |--> 117649/46656
```

as well as in maxima console it's all just fine:
```
$ maxima
;;; Loading #P"/usr/lib64/ecl-21.2.1/sb-bsd-sockets.fas"
;;; Loading #P"/usr/lib64/ecl-21.2.1/sockets.fas"
Maxima 5.46.0 https://maxima.sourceforge.io
using Lisp ECL 21.2.1
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) f:(1+1/x)^x
;
                                    1     x
(%o1)                              (- + 1)
                                    x
(%i2) limit(f,x,6/5);
                                   6 log(11/6)
                                   -----------
                                        5
(%o2)                            %e
```

**Comment by nbruin** [comment]
By the looks of it, the expression that sage passes to maxima is the same as what should ressult from entering it directly into maxima. Hence, any differences probably arise from the different options that maxima_calculus sets. Hence, in order to identify the regression in maxima, you should run the example with the environment options that maxima_calculus uses. It's very conceivable that maxima development introduced a regression in the behaviour with those options activated, since their testing mainly takes place with the standard options in force.

**Comment by dimpase** [comment]
ah, right, it's that kind of thing again.
```
$ maxima
;;; Loading #P"/usr/lib64/ecl-21.2.1/sb-bsd-sockets.fas"
;;; Loading #P"/usr/lib64/ecl-21.2.1/sockets.fas"
Maxima 5.46.0 https://maxima.sourceforge.io
using Lisp ECL 21.2.1
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) f:(1+1/x)^x;
                                    1     x
(%o1)                              (- + 1)
                                    x
(%i2) domain: complex;
(%o2)                               complex
(%i3) limit(f,x,6/5);
(%o3)                                 und
(%i4) limit(f,x,4/3);
                                   4 log(7/4)
                                   ----------
                                       3
(%o4)                            %e
(%i8) domain: real;
(%o8)                                real
(%i9) limit(f,x,6/5);
                                   6 log(11/6)
                                   -----------
                                        5
(%o9)                            %e

```

Reported upstream : https://sourceforge.net/p/maxima/bugs/4138/

**Comment by dimpase** [comment]
@thierry-FreeBSD - is https://github.com/sagemath/sage/pull/35615/commits/ed729a925a6ce4c4da3d4b09e3271092aa69ac50 OK?

**Comment by mkoeppe** [comment]
Is no version check needed at all? 
Debian 10 (buster) has 5.42.1, Ubuntu trusty has 5.32.1
https://repology.org/project/maxima/versions

**Comment by thierry-FreeBSD** [comment]
> @thierry-FreeBSD - is [ed729a9](https://github.com/sagemath/sage/commit/ed729a925a6ce4c4da3d4b09e3271092aa69ac50) OK?

Yes it is!

**Comment by thierry-FreeBSD** [comment]
> Is no version check needed at all? Debian 10 (buster) has 5.42.1, Ubuntu trusty has 5.32.1 https://repology.org/project/maxima/versions

ATM FreeBSD has 5.46.0. It is usually kept up-to-date.

**Comment by dimpase** [comment]
let's review this as a part of #35619 and close after it's merged.

**Comment by dimpase** [comment]
this will be completed in #35619

**Pull request closed without merging**
