### PR TITLE
Clear up left right confusion in `ore_polynomial_element.pyx`

### LINKED ISSUE #35531: Confusions in left and right division for Ore polynomials
```sage
sage: k.<a> = GF(5^3)
....: Frob = k.frobenius_endomorphism()
....: S = OrePolynomialRing(k, Frob, 'x')
....: S
Ore Polynomial Ring in x over Finite Field in a of size 5^3 twisted by a |--> a^5
sage: x = S.gen()
sage: f = x*a + a*x^2+a*x^4
sage: g = (a^7+a)*x^2*(a+1)+ (a^3+1)*x + 1
sage: f
a*x^4 + a*x^2 + (2*a^2 + 4*a + 4)*x
sage: g
(3*a^2 + 2*a + 4)*x^2 + (2*a + 3)*x + 1
sage: q = f // g
sage: r = f % g
sage: f == g*q+r
False
sage: f == q*g+r
True
```

According to the documentation (1)
```
The operators // and % give respectively the quotient and the remainder of the right euclidean division
```

But the definition of the right euclidean division is (2)

Screen Shot 2023-04-18 at 1 34 25 PM

Apparently the two docs are inconsistent. What is the correct definition of the right euclidean division? @xcaruso 

According to Ore himself, the right-hand division of $F$ by $G$ is $F=QG+R$. So (2) is wrong.

### PR DESCRIPTION
**Pull request by kwankyu**
### :books: Description

Fix #35531. While we are at it, I made other minor edits.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by xcaruso — APPROVED** [review]
There was a lot of misprints in this documentation. Thanks for catching all of these!

**Comment by xcaruso** [comment]
However, the patchbot (should we continue to use this term?) reports some failures. Should we fix them before giving a positive review?

**Comment by kwankyu** [comment]
No. They are not related with this PR. The lint check is being dealt with in other PR, and the codecov/project is plaguing all PRs.

Thanks for review!

**Comment by vbraun** [comment]
merge conflict

**Comment by kwankyu** [comment]
Resolved merge conflict

**Pull request merged**
