### PR TITLE
CI: Fix the multi-stage build in ci-linux.yml, fix conda/centos/archlinux system packages

### LINKED ISSUE #34786: Fix distro information for _python* on fedora/centos
<div id="comment:0"></div>

- centos-7 has no usable python packages
- centos-stream-8 has python39-devel and python3.11-devel, but not python3.9-devel
- centos-stream-9 has python{3.9,3.11}-devel, but not python39-devel
- fedora-32 has python3-devel (3.8) but no versioned -devel packages
- fedora-33 has python3-devel (3.9)
- fedora-34 has python3-devel (3.9)
- fedora-36 has python3-devel (3.10), but not python310-devel nor python3.10-devel
- fedora-38 has python{3.10,3.12}-devel, but not python310-devel 

Also fedora-33-maximal: Error: Unable to find a match: gh

Component: **porting**

_Issue created by migration from https://trac.sagemath.org/ticket/34786_

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes breakage from #36338 seen in https://github.com/sagemath/sage/actions/runs/6332061118/job/17206153694:

The 2nd stage (`...-with-targets`) does not find the container from the 1st stage (`...-with-targets-pre`) because they are keyed to the commit sha. Fixed here by keying it to the sha before merging the CI fixes.

Also fixing the following failures:
- `conda-forge-minimal` (as seen in https://github.com/sagemath/sage/actions/runs/6207962004/job/16858998561); failed because the python3 depcheck packages were missing. Fixed now - check with `tox -e docker-conda-forge-minimal -- config.status`
- `centos-stream-9-python3.9-minimal` (https://github.com/sagemath/sage/actions/runs/6207962004/job/16858997494), `almalinux-9-python3.11-minimal` (https://github.com/sagemath/sage/actions/runs/6207962004/job/16858997663) and `-standard`; fixes #34786 
- `archlinux-standard` - libgiac was missing in at least one run

Also adding a few more uses of GH Action output groups for convenience.

Tests running at https://github.com/mkoeppe/sage/actions/workflows/ci-linux.yml

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dimpase — APPROVED** [review]

**Comment by mkoeppe** [comment]
Thanks!

**Comment by tobiasdiez** [comment]
This cannot be marked yet as positive review since it has an unreviewed dependency (which in my opinion still needs work).

**Comment by mkoeppe** [comment]
Nope, also the dependency has a positive review.

**Comment by mkoeppe** [comment]
Rebased away from #36348, for natural velocity

**Comment by tobiasdiez** [comment]
Thanks!

**Pull request merged**
