### PR TITLE
checking that the system maxima has working help

### LINKED ISSUE #36028: archlinux-latest-standard: System maxima does not work
Building the documentation fails with this:

https://github.com/sagemath/sage/actions/runs/5706565894/job/15465342057#step:8:2303
```
  [sagemath_doc_html-none]   ;;; Warning: Maxima is unable to set up the help system.
  [sagemath_doc_html-none]   (Details: CL-INFO::LOAD-PRIMARY-INDEX: Filesystem error with pathname #P"/usr/share/info/maxima-index.lisp".
  [sagemath_doc_html-none]   Either
  [sagemath_doc_html-none]    1) the file does not exist, or
  [sagemath_doc_html-none]    2) we are not allowed to access the file, or
  [sagemath_doc_html-none]    3) the pathname points to a broken symbolic link.)
  [sagemath_doc_html-none]   
```

@dimpase @antonio-rojas @orlitzky

### PR DESCRIPTION
**Pull request by dimpase**
This is needed for e.g. building Sage docs, cf
e.g. Sage's #36028. Some distos mix this up.

Fixes #36028

### CODE REVIEW

**Comment by dimpase** [comment]
the puzzling pattern checked there is due to broken/no Maxima's help giving
```
$ echo ? ? | maxima 2>&1 | grep Couldn
(Details: CL-INFO::LOAD-PRIMARY-INDEX: Couldn't load
```

**Comment by antonio-rojas** [comment]
Even though this makes sense, this should be fixed at the docker CI level first as noted in https://github.com/sagemath/sage/issues/36028#issuecomment-1663366136. Otherwise building on Arch with system maxima will no longer be tested.

**Comment by dimpase** [comment]
> Even though this makes sense, this should be fixed at the docker CI level first as noted in [#36028 (comment)](https://github.com/sagemath/sage/issues/36028#issuecomment-1663366136). Otherwise building on Arch with system maxima will no longer be tested.

I don't see where the image is installed in CI. There are a number of places `archlinux` is mentioned, but no idea where
one can sneak in commands to modify the running image (to install Maxima with help)

**Comment by mkoeppe** [comment]
> I don't see where the image is installed in CI. There are a number of places `archlinux` is mentioned, but no idea where
> one can sneak in commands to modify the running image (to install Maxima with help)

`build/bin/write-dockerfile.sh`

**Comment by dimpase** [comment]
> > I don't see where the image is installed in CI. There are a number of places `archlinux` is mentioned, but no idea where
> > one can sneak in commands to modify the running image (to install Maxima with help)
> 
> `build/bin/write-dockerfile.sh`

can we handle this in another, archlinux-specific, PR?

**Comment by dimpase** [comment]
> > I don't see where the image is installed in CI. There are a number of places `archlinux` is mentioned, but no idea where
> > one can sneak in commands to modify the running image (to install Maxima with help)
> 
> `build/bin/write-dockerfile.sh`

Would 
```diff
--- a/build/bin/write-dockerfile.sh
+++ b/build/bin/write-dockerfile.sh
@@ -104,6 +104,7 @@ EOF
         UPDATE="pacman -Sy &&"
         EXISTS="pacman -Si"
         INSTALL="pacman -Su --noconfirm"
+       RUN="RUN sed -i '/^NoExtract/d' /etc/pacman.conf"
         ;;
     nix*)
         # https://hub.docker.com/r/nixos/nix
```
do the trick, or I misunderstand what `RUN` does?

**Comment by dimpase** [comment]
as far as I can see, test on arch fails due to missing container:
```
Step 1/44 : ARG BASE_IMAGE
Step 2/44 : FROM ${BASE_IMAGE} as with-system-packages
manifest unknown
Error response from daemon: No such container: ghcr.io/sagemath/sage/sage-archlinux-standard-sitepackages-with-targets:10.2.beta5-6-g6bb5776cad-failed
Pushing ghcr.io/sagemath/sage/sage-archlinux-standard-sitepackages-with-targets:10.2.beta5-6-g6bb5776cad-failed
The push refers to repository [ghcr.io/sagemath/sage/sage-archlinux-standard-sitepackages-with-targets]
```

**Comment by mkoeppe** [comment]
> I misunderstand what `RUN` does?

I've fixed it for you

**Comment by dimpase** [comment]
I don't understand what it does. Does it create a file? A script to run?

**Comment by mkoeppe** [comment]
The script writes a Dockerfile to stdout

**Review by mkoeppe — APPROVED** [review]

**Comment by mkoeppe** [comment]
> why it's not just using `echo` to dump these `RUN ...` lines?

That would be equivalent, of course, but this file uses HERE docs for various multi-line snippets, and so it also does single-line snippets in the same way for consistency.

**Pull request merged**
