### PR TITLE
`gcc`, `gfortran`: Update to 13.2.0; remove `debian-buster-gcc_spkg` from CI

### LINKED ISSUE #38006: gfortran doesn't build on latest OS X + Xcode + Homebrew
### Environment

```markdown
- **OS**: OS X 14.4.1
- **Sage Version**: 10.4.beta6
```

### Steps To Reproduce

`./configure --with-system-gfortran=no` followed by `make`.

### Config log

[config.log](https://github.com/sagemath/sage/files/15325568/config.log)

### Package logs

[gfortran-12.2.0.log](https://github.com/sagemath/sage/files/15325571/gfortran-12.2.0.log)

### Additional Information

With this plus #38002, it is now difficult to build Sage on OS X: any version of Sage earlier than 10.4.beta6 refuses to use the system's `gfortran` because it is too new, so it tries to build its own, which fails as noted here. With 10.4.beta6, the problem at #38002 arises, causing the build to fail.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by mkoeppe**
- Fixes #38006 @jhpalmieri 
- `gcc` does not build on `debian-buster` (which we supported via `-gcc_spkg` because it is LTS until 2024-06), so we drop this platform now; see #32074.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

- Depends on #37726 (merged here to resolve merge conflict)

### CODE REVIEW

**Comment by mkoeppe** [comment]
Testing (ci-37203-37834-37919-37931-38008-38009) at https://github.com/mkoeppe/sage/actions/runs/9105145243 (Linux), https://github.com/mkoeppe/sage/actions/runs/9105145246 (macOS)

**Comment by mkoeppe** [comment]
gcc build fails on [standard-pre / linux (debian-buster-gcc_spkg, standard)](https://github.com/mkoeppe/sage/actions/runs/9105145243/job/25030236521#logs)

**Comment by jhpalmieri** [comment]
I'm confused: which parts of this PR remove debian-buster-gcc_spkg from the CI?

**Comment by mkoeppe** [comment]
... the part that I forgot to commit ...

**Comment by mkoeppe** [comment]
Here it is.

**Comment by jhpalmieri** [comment]
On an Apple Silicon machine, latest OS and Xcode and homebrew, `gfortran` builds and works fine. Using `./configure --with-system-gcc=no`, several packages fail to build: `lcalc`, `givaro`, `ppl`, with errors:
```
[spkg-build] Undefined symbols for architecture arm64:
[spkg-build]   "___emutls_v.avma", referenced from:
[spkg-build]       _rdiviiz in libLfunction.1.0.1.dylib-master.o
[spkg-build]       _cxcompotor.constprop.0 in libLfunction.1.0.1.dylib-master.o
[spkg-build]       _gtofp.constprop.0 in libLfunction.1.0.1.dylib-master.o
[spkg-build]       __Z6data_EPcS_S_S_S_iPd in libLfunction.1.0.1.dylib-master.o
[spkg-build]   "___emutls_v.pari_mainstack", referenced from:
[spkg-build]       _cxcompotor.constprop.0 in libLfunction.1.0.1.dylib-master.o
[spkg-build]       _gtofp.constprop.0 in libLfunction.1.0.1.dylib-master.o
[spkg-build]       __Z6data_EPcS_S_S_S_iPd in libLfunction.1.0.1.dylib-master.o
[spkg-build] ld: symbol(s) not found for architecture arm64
```
and
```
[spkg-install] Undefined symbols for architecture arm64:
[spkg-install]   "__ZlsRSoPK12__mpz_struct", referenced from:
[spkg-install]       __ZNK6Givaro7Integer5printERSo in libgivaro.9.dylib-master.o
[spkg-install]       __ZN6GivarolsERSoRKNS_7IntegerE in libgivaro.9.dylib-master.o
[spkg-install]   "__ZrsRSiP12__mpz_struct", referenced from:
[spkg-install]       __ZN6GivarorsERSiRNS_7IntegerE in libgivaro.9.dylib-master.o
[spkg-install] ld: symbol(s) not found for architecture arm64
```
and
```
[spkg-install] Undefined symbols for architecture arm64:
[spkg-install]   "__ZlsRSoPK12__mpq_struct", referenced from:
[spkg-install]       __ZN12_GLOBAL__N_116write_polyhedronERSoRKN23Parma_Polyhedra_Library12C_PolyhedronENS_14RepresentationE in ppl_lcdd.o
[spkg-install]   "__ZlsRSoPK12__mpz_struct", referenced from:
[spkg-install]       __ZN12_GLOBAL__N_113guarded_writeI10__gmp_exprIA1_12__mpz_structS3_EEEvRSoRKT_ in ppl_lcdd.o
[spkg-install]   "__ZrsRSiP12__mpq_struct", referenced from:
[spkg-install]       __ZN12_GLOBAL__N_117read_coefficientsERSiNS_11Number_TypeERSt6vectorI10__gmp_exprIA1_12__mpz_structS5_ESaIS6_EERS6_ in ppl_lcdd.o
[spkg-install]   "__ZrsRSiP12__mpz_struct", referenced from:
[spkg-install]       __ZN12_GLOBAL__N_117read_coefficientsERSiNS_11Number_TypeERSt6vectorI10__gmp_exprIA1_12__mpz_structS5_ESaIS6_EERS6_ in ppl_lcdd.o
[spkg-install] ld: symbol(s) not found for architecture arm64
```
respectively.

**Comment by mkoeppe** [comment]
I don't think we have supported building with gcc from SPKG on macOS

**Comment by jhpalmieri** [comment]
> I don't think we have supported building with gcc from SPKG on macOS

Okay, then I won't worry about it. I realize that I can't check if the problems are new because the whole point is that I can't build the old gcc spkg.

**Comment by culler** [comment]
I was able to build gfortran-13.2.0 from this PR with no errors.  (There were around 40,000 warnings, but I think that is normal.)

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
