### PR TITLE
Fix typos and outdated links in `igraph_graph()` docs

### PR DESCRIPTION
**Pull request by szhorvat**
This PR simply fixes typos and updates broken links in the documentation here: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html#sage.graphs.generic_graph.GenericGraph.igraph_graph

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by szhorvat** [comment]
There's a piece of text `(0, \ldots, n-1)` which should be rendered in math mode instead of as code. I am not sure how to do this, help would be appreciated.

**Comment by mkoeppe** [comment]
use single backquotes for math

**Comment by szhorvat** [comment]
I checked the documentation preview and I believe this is now ready to go.

**Review by mkoeppe — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
