### PR TITLE
Fix coercion problem with Algebraic Real Field

### LINKED ISSUE #12745: Coercion problem with Algebraic Real Field
<div id="comment:0"></div>

The following algebraic number is clearly real, but the AA class seems to have trouble digesting it:

```
----------------------------------------------------------------------
| Sage Version 5.0.beta10, Release Date: 2012-03-23                  |
| Type notebook() for the GUI, and license() for information.        |
----------------------------------------------------------------------
**********************************************************************
*                                                                    *
* Warning: this is a prerelease version, and it may be unstable.     *
*                                                                    *
**********************************************************************
sage: x = exp(2*I*pi/7) + exp(-2*I*pi/7)
sage: QQbar(x) in AA
True
sage: AA(x)
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (1327, 0))

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (4541, 0))

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (1327, 0))

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

/storage/masiao/sage-5.0.beta10/devel/sage-main/<ipython console> in <module>()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/parent.so in sage.structure.parent.Parent.__call__ (sage/structure/parent.c:7940)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/coerce_maps.so in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (sage/structure/coerce_maps.c:3344)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/coerce_maps.so in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (sage/structure/coerce_maps.c:3247)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/rings/qqbar.pyc in _element_constructor_(self, x)
    689                 raise ValueError("Cannot coerce algebraic number with non-zero imaginary part to algebraic real")
    690         elif hasattr(x, '_algebraic_'):
--> 691             return x._algebraic_(AA)
    692         return AlgebraicReal(x)
    693 

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression.so in sage.symbolic.expression.Expression._algebraic_ (sage/symbolic/expression.cpp:6286)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression_conversions.pyc in algebraic(ex, field)
    830         0
    831     """
--> 832     return AlgebraicConverter(field)(ex)
    833 
    834 ##############

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression_conversions.pyc in __call__(self, ex)
    212                 div = self.get_fake_div(ex)
    213                 return self.arithmetic(div, div.operator())
--> 214             return self.arithmetic(ex, operator)
    215         elif operator in relation_operators:
    216             return self.relation(ex, operator)

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression_conversions.pyc in arithmetic(self, ex, operator)
    717                 return self.field(base**expt)
    718             else:
--> 719                 return reduce(operator, map(self, ex.operands()))
    720         except TypeError:
    721             if operator is _operator.pow:

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression_conversions.pyc in __call__(self, ex)
    218             return self.derivative(ex, operator)
    219         else:
--> 220             return self.composition(ex, operator)
    221 
    222     def get_fake_div(self, ex):

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/symbolic/expression_conversions.pyc in composition(self, ex, operator)
    787             if cmp(res, ex) == 0:
    788                 raise TypeError, "unable to convert %s to %s"%(ex, self.field)
--> 789         return self.field(res)
    790     
    791 def algebraic(ex, field):

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/parent.so in sage.structure.parent.Parent.__call__ (sage/structure/parent.c:7940)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/coerce_maps.so in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (sage/structure/coerce_maps.c:3344)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/structure/coerce_maps.so in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (sage/structure/coerce_maps.c:3247)()

/storage/masiao/sage-5.0.beta10/local/lib/python2.7/site-packages/sage/rings/qqbar.pyc in _element_constructor_(self, x)
    687                 return x.real()
    688             else:
--> 689                 raise ValueError("Cannot coerce algebraic number with non-zero imaginary part to algebraic real")
    690         elif hasattr(x, '_algebraic_'):
    691             return x._algebraic_(AA)

ValueError: Cannot coerce algebraic number with non-zero imaginary part to algebraic real

```

This does not seem to be related to #12665 or to #12727 -- applying the patches at those tickets does not fix the problem.

Component: **symbolics**

Author: **Marc Mezzarobba**

Branch/Commit: **[u/mmezzarobba/12745-SR_to_AA](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/12745-SR_to_AA) @ [`8f74a7b`](https://github.com/sagemath/sagetrac-mirror/commit/8f74a7b8af077e27beff9b6f4b663d9deeea728b)**

_Issue created by migration from https://trac.sagemath.org/ticket/12745_

### PR DESCRIPTION
**Pull request by RuchitJagodara**
- Simplify the expression before converting it to algebraic number
- Added a doctest

This patch fixes #12745. With this commit, the coerce
issue of Algebraic Real Field is fixed. Now it is giving correct answer for below cases

```python
sage: x = exp(2*I*pi/7) + exp(-2*I*pi/7)
sage: QQbar(x) in AA
True
sage: AA(x)
1.246979603717467?
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.

### :hourglass: Dependencies

None

### CODE REVIEW

**Comment by RuchitJagodara** [comment]
@mkoeppe, can you please review this PR? The PR is encountering test failures, but I believe the revised answer aligns closely with the expected one. So should I make adjustments to the tests?

**Comment by tscrim** [comment]
@videlec @zimmermann6 @nbruin @mezzarobba cc-ing some people who might be interested.

**Comment by videlec** [comment]
I do not think it is a good idea to systematically `full_simplify`. Can you test the following with your patch?
```python
sage: %time AA(sum(QQbar(i).sqrt() for i in range(20)))
CPU times: user 35.5 ms, sys: 2.95 ms, total: 38.5 ms
Wall time: 47.1 ms
57.19384185642023?
```

**Comment by RuchitJagodara** [comment]
This is my output 

```python
sage: %time AA(sum(QQbar(i).sqrt() for i in range(20)))
CPU times: user 3.55 ms, sys: 0 ns, total: 3.55 ms
Wall time: 3.55 ms
57.19384185642023?
```

**Comment by tscrim** [comment]
You should give timings before your change and with your change to look at possible speed regressions.

**Comment by nbruin** [comment]
I suspect you're going to be better off going via `QQbar` rather than via symbolics here. Symbolics will generally have rather high overhead. The example below illustrates this on the motivating example above.
```
sage: %timeit AA(x.simplify_full())
8.98 ms ± 34.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
sage: %timeit AA(QQbar(x))
382 µs ± 731 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by RuchitJagodara** [comment]
So should I go via `QQbar`?

**Comment by nbruin** [comment]
I would first explore `QQbar` solutions, indeed. However, as https://github.com/sagemath/sage/issues/12745#issuecomment-1417453855 indicates, there are some more fundamental problems and inconsistencies between `AA` and `QQbar` (there is also the naming convention, since most books about algebraic numbers that use `AA` would use it to indicate the field of algebraic numbers; not just the real ones). So I expect that if you start making more conversions from `SR` to `AA` go through `QQbar`, you'll start to see side-effects: conversions that already worked previously will yield different results due to differences in branch cuts chosen between `AA` and `QQbar`.

**Comment by RuchitJagodara** [comment]
Did you find anything, @nbruin, or should I proceed with QQbar and then address any errors that may arise as a result? Alternatively, should I stick with simplify_full() for now, prioritizing correctness over speed? It's better to provide a correct answer than to deliver an incorrect one quickly.

**Comment by tscrim** [comment]
> Did you find anything, @nbruin, or should I proceed with QQbar and then address any errors that may arise as a result? Alternatively, should I stick with simplify_full() for now, prioritizing correctness over speed? It's better to provide a correct answer than to deliver an incorrect one quickly.

That is a fallacy. You could cause code to be so slow that it is rendered unusable. In the case at hand, it doesn't "know" (in general) that the result lies in `AA` (welcome to dealing with symbolics and other places where undecidable problems exist). However, we have no way to really explain that to the user in the output, so it defaults to the "safe" choice of saying no.

Also @nbruin's suggestion was for you to do the exploration.

That being said, looking at `AA._element_constructor_`, it seems to be trying to convert the result on each term rather than the final result:
```
sage: x.imag().is_zero()
True
```
The quick solution is likely to go through `QQbar` since it is algebraic closed and then convert that to `AA`, as opposed to trying to rework the converter to only look at the final result.

**Comment by RuchitJagodara** [comment]
I think this PR is merged by mistake (Because there was no positive review on this PR), I was working on the solution but suddenly I noticed that this PR is merged. And the problem is that I didn't fixed the answers of some doctests which were failing (because I was exploring QQbar solutions), so some doctests are failing, now. like below 
```python
sage: elems = [sqrt(5), 2^(1/3)+sqrt(3)*I, 3/4]
....: nf, nums, hom = number_field_elements_from_algebraics(elems,
....:                                                     embedded=True)
sage: list(map(hom, nums)) == list(map(QQbar, nums))
True
sage: list(map(hom, nums)) == elems
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
...
NotImplementedError: cannot find radical expression
```
Above example was working fine before these changes but now it is giving the error.

And while exploring QQbar solutions, I observed that using QQbar instead of simplify_full may produce some problems as @nbruin said, if we are doing this conversion then we will face many side-effects.

So what should I do now ? Should I make a new PR/issue to fix these doctests or should I revert these changes?

**Comment by tscrim** [comment]
@vbraun This was indeed incorrectly merged into the develop branch. I don't recall anyone approving this either. Please revert the merge.

Perhaps there is an issue with the merge scripts?

**Comment by vbraun** [comment]
I didn't merge this PR, but this PR branch was entirely contained in https://github.com/sagemath/sage/pull/37038. The latter had positive review and was merged. 
```
~/Sage$ git log --graph --oneline 55c9f9c5561
*   55c9f9c5561 gh-37038: Add minimal_normal_subgroups and maximal_normal_subgroups functions for permutation groups
|\  
| *   fa26be9ac37 Merge branch 'develop' into add_minimal_normal_subgroups_method
| |\  
| * | 0f17e65a28f Corrected the error in functions
| * | 14c225e2ac6 Corrected linting error
| * | fa5b61b22ac Changed the method for constructing subgroups
| * | d2f349e347e Corrected some errors
| * | 297e8b2e576 Implemented functions in ParentLibGAP
| * | df7bf349558 Improved the codestyle
| * | c1f9dbecc8d Changed the example and added some description
| * | 4c351f711ac Added another function maximal_normal_subgroups and did some changes in example
| * | 4fc4d26e180 Convert the result back into sage subgroup
| * | cc09a88a561 Update expression.pyx
| * | 295e3836840 Update qqbar.py
| * | fe0fd281b89 Added the function
| * |   108470bce0c Merge remote-tracking branch 'upstream/develop' into develop
```
There is nothing wrong with this PR, its still open. The **merged** note will just remind you that currently there is no new code here (i.e. merging would not add new code)

**Comment by tscrim** [comment]
@vbraun I see, thanks for the diagnosis and explanation. Do you think you could squash away all of those intermediate commits from the main branch? I don't think it is a good idea to have some WIP that was reverted because it was meant for an independent ticket. I can figure out the precise commits if that would be helpful.

@RuchitJagodara Please make sure your branches are properly independent (and only have correct dependencies and common history).

**Comment by vbraun** [comment]
The commit history is immutable, once its released its done. Don't worry, sometimes the commit history is messy. But that is not a problem, git has all the tools necessary to deal with it.

Really squashing can only be done before code is released, and by the author and not by the release manager.

**Comment by tscrim** [comment]
Okay, thank you for the explanation. I am slightly worried about if someone is doing a `git bisect` and finds these commits and thinks the problem is associated with this PR. Admittedly it is a highly unlikely scenario.

@RuchitJagodara You will need to fix the commits here by copying them to a new branch and force pushing it to this branch on git.

**Comment by RuchitJagodara** [comment]
> @RuchitJagodara Please make sure your branches are properly independent (and only have correct dependencies and common history).

I will take care of that and apologize for my mistake.

> @RuchitJagodara You will need to fix the commits here by copying them to a new branch and force pushing it to this branch on git.

I tried to force push the branch but it is giving me the following error 
```
remote: Permission to sagemath/sage.git denied to RuchitJagodara.
fatal: unable to access 'https://github.com/sagemath/sage.git/': The requested URL returned error: 403```

**Comment by vbraun** [comment]
This PR is based on the _develop_ branch in your own account _https://github.com/RuchitJagodara/sage.git_, you have to push there.

**Comment by RuchitJagodara** [comment]
I have pushed my changes there but it is not reflecting here.

**Comment by tscrim** [comment]
This PR might just be fully corrupted and we should close it and have @RuchitJagodara open a new one based on a branch that is not `develop`. We completely fragment the discussion, but it might be the only way to repair the broken git history with GH. Any thoughts @vbraun @mkoeppe @kwankyu?

**Pull request merged**
