### PR TITLE
CI Build&Test: Show full logs, do not truncate

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [x] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Unfortunately the annotations don't work because each line is prefixed by Docker buildx's decorations

**Comment by kwankyu** [comment]
> Unfortunately the annotations don't work because each line is prefixed by Docker buildx's decorations

Fixed? Can I see the changed behavior somewhere?

**Comment by mkoeppe** [comment]
Not fixed, not fixable.
What I hoped to do there regarding annotations will have to be done in a different way, by having the Docker build succeed even when there is a build error, and then retrieving the logs from the container and printing them out, similar to what is done in CI Linux.

**Comment by mkoeppe** [comment]
For this PR, I have reduced the scope to just print out the log without truncating. This was good enough to debug #38224.

**Comment by kwankyu** [comment]
OK.

**Review by kwankyu — APPROVED** [review]
LGTM

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
