### PR TITLE
Implement all G(r,p,m) complex reflection groups

### PR DESCRIPTION
**Pull request by tscrim**
We provide an implementation of the whole family of `G(r, p, n)` complex reflection groups by realizing them as a subgroup of `ColoredPermutations`.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by tscrim** [comment]
This has a merge conflict with the splitting of the `combinat/all.py`. I will deal with that once this is reviewed (if that is still an issue at that time).

**Comment by fchapoton** [comment]
where does the merge conflict comes from ? which pull request ?

**Comment by fchapoton** [comment]
maybe the choice of the name `ComplexReflectionGroup` is a bit confusing with a category.

**Comment by tscrim** [comment]
It came from the one that split the `all.py` files, which has then been reverted. So there shouldn’t be a conflict anymore.

It’s the same situation with, e.g., `WeylGroup(s)`. This is most naturally called a complex reflection group at this level of generality; I can’t really call it $G(r,p,n)$. Of course, this isn’t all such groups, but it is the unique infinite family. I guess the $p > 1$ case could be called the `ImprimitiveComplexReflectionGroup` (with $p=1$ being the colored permutations). What do you think?

**Comment by fchapoton** [comment]
no, ok, I was just asking. It is indeed reasonable to keep your proposed name, with appropriate documentation

**Comment by fchapoton** [comment]
There is a typo "Klien" instead of Klein.

For the name, I would suggest to keep it shorter. What about "ComplexReflectionG" ?

**Comment by tscrim** [comment]
That makes it seem like I just couldn't type `roup`. How about `ShephardToddFamilyGroup` or `ShephardToddFamilyCRG`?

**Comment by fchapoton** [comment]
right. :smile: 

What about `ShephardToddFamilyGroup` in the class and `ShephardToddFamily` in the catalog ?

**Comment by tscrim** [comment]
Changed. I also removed the global (renamed) import `ComplexReflectionGroup` and added the hook under `groups.misc.ShephardToddFamily`. At some point, I want to change the `ReflectionGroup` to dispatch to these implementations (as well as via `CoxeterGroup` in the real case), but that is for later.

**Review by fchapoton — APPROVED** [review]
ok, looks good, Thanks

**Comment by tscrim** [comment]
Thank you!

**Pull request merged**
