### PR TITLE
`build/pkgs/normaliz`: Add patch for FLINT 3

### PR DESCRIPTION
**Pull request by mkoeppe**
### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36901

### CODE REVIEW

**Comment by tscrim** [comment]
Shouldn't we bump the patch level?

Also, even with this patch and #36901 I cannot build normaliz:
```
checking for fmpz_poly_set_coeff_mpz in -lflint... no
configure: error: flint is not available but was requested
```

**Comment by mkoeppe** [comment]
> Shouldn't we bump the patch level?

Really only necessary when we want to replace something that builds by something else that builds.

**Comment by mkoeppe** [comment]
This builds for me now

**Review by tscrim — APPROVED** [review]
This now builds and works for me (as far as I can tell).

**Comment by mkoeppe** [comment]
Thanks! I've thrown in the patch level bump for you

**Pull request merged**
