### PR TITLE
Move matroid constructor

### PR DESCRIPTION
**Pull request by gmou3**
Move the matroid constructor from `constructor.py` to within the `Matroid` class in `matroid.pyx`.

The main `Matroid` class with its new method `__classcall_private__` are to serve as the factory method from which the appropriate subclass is called to instantiate a new matroid.

This has the advantage of identifying the `Matroid` class with the matroid constructor, without requiring an external `Matroid()` constructor function. Now,  instead of the `Matroid()` constructor function, we import directly the `Matroid` class through `all.py` . This means that `isinstance(M, Matroid)` works properly.

This PR follows the same choice of architecture as in #38024.

### CODE REVIEW

**Comment by gmou3** [comment]
@thecaligarmo @tscrim
It seems like the `metaclass=ClasscallMetaclass` doesn't work with a `cdef class`. I have also tried overriding the `__new__` method. Any ideas of how we can make the `__classcall_private__` work within a `cdef class`?
As things stand the code compiles but the `__classcall_private__` is not called and every matroid is rendered as a generic `Matroid`.

**Comment by tscrim** [comment]
Sorry for not responding sooner. Hmm...that is indeed a problem. That might be a technical limitation for `Matroid` that requires the separate constructor. We could hack around this by having the public `Matroid` class be the construction using the `ClasscallMetaclass` mechanism, which is then inherited by the lowest level Python classes. But that's ugly and not worth it IMO. The only other thing I know is this:
https://doc.sagemath.org/html/en/reference/cpython/sage/cpython/cython_metaclass.html
That might work.

Note that it is probably better (in this case) for readability to have the construction function in a separate file and then have the `__classcall_private__` redirect to that function.

**Comment by gmou3** [comment]
I will heed the article's warning and not enter these murky `Cython` waters.
I'll probably close this PR soon, unless some other idea emerges.

**Comment by thecaligarmo** [comment]
@gmou3 I see that I'm roughly 2 hours late, but I was going to try and see if I can figure it out. Do you still have a copy of the branch by some chance? Last few days have been busy so I didn't have time to look at things.

If not, no worries, I can try and use the commits above to figure it out and implement something.

**Comment by gmou3** [comment]
Just restored it. Good luck!

**Pull request closed without merging**
