### PR TITLE
a few simplified isinstance (ruff SIM101)

### PR DESCRIPTION
**Pull request by fchapoton**
a few simplified calls of isinstance

following ruff SIM101

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Review by vincentmacri — COMMENTED** [review]
Looks good. Before approving: is there a linter check you can enable to make sure future code uses `isinstance` correctly?

**Comment by fchapoton** [comment]
yes, but but the ruff linter check has to wait that one fixes later the remaining 27 cases.

**Comment by vincentmacri** [comment]
Thanks for the contribution!

**Comment by fchapoton** [comment]
I think the failures are not related. I therefore set back to positive, as the merge was trivial.

**Pull request merged**
