### PR TITLE
get rid of some ParentWithGens in real and complex fields

### PR DESCRIPTION
**Pull request by fchapoton**
another step towards suppression of `ParentWithGens`, here in real and complex rings

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

### CODE REVIEW

**Comment by mkoeppe** [comment]
Isn't `Ring` a subclass of `ParentWithGens`? How does it help to eliminate that class?

**Comment by fchapoton** [comment]
well, we can later move the content of `ParentWithGens` to `Ring` ? in particular everything about handling the methods `gen` and`gens` ?

**Comment by mkoeppe** [comment]
Sounds like a plan, thanks.

**Review by mkoeppe — APPROVED** [review]
LGTM

**Pull request merged**
